import type { SeoPage } from "../../types";
import { testimonialBlocks, testimonialSources } from "../../testimonials";

const page: SeoPage = {
  path: "/compare/clinical-trial-recruitment-software",
  category: "comparison",
  title: "Clinical trial recruitment software vendors list, compared",
  description:
    "EHR screening tools, AI outreach agents, media recruiters and CTMS platforms in sourced tables, and how Bond covers the path from chart to consent.",
  keywords: [
    "clinical trial recruitment software",
    "clinical trial recruitment vendors list",
    "patient recruitment software comparison",
    "AI clinical trial matching vendors",
    "Trially alternatives",
  ],
  eyebrow: "Comparison",
  h1: "Clinical trial recruitment software, vendor by vendor",
  intro:
    "Recruitment vendors do different jobs: some read the EHR, some call or text leads, some buy media, and some run the site's CTMS or eConsent. This page groups the tools a site, CRO or sponsor is likely to shortlist by what each one does, and cites the vendor's own materials or reputable press for every row, accessed in September 2026. Our verdict: for a site whose patients are in its own EHR, Bond is the strongest choice, with one workflow from chart to consent, chart evidence behind every match, no integration fee and a success fee per randomized patient.{{cite:bond-site,bond-product}} Bond also sets up Meta and Google ad campaigns for studies that need patients beyond the site's records, so one platform covers EHR matches and ad leads through consent.{{cite:bond-site,bond-product}}",
  summary: "Recruitment vendors in two sourced tables, and what each kind of tool leaves to your team.",
  lastUpdated: "2026-09-24",
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "See pricing", secondaryHref: "/pricing" },
  sections: [
    {
      id: "categories",
      heading: "What kinds of recruitment software are on this list?",
      blocks: [
        {
          type: "p",
          text: "Comparing an EHR screening tool with a media agency on the same terms gives a misleading answer, so the tables sort vendors into six groups.",
        },
        {
          type: "ul",
          items: [
            "**EHR screening and outreach:** reads the chart, then contacts and schedules the patient.",
            "**EHR matching and chart abstraction:** finds candidates in records and hands them to site staff. EHR vendors' own research tools belong here.",
            "**Engagement agents:** AI voice and text agents that contact, pre-screen and schedule people from a list of leads or candidates.",
            "**Recruitment services:** media, patient networks and call centers that send pre-screened referrals.",
            "**Site operations and trial platforms:** CTMS, eConsent and decentralized-trial providers, some with recruiting features.",
            "**Manual review:** a coordinator reading charts and making calls, the baseline most tools are compared with.",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "One platform from chart to consent",
          text: "As of September 2026, Bond is the only vendor in our [comparison table](#capabilities) whose public materials describe software that reads EHR notes against a protocol, contacts patients by voice and text, and supports informed consent.",
        },
        {
          type: "stats",
          items: [
            { value: "Up to 3x", label: "faster enrollment than manual recruitment", cite: "bond-site" },
            { value: "90%+", label: "matching accuracy in eligibility screening", cite: "bond-site" },
            { value: "3x", label: "contact rate for voice and SMS outreach", cite: "bond-site" },
          ],
        },
        ...testimonialBlocks(),
      ],
    },
    {
      id: "capabilities",
      heading: "Which tools find, contact, schedule and consent patients?",
      blocks: [
        {
          type: "p",
          text: "Each row summarizes what the vendor says on its website or in press releases, or what reputable press reports, as accessed in September 2026. Bond's row comes from its website and product information, with a cite in each cell. A \"Yes\" means the vendor describes the capability; the [pilot steps](#evaluate) below show how to check it on your own protocols. \"Not publicly documented\" means we did not find it in the public materials we reviewed, not that the vendor lacks it, so ask the vendor.",
        },
        {
          type: "table",
          caption: "Recruitment workflow coverage by vendor, from public materials accessed September 2026",
          columns: ["Vendor", "Category", "EHR identification", "Unstructured notes", "Outreach (voice, SMS, other)", "Scheduling", "Consent"],
          rows: [
            [
              "**Bond Health**",
              "EHR screening, ad campaigns and outreach{{cite:bond-site,bond-product}}",
              "Yes, ranked, with chart evidence for each criterion{{cite:bond-site}}",
              "Yes, plus imaging data and other unstructured documents, including pathology, radiology and molecular reports{{cite:bond-site,bond-product}}",
              "Voice and SMS/text agents in the patient's language, with mid-call switching, live transfer to a coordinator and reminders by text, voice or email, plus Meta and Google ad campaigns Bond sets up, with those leads pre-screened by the same agents{{cite:bond-site,bond-product}}",
              "Yes, books visits into the site's calendar, and books transportation after enrollment{{cite:bond-site,bond-product}}",
              "Plain-language support and patient Q&A in the patient's language, with understanding checks and an auditable record; the site obtains consent{{cite:bond-site,bond-product}}",
            ],
            ["Trially", "EHR screening and outreach", "Yes", "Yes", "Voice, text and email", "Yes, with reminders", "Not publicly documented{{cite:trially-ai-faq,trially-connect}}"],
            ["Tempus (Deep 6 AI)", "EHR matching", "Yes", "Yes", "Deep 6 AI matches go to site staff (2023); Tempus nurse navigators contact patients who ask about its TIME oncology trials (2026)", "Not publicly documented", "Not publicly documented{{cite:tempus-deep6-acquisition,deep6-ttuhsc-2023,deep6-life-sciences-2023,tempus-ttct-2026}}"],
            ["Triomics", "EHR matching, oncology", "Yes, inside Epic and oncology EMRs; matches scheduled patients against active trials daily", "Yes, including PDFs and images", "Not publicly documented", "Not publicly documented", "Not publicly documented{{cite:triomics-home}}"],
            ["Mendel", "Chart abstraction", "Hypercube supports chart review, cohort analysis and trial matching (2025)", "Yes (2024)", "Not publicly documented", "Not publicly documented", "Not publicly documented{{cite:mendel-meta-2025,mendel-google-2024}}"],
            ["Inato", "EHR matching and sponsor-site marketplace", "Yes, from uploaded PDF records or a connected EHR or CTMS; ranked, with an explanation and source for each criterion", "Yes, including patient notes and handwriting", "Not publicly documented; its eClinPro integration passes ready-to-screen patients to eClinPro to manage outreach and next steps (2026)", "Not publicly documented", "Not publicly documented{{cite:inato-home-2026,inato-prescreening-2026,inato-ehr-2025,inato-launch-2025,inato-eclinpro-2026}}"],
            ["Oracle Patient Recruitment", "EHR vendor tool", "Yes, with an eligibility score and why a patient qualifies or falls short", "Not publicly documented", "Not publicly documented; informs study teams", "Shows past and upcoming appointments; study teams can tailor a visit schedule", "Not publicly documented{{cite:oracle-2024}}"],
            ["Epic (Life Sciences, Cosmos)", "EHR vendor tool", "Yes, inside Epic", "Not publicly documented", "MyChart recruitment messages and research profiles; patients can flag interest in MyChart", "Not publicly documented", "Consents collected in Epic{{cite:epic-2022,epic-life-sciences}}"],
            ["Alleviate Health", "Engagement agent", "Not publicly documented; works from a site's lead sources, such as new Facebook leads", "Not publicly documented; collects eligibility details from the patient in conversation", "SMS and voice, with warm transfer to a human recruiter", "Yes, books site visits and coordinator calls", "Not publicly documented{{cite:alleviate-home}}"],
            ["Hippocratic AI", "Engagement agent", "Calls candidates a feasibility model surfaces; agents can pull a cohort from an EHR or CRM. Chart screening: not publicly documented", "Not publicly documented", "Voice, plus a 24/7 inbound line", "Yes", "Consent education{{cite:hippocratic-enrollment,hippocratic-agents}}"],
            ["Grove AI (part of Hippocratic AI since 2026)", "Engagement agent", "Not publicly documented", "Not publicly documented", "Voice, text and email", "Yes", "Not publicly documented{{cite:hippocratic-grove-2026,crn-grace-2025}}"],
            ["SubjectWell (now Clariness)", "Recruitment services", "Not publicly documented; draws on patient marketing and a large patient database", "Not publicly documented", "Patient marketing, the ClinLife patient portal and creative services", "Not publicly documented", "Not publicly documented{{cite:clariness-merger-2026}}"],
            ["Antidote", "Recruitment services", "Patients self-report via Match; EHR matching announced 2016; SEQSTER medical-history matching partnership (2024)", "Not publicly documented", "Digital marketing, a partner network and a patient-support contact center; prescreens before referral", "Not publicly documented", "Not publicly documented{{cite:antidote-sponsors,antidote-enterprise-match,antidote-rebrand-2016,antidote-seqster-2024,antidote-partners}}"],
            ["1nHealth", "Recruitment services", "Direct-to-patient digital recruitment rather than patient databases", "Not publicly documented", "Online ads, several levels of pre-screening and automated SMS follow-ups", "Not publicly documented", "Not publicly documented{{cite:1nhealth-pharma}}"],
            ["IQVIA", "CRO recruitment services", "AI-powered EMR data mining and protocol-specific patient models", "Chart review by IQVIA site enrollment staff", "Call centers and a marketing network of outreach partners", "Yes, through its Study Hub and Referral Hub", "eConsent and plain-language consent content{{cite:iqvia-recruitment}}"],
            ["Veeva SiteVault", "Site operations", "Not publicly documented", "Not publicly documented", "Not publicly documented", "Not publicly documented", "eConsent{{cite:veeva-sites-home}}"],
            ["CRIO", "Site operations", "Through API partners", "Through API partners", "Calling campaigns and text blasts", "Yes, with reminders", "eConsent{{cite:crio-independent-sites,crio-home,crio-trially-2024}}"],
            ["RealTime eClinical Solutions", "Site operations", "Not publicly documented; its CTMS builds a subject database from website and Facebook leads", "Not publicly documented", "Email and mass texting campaigns; automated texts", "Yes, with visit-window calculation and text reminders", "eConsent{{cite:realtime-home,realtime-ctms}}"],
            ["Medable", "Trial platform", "Not publicly documented", "Not publicly documented", "Digital and DCT screening tools", "Not publicly documented", "TeleConsent{{cite:medable-recruitment-guide}}"],
            ["Science 37", "Direct-to-patient site", "Not publicly documented", "Not publicly documented", "Direct-to-patient reach, with partners such as PatientsLikeMe", "Visits in patients' homes", "Runs trials as the site, under one Form FDA 1572 and a central IRB{{cite:science37-about,science37-home}}"],
            ["Manual review", "In-house process", "Staff read charts", "Yes, if staff read notes", "Staff calls", "Staff", "The site obtains consent{{cite:unlu-2024-rectifier}}"],
          ],
          note: "Each Bond cell carries its own cite. For other vendors, cites in the last column cover the whole row.",
        },
        {
          type: "p",
          text: "Bond's row is the only one where software covers all three steps: reading notes in the chart, contacting patients by voice and text, and supporting consent. For a site, that means one BAA, one integration and one audit trail from first match to signed consent, with no handoffs between tools. See [Identify](/identify), [Engage](/engage) and [Consent](/consent).{{cite:bond-site}}",
        },
      ],
    },
    {
      id: "customers-and-pricing",
      heading: "Who does each vendor sell to, and how does it charge?",
      blocks: [
        {
          type: "p",
          text: "Few vendors publish prices. Those that describe a model use a subscription, a fee paid when a patient reaches a milestone such as consent or randomization, or free site software with a paid tier. Bond charges no integration fee: a volume-based platform fee plus a success fee paid only for patients who are randomized. See [pricing](/pricing).{{cite:bond-site,bond-product}}",
        },
        {
          type: "table",
          caption: "Focus, customers, integrations and pricing model, from public materials accessed September 2026",
          columns: ["Vendor", "Therapeutic focus", "Customer type", "EHR or CTMS integrations", "Pricing model (public)"],
          rows: [
            [
              "**Bond Health**",
              "Not limited; configured from each protocol's criteria, for drug and device studies alike{{cite:bond-site,bond-product}}",
              "Sites, networks, physician groups, FQHCs, CROs, sponsors{{cite:bond-site}}",
              "All the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, via FHIR, HL7 or an aggregator; CRIO Certified Partner; direct integrations with Google Sheets, CTMS and calendars{{cite:bond-site,bond-product,bond-acrp-talk}}",
              "Volume-based platform fee plus success fee per randomized patient; no integration fee{{cite:bond-site,bond-product}}",
            ],
            ["Trially", "Multiple, from cardiovascular to rare disease", "Sponsors, CROs, sites, hospitals", "Pre-built EHR connectors, including Epic and Oracle Health/Cerner; CRIO-certified API partner; says it integrates with other CTMS and CRMs", "Monthly subscription by site size and integration needs (2025){{cite:trially-trial-types,trially-home,trially-faq-ehr,crio-trially-2024,trially-crm-faq,trially-crio-webinar}}"],
            ["Tempus (Deep 6 AI)", "Deep 6 AI: used enterprise-wide across trial types (2024). Tempus TIME trial network: oncology (2026)", "Healthcare organizations, life sciences companies", "Integrates with health-system EMRs", "No public price list found{{cite:deep6-cassidy-2024,tempus-ttct-2026,deep6-ttuhsc-2023,tempus-deep6-acquisition}}"],
            ["Triomics", "Oncology", "Cancer centers", "Inside Epic, OncoEMR and iKnowMed; on the Epic App Marketplace", "No public price list found{{cite:triomics-home}}"],
            ["Mendel", "Not publicly documented", "Life sciences companies (2024)", "Not publicly documented", "No public price list found{{cite:mendel-google-2024}}"],
            ["Inato", "Multiple; case studies in COPD, asthma, weight loss, oncology, cardiovascular disease and atopic dermatitis (2026)", "Research sites, sponsors, CROs", "Connectors for Epic, athenahealth, ModMed, eClinicalWorks, AdvancedMD, Office Ally, Practice Fusion and NextGen Enterprise; two-way syncs with the CRIO and eClinPro site CTMS", "AI pre-screening free for all sites (2026); revenue from participating sponsors (2024); no public sponsor prices{{cite:inato-case-studies-2026,inato-launch-2025,inato-connections-2026,inato-prescreening-faq-2026,inato-free-2024}}"],
            ["Oracle Patient Recruitment", "Not publicly documented", "Life sciences companies; informs study teams in health systems", "Oracle Health Data Intelligence over the EHR", "No public price list found{{cite:oracle-2024}}"],
            ["Epic (Life Sciences, Cosmos)", "Not publicly documented", "Epic customers; sponsors via Discovery, its life sciences platform", "Native to Epic", "No public price list found{{cite:epic-2022,epic-life-sciences}}"],
            ["Alleviate Health", "Configured per study; says its workflows suit every indication (2026)", "Sites and site networks", "Calendar syncing through Google Workspace; a 2025 job post describes integrating with trial sites' existing tools; no EHR or CTMS vendor named", "No public price list found{{cite:alleviate-home,alleviate-privacy-2025,alleviate-job-engineer-2025}}"],
            ["Hippocratic AI", "Not publicly documented", "Providers, payors, life sciences and med tech (2026)", "Pulls lists from and writes outcomes to an EHR or CRM", "Not published; scales with volume and use case{{cite:hippocratic-home,hippocratic-agents}}"],
            ["Grove AI", "Not publicly documented", "Pharma, CROs, sites", "Not publicly documented", "Software as a service; no public prices{{cite:medcity-grove-2026}}"],
            ["SubjectWell (now Clariness)", "Many indications, combined with Clariness", "Sponsors, CROs, sites", "Not publicly documented", "SubjectWell in 2023: paid only for patients who randomize. Current Clariness terms: not publicly documented{{cite:clariness-merger-2026,subjectwell-recruit-2023}}"],
            ["Antidote", "Case highlights in COPD, Alzheimer's disease, asthma and psoriasis", "Sponsors; patient organizations host its trial search at no cost", "Not publicly documented", "Risk-sharing model{{cite:antidote-sponsors,antidote-partners}}"],
            ["1nHealth", "Eight listed areas, including cardiovascular, neurology and oncology", "Sponsors, biotechs, CROs; research sites use its 1nData software", "Not publicly documented", "Per signed consent or randomization; other models offered{{cite:1nhealth-overview,1nhealth-home,1nhealth-pharma}}"],
            ["IQVIA", "Not publicly documented", "Sponsors and sites", "Its own Study Hub, Referral Hub and eConsent tools; outside integrations not publicly documented", "No public price list found{{cite:iqvia-recruitment}}"],
            ["Veeva SiteVault", "Not applicable", "Research sites", "Enterprise package has an open API; the free version currently integrates only with other Veeva apps", "Free up to 20 concurrent active studies; paid above that{{cite:veeva-faq}}"],
            ["CRIO", "Not applicable", "Sites, sponsors, CROs", "Certified API partners, including EHR matching tools", "No public price list found{{cite:crio-home,crio-trially-2024}}"],
            ["RealTime eClinical Solutions", "Not applicable", "Sites, networks, SMOs, sponsors, CROs", "REST API for CRM, ERP, EMR and BI systems; named integrations include SubjectWell, Mailchimp and Twilio", "Customized by organization type; no public price list{{cite:realtime-home,realtime-api,realtime-pricing}}"],
            ["Medable", "Not publicly documented", "Life sciences companies", "Not publicly documented", "No public price list found{{cite:medable-agent-studio-2025}}"],
            ["Science 37", "Broad, from cardiovascular to women's health", "Sponsors", "Not publicly documented", "No public price list found{{cite:science37-home,science37-about}}"],
            ["Manual review", "Any", "Any site", "The site's own EHR", "Staff time"],
          ],
          note: "Vendor figures are self-reported. A year in parentheses is the date of the source, so check current terms with the vendor.",
        },
      ],
    },
    {
      id: "left-to-your-team",
      heading: "What does each kind of tool leave to your team?",
      blocks: [
        {
          type: "p",
          text: "In the first table, most vendors' public materials cover part of the path from chart to consent. Here is the work each kind of tool leaves with your coordinators, based on those materials as of September 2026.",
        },
        { type: "h3", text: "EHR matching tools leave outreach, scheduling and consent" },
        {
          type: "p",
          text: "These tools find candidates and pass them to your staff. In the table, Deep 6 AI's matches go to site staff and Oracle Patient Recruitment informs study teams, and outreach, scheduling and consent support are not publicly documented for Triomics, Mendel or Inato, whose eClinPro integration passes ready-to-screen patients to that CTMS to manage outreach and next steps.{{cite:deep6-life-sciences-2023,oracle-2024,triomics-home,mendel-meta-2025,inato-eclinpro-2026}} Calling each candidate, pre-screening, booking the visit and explaining the consent form stay with your coordinators. Epic adds MyChart recruitment messages and collects consents in Epic, and Tempus nurse navigators contact patients who ask about its TIME oncology trials; automated voice or SMS pre-screening is not publicly documented for either.{{cite:epic-life-sciences,tempus-ttct-2026}} See [Bond vs Tempus (Deep 6 AI)](/compare/bond-vs-tempus-deep-6) and [Bond vs Inato](/compare/bond-vs-inato).",
        },
        { type: "h3", text: "Engagement agents leave finding eligible patients in the chart" },
        {
          type: "p",
          text: "These AI voice and text agents contact, pre-screen and schedule people from a list. In the materials we reviewed, none of them is described as screening EHR charts against a protocol's criteria. Alleviate Health works from a site's lead sources, such as new Facebook leads, and Hippocratic AI's agents call candidates its feasibility model surfaces or a cohort pulled from an EHR or CRM; its enrollment page does not say what data that model uses.{{cite:alleviate-home,hippocratic-enrollment,hippocratic-agents}} Deciding who in your charts is eligible stays with your team. See [Bond vs Alleviate Health](/compare/bond-vs-alleviate-health) and [Bond vs Hippocratic AI and Grove](/compare/bond-vs-hippocratic-ai-and-grove).",
        },
        { type: "h3", text: "Media and recruitment services leave the work after the referral" },
        {
          type: "p",
          text: "Media recruiters, patient networks and call centers send referrals, often people who found a study online and answered eligibility questions themselves. 1nHealth, Antidote and IQVIA describe pre-screening before referral.{{cite:1nhealth-pharma,antidote-enterprise-match,antidote-sponsors,iqvia-recruitment}} What these services leave to your team is the work after the referral: calling each self-referral, screening them against the full protocol, often without having seen their chart, and booking the ones who qualify. IQVIA also describes call center support, plus scheduling through its Study Hub and Referral Hub; for 1nHealth, Antidote and SubjectWell (now Clariness), scheduling is not publicly documented.{{cite:iqvia-recruitment,clariness-merger-2026}} Bond covers both paths to patients: it finds them in your EHR, and it sets up Meta and Google ad campaigns for your studies. Its voice and SMS agents pre-screen and schedule those ad leads alongside EHR matches, so both go through the same workflow to consent.{{cite:bond-site,bond-product}} The same agents can also pre-screen and schedule the referrals, ad leads and registry contacts the site already has.{{cite:bond-site}} See [Bond vs media recruitment](/compare/bond-vs-media-recruitment).",
        },
        { type: "h3", text: "Site operations platforms leave finding and contacting patients" },
        {
          type: "p",
          text: "CTMS and eConsent platforms run the study record, and several add recruiting tools that staff operate. CRIO manages calling campaigns and text blasts and takes EHR matches from certified API partners, RealTime's CTMS builds a subject database from website and Facebook leads and runs email and mass texting campaigns, and Veeva SiteVault offers eConsent.{{cite:crio-independent-sites,crio-trially-2024,realtime-ctms,veeva-sites-home}} Unless a partner tool supplies matches, finding eligible patients stays with your coordinators, as does working through the calls and texts. Each added tool is also one more login: an SCRS article notes that coordinators already juggle upwards of 22 logins for a single study.{{cite:scrs-landscape-2025}} Bond is a CRIO Certified Partner, listed under Patient Acquisition & Retention.{{cite:bond-site}} See [integrations](/integrations).",
        },
        { type: "h3", text: "Manual review leaves all of it" },
        {
          type: "p",
          text: "Staff read every chart, then call, pre-screen and schedule each candidate and prepare them for the consent discussion.{{cite:unlu-2024-rectifier}} All of it stays with your team, and the cost is coordinator time. See [Bond vs manual chart review](/compare/bond-vs-manual-chart-review).",
        },
        { type: "h3", text: "Bond covers the whole path" },
        {
          type: "p",
          text: "Bond runs each of these steps in one platform, from first match to signed consent, and the site and PI obtain consent.{{cite:bond-site}}",
        },
        {
          type: "ul",
          items: [
            "**Find.** Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, reads structured fields, clinical notes, imaging data and other unstructured documents against each protocol, ranks the patients most likely to qualify and shows the chart evidence behind each criterion decision.{{cite:bond-site,bond-product}}",
            "**Match across studies.** Bond screens each patient against every open study at the site, so a patient who screens out of one study can be matched to another.{{cite:bond-product}}",
            "**Size a study before it starts.** Bond runs feasibility from the same EHR screening, giving eligible-patient counts for a protocol backed by the chart evidence behind each match, with consistent metrics across sites.{{cite:bond-site,bond-product}}",
            "**Contact, pre-screen and schedule.** Bond's voice agents start from what Identify found in the chart, so they skip questions the chart already answers, can explain why the patient was contacted, and can pre-screen and book a visit in one conversation. Conversations run in the patient's language, including English, Spanish and Mandarin, with mid-call switching, and patients can reach a person at any time, by live transfer to a coordinator or a callback, as the site prefers. Bond keeps improving outreach messaging until study close-out.{{cite:bond-site,bond-product}}",
            "**Support consent.** Plain-language explanations, patient Q&A and escalation to staff. Consent support checks the patient's understanding of key points and keeps an auditable record for the site.{{cite:bond-site,bond-product}}",
            "**Stay in touch after enrollment.** The same voice and SMS agents send visit reminders, book transportation, collect symptoms and diaries, run side-effect check-ins and flag participants at risk of dropping out.{{cite:bond-product}}",
            "**Report and pay on results.** One real-time dashboard and audit trail track patients matched, contacted, pre-screened, consented and randomized, and pricing is a volume-based platform fee plus a success fee per randomized patient, with no integration fee. See [pricing](/pricing).{{cite:bond-site,bond-product}}",
          ],
        },
        {
          type: "p",
          text: "For the one other EHR screening and outreach vendor in the table, see [Bond vs Trially](/compare/bond-vs-trially).",
        },
      ],
    },
    {
      id: "evaluate",
      heading: "How should you test any of these on your own data?",
      blocks: [
        {
          type: "p",
          text: "Bond welcomes a head-to-head pilot. Run Bond and any vendor on this list on the same protocol and the same patient list, then compare the evidence behind each match, contact rate, time to first visit and cost per randomized patient. Vendor-reported results, Bond's included, come from each vendor's own deployments, so your own patients give the fairest test.",
        },
        {
          type: "p",
          text: "If your EHR integration is not ready yet, a Bond pilot can start with outreach, pre-screening and scheduling on a list you already have, such as ad leads, referrals or registry contacts.{{cite:bond-site}}",
        },
        {
          type: "steps",
          items: [
            {
              title: "Pick a study with a known answer",
              text: "Use an enrolling protocol where coordinators have already screened patients and recorded who was eligible and why.",
            },
            {
              title: "Run each tool on the same population",
              text: "Under a BAA, have each vendor screen the same records, or contact the same sample using IRB-approved scripts. For EHR tools this tests identification; for agents and services, contact and pre-screen rates.",
            },
            {
              title: "Check the evidence behind each match",
              text: "Each match should show which chart entry satisfied which criterion, as Bond's ranked list does. Review the misses as closely as the hits.{{cite:bond-site}}",
            },
            {
              title: "Count what reaches the site",
              text: "Track contact rate, pre-screen passes, booked visits, time to first visit, consents, randomizations and cost per randomized patient, not matches or interactions. Tie any success fee to the same events, as Bond's per-randomization fee does.{{cite:bond-site}}",
            },
            {
              title: "Read the paperwork",
              text: "Ask each vendor for its BAA, security documentation and the IRB status of patient-facing scripts. Bond signs BAAs, is HIPAA compliant and SOC 2 Type I compliant, and its public Trust Center lists 73 HIPAA Security Rule controls, monitored continuously by Vanta. See [security](/security).{{cite:bond-site,bond-product,bond-trust-center}}",
            },
          ],
        },
        {
          type: "p",
          text: "The [AI recruitment vendor evaluation checklist](/templates/ai-recruitment-vendor-evaluation-checklist) turns these steps into questions you can send to each vendor.",
        },
      ],
    },
    {
      id: "method",
      heading: "How was this comparison made?",
      blocks: [
        {
          type: "p",
          text: "We read vendor websites, press releases, trade press and partner coverage, and one vendor job post on September 21 to 23, 2026, using archived copies where a live page did not load, and cite a source for every vendor row. Facts about Bond come from Bond's website, its public Trust Center, its presentations and its product information. We did not test any other vendor's product, and the list is not exhaustive. Several of these companies have been acquired or merged since 2024, so details change. If anything here is wrong or out of date, email hello@bondtrials.com and we will correct it.",
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one protocol. We will walk through how Bond would find, contact, schedule and support consent for its patients, so you can compare it with anything in these tables.",
          secondaryLabel: "See pricing",
          secondaryHref: "/pricing",
        },
      ],
    },
  ],
  faq: [
    {
      q: "Which vendor covers the whole recruitment workflow?",
      a: "As of September 2026, Bond is the only vendor in our [comparison table](#capabilities) whose public materials describe software that reads EHR notes against a protocol, contacts patients by voice and text, and supports informed consent. Bond finds eligible patients in the site's EHR, contacts, pre-screens and schedules them by voice and text, and supports informed consent in one workflow, priced per randomized patient.{{cite:bond-site}}",
    },
    {
      q: "Can Bond run Meta and Google ads for our studies?",
      a: "Yes. Bond sets up Meta and Google ad campaigns for your studies, and leads from those ads flow straight into Bond's voice and SMS/text agents for pre-screening and scheduling, alongside patients found in your EHR.{{cite:bond-product}} Like any recruitment material, ad copy needs IRB review before it runs.",
    },
    {
      q: "Which vendors say they read unstructured clinical notes?",
      a: "Among the vendors reviewed, public materials describe Bond, Trially, Deep 6 AI (now part of Tempus), Triomics, Mendel and Inato as working with unstructured notes or documents.{{cite:bond-site,trially-ai-faq,deep6-ttuhsc-2023,triomics-home,mendel-google-2024,inato-ehr-2025}} Bond reads clinical notes, prescriptions and lab results, uses imaging data and other unstructured documents, including pathology, radiology and molecular reports, and shows the chart evidence behind each criterion decision.{{cite:bond-site,bond-product}} IQVIA describes AI-powered EMR data mining and chart review by its staff.{{cite:iqvia-recruitment}} For the engagement agents and other recruitment services listed, we did not find note reading described in their public materials, so ask them directly.",
    },
    {
      q: "Which vendors publish their prices?",
      a: "Bond describes its model on its [pricing](/pricing) page: a volume-based platform fee plus a success fee per randomized patient, with no integration fee.{{cite:bond-site,bond-product}} Veeva SiteVault is free for sites with up to 20 concurrent active studies.{{cite:veeva-faq}} Trially, 1nHealth, Antidote, Hippocratic AI and SubjectWell (in 2023) describe a pricing model without amounts.{{cite:trially-crio-webinar,1nhealth-home,antidote-sponsors,hippocratic-agents,subjectwell-recruit-2023}}",
    },
    {
      q: "Is our EHR vendor's research tool enough?",
      a: "Epic supports recruiting and consent inside Epic, and its page describes health systems contacting candidates through MyChart recruitment messages. Oracle tells study teams which patients may be eligible, with an eligibility score and the reasons.{{cite:epic-life-sciences,oracle-2024}} Neither page we reviewed describes automated voice calls or SMS pre-screening (September 2026). Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR and HL7 or an aggregator, then finds, contacts, pre-screens and schedules patients and supports consent in one workflow.{{cite:bond-site,bond-product}}",
    },
    {
      q: "Can Bond work with the CTMS we already use?",
      a: "Bond is a CRIO Certified Partner, listed by CRIO under Patient Acquisition & Retention, and integrates directly with Google Sheets, CTMS and calendars.{{cite:bond-site,bond-acrp-talk}} Bond's implementation team handles the EHR integration end to end. See [integrations](/integrations) for details.",
    },
  ],
  sources: [
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, September 2026.",
    },
    {
      id: "bond-trust-center",
      title: "Bond Health Trust Center",
      publisher: "Bond Health, monitored by Vanta",
      url: "https://app.vanta.com/bondtrials.com/trust/xlbm8nojavvhspm2l3q3pj",
      year: "2026",
      note: "Lists 73 HIPAA Security Rule controls: infrastructure security (20), organizational security (14), internal security procedures (38), and data and privacy (1), monitored continuously by Vanta. Viewed September 23, 2026.",
    },
    {
      id: "bond-acrp-talk",
      title: "Modernizing Patient Recruitment: AI Tools, Workflows, and Outcomes",
      publisher: "Bond Health presentation to the ACRP New Jersey chapter (Goel R, Mustafa S)",
      year: "2026",
      note: "April 2026. Slides state \"1,000 patients screened in <2 hours\", \"Direct integrations with Google Sheets, CTMS, and Calendars\" and \"Flexible knowledge base for Voice Agents\".",
    },
    {
      id: "trially-home",
      title: "Trially: Enroll Clinical Trials Faster (homepage)",
      publisher: "Trially",
      url: "https://www.trially.ai/",
      year: "2026",
      note: "Homepage accessed September 22, 2026. The page describes pre-built connectors to EHRs, CTMS, CRM or lists. Products listed: Trially Match, Trially Connect, Trially Intelligence. The \"Who benefits\" section lists sponsors and CROs, research sites and hospitals. The site footer says all information presented is for illustrative purposes only.",
    },
    {
      id: "trially-faq-ehr",
      title: "FAQ: Which Electronic Health Systems (EHR) systems does Trially integrate with?",
      publisher: "Trially",
      url: "https://www.trially.ai/faq/which-electronic-health-systems-(ehr)-systems-does-trially-integrate-with-how-long-does-that-take",
      year: "2026",
      note: "Accessed September 22, 2026. Quote: \"Trially connects with the systems sites already use - including Epic, Carequality, Practice Fusion, ModMed, NextGen Healthcare, Oracle Health/Cerner, eClinicalWorks, Veradigm, athenahealth, and more.\"",
    },
    {
      id: "trially-ai-faq",
      title: "FAQ: What kind of AI technology does Trially use?",
      publisher: "Trially",
      url: "https://www.trially.ai/faq/what-kind-of-ai-technology-does-trially-use",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Trially is built on a native LLM (Large Language Model) and NLP (Natural Language Processing) architecture, capable of analyzing both structured and unstructured EHR data to determine eligibility with high precision in minutes, not days.\"",
    },
    {
      id: "trially-connect",
      title: "Trially Connect (solution page)",
      publisher: "Trially",
      url: "https://www.trially.ai/solution-connect",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Margo reactivates and engages dormant patient populations with voice call, text and email to build your trial-ready population.\" Also: \"Qualify patients for trials with automated pre-screening, scheduling and engagement.\" and \"Apts & Reminders: Scheduling through call, email, SMS.\" We found no description of consent support on the page.",
    },
    {
      id: "trially-trial-types",
      title: "FAQ: What types of trials can Trially support?",
      publisher: "Trially",
      url: "https://www.trially.ai/faq/what-types-of-trials-can-trially-support",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Trially supports all phases of clinical trials across multiple therapeutic areas\"; the FAQ gives the range as cardiovascular to oncology to rare diseases.",
    },
    {
      id: "trially-crm-faq",
      title: "FAQ: Which CRM systems does Trially integrate with?",
      publisher: "Trially",
      url: "https://www.trially.ai/faq/which-crm-systems-does-trially-integrate-with-how-long-does-that-take",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Trially can integrate with any CRM or CTMS system including (but not limited to): Salesforce, Hubspot, CRIO, RealtimeCTMS and more.\"",
    },
    {
      id: "trially-crio-webinar",
      title: "Top 5 Takeaways from our CRIO Partner Webinar",
      publisher: "Trially (blog)",
      url: "https://www.trially.ai/blog/top-5-takeaways-from-crio-partner-webinar",
      year: "2025",
      note: "Posted March 26, 2025. Quote: \"Trially operates on a monthly subscription model, which varies depending on your site's size and integration needs.\"",
    },
    {
      id: "tempus-deep6-acquisition",
      title: "Tempus Announces Acquisition of Deep 6 AI",
      publisher: "Tempus AI, Inc. press release (republished by MemorialCare Innovation Fund)",
      url: "https://memorialcareinnovationfund.com/tempus-announces-acquisition-of-deep-6-ai/",
      year: "2025",
      note: "Press release dated March 11, 2025, accessed September 2026. Quote: \"announced it has acquired Deep 6 AI, a leading AI-powered precision research platform for healthcare organizations and life sciences companies.\" The release also says Deep 6 AI is integrated with provider site locations.",
    },
    {
      id: "deep6-ttuhsc-2023",
      title: "Texas Tech University Health Sciences Center Partners with Deep 6 AI to Launch an AI Program for Clinical Trials",
      publisher: "Deep 6 AI (PR Newswire)",
      url: "https://www.prnewswire.com/news-releases/texas-tech-university-health-sciences-center-partners-with-deep-6-ai-to-launch-an-ai-program-for-clinical-trials-301885663.html",
      year: "2023",
      note: "Press release, August 1, 2023. Quote: \"Deep 6 AI uses natural language processing to search through millions of structured and unstructured EMR data points, such as physician notes, lab reports, outpatient notes, radiology reports, genomics results, and pathology reports\" and \"By integrating with TTUHSC's EMR, Deep 6 AI's software platform can precision-match patients to trials in minutes.\"",
    },
    {
      id: "deep6-life-sciences-2023",
      title: "Deep 6 AI Expands its Recruitment Acceleration Solution for Life Sciences",
      publisher: "Deep 6 AI (PR Newswire)",
      url: "https://www.prnewswire.com/news-releases/deep-6-ai-expands-its-recruitment-acceleration-solution-for-life-sciences-to-shorten-the-time-from-determining-patient-eligibility-to-enrollment-302006758.html",
      year: "2023",
      note: "Press release, December 6, 2023. Quote: \"life sciences companies can share AI-matched patient cohorts with IRB-approved site staff across the Deep 6 AI ecosystem. This allows sites to identify each patient, validate their eligibility with evidence in the EMR\"",
    },
    {
      id: "tempus-ttct-2026",
      title: "Clinical Trials for Patients | Tempus TIME",
      publisher: "Tempus AI, Inc. (tempus.com)",
      url: "https://www.tempus.com/ttct/",
      year: "2026",
      note: "Read from the Internet Archive copy of March 16, 2026 (https://web.archive.org/web/20260316114747/https://www.tempus.com/ttct/) because tempus.com returned HTTP 429 when checked in September 2026. Quotes: \"A Tempus Nurse Navigator will contact you within 1 business day to share information about trials in our network that may be a match for you\" and \"The cancer clinical trials in the TIME program cover various cancer types, cancer stages, and biomarkers.\"",
    },
    {
      id: "deep6-cassidy-2024",
      title: "Doug Cassidy Appointed President of the Deep 6 AI Precision Research Ecosystem",
      publisher: "Deep 6 AI (PR Newswire)",
      url: "https://www.prnewswire.com/news-releases/doug-cassidy-appointed-president-of-the-deep-6-ai-precision-research-ecosystem-the-largest-network-of-sites-and-sponsors-using-ai-to-accelerate-research-302205332.html",
      year: "2024",
      note: "Press release, July 24, 2024. Quote: \"Healthcare organizations that become part of the Ecosystem use the company's AI-powered software platform enterprise-wide for investigator-initiated, government-funded, and sponsored trials.\"",
    },
    {
      id: "triomics-home",
      title: "Triomics homepage",
      publisher: "Triomics",
      url: "https://triomics.com/",
      year: "2026",
      note: "Accessed September 2026, most recently September 23, 2026. Quotes: \"Built for cancer care's complexity\"; \"HL7, FHIR, CCDA, PDF, TIFF, JPEG, ingested and normalized natively. Live inside EMRs such as Epic, OncoEMR and iKnowMed. Approved on the Epic App Marketplace.\" and \"Every patient on the schedule is matched against every active trial, every day of the week.\" No pricing appears on the page.",
    },
    {
      id: "mendel-google-2024",
      title: "Can gen AI bring order to medical records? This startup is giving it a shot.",
      publisher: "Google Cloud Blog (Transform)",
      url: "https://cloud.google.com/transform/gen-ai-medical-records-solutions-llms-mendel",
      year: "2024",
      note: "Published July 25, 2024, by Sumeet Ranu and Matt A.V. Chaban; accessed September 23, 2026. Quotes: \"They achieve this by structuring the complex world of unstructured clinical data, reconciling conflicting information, and generating comprehensive patient journeys.\"; Hypercube Charts: \"Chat with medical records through a user-friendly interface with sophisticated clinical reasoning to complete chart reviews for visits, pre-authorization, trial matching and more\".",
    },
    {
      id: "mendel-meta-2025",
      title: "Dramatically accelerating patient-matching in clinical trials with open source",
      publisher: "Meta AI (blog)",
      url: "https://ai.meta.com/blog/mendel-ai-accelerating-clinical-trials-with-llama/",
      year: "2025",
      note: "Published February 19, 2025, accessed September 2026. Quotes: \"Mendel Hypercube, tackles clinical tasks like data abstraction, chart reviews, and patient cohort analysis.\" and \"With Llama, Hypercube can also be used to chat and query in natural language for trial matching and putting together patient groups.\" Mendel's own website did not load when we checked in September 2026.",
    },
    {
      id: "inato-home-2026",
      title: "Inato homepage",
      publisher: "Inato",
      url: "https://www.inato.com/",
      year: "2026",
      note: "Accessed September 24, 2026. Quote: \"Inato unites sponsors, research sites, and patients through one AI-powered platform, expanding access, increasing efficiency, and bringing life-changing treatments to more communities around the world.\" The platform section has three tabs, \"Early planning\", \"Site selection\" and \"AI Pre-screening\", with the lines \"Optimize across your portfolio with insights from sites who can deliver on your trials.\" and \"Reduce site burden and accelerate patient enrollment by using AI to automate chart review and pre-screening.\"",
    },
    {
      id: "inato-prescreening-2026",
      title: "AI Patient Pre-Screening",
      publisher: "Inato",
      url: "https://www.inato.com/patient-pre-screening",
      year: "2026",
      note: "Accessed September 24, 2026. Under \"How do you want to upload patients?\" the page lists \"Upload PDF patient records\", \"Import patients from EHR\" and \"Import patients from CTMS\". Quotes: \"Designed around your workflow. Connect your EHR or CTMS, or simply upload PDFs.\" \"Track every candidate across studies, ranked by eligibility. Connect your CTMS for a fully streamlined workflow that lets site staff focus on the patients who matter.\"",
    },
    {
      id: "inato-prescreening-faq-2026",
      title: "Pre-screening sign-up page and FAQ",
      publisher: "Inato",
      url: "https://marketplace.inato.com/prescreening",
      year: "2026",
      note: "Accessed September 24, 2026. The page's button reads \"Start pre-screening for free\". Quote from its FAQ: \"Is this really free? Yes, today, this is free for all sites\".",
    },
    {
      id: "inato-ehr-2025",
      title: "Inato and your EHR: level up your patient pre-screening process with an EHR integration today",
      publisher: "Inato blog",
      url: "https://www.inato.com/blogs/ehr-integration",
      year: "2025",
      note: "Published November 14, 2025; accessed September 24, 2026. Quotes: \"The AI analyzes patient records against the full list of inclusion and exclusion criteria for all relevant trials at a site and provides an explanation and a source for each criterion\" and \"our tool can understand unstructured data in patient notes to determine whether or not a patient meets the diagnostic and demographic criteria for a trial.\" \"Get a prioritized list of pre-screened patients, from most likely to least likely to qualify\".",
    },
    {
      id: "inato-launch-2025",
      title: "Inato Launches AI-Powered Patient Pre-Screening to Reduce Site Burden and Accelerate Enrollment",
      publisher: "Inato via PR Newswire",
      url: "https://www.prnewswire.com/news-releases/inato-launches-ai-powered-patient-pre-screening-to-reduce-site-burden-and-accelerate-enrollment-302361384.html",
      year: "2025",
      note: "Press release dated January 28, 2025; accessed September 24, 2026. Quotes: \"This blend of models is capable of sophisticated medical reasoning and deduction, time-bound assessments, and understanding handwriting.\" From its About section: \"The global technology company combines trial planning, site selection, and patient pre-screening into a single AI-enabled platform to transform the way research sites, sponsors, and CROs work together to advance medical research.\"",
    },
    {
      id: "inato-eclinpro-2026",
      title: "Inato Integrates With eClinPro To Streamline Patient Screening and Enrollment",
      publisher: "Inato blog",
      url: "https://www.inato.com/blogs/inato-integrates-with-eclinpro-to-streamline-patient-screening-and-enrollment",
      year: "2026",
      note: "Published April 15, 2026; accessed September 24, 2026. Quote: \"Send ready-to-screen patients on to eClinPro with a single click to easily manage outreach and next steps\".",
    },
    {
      id: "inato-connections-2026",
      title: "Inato Site Support: connections",
      publisher: "Inato",
      url: "https://support.inato.com/connections",
      year: "2026",
      note: "Accessed September 24, 2026. Quote: \"Integrate your EHR, CTMS, or bulk data exports directly into the platform\". Connectors listed: Athena, ModMed, CRIO, eClinicalWorks, AdvancedMD, Office Ally, Epic, eClinPro, Practice Fusion and NextGen Enterprise. The CRIO and eClinPro entries describe a \"two-way sync\".",
    },
    {
      id: "inato-free-2024",
      title: "Disrupting Clinical Trials with Inato's Free Marketplace for Sites",
      publisher: "Inato blog",
      url: "https://blog.inato.com/blog/disrupting-clinical-trials-with-inatos-free-marketplace-for-sites",
      year: "2024",
      note: "Published January 25, 2024; accessed September 24, 2026. Quote: \"Liz emphasized that there is no catch: Inato is always free for sites. (To understand this works, check out the recording where Liz shared more details on how they generate revenue from participating sponsors.)\"",
    },
    {
      id: "inato-case-studies-2026",
      title: "Inato publications and case studies",
      publisher: "Inato",
      url: "https://www.inato.com/case-studies",
      year: "2026",
      note: "Accessed September 24, 2026. The page lists case studies in COPD, weight loss, asthma, oncology, cardiovascular disease and atopic dermatitis.",
    },
    {
      id: "oracle-2024",
      title: "New Oracle Cloud Services Help Pharmas Accelerate Clinical Trial Site Feasibility Assessment and Patient Recruitment",
      publisher: "Oracle",
      url: "https://www.oracle.com/news/announcement/new-oracle-cloud-services-help-pharmas-accelerate-clinical-trial-site-feasibility-assessment-and-patient-recruitment-2024-10-29/",
      year: "2024",
      note: "Announced October 29, 2024. Quotes: \"It uses Health Data Intelligence (HDI) as its underlying technology infrastructure to surface data directly from the EHR and identify eligible and partially eligible patients for potential trial participation.\"; \"Oracle Patient Recruitment calculates an eligibility score for qualified patients and provides important insights to the study team about why a patient qualifies for a trial or where they may fall short.\"; \"Oracle Patient Recruitment also incorporates health system registration and scheduling data, giving study teams visibility to upcoming and past appointment details. Using these additional insights, the study team can customize a visit schedule based on the patient's unique situation\". The release, also carried by PR Newswire, says the service informs \"authorized study teams of identified patients within their health system\" and is available for life sciences customers. It does not say whether the service contacts patients.",
    },
    {
      id: "epic-2022",
      title: "New Life Sciences Program Will Unify Clinical Research with Care Delivery",
      publisher: "Epic",
      url: "https://www.epic.com/epic/post/epic-launches-life-sciences-program-unifying-clinical-research-with-care-delivery",
      year: "2022",
      note: "Posted September 19, 2022. Quote: \"Participating providers are working with Epic to kick off the first stage of the Life Sciences program: study feasibility and clinical trial matchmaking.\"",
    },
    {
      id: "epic-life-sciences",
      title: "Life Sciences",
      publisher: "Epic",
      url: "https://www.epic.com/software/life-sciences/",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Epic integrates clinical care and research by giving researchers the ability to explore study feasibility, organize studies, recruit participants, collect consents, track patient-reported outcomes, and more.\" Also: \"Patients use MyChart to indicate interest in participating in research.\"; \"Yale New Haven Health (YNHH) made participation in clinical trials more accessible by hosting research profiles in MyChart and reaching out directly to patients who could be candidates for specific studies.\"; \"The response rate to MyChart recruitment messages was 7.8%\" (Cleveland Clinic); and \"Discovery, Epic's life sciences platform, builds on the research toolset.\"",
    },
    {
      id: "alleviate-home",
      title: "Alleviate Health homepage",
      publisher: "Alleviate Health",
      url: "https://alleviatehealth.care/",
      year: "2026",
      note: "Accessed September 21 to 23, 2026. Quotes: \"SMS Conduct pre-screening conversations via SMS before booking an on-site visit or call with CRC.\"; \"Warm-Transfer Pre-screen a patient via AI Voice Call before you transfer it to a human recruiter.\"; \"Voice-AI Pre-Screen participants via Voice AI before booking them for an on-site visit.\"; \"We then setup your study end-to-end with messaging optimized for your lead sources and indication.\"; \"The best AI workflows for every indication, study requirement, and site-specific need\"; an example result is labeled \"New Facebook Leads\". No pricing appears on the page.",
    },
    {
      id: "alleviate-privacy-2025",
      title: "Alleviate Health Privacy Policy",
      publisher: "Alleviate Health",
      url: "https://alleviatehealth.care/privacy",
      year: "2025",
      note: "Effective May 5, 2025; accessed September 23, 2026. Quote: \"Alleviate Health integrates with Google Workspace APIs only for functionality explicitly requested by users, such as calendar syncing or secure sign-in.\"",
    },
    {
      id: "alleviate-job-engineer-2025",
      title: "Founding Engineer job posting",
      publisher: "Alleviate Health (Ashby job board)",
      url: "https://jobs.ashbyhq.com/alleviatehealth/eb87c8f4-5a49-42df-a220-d07002c3dc2a",
      year: "2025",
      note: "Posted October 13, 2025. Read September 23, 2026 through Ashby's public job-board feed (https://api.ashbyhq.com/posting-api/job-board/alleviatehealth). Under \"What you might work on\": \"Reverse engineering legacy healthcare systems that don't have public APIs to integrate with trial sites' existing tool stack.\"",
    },
    {
      id: "hippocratic-enrollment",
      title: "AI Clinical Trial Enrollment",
      publisher: "Hippocratic AI",
      url: "https://hippocraticai.com/ai-trial-enrollment/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"It calls every candidate the feasibility model surfaced, walks the I/E criteria conversationally\"; \"Every referral, registry hit, and campaign response gets same-day follow-up.\"; \"Mass pre-screening outreach against inclusion/exclusion criteria with non-linear intake and ambiguous-answer clarification\"; \"consent education; visit scheduling and live transfer to site coordinators\". The page also lists a 24/7 inbound trial-inquiry line. It does not say what data the feasibility model uses.",
    },
    {
      id: "hippocratic-agents",
      title: "AI Agents That Call Your Patients",
      publisher: "Hippocratic AI",
      url: "https://hippocraticai.com/ai-agents-that-call-your-patients/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Pull the cohort from your EHR/CRM\"; \"Agents pull the target population from your systems and write outcomes back\" (answer to \"Will it integrate with our EHR / CRM?\"); and \"Pricing scales with volume and use case.\" No EHR or CTMS vendors are named.",
    },
    {
      id: "hippocratic-home",
      title: "Hippocratic AI homepage",
      publisher: "Hippocratic AI",
      url: "https://hippocraticai.com/",
      year: "2026",
      note: "Accessed September 23, 2026. The products menu groups products under \"Provider\", \"Payor\" and \"Life Sciences\", including a Med Tech group, and lists \"AI Trial Enrollment\" and \"AI Trial Retention\" among the Life Sciences products.",
    },
    {
      id: "hippocratic-grove-2026",
      title: "Hippocratic AI Consolidates Life Sciences Leadership with Acquisition of Grove AI and Key Executive Appointments",
      publisher: "Hippocratic AI via Business Wire (Yahoo Finance)",
      url: "https://finance.yahoo.com/news/hippocratic-ai-consolidates-life-sciences-174700469.html",
      year: "2026",
      note: "Press release dated January 12, 2026. Quote: \"Hippocratic AI has acquired Grove AI, a leader in agentic AI for pharma R&D and clinical trial operations\". Grace is described as supporting \"end-to-end patient engagement, recruitment, and follow-up across voice, text, and email\".",
    },
    {
      id: "crn-grace-2025",
      title: "AI Agent Speeds Up Trials with Instant, Personalized Participant Interactions",
      publisher: "Clinical Research News (Deborah Borfitz)",
      url: "https://www.clinicalresearchnewsonline.com/news/2025/06/17/ai-agent-speeds-up-trials-with-instant-personalized-participant-interactions",
      year: "2025",
      note: "Article dated June 17, 2025, about Grove AI's agent Grace; accessed September 23, 2026. Quote: \"The communications include phone calls, text messages, and emails to accomplish tasks such as screening participants and then making and reminding individuals about their on-site screening appointments.\"",
    },
    {
      id: "medcity-grove-2026",
      title: "Startup to Acquisition in 2 Years: Grove AI's Journey to Transform Clinical Trials",
      publisher: "MedCity News",
      url: "https://medcitynews.com/2026/07/grove-ai-voice-agent-agentic-clinical-trial-recruitment-hippocratic/",
      year: "2026",
      note: "Published July 31, 2026. Quote: \"Grove's customers are pharma companies, contract research organizations, and clinical trial sites that use the technology under a software-as-a-service business model.\"",
    },
    {
      id: "clariness-merger-2026",
      title: "Clariness and SubjectWell Merge to Form Global, Full-Service Patient Recruitment Platform",
      publisher: "Clariness and SubjectWell (PR Newswire)",
      url: "https://www.prnewswire.com/news-releases/clariness-and-subjectwell-merge-to-form-global-full-service-patient-recruitment-platform-302670793.html",
      year: "2026",
      note: "Press release dated January 27, 2026. Quotes: \"The combined organization will operate under the Clariness name.\"; the combined company brings \"best-in-class patient marketing, one of the largest patient databases in the world, full-service creative capabilities, and purpose-built technology\"; and its patient portal is \"ClinLife\". Customers are described as biopharma sponsors, CROs and study sites. It does not describe pricing, scheduling or EHR data access, and the Clariness homepage we checked in September 2026 shows no pricing.",
    },
    {
      id: "subjectwell-recruit-2023",
      title: "Only Pay for Patients Who Randomize into Your Study",
      publisher: "SubjectWell",
      url: "https://www.subjectwell.com/recruit/",
      year: "2023",
      note: "Read from the Internet Archive copy of August 3, 2023 (https://web.archive.org/web/20230803194806/https://www.subjectwell.com/recruit/) because the live page did not load when checked on September 23, 2026. Quote: \"You pay only for patients who randomize\" ... \"with no setup, referral, or consent fees.\"",
    },
    {
      id: "antidote-sponsors",
      title: "Antidote for Sponsors",
      publisher: "Antidote Technologies",
      url: "https://www.antidote.me/sponsors",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"We thoroughly prescreen patients before referring them\"; \"Our payment model is a risk-sharing one that aligns your objectives\". Undated case highlights cover a UK asthma study, a US Alzheimer's study, a global psoriasis study and a North American COPD study.",
    },
    {
      id: "antidote-enterprise-match",
      title: "Enterprise Match",
      publisher: "Antidote Technologies",
      url: "https://www.antidote.me/sponsors/enterprise-match",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Enterprise Match is a SaaS offering that provides an accurate, patient-friendly search of all the trials you're running, right on your company's website.\" Patients answer eligibility questions themselves.",
    },
    {
      id: "antidote-rebrand-2016",
      title: "TrialReach Rebrands as Antidote and Expands its Products to Include EHR Matching",
      publisher: "Antidote Technologies (press release)",
      url: "https://www.antidote.me/press/press-release/trialreach-rebrands-as-antidote-and-expands-its-products-to-include-ehr-matching",
      year: "2016",
      note: "Press release dated September 20, 2016. Announces the rename from TrialReach to Antidote and, per its headline, an expansion of its products to include EHR matching.",
    },
    {
      id: "antidote-partners",
      title: "Partner with Antidote",
      publisher: "Antidote Technologies",
      url: "https://www.antidote.me/partners",
      year: "2026",
      note: "Accessed September 2026. Quote: \"A precision recruitment company that connects patients with research and educational resources through digital marketing and our partner network.\" For partners: \"Receive free, dynamic content for your site that requires no expertise to install or use\".",
    },
    {
      id: "antidote-seqster-2024",
      title: "Antidote Partners with SEQSTER to Accelerate Patient Identification & Enrollment for Clinical Trials",
      publisher: "SEQSTER PDM Inc. and Antidote Technologies via Business Wire (BioSpace)",
      url: "https://www.biospace.com/antidote-partners-with-seqster-to-accelerate-patient-identification-enrollment-for-clinical-trials",
      year: "2024",
      note: "Press release dated July 8, 2024. Quotes: \"Antidote can more accurately match patients to clinical trials based on a 360° view of their medical history, genomic data, and lifestyle factors.\" and \"contact center for patient support\".",
    },
    {
      id: "1nhealth-overview",
      title: "Company Overview",
      publisher: "1nHealth",
      url: "https://1nhealth.com/company-overview/",
      year: "2026",
      note: "Accessed September 2026. Quote: \"1nHealth is a U.S.-based clinical trial patient recruitment and enrollment company founded in 2019 and headquartered in Orlando, Florida. The company provides digital recruitment and enrollment management services to sponsors, biotech firms, and CROs.\"",
    },
    {
      id: "1nhealth-home",
      title: "1nHealth: We own enrollment (homepage FAQ)",
      publisher: "1nHealth",
      url: "https://1nhealth.com/",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Our pricing is based on specific milestones\" ... \"such as signed ICFs or patient randomization.\" The FAQ adds that flexible pricing models are available, and the page says research sites use its 1nData software.",
    },
    {
      id: "1nhealth-pharma",
      title: "Patient Recruitment For Pharma",
      publisher: "1nHealth",
      url: "https://1nhealth.com/patient-recruitment-for-pharma/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Our team conducts multiple levels of pre-screening before passing referrals on to your clinical sites.\"; \"We didn't choose direct-to-patient recruitment over databases because we wanted to be different\"; 1nData offers \"real-time patient insights, automated SMS follow-ups, and more\". Therapeutic areas listed: \"Cardiovascular, Gastrointestinal, Neurological, Infectious Diseases, Dermatology, Immunology, Pulmonary, Oncology\". The page also describes \"designing scroll-stopping ads\".",
    },
    {
      id: "iqvia-recruitment",
      title: "Patient Recruitment for Clinical Trials",
      publisher: "IQVIA",
      url: "https://www.iqvia.com/solutions/research-and-development/patient-and-site-centric-solutions/patient-recruitment",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"IQVIA uses AI-powered, protocol-specific patient models built on proprietary data to precisely identify and engage eligible participants\"; \"AI-powered EMR data mining\"; \"From chart review and prescreening to referral outreach and patient pathway mapping, Site Enrollment & Engagement Leads actively identify and engage patients.\"; \"call center support to extend site capacity\"; \"IQVIA's integrated patient- and site-facing technology (e.g., Study Hub, Referral Hub, eConsent/eCOA) streamlines education, screening, scheduling, communications, and referral-to-randomization workflows.\"; and, on consent, \"Plain-language content, multimedia tools, and accessibility features designed to improve understanding, support informed decision-making\". The page also describes a \"Health Marketing Network\" of outreach partners.",
    },
    {
      id: "veeva-faq",
      title: "SiteVault FAQ",
      publisher: "Veeva Systems",
      url: "https://sites.veeva.com/sitevault-faq",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Why is SiteVault free for up to 20 concurrent active studies?\" and \"The SiteVault Enterprise Package enables integration. SiteVault is the only eRegulatory application with an open, publicly available API. The free version of SiteVault integrates with other Veeva applications but does not currently integrate with third-party systems\"",
    },
    {
      id: "veeva-sites-home",
      title: "Veeva SiteVault for research sites",
      publisher: "Veeva Systems",
      url: "https://sites.veeva.com/",
      year: "2026",
      note: "Accessed September 2026. The page presents SiteVault CTMS, eISF and eSource in one system, lists SiteVault eConsent separately, and says \"Free for 90% of Sites.\" No patient recruitment or EHR screening features are described.",
    },
    {
      id: "crio-home",
      title: "CRIO clinical research platform",
      publisher: "Clinical Research IO (CRIO)",
      url: "https://clinicalresearch.io/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Beyond eSource, CRIO connects the full site workflow: eConsent, eRegulatory, and CTMS all live within a single platform.\" and \"CRIO is the leading eSource and clinical trial management platform, purpose-built for research sites and trusted by sponsors and CROs worldwide.\"",
    },
    {
      id: "crio-independent-sites",
      title: "Clinical Research Software Solutions for Independent Sites",
      publisher: "Clinical Research IO (CRIO)",
      url: "https://clinicalresearch.io/solutions/independent-sites/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Manage calling campaigns, send text blasts, build interactive prescreening questionnaires, and pull web leads directly into the system\" and \"Schedule visits and preprogram appointment reminders to keep patient visits on track\". The page also lists eConsent to \"Automate informed consent completion and execution\".",
    },
    {
      id: "crio-trially-2024",
      title: "CRIO-Trially Integration: Enhancing EMR Workflows and Patient Identification",
      publisher: "Clinical Research IO (CRIO)",
      url: "https://clinicalresearch.io/blog/company-news/crio-trially-integration-enhancing-emr-workflows-and-patient-identification/",
      year: "2024",
      note: "Published September 3, 2024. Quote: \"As a CRIO-certified API partner, Trially can\" ... \"integrate with CRIO's recruitment module in addition to EMR systems, to analyze a site's patient population and identify qualified patients based on protocol eligibility criteria.\"",
    },
    {
      id: "realtime-home",
      title: "RealTime eClinical Solutions homepage",
      publisher: "RealTime eClinical Solutions",
      url: "https://realtime-eclinical.com/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Site Operations Management System (SOMS) delivers the essential eClinical tools your research organization needs in a single, integrated platform.\"; \"Recruit, remind, and connect with participants\" (Engage!); \"Automated patient communication & reminders.\" (Text solution); \"eConsent\"; customer groups listed as \"Sites, Networks, SMOS AMCS & Health Systems Sponsors & CRO's\".",
    },
    {
      id: "realtime-ctms",
      title: "CTMS | Clinical Trial Management System",
      publisher: "RealTime eClinical Solutions",
      url: "https://realtime-eclinical.com/solutions/ctms/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Grow your patient database with integrations for your website, Facebook ads, SubjectWell, and more.\"; \"Instant CTMS sync creates subject profiles automatically from website form submissions\"; \"Accelerate scheduling with automated study target dates and window calculations, text reminders, and Outlook integration.\"; \"Remarket directly from your database with our Mailchimp integration for email blasts and mass texting campaigns.\"",
    },
    {
      id: "realtime-api",
      title: "API & Integrations",
      publisher: "RealTime eClinical Solutions",
      url: "https://realtime-eclinical.com/api-integrations/",
      year: "2026",
      note: "Accessed September 2026. Quote: the API offers \"a simple and efficient way to seamlessly integrate RealTime data with your other critical systems such as CRM, ERP, EMR, analytics, and business intelligence (BI) platforms.\" Named integrations: Devana, Mailchimp, Microsoft Outlook, SubjectWell and Twilio.",
    },
    {
      id: "realtime-pricing",
      title: "Pricing",
      publisher: "RealTime eClinical Solutions",
      url: "https://realtime-eclinical.com/pricing/",
      year: "2026",
      note: "Accessed September 2026. Quote: \"Transparent pricing that scales with your organization. No hidden fees, no surprises.\" The page offers pricing requests by organization type (sites, networks, AMCs, sponsors, CROs) and lists no prices.",
    },
    {
      id: "medable-recruitment-guide",
      title: "What is clinical trial recruitment?",
      publisher: "Medable",
      url: "https://www.medable.com/knowledge-center/guides-what-is-clinical-trial-recruitment",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Medable's Digital & DCT screening tools can help study teams create a unified recruitment strategy\" and \"Medable can help streamline the process with solutions like TeleConsent, ePRO and TeleVisit.\"",
    },
    {
      id: "medable-agent-studio-2025",
      title: "Medable Launches The Industry's First Agentic AI Platform and CRA Agent; Removes Bottlenecks in Clinical Development",
      publisher: "Medable",
      url: "https://www.medable.com/newsroom/medable-launches-the-industrys-first-agentic-ai-platform-and-cra-agent-removes-bottlenecks-in-clinical-development",
      year: "2025",
      note: "Press release dated September 3, 2025. Describes Agent Studio as \"the industry's first agentic AI platform purpose-built for life sciences\".",
    },
    {
      id: "science37-about",
      title: "About Us",
      publisher: "Science 37",
      url: "https://www.science37.com/about-us/",
      year: "2026",
      note: "Accessed September 2026. Quotes: \"Science 37 is a modern clinical research site that delivers trials directly to patients' homes.\" and that it operates \"under a single Form FDA 1572 and a central IRB\".",
    },
    {
      id: "science37-home",
      title: "Science 37 homepage",
      publisher: "Science 37",
      url: "https://www.science37.com/",
      year: "2026",
      note: "Accessed September 2026. Therapeutic areas listed: \"Cardiovascular, Central Nervous System, Dermatology, Endocrinology, Gastroenterology, Hematology, Immunology, Infectious Disease, Men's Health, Musculoskeletal, Oncology, Ophthalmology, Respiratory, Urology, Women's Health\". Also: \"PatientsLikeMe and Science 37 Partner to Unlock Trial Access for Interested, Eligible Patients\".",
    },
    {
      id: "unlu-2024-rectifier",
      title: "Retrieval Augmented Generation Enabled GPT-4 Performance for Clinical Trial Screening (Unlu O et al.)",
      publisher: "medRxiv preprint via PubMed Central; peer-reviewed version in NEJM AI",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10871450/",
      year: "2024",
      note: "Describes manual screening for the COPILOT-HF trial. Quote: \"Trained, but non-licensed, study staff complete manual chart review to determine patient eligibility\"",
    },
    {
      id: "scrs-landscape-2025",
      title: "Navigating the Patient Recruitment Landscape: A Framework for Sites, Sponsors, and CROs",
      publisher: "Society for Clinical Research Sites (SCRS) InFocus",
      url: "https://myscrs.org/resources/patient-recruitment-landscape/",
      year: "2025",
      note: "Published October 22, 2025; authors are from TrialScreen, a recruitment vendor. Quote: \"Coordinators already juggle several systems with upwards of 22 logins for a single study\"",
    },
    ...testimonialSources(),
  ],
  related: [
    { label: "All comparisons", href: "/compare", description: "One-on-one comparisons of Bond with each type of recruitment tool." },
    { label: "Pricing", href: "/pricing", description: "No integration fee: a volume-based platform fee plus a success fee per randomized patient." },
    { label: "Security", href: "/security", description: "HIPAA and SOC 2 Type I compliance, BAAs, access control and audit logging." },
    { label: "Identify", href: "/identify", description: "How Bond screens structured fields and notes against a protocol." },
    { label: "Engage", href: "/engage", description: "Voice and SMS outreach, pre-screening and scheduling." },
    { label: "Consent", href: "/consent", description: "Plain-language explanations, patient Q&A and staff escalation; the site obtains consent." },
  ],
};

export default page;
