import type { SeoPage } from "../types";

const page: SeoPage = {
  path: "/neurology-and-alzheimers",
  category: "therapeutic",
  title: "Alzheimer's trial recruitment: amyloid and screen failure",
  description:
    "How Alzheimer's eligibility works: cognitive scores, amyloid PET or CSF, MRI exclusions and study partners, why screen failure runs high, and how Bond screens.",
  keywords: [
    "Alzheimer's clinical trial recruitment",
    "Alzheimer's trial screen failure",
    "amyloid PET screening clinical trials",
    "study partner requirement Alzheimer's trials",
    "neurology clinical trial recruitment",
  ],
  eyebrow: "Neurology and Alzheimer's",
  h1: "Neurology and Alzheimer's trials: cognitive scores, amyloid, and study partners",
  intro:
    "Alzheimer's protocols screen for things a problem list rarely holds: a cognitive score inside a set window, amyloid confirmed by PET or spinal fluid, a clean brain MRI, and a study partner. At two California sites screening for a Phase 2 anti-amyloid antibody trial in 2024, 147 of 185 people failed screening.{{cite:huoh-2025}} Most of these criteria live in free-text notes and reports, not structured fields.",
  summary: "How Alzheimer's criteria map to the chart, why screen failure runs high, and how Bond screens for it.",
  lastUpdated: "2026-09-24",
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "How Identify works", secondaryHref: "/identify" },
  sections: [
    {
      id: "how-eligibility-works",
      heading: "How does eligibility work in Alzheimer's trials?",
      blocks: [
        {
          type: "p",
          text: "Early Alzheimer's protocols define a participant in layers: clinical stage, a cognitive score window, objective memory impairment, and amyloid confirmed by PET or cerebrospinal fluid. Clarity AD, the Phase 3 lecanemab trial, enrolled people aged 50 to 90 on that basis.{{cite:honig-2024}} Antibody trials add MRI exclusions, and Alzheimer's trials typically require a study partner.{{cite:grill-2013,grill-karlawish-2017}}",
        },
        {
          type: "table",
          caption: "Common criteria and where the evidence lives (Clarity AD unless noted)",
          columns: ["Criterion", "Example protocol language", "Where it lives in the chart", "Structured or unstructured?"],
          rows: [
            ["Clinical stage", "NIA-AA criteria for MCI due to AD or mild AD dementia; global CDR 0.5 to 1.0{{cite:clarity-ad-ctgov}}", "Neurology and memory clinic notes; codes rarely record the stage", "Mostly unstructured"],
            ["Cognitive score", "MMSE 22 to 30; 20 to 28 in TRAILBLAZER-ALZ 2{{cite:clarity-ad-ctgov,trailblazer-alz2-ctgov}}", "Neurology or primary care notes", "Mostly unstructured"],
            ["Memory impairment", "At least 1 standard deviation below the age-adjusted mean on Logical Memory II{{cite:clarity-ad-ctgov}}", "Neuropsychology reports, if testing was done", "Unstructured"],
            ["Amyloid", "Positive amyloid biomarker by PET or CSF{{cite:clarity-ad-ctgov,honig-2024}}", "PET reports and CSF results, often from outside centers", "Mixed"],
            ["Tau PET, some trials", "Meets flortaucipir PET criteria (TRAILBLAZER-ALZ 2){{cite:trailblazer-alz2-ctgov}}", "Rarely in the chart before screening", "Unstructured"],
            ["MRI findings", "Excludes more than 4 microhemorrhages, superficial siderosis, severe white matter disease{{cite:clarity-ad-ctgov}}", "Brain MRI reports", "Unstructured"],
            ["Medications", "Cholinesterase inhibitor or memantine stable 12 weeks; anticoagulant stable 4 weeks{{cite:clarity-ad-ctgov}}", "Medication lists and orders", "Structured"],
            ["Prior anti-amyloid drug", "No known prior lecanemab; no prior anti-amyloid trial drug unless placebo{{cite:clarity-ad-ctgov}}", "Infusion history, research notes", "Mixed"],
            ["Study partner", "Spends at least 8 hours per week with the participant{{cite:clarity-ad-ctgov}}", "Social history, notes naming who attends visits", "Unstructured"],
            ["Consent capacity", "If the investigator judges capacity lacking, a legal representative consents where local law allows{{cite:clarity-ad-ctgov}}", "Capacity notes, health care proxy documents", "Unstructured"],
          ],
        },
        {
          type: "p",
          text: "A patient can match on a diagnosis code and fail on one sentence in a memory clinic note or MRI report. Parkinson's, multiple sclerosis, epilepsy and migraine trials use their own scales, and that evidence also sits mostly in neurology notes and imaging. See [therapeutic areas](/therapeutic-areas) for other diseases.",
        },
      ],
    },
    {
      id: "screen-failure",
      heading: "Why do so many Alzheimer's trial candidates fail screening?",
      blocks: [
        {
          type: "p",
          text: "Start with how little is reported. A 2026 review of nearly 1,000 publications on Alzheimer's trial recruitment found that only 14% reported how many screened people enrolled, and 4% a monthly recruitment rate.{{cite:schaeffer-2026}} The published data is thin, and the figures that exist are high.",
        },
        {
          type: "stats",
          items: [
            { value: "147 of 185", label: "people screened at two sites in 2024 for a Phase 2 anti-amyloid antibody trial failed screening", cite: "huoh-2025" },
            { value: "17%", label: "of 6,763 people screened for the A4 prevention trial were randomized", cite: "a4-screening-2026" },
            { value: "39%", label: "of patients with an evaluable PET scan in a Phase 1b trial were excluded as amyloid negative", cite: "sevigny-2016" },
          ],
        },
        {
          type: "p",
          text: "Amyloid is a gate the chart cannot settle without a biomarker result. In that Phase 1b trial, everyone scanned met clinical criteria for prodromal or mild Alzheimer's, yet 39% of those with an evaluable scan were excluded as amyloid negative.{{cite:sevigny-2016}} Among cognitively normal adults screening for the A4 study, only 29.5% of the 4,486 scanned were amyloid positive.{{cite:sperling-2020}} A4 screening took up to five visits over 90 days.{{cite:a4-screening-2026}}",
        },
        {
          type: "p",
          text: "Where candidates come from matters too. In Europe's EPAD program, 6.9 people were prescreened per eligible amyloid-positive participant in a memory clinic cohort, against 88.5 in a population cohort.{{cite:vermunt-2020}} The clinic group was already trial-interested with a partner available, which explains part of the gap, but it still favors starting with a site's own memory and neurology patients. See [how to reduce screen failure](/guides/reduce-screen-failure).",
        },
      ],
    },
    {
      id: "mri-and-aria",
      heading: "How do MRI findings and ARIA risk shape eligibility?",
      blocks: [
        {
          type: "p",
          text: "Anti-amyloid antibodies can cause amyloid-related imaging abnormalities (ARIA), swelling or small bleeds seen on MRI. The lecanemab pivotal trial excluded people with more than 4 microhemorrhages, a prior cerebral hemorrhage over 1 cm, superficial siderosis, vasogenic edema, an aneurysm or a vascular malformation.{{cite:fda-leqembi-2025}}",
        },
        {
          type: "p",
          text: "ApoE ε4 homozygotes, about 15% of Alzheimer's patients, have higher rates of ARIA, including serious ARIA. In the lecanemab pivotal trial, ARIA occurred in 45% of homozygotes on drug against 22% on placebo.{{cite:fda-leqembi-2025}} Across all patients in the donanemab pivotal trial, ARIA occurred in 36% on drug and 14% on placebo.{{cite:fda-kisunla-2024}}",
        },
        {
          type: "p",
          text: "Both drugs are now prescribed, which changes what charts hold. As of September 2026, both FDA labels call for confirmed amyloid, ApoE ε4 testing and a baseline brain MRI before treatment, then scheduled follow-up MRIs.{{cite:dailymed-leqembi-2026,dailymed-kisunla-2026}} A patient evaluated for either drug may already have the results a trial asks for. A treated patient may be excluded: Clarity AD barred anyone with known prior lecanemab exposure.{{cite:clarity-ad-ctgov}}",
        },
      ],
    },
    {
      id: "study-partners-and-consent",
      heading: "What do study partner and consent rules add to recruitment?",
      blocks: [
        {
          type: "p",
          text: "Alzheimer's dementia trials enroll two people, a patient and a study partner. In six Alzheimer's Disease Cooperative Study trials, 67% of participants enrolled with a spouse, 26% with an adult child and 7% with someone else; dropout was 25%, 32% and 34%, though only the spouse versus other gap was statistically significant.{{cite:grill-2013}} Preclinical trials require partners too, which Grill and Karlawish call a barrier to recruitment.{{cite:grill-karlawish-2017}}",
        },
        {
          type: "p",
          text: "Capacity is the other difference. Under the Common Rule, who can act as a legally authorized representative depends on applicable law, so it varies by state and institution.{{cite:cfr-46-102}} In an interview study using hypothetical trials, 37.7% of people with Alzheimer's judged unable to consent to a drug trial could still appoint a research proxy.{{cite:kim-2011}} In a randomized trial, a plain-language memory aid made people with Alzheimer's more likely to be judged capable of consenting.{{cite:rubright-2010}}",
        },
        {
          type: "callout",
          tone: "info",
          title: "Two people to reach, not one",
          text: "Confirm the partner as early as the patient: who they are, whether they can attend visits, and whether they can give the time asked. Clarity AD asked for at least 8 hours per week.{{cite:clarity-ad-ctgov}}",
        },
      ],
    },
    {
      id: "what-bond-reads",
      heading: "What does Bond read in the chart to find Alzheimer's candidates?",
      blocks: [
        {
          type: "p",
          text: "Bond's [Identify](/identify) stage reads structured and unstructured records against each inclusion and exclusion criterion, ranks candidates, and shows the evidence behind each decision.{{cite:bond-site}} It uses imaging data, clinical notes and other unstructured documents, including pathology, radiology and molecular reports.{{cite:bond-product}} It connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR or HL7 interfaces or through an aggregator.{{cite:bond-site,bond-product}}",
        },
        {
          type: "steps",
          items: [
            {
              title: "Memory clinic notes",
              text: "MMSE or MoCA scores with dates, and the clinician's staging. Bond's terminology graph maps synonyms and codes across SNOMED CT, ICD-10-CM, LOINC and other vocabularies, so differently worded criteria and notes still match.{{cite:bond-whitepaper}}",
            },
            {
              title: "Biomarker results",
              text: "Amyloid PET reports, CSF results and ApoE genotype. A documented negative amyloid result flags a likely exclusion before a visit is booked.",
            },
            {
              title: "Brain MRI reports",
              text: "Microhemorrhages, siderosis, prior hemorrhage and white matter disease, read against the protocol's MRI exclusions.",
            },
            {
              title: "Medications",
              text: "Anticoagulants with start dates, cholinesterase inhibitor and memantine dose history, and prior anti-amyloid infusions.",
            },
            {
              title: "Partner and capacity signals",
              text: "Notes naming who comes to visits, health care proxy documents and capacity assessments. These suggest; they do not decide.",
            },
          ],
        },
        {
          type: "p",
          text: "What the chart cannot settle goes to people. Partner availability and willingness to have PET or a lumbar puncture are pre-screening questions for Bond's [Engage](/engage) voice and text agents or site staff; patients are told AI assistance is used and can reach a person at any time, through a live transfer to a coordinator or a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Capacity is the investigator's judgment, and the site obtains consent, with [Consent](/consent) support explaining the study in plain language.",
        },
        {
          type: "callout",
          tone: "bond",
          title: "What Bond has published, and what it has not",
          text: "Bond reports above 90% matching accuracy and more than 50% less chart review; full EHR integration typically takes 48 hours.{{cite:bond-site}} None is neurology-specific, and Bond has not published neurology screen failure or enrollment results. Site reporting tracks matches, pre-screens, randomizations and screen-failure signals for each study.",
        },
      ],
    },
    {
      id: "trial-pool",
      heading: "How many neurology and Alzheimer's trials are recruiting in the US?",
      blocks: [
        {
          type: "p",
          text: "As of September 21, 2026, 987 of the 22,041 recruiting studies with a US site matched a neurology keyword search of the condition field: Alzheimer, dementia, Parkinson, multiple sclerosis, migraine or epilepsy.{{cite:ctgov-api}} The count includes observational studies and is not Alzheimer's-only. Migraine studies also fall under pain, and a study can count in more than one area.",
        },
        {
          type: "chart",
          title: "Recruiting studies with at least one US site, by area (keyword search, September 21, 2026)",
          unit: "studies",
          data: [
            { label: "Oncology", value: 7074 },
            { label: "Cardiology", value: 2845 },
            { label: "Psychiatry", value: 1273 },
            { label: "Neurology", value: 987 },
            { label: "Obesity and type 2 diabetes", value: 852 },
            { label: "Pain", value: 629 },
            { label: "Gastroenterology", value: 285 },
            { label: "Dermatology", value: 214 },
          ],
          cite: "ctgov-api",
        },
        {
          type: "p",
          text: "The 2026 pipeline census (index date January 1, 2026) counted 158 drugs in 192 Alzheimer's trials worldwide, needing 54,728 participants, 38,417 of them in Phase 3.{{cite:cummings-2026}} The 2024 census found that Phase 3 disease-modifying trials of biologics planned an average of 3.5 years to recruit.{{cite:cummings-2024}} In two decades of NIH-funded Alzheimer's Disease Cooperative Study trials, none recruited more than one participant per site per month overall.{{cite:ritchie-2023}}",
        },
        {
          type: "table",
          caption: "US patient populations behind these trials",
          columns: ["Condition", "US estimate"],
          rows: [
            ["Alzheimer's dementia, age 65 and older", "7.4 million in 2026 (model-based){{cite:alz-facts-2026}}"],
            ["Parkinson's disease", "1.1 million{{cite:parkinson-foundation}}"],
            ["Multiple sclerosis", "727,344 adults in 2010 (claims-based){{cite:wallin-2019}}"],
            ["Epilepsy with uncontrolled seizures", "About 1.5 million adults, 2021 to 2022 (self-reported){{cite:kobau-2024}}"],
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one neurology protocol and we will walk through how its hardest criteria, such as amyloid status and MRI exclusions, map to your chart.",
          secondaryLabel: "Reduce screen failure",
          secondaryHref: "/guides/reduce-screen-failure",
        },
      ],
    },
  ],
  faq: [
    {
      q: "What screen failure rate should an Alzheimer's site expect?",
      a: "Published data is thin, and the rates it shows are high: at two sites screening for a Phase 2 antibody trial in 2024, 147 of 185 people failed, and the A4 prevention study randomized about 17% of those it screened.{{cite:huoh-2025,a4-screening-2026}}",
    },
    {
      q: "Can Bond find patients who have not had an amyloid test?",
      a: "Yes, as candidates for biomarker testing. Each match shows the chart evidence per criterion, so amyloid status stays open for confirmation at screening.{{cite:bond-site}}",
    },
    {
      q: "Does Bond contact the study partner?",
      a: "Only as the site configures it. Scripts are set per site and study, so a pre-screening call can ask who would serve as the partner.{{cite:bond-site}} The site and its IRB-approved materials decide whether and how the partner is contacted.",
    },
    {
      q: "Does Bond decide whether a patient can consent?",
      a: "No. Capacity and consent stay with the investigator under the site's IRB-approved process. Bond's consent support explains the study in plain language and escalates questions to staff.{{cite:bond-site}}",
    },
  ],
  sources: [
    {
      id: "huoh-2025",
      title: "Non-inferior screen fail rate for persons under the age of 65 in an anti-amyloid monoclonal antibody clinical trial on Alzheimer's Disease",
      publisher: "Alzheimer's & Dementia (Huoh et al., AAIC abstract)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12741874/",
      year: "2025",
      note: "Conference abstract; two sites in the Irvine Clinical network, California, 2024 screening year. Quote: \"In 2024, 185 persons were screened for a Phase 2 clinical trial of an anti-amyloid monoclonal antibody in early AD across two sites ... The overall screen failure rate was 74.1% (147 screen fails).\" The abstract's stated 74.1% does not match its own counts: 147 of 185 is 79.5%, and it reports age-group rates of 78.2% (ages 55 to 64) and 79.9% (65 and older). This page therefore uses the counts, 147 of 185.",
    },
    {
      id: "a4-screening-2026",
      title: "Cognitive screening biases in a secondary prevention Alzheimer's disease clinical trial",
      publisher: "Alzheimer's & Dementia",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12958866/",
      year: "2026",
      note: "A4 secondary-prevention trial, cognitively unimpaired adults. Quote: \"The A4 study screened 6763 individuals ... to identify 1169 A+ CU older adults who were randomized into drug or placebo arms. The screening process involved up to five visits over 90 days\"",
    },
    {
      id: "sperling-2020",
      title: "Association of Factors With Elevated Amyloid Burden in Clinically Normal Older Individuals",
      publisher: "JAMA Neurology (Sperling RA et al.)",
      url: "https://pubmed.ncbi.nlm.nih.gov/32250387/",
      year: "2020",
      note: "A4 study screening data. Abstract text checked via Europe PMC on September 22, 2026. Quote: \"Amyloid PET results were acquired for 4486 participants (mean [SD] age, 71.29 [4.67] years; 2647 women [59%]), with 1323 (29.5%) classified as Aβ+.\"",
    },
    {
      id: "sevigny-2016",
      title: "Amyloid PET Screening for Enrichment of Early-Stage Alzheimer Disease Clinical Trials: Experience in a Phase 1b Clinical Trial",
      publisher: "Alzheimer Disease & Associated Disorders (Sevigny J et al.)",
      url: "https://pubmed.ncbi.nlm.nih.gov/26885819/",
      year: "2016",
      note: "Quote: \"Of 278 patients with an evaluable PET scan, 170 (61%) and 185 (67%) were amyloid-positive by visual reading and quantitative analysis, respectively; 39% were excluded from the study due to an amyloid-negative scan based on visual readings.\"",
    },
    {
      id: "vermunt-2020",
      title: "Prescreening for European Prevention of Alzheimer Dementia (EPAD) trial-ready cohort: impact of AD risk factors and recruitment settings",
      publisher: "Alzheimer's Research & Therapy (Vermunt L et al.)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6945608/",
      year: "2020",
      note: "European data, four cohorts; the clinical cohort is the Toulouse memory clinic registry, whose inclusion criteria were interest in clinical trials and an available study partner. Quote: \"The NNPS were 6.9 (clinical cohort), 7.5 (research in-person cohort), 8.4 (research online cohort), and 88.5 (population-based cohort).\" \"the NNPS to find one eligible amyloid-positive participant varied\"",
    },
    {
      id: "schaeffer-2026",
      title: "What Nearly 1,000 Studies Reveal About Alzheimer's Clinical Trial Recruitment",
      publisher: "USC Schaeffer Center",
      url: "https://schaeffer.usc.edu/research/alzheimers-trial-recruitment-study-analysis/",
      year: "2026",
      note: "Summary of a literature review in the Journal of Prevention of Alzheimer's Disease. Quote: \"Only 18% of studies reported how many individuals contacted to participate in trials were screened (yield rate), while only 14% reported how many of those screened were enrolled (conversion rate). Only 4% reported monthly enrollment figures (recruitment rate).\"",
    },
    {
      id: "honig-2024",
      title: "Updated safety results from phase 3 lecanemab study in early Alzheimer's disease",
      publisher: "Alzheimer's Research & Therapy (Honig LS et al.)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11084061/",
      year: "2024",
      note: "Clarity AD methods. Quote: \"age 50 to 90 years old\"; \"amyloid pathology confirmed by amyloid positron emission tomography (PET) or cerebrospinal fluid (CSF)\"; \"All participants were required to have objective impairment in episodic memory as indicated by at least 1 standard deviation below the age-adjusted mean in the Wechsler Memory Scale IV-Logical Memory (subscale) II.\"",
    },
    {
      id: "clarity-ad-ctgov",
      title: "A Placebo-Controlled, Double-Blind, Parallel-Group, 18-Month Study With an Open-Label Extension Phase to Confirm Safety and Efficacy of BAN2401 in Subjects With Early Alzheimer's Disease (Clarity AD, NCT03887455)",
      publisher: "ClinicalTrials.gov (Eisai)",
      url: "https://clinicaltrials.gov/study/NCT03887455",
      year: "2026",
      note: "Eligibility text read from this record through the ClinicalTrials.gov API v2 (https://clinicaltrials.gov/api/v2/studies/NCT03887455) on September 22, 2026. Quote: \"Meet the National Institute of Aging - Alzheimer's Association (NIA-AA) core clinical criteria for MCI due to Alzheimer's disease - intermediate likelihood\"; \"Have a global CDR score of 0.5 to 1.0\" (mild AD dementia); \"Objective impairment in episodic memory as indicated by at least 1 standard deviation below age-adjusted mean in the Wechsler Memory Scale IV-Logical Memory (subscale) II\"; \"Positive biomarker for brain amyloid pathology\"; \"Mini mental state examination (MMSE) score >=22 at Screening and Baseline and <=30 at Screening and Baseline\"; \"If receiving an approved Alzheimer's disease treatment such as acetylcholinesterase inhibitor (AChEIs) or memantine or both for Alzheimer's disease, must be on a stable dose for at least 12 weeks prior to Baseline\"; \"Have an identified study partner (defined as a person able to support the participant for the duration of the study and who spends at least 8 hours per week with the participant)\"; \"If a participant lacks capacity to consent in the investigator's opinion ... the written informed consent of a legal representative should be obtained\"; exclusions: \"more than 4 microhemorrhages ... an area of superficial siderosis ... severe small vessel, or white matter disease\"; \"Participants who are on anticoagulant therapy should have their anticoagulant status optimized and be on a stable dose for 4 weeks before Screening\"; \"Participation in a clinical study involving any anti-amyloid therapies ... unless it can be documented that the participant only received placebo\"; \"Participants who have any known prior exposure to lecanemab\".",
    },
    {
      id: "trailblazer-alz2-ctgov",
      title: "A Study of Donanemab (LY3002813) in Participants With Early Alzheimer's Disease (TRAILBLAZER-ALZ 2) (NCT04437511)",
      publisher: "ClinicalTrials.gov (Eli Lilly and Company)",
      url: "https://clinicaltrials.gov/study/NCT04437511",
      year: "2026",
      note: "Eligibility text read from this record through the ClinicalTrials.gov API v2 (https://clinicaltrials.gov/api/v2/studies/NCT04437511) on September 22, 2026. Quote: \"MMSE score of 20 to 28 (inclusive) at baseline\"; \"Meet 18F flortaucipir PET scan (central read) criteria\"; \"Have a study partner who will provide written informed consent to participate\".",
    },
    {
      id: "fda-leqembi-2025",
      title: "LEQEMBI (lecanemab-irmb) Prescribing Information (revised 8/2025)",
      publisher: "U.S. Food and Drug Administration",
      url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761375s000lbl.pdf",
      year: "2025",
      note: "Quote: \"Patients were excluded from enrollment in Study 2 for the presence of more than 4 microhemorrhages and additional findings suggestive of cerebral amyloid angiopathy (prior cerebral hemorrhage greater than 1 cm in greatest diameter, superficial siderosis, vasogenic edema) or other lesions (aneurysm, vascular malformation)\"; \"apolipoprotein E ε4 (ApoE ε4) homozygotes (approximately 15% of Alzheimer's disease patients)\"; \"The incidence of ARIA was higher in ApoE ε4 homozygotes (45% on LEQEMBI vs. 22% on placebo) than in heterozygotes (19% on LEQEMBI vs 9% on placebo) and noncarriers (13% on LEQEMBI vs 4% on placebo).\" The same passages appear in the July 2026 revision.",
    },
    {
      id: "dailymed-leqembi-2026",
      title: "LEQEMBI (lecanemab-irmb) Prescribing Information (revised 7/2026)",
      publisher: "DailyMed, U.S. National Library of Medicine",
      url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9d1ff786-e577-410a-a273-c4d7d0e4e975",
      year: "2026",
      note: "Label version published on DailyMed July 27, 2026; checked September 22, 2026. It replaces the earlier schedule of MRIs before the 3rd, 5th, 7th and 14th infusions. Quote: \"Confirm the presence of amyloid beta pathology prior to initiating treatment.\" \"Obtain a recent baseline brain MRI prior to initiating treatment.\" \"Obtain an MRI after 1, 2, 3, and 6 months of treatment.\" \"Testing for ApoE ε4 status should be performed prior to initiation of treatment to inform the risk of developing ARIA.\"",
    },
    {
      id: "dailymed-kisunla-2026",
      title: "KISUNLA (donanemab-azbt) Prescribing Information",
      publisher: "DailyMed, U.S. National Library of Medicine",
      url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=190352d4-ef62-4679-b4fa-e846e2766afa",
      year: "2026",
      note: "Label version published on DailyMed January 2, 2026; checked September 22, 2026. Quote: \"Confirm the presence of amyloid beta pathology prior to initiating treatment.\" \"Obtain a recent baseline brain MRI prior to initiating treatment.\" \"Obtain an MRI prior to the 2nd, 3rd, 4th, and 7th infusions.\" \"Testing for ApoE ε4 status should be performed prior to initiation of treatment\"",
    },
    {
      id: "fda-kisunla-2024",
      title: "KISUNLA (donanemab-azbt) Prescribing Information (revised 7/2024)",
      publisher: "U.S. Food and Drug Administration",
      url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761248s000lbl.pdf",
      year: "2024",
      note: "Quote: \"Including asymptomatic radiographic events, ARIA was observed in 36% (307/853) of patients treated with KISUNLA, compared to 14% (122/874) of patients on placebo in Study 1.\"",
    },
    {
      id: "grill-2013",
      title: "Effect of study partner on the conduct of Alzheimer disease clinical trials",
      publisher: "Neurology (Grill JD, Raman R, Ernstrom K, Aisen P, Karlawish J)",
      url: "https://pubmed.ncbi.nlm.nih.gov/23255824/",
      year: "2013",
      note: "Six Alzheimer's Disease Cooperative Study trials. Quote: \"Alzheimer disease (AD) dementia clinical trials require 2 participants: a patient and a study partner. ... More participants (67%) enrolled with spouses than adult children (26%) or other study partners (7%). Participants with spouse partners had a lower dropout rate (25%) than those with adult child (32%) or other study partners (34%); only the difference vs. others was statistically significant.\"",
    },
    {
      id: "grill-karlawish-2017",
      title: "Study partners should be required in preclinical Alzheimer's disease trials",
      publisher: "Alzheimer's Research & Therapy (Grill JD, Karlawish J)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5719524/",
      year: "2017",
      note: "Quote: \"Yet, like AD dementia trials, preclinical trials require dual enrollment of a participant and a knowledgeable informant, or study partner. The requirement of dyadic enrollment is a barrier to recruitment and may present unique ethical challenges.\"",
    },
    {
      id: "cfr-46-102",
      title: "45 CFR 46.102 Definitions for purposes of this policy",
      publisher: "U.S. Government Publishing Office (Code of Federal Regulations, 2023 edition)",
      url: "https://www.govinfo.gov/content/pkg/CFR-2023-title45-vol1/xml/CFR-2023-title45-vol1-sec46-102.xml",
      year: "2023",
      note: "Quote: \"Legally authorized representative means an individual or judicial or other body authorized under applicable law to consent on behalf of a prospective subject to the subject's participation in the procedure(s) involved in the research. If there is no applicable law addressing this issue, legally authorized representative means an individual recognized by institutional policy as acceptable for providing consent in the nonresearch context\"",
    },
    {
      id: "kim-2011",
      title: "Preservation of the capacity to appoint a proxy decision maker: implications for dementia research",
      publisher: "Archives of General Psychiatry (Kim SY, Karlawish JH, et al.)",
      url: "https://pubmed.ncbi.nlm.nih.gov/21300949/",
      year: "2011",
      note: "Interview study of 188 people with Alzheimer's using 2 hypothetical research scenarios. Abstract text checked via Europe PMC on September 22, 2026. Quote: \"Data showed that 37.7% (40 of 106) of those deemed incapable of consenting to the drug RCT and 54.8% (86 of 157) of those deemed incapable of consenting to the neurosurgical RCT were found capable of appointing a research proxy.\"",
    },
    {
      id: "rubright-2010",
      title: "A memory and organizational aid improves Alzheimer disease research consent capacity: results of a randomized, controlled trial",
      publisher: "American Journal of Geriatric Psychiatry (Rubright J, Sankar P, Casarett DJ, Gur R, Xie SX, Karlawish J)",
      url: "https://pubmed.ncbi.nlm.nih.gov/20808101/",
      year: "2010",
      note: "Abstract text checked via Europe PMC on September 22, 2026. Quote: \"The intervention group was more likely to be judged competent than control group and had higher scores on MacCAT-CR measure of understanding.\"",
    },
    {
      id: "alz-facts-2026",
      title: "2026 Alzheimer's Disease Facts and Figures",
      publisher: "Alzheimer's Association",
      url: "https://www.alz.org/alzheimers-dementia/facts-figures",
      year: "2026",
      note: "Quote: \"An estimated 7.4 million Americans age 65 and older are living with Alzheimer's in 2026.\" \"About 1 in 9 people age 65 and older (11%) has Alzheimer's.\"",
    },
    {
      id: "cummings-2026",
      title: "Alzheimer's disease drug development pipeline: 2026",
      publisher: "Alzheimer's & Dementia: Translational Research & Clinical Interventions (Cummings JL et al.)",
      url: "https://pubmed.ncbi.nlm.nih.gov/42095064/",
      year: "2026",
      note: "Index date January 1, 2026; trials worldwide. Quote: \"There are currently 158 drugs in 192 AD trials. ... Currently active trials require 54,728 participants of which 38,417 are in Phase 3.\"",
    },
    {
      id: "cummings-2024",
      title: "Alzheimer's disease drug development pipeline: 2024",
      publisher: "Alzheimer's & Dementia: Translational Research & Clinical Interventions (Cummings J et al.)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11040692/",
      year: "2024",
      note: "Planned, not observed, recruitment periods. Quote: \"On average, DMT Phase 3 trials (not including prevention trials) of biologics will require 3.5 years and small molecules will require 2.2 years to recruit the needed number of patients.\"",
    },
    {
      id: "ritchie-2023",
      title: "Recruitment across two decades of NIH-funded Alzheimer's disease clinical trials",
      publisher: "Alzheimer's Research & Therapy (Ritchie M, Gillen DL, Grill JD)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9893207/",
      year: "2023",
      note: "Quote: \"No trial achieved an overall recruitment rate greater than one subject per site per month.\"",
    },
    {
      id: "parkinson-foundation",
      title: "Parkinson's Disease Statistics",
      publisher: "Parkinson's Foundation",
      url: "https://www.parkinson.org/understanding-parkinsons/statistics",
      year: "2026",
      note: "Quote: \"An estimated 1.1 million people in the U.S. are living with Parkinson's disease (PD). ... Nearly an estimated 90,000 people in the U.S. are diagnosed with PD each year.\"",
    },
    {
      id: "wallin-2019",
      title: "The prevalence of MS in the United States: A population-based estimate using health claims data",
      publisher: "Neurology (Wallin MT et al.)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6442006/",
      year: "2019",
      note: "The 2017 figures are extrapolations the authors say should be viewed with caution. Quote: \"The estimated 2010 prevalence of MS in the US adult population cumulated over 10 years was 309.2 per 100,000 (95% confidence interval [CI] 308.1-310.1), representing 727,344 cases.\"",
    },
    {
      id: "kobau-2024",
      title: "About 1.5 million community-dwelling US adults with active epilepsy reported uncontrolled seizures in the past 12 months, and seizure control varied by annual family income-National Health Interview Survey, United States 2021 and 2022",
      publisher: "Epilepsy & Behavior (Kobau R, Luncheon C, Greenlund KJ; CDC)",
      url: "https://pubmed.ncbi.nlm.nih.gov/38820685/",
      year: "2024",
    },
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Queried September 21, 2026.",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, September 2026.",
    },
    {
      id: "bond-whitepaper",
      title: "Terminology Infrastructure and Graph-Grounded RAG for Clinical Trial Patient Matching",
      publisher: "Bond Health, preprint",
      year: "2026",
      note: "Goel R. Bond Health preprint, August 2026. No public URL yet.",
    },
  ],
  related: [
    { label: "Identify: LLM-based EHR screening", href: "/identify", description: "How Bond reads notes, reports and structured data against each criterion." },
    { label: "Consent support", href: "/consent", description: "Plain-language explanations and Q&A, with the site still obtaining consent." },
    { label: "How to reduce screen failure", href: "/guides/reduce-screen-failure", description: "Causes, benchmarks and fixes a site can apply." },
    { label: "Therapeutic areas", href: "/therapeutic-areas", description: "Eligibility and chart evidence in the other areas Bond covers." },
  ],
};

export default page;
