import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/arizona",
  category: "geography",
  title: "Arizona clinical trial recruitment: Phoenix research sites",
  description:
    "For Phoenix and Tucson research sites: Arizona recruiting-trial counts, research hubs, health system EHRs, demographics and state rules on outreach and AI.",
  keywords: [
    "clinical trial recruitment Arizona",
    "Phoenix research sites",
    "clinical trials Phoenix Scottsdale Tucson",
    "Arizona patient recruitment",
    "Arizona health system EHRs",
  ],
  eyebrow: "Arizona",
  h1: "Recruiting for clinical trials in Arizona",
  intro:
    "As of September 21, 2026, 1,689 studies on ClinicalTrials.gov were recruiting at one or more Arizona sites, about 7.7% of the 22,041 recruiting in the United States, from a state with about 2.2% of US residents.{{cite:ctgov-api,census-pop-2025}} This page is for research sites in Phoenix, Tucson and the rest of the state.",
  summary: "Arizona recruiting-trial counts, Phoenix and Tucson research hubs, health systems and their EHRs, demographics, and state outreach rules.",
  lastUpdated: "2026-09-24",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in Arizona?",
      blocks: [
        {
          type: "p",
          text: "Arizona sites appear on 709 of the 7,074 recruiting US oncology studies and 100 of the 987 neurology studies, about 10% each. Among tracked areas, its share is highest in gastroenterology (56 of 285) and dermatology (38 of 214) and lowest in psychiatry (43 of 1,273).{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "arizona", cite: "ctgov-api" },
        {
          type: "p",
          text: "A count shows where sponsors placed studies, not which ones enroll on schedule, and keyword matching can pull in off-target studies. The examples below are cardiology, where Arizona sites appear on 257 of 2,845 studies.{{cite:ctgov-api}} See [cardiology](/cardiology) and [oncology](/oncology).",
        },
        { type: "trials", geo: "arizona", condition: "cardiology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are Arizona's research hubs?",
      blocks: [
        {
          type: "table",
          caption: "Arizona research hubs and what their anchor institutions report",
          columns: ["Hub", "Anchor institutions", "What they report"],
          rows: [
            [
              "Downtown Phoenix",
              "Phoenix Bioscience Core: ASU, NAU and the University of Arizona, TGen, Banner Health, Phoenix Children's, Dignity Health and Valleywise Health{{cite:pbc}}",
              "A 30-acre life sciences district{{cite:pbc}}. TGen, a genomics institute, is an affiliate of City of Hope{{cite:tgen}}",
            ],
            [
              "Phoenix and Scottsdale",
              "Mayo Clinic Cancer Center{{cite:nci-centers}}, HonorHealth Research Institute, Barrow Neurological Institute",
              "Barrow reports more than 223 active trials and hosts the Ivy Brain Tumor Center, which it calls the largest Phase 0 program in the world{{cite:barrow}}",
            ],
            [
              "Tucson",
              "University of Arizona Cancer Center{{cite:nci-centers}}, Banner-University Medicine",
              "The cancer center reports more than 200 clinical trials{{cite:uacc}}. Banner Health says it and the University of Arizona together run more than 800 active trials{{cite:banner-about}}",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "**Cancer.** Arizona's two NCI-designated comprehensive cancer centers are in Tucson and Phoenix.{{cite:nci-centers}}",
            "**Memory.** The Arizona Alzheimer's Consortium, established in 1998, links institutions statewide in Alzheimer's research.{{cite:azalz}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do Arizona's health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Arizona health systems, from public sources as of September 2026",
          columns: ["System", "Arizona footprint", "EHR"],
          rows: [
            [
              "Banner Health (Phoenix)",
              "Arizona's largest health care provider; 33 hospital locations and more than 400 outpatient sites across six states{{cite:banner-about}}",
              "Oracle Health (Cerner), listed in Oracle's FHIR endpoint directory{{cite:oracle-endpoints}}. Banner Health Network prefers eClinicalWorks or Cerner Ambulatory for its practices{{cite:bhn-ehr}}",
            ],
            ["Mayo Clinic (Phoenix and Scottsdale)", "Academic campus and comprehensive cancer center{{cite:nci-centers}}", "Epic, live since October 6, 2018{{cite:mayo-epic}}"],
            ["HonorHealth (Scottsdale)", "Health system with its own research institute{{cite:honorhealth-research}}", "Epic{{cite:epic-endpoints}}"],
            ["TMC HealthCare (Tucson)", "Tucson Medical Center", "Epic{{cite:epic-endpoints}}"],
            ["Northern Arizona Healthcare (Flagstaff)", "Northern Arizona", "Oracle Health (Cerner){{cite:oracle-endpoints}}"],
            ["Phoenix Children's", "Pediatric system", "Sunrise, per a client story from its vendor, Altera Digital Health{{cite:altera-pch}}"],
            [
              "Community health centers",
              "23 HRSA-funded awardees serving 856,192 patients in 2025{{cite:hrsa-az}}",
              "Varies; El Rio Health in Tucson runs Epic{{cite:epic-endpoints}}",
            ],
          ],
        },
        {
          type: "p",
          text: "Epic and Oracle Health split the large systems, so a study that draws on several metro Phoenix systems may need both. Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR R4 APIs, HL7 v2 where applicable, or an aggregator.{{cite:bond-site,bond-product}} For Sunrise or eClinicalWorks, the site's IT team confirms which FHIR access its vendor supports. See [Epic](/integrations/epic), [Oracle Health (Cerner)](/integrations/oracle-cerner) and [eClinicalWorks](/integrations/eclinicalworks).",
        },
        {
          type: "p",
          text: "Contexture runs the statewide health information exchange, and patients are included unless they opt out.{{cite:contexture}} State law limits research use of exchange data, so screening should run on the site's own EHR.{{cite:ars-36-3805}}",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in Arizona, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "7.6 million", label: "Residents on July 1, 2025", cite: "census-pop-2025" },
            { value: "32.5%", label: "Hispanic or Latino, 2025", cite: "census-asrh-2025" },
            { value: "20.6%", label: "Age 65 or older, up from 18.7% in 2020", cite: "census-asrh-2025" },
            { value: "10.3%", label: "Uninsured in 2024, against 8.2% nationally", cite: "census-acs-uninsured" },
          ],
        },
        {
          type: "p",
          text: "Maricopa County (Phoenix) had 4,689,558 residents on July 1, 2025, about 61.5% of the state, and its one-year gain of 35,411 was the third-largest of any US county.{{cite:census-metro-2025,census-pop-2025}}",
        },
        {
          type: "p",
          text: "About 5.6% of Arizonans identify as American Indian or Alaska Native alone.{{cite:census-asrh-2025}} The state is home to 22 federally recognized tribes.{{cite:uacc}} The Indian Health Service's Phoenix Area serves about 180,000 people in Arizona, Nevada and Utah. Its Navajo Area, which spans Arizona, New Mexico and Utah, reports more than 244,000 users, a fiscal 2016 figure.{{cite:ihs-phoenix,ihs-navajo}}",
        },
        {
          type: "p",
          text: "Coverage shapes what a chart can show. In 2024, 13.8% of Arizonans aged 19 to 64 were uninsured.{{cite:census-acs-uninsured}} At the state's community health centers in 2025, 54.8% of patients were Hispanic or Latino, 22.7% had limited English proficiency and 41.7% had Medicaid or CHIP.{{cite:hrsa-az}} A representative cohort usually needs those clinics and a plan for Spanish speakers. See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks and research sites work in Arizona?",
      blocks: [
        {
          type: "p",
          text: "Each organization's own website, as of September 2026:",
        },
        {
          type: "ul",
          items: [
            "**HonorHealth Research Institute** in Scottsdale reports about 300 studies a year, about 2,500 participating patients and an average launch window of four months.{{cite:honorhealth-research}}",
            "**Elite Clinical Network** lists four Arizona sites: Noble Clinical Research in Tucson, Chandler Clinical Trials, Scottsdale Clinical Trials and Sun City Clinical Research in Glendale.{{cite:elite-network}}",
            "**AMR Clinical** runs a Phase I to IV site in Tempe on the campus of Tempe St. Luke's Hospital.{{cite:amr-tempe}}",
            "**Celerion** runs a Tempe early-phase unit with more than 350 beds, which it calls the largest in the US.{{cite:celerion}}",
          ],
        },
        {
          type: "p",
          text: "Bond is a CRIO Certified Partner and works with research sites, site networks, physician groups and community health centers.{{cite:bond-site}} See [research sites](/for/research-sites) and [site networks](/for/site-networks).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which Arizona laws apply to AI outreach and patient records?",
      blocks: [
        {
          type: "p",
          text: "None of these laws targets trial recruitment. Treat this list as a map for your counsel, not legal advice.",
        },
        {
          type: "ul",
          items: [
            "**Medical records (A.R.S. 12-2292).** Records are privileged and confidential, and a provider may disclose them only as law allows or with the patient's written authorization.{{cite:ars-12-2292}}",
            "**Health information exchange (A.R.S. 36-3805).** An exchange may not transfer identifiable or de-identified data for research unless the provider obtains the patient's signed consent after a written notice in at least 12-point type.{{cite:ars-36-3805}}",
            "**Telephone solicitation (A.R.S. 44-1278 and 44-1282).** Artificial or prerecorded voice calls to residential phones need prior express consent.{{cite:ars-44-1278}} Solicitation calls and texts to numbers on the national do-not-call registry carry civil penalties of up to $1,000 per violation.{{cite:ars-44-1282}} Both cover telephone solicitation, which state law defines as a call that offers merchandise for sale or rent, so a study invitation may fall outside them.{{cite:ars-44-1271}} Federal rules apply regardless; see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026).",
            "**Call recording (A.R.S. 13-3012).** The state wiretap law exempts recording made with the consent of one party to the call.{{cite:ars-13-3012}}",
            "**Breach notice (A.R.S. 18-552).** HIPAA covered entities and business associates follow HIPAA's breach rules, not the state's 45-day notice rule.{{cite:ars-18-552}}",
            "**AI disclosure.** As of September 2026, no Arizona statute we reviewed requires AI disclosure in patient outreach. The House-passed version of HB 2311 would have required a conversational AI service to disclose it is AI when a person could be misled into thinking they were talking to a human; the governor vetoed the bill in June 2026.{{cite:az-hb2311,az-vetoes}} HB 2175, in force since July 1, 2026, requires a medical director's individual review of insurers' medical-necessity denials; it governs claims, not recruitment.{{cite:az-hb2175}}",
          ],
        },
        {
          type: "callout",
          tone: "warning",
          title: "Research with tribal communities",
          text: "Research at an Indian Health Service direct-care facility serving a tribe with its own IRB needs approval from both the tribal IRB and the IHS IRB. The Navajo Nation Human Research Review Board also serves as the Navajo Area IHS IRB.{{cite:ihs-irb}} A central [IRB](/glossary/irb) approval alone is not enough.",
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI assistance is being used, and patients can reach a person at any time: the agent transfers the call live to a coordinator or books a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Scripts are configured per site and study, so an Arizona site can use its own IRB-reviewed wording.",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with an Arizona site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration usually takes 4 to 6 weeks. A pilot from a patient list, without EHR integration, can begin in under 2 weeks.{{cite:bond-site}} See [implementation](/implementation) for the week-by-week plan.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Agree scope and paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path. If the study reaches IHS or tribal facilities, add tribal review.",
            },
            {
              title: "Connect the EHR",
              text: "Connect Epic, Oracle Health or another EHR through FHIR, HL7 or an aggregator. Screen the site's own records, not exchange data.",
            },
            {
              title: "Check criteria before outreach",
              text: "Each match shows the chart evidence behind every inclusion and exclusion criterion, so coordinators can review a sample before any patient is contacted. See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Screen, reach out and schedule",
              text: "Voice and text agents pre-screen and schedule in the patient's preferred language, including English, Spanish, Mandarin and many others, then hand off to coordinators.{{cite:bond-product}} Agree up front how Spanish speakers reach bilingual staff.",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting in Arizona?",
      a: "As of September 21, 2026, 1,689 studies on ClinicalTrials.gov listed a recruiting Arizona site, 709 of them in oncology.{{cite:ctgov-api}}",
    },
    {
      q: "Does Arizona require patients to be told when AI is used?",
      a: "As of September 2026, no Arizona statute we reviewed requires it for patient outreach, and a 2026 AI disclosure bill was vetoed.{{cite:az-vetoes}} Bond's agents disclose AI use regardless.{{cite:bond-site}}",
    },
    {
      q: "Can Arizona HIE data be used to find trial patients?",
      a: "Not without the patient's signed consent, so screening runs on the site's own EHR.{{cite:ars-36-3805}}",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Queried September 21, 2026.",
    },
    {
      id: "census-pop-2025",
      title: "U.S. Population Growth Slows Due to Historic Decline in Net International Migration (Press Release CB26-20)",
      publisher: "U.S. Census Bureau",
      url: "https://www.census.gov/newsroom/press-releases/2026/population-growth-slows.html",
      year: "2026",
      note: "Quote: \"Between July 1, 2024, and July 1, 2025, the U.S. population grew by 1.8 million (or 0.5%) to reach 341.8 million.\" Table \"Top 10 States by Numeric Growth\" row: \"7 | Arizona | 7,158,104 | 7,556,424 | 7,623,818\". The 2.2% share and Maricopa's 61.5% share of the state are Bond's arithmetic.",
    },
    {
      id: "census-asrh-2025",
      title: "Annual State Resident Population Estimates for 6 Race Groups by Age, Sex, and Hispanic Origin: April 1, 2020 to July 1, 2025 (SC-EST2025-ALLDATA6)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/state/asrh/sc-est2025-alldata6.csv",
      year: "2026",
      note: "Downloaded September 2026 and summed by Bond for Arizona, POPESTIMATE2025, both sexes, all ages: total 7,623,818; Hispanic origin 2,479,648 (32.5%); American Indian and Alaska Native alone 425,209 (5.6%); age 65 and over 1,571,773 (20.6%), against 1,344,960 of the 2020 estimate (18.7%).",
    },
    {
      id: "census-metro-2025",
      title: "Slow Growth Impacts Nation's Largest Counties Hardest (Press Release CB26-56)",
      publisher: "U.S. Census Bureau",
      url: "https://www.census.gov/newsroom/press-releases/2026/2025-popest-metro-micro-counties.html",
      year: "2026",
      note: "Quote: table \"Top 10 Most Populous Counties: July 1, 2025\" row \"4 | Arizona | Maricopa County | 4,425,302 | 4,654,147 | 4,689,558\"; table \"Top 10 Counties by Numeric Growth\" row \"3 | Arizona | Maricopa County ... 35,411\"; table \"Top 10 U.S. Metro Areas by Numeric Growth\" row \"4 | Phoenix-Mesa-Chandler, AZ | 4,851,295 | 5,169,873 | 5,228,938 | 59,065\".",
    },
    {
      id: "census-acs-uninsured",
      title: "Health Insurance Coverage by State: 2023 and 2024 (ACSBR-024)",
      publisher: "U.S. Census Bureau, American Community Survey Briefs",
      url: "https://www2.census.gov/library/publications/2025/demo/acsbr-024.pdf",
      year: "2025",
      note: "Quote: Appendix Table 2, \"United States 7.9 0.1 8.2 0.1\" and \"Arizona 9.9 0.3 10.3 0.4\" (2023 and 2024 uninsured percent with margins of error). Appendix Table 3, adults aged 19 to 64: \"Arizona 13.5 0.4 13.8 0.5\".",
    },
    {
      id: "hrsa-az",
      title: "Arizona Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/AZ",
      year: "2026",
      note: "Quote: \"Total Number of Reporting Program Awardees: 23. Reporting Period: 2025. Total Patients Served: 856,192.\" Patient characteristics on the same page, 2025: Hispanic, Latino/a, or Spanish Origin 54.81%; Limited English Proficiency 22.65%; Medicaid/CHIP 41.72%. Rechecked September 22, 2026.",
    },
    {
      id: "ihs-phoenix",
      title: "Phoenix Area",
      publisher: "Indian Health Service, HHS",
      url: "https://www.ihs.gov/phoenix/",
      year: "2026",
    },
    {
      id: "ihs-navajo",
      title: "Navajo Area",
      publisher: "Indian Health Service, HHS",
      url: "https://www.ihs.gov/navajo/",
      year: "2026",
      note: "Quote: \"The NAIHS delivers health services to a user population of over 244,000 American Indians in five Federal service units on and near the Navajo Nation.\" The user-population figure dates from FY2016 on the source page.",
    },
    {
      id: "ihs-irb",
      title: "Institutional Review Boards, Human Subjects Research Protections",
      publisher: "Indian Health Service, Division of Planning, Evaluation, and Research",
      url: "https://www.ihs.gov/dper/research/hsrp/instreviewboards/",
      year: "2026",
    },
    {
      id: "uacc",
      title: "University of Arizona Cancer Center",
      publisher: "University of Arizona Cancer Center",
      url: "https://cancercenter.arizona.edu/",
      year: "2026",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
    },
    {
      id: "banner-about",
      title: "About Banner Health",
      publisher: "Banner Health",
      url: "https://www.bannerhealth.com/about",
      year: "2026",
    },
    {
      id: "honorhealth-research",
      title: "HonorHealth Research Institute",
      publisher: "HonorHealth Research Institute",
      url: "https://honorhealthresearch.org/",
      year: "2026",
    },
    {
      id: "pbc",
      title: "Phoenix Bioscience Core",
      publisher: "City of Phoenix Community and Economic Development Department",
      url: "https://phoenixbiosciencecore.com/",
      year: "2026",
    },
    {
      id: "tgen",
      title: "About TGen",
      publisher: "Translational Genomics Research Institute (TGen)",
      url: "https://www.tgen.org/about/",
      year: "2026",
      note: "Quote: \"TGen has joined forces with City of Hope to accelerate the speed at which scientists and medical staff convert research discoveries into cures for patients.\" The page header reads \"An affiliate of City of Hope\". Read September 22, 2026.",
    },
    {
      id: "barrow",
      title: "Research",
      publisher: "Barrow Neurological Institute",
      url: "https://www.barrowneuro.org/research/",
      year: "2026",
      note: "Quote: \"Offering more than 223 active clinical trials\" and \"We're also home to the Ivy Brain Tumor Center, the largest Phase 0 clinical trials program in the world.\"",
    },
    {
      id: "azalz",
      title: "Arizona Alzheimer's Consortium",
      publisher: "Arizona Alzheimer's Consortium",
      url: "https://azalz.org/",
      year: "2026",
    },
    {
      id: "celerion",
      title: "Phase 1 CRO Facility Phoenix, Arizona",
      publisher: "Celerion",
      url: "https://www.celerion.com/clinicaltrialfacilities/phoenix/",
      year: "2026",
      note: "Quote: \"The Largest Early Phase Clinical Research Site in the US\" ... \"350+ beds including Intensive Conduct Units\" ... \"Located in Tempe, minutes from Phoenix Sky Harbor International Airport\".",
    },
    {
      id: "amr-tempe",
      title: "Site in Phoenix, Arizona",
      publisher: "AMR Clinical",
      url: "https://www.amr-clinical.com/sites/phoenix/",
      year: "2026",
      note: "Quote: \"1492 S. Mill Ave. Suite 312 Tempe, AZ 85281\" ... \"Located on campus of Tempe St. Luke's Hospital\" ... conducts \"Phase I, II, III, and IV trials\".",
    },
    {
      id: "elite-network",
      title: "Clinical sites",
      publisher: "Elite Clinical Network",
      url: "https://eliteclinicalnetwork.com/clinical-sites/",
      year: "2026",
      note: "Quote: Arizona entries \"Noble Clinical Research, 2055 W Hospital Drive, Suite 175, Tucson, AZ 85704\"; \"Chandler Clinical Trials, 255 S Dobson Rd, Suite 4, Chandler, AZ 85224\"; \"Scottsdale Clinical Trials, 8997 E Desert Cove Ave #2, Scottsdale, AZ 85260\"; \"Sun City Clinical Research, 11851 North 51st Avenue, BLDG G, Glendale, AZ\".",
    },
    {
      id: "mayo-epic",
      title: "Mayo Clinic completes installation of Epic electronic health record",
      publisher: "Healthcare Innovation (HCI Innovation Group)",
      url: "https://www.hcinnovationgroup.com/clinical-it/electronic-health-record-electronic-medical-record-ehr-emr/article/13010956/mayo-clinic-completes-installation-of-epic-electronic-health-record",
      year: "2018",
      note: "Quote: \"On Oct. 6, the Epic system went live on Mayo campuses in Jacksonville, FL, and Phoenix and Scottsdale, AZ.\" and \"All Mayo locations are now on a single, integrated electronic health record (EHR) and revenue cycle management (RCM) system.\" Article dated October 10, 2018.",
    },
    {
      id: "oracle-endpoints",
      title: "Oracle Health Millennium patient R4 FHIR endpoints (millennium_patient_r4_endpoints.json)",
      publisher: "Oracle (oracle-samples/ignite-endpoints on GitHub)",
      url: "https://raw.githubusercontent.com/oracle-samples/ignite-endpoints/main/oracle_health_fhir_endpoints/millennium_patient_r4_endpoints.json",
      year: "2026",
      note: "Quote: Organization entries \"BANNER HEALTH\" (city \"Phoenix\", state \"AZ\") and \"Northern Arizona HealthCare\" (city \"FLAGSTAFF\", state \"AZ\"). Downloaded September 22, 2026. A listing shows a Millennium FHIR endpoint, not every system the organization runs.",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Quote: endpoint entries \"name\": \"HonorHealth\"; \"name\": \"TMC HealthCare\"; \"name\": \"El Rio Health\"; \"name\": \"Yuma Regional Medical Center\", each with connection type \"hl7-fhir-rest\" and status \"active\". Downloaded September 22, 2026.",
    },
    {
      id: "altera-pch",
      title: "Phoenix Children's Hospital extends its reach of care with Altera Digital Health",
      publisher: "Altera Digital Health",
      url: "https://www.alterahealth.com/client-stories/phoenix-childrens-hospital-extends-reach-of-care-with-altera-digital-health/",
      year: "2026",
      note: "Quote: \"Phoenix Children's quickly rolled out its hospital's electronic health record (EHR) system, Sunrise, as a turnkey solution\". Vendor client story, undated; read September 2026.",
    },
    {
      id: "bhn-ehr",
      title: "Electronic Health Records",
      publisher: "Banner Health Network",
      url: "https://www.bannerhealthnetwork.com/ehr",
      year: "2026",
      note: "Quote: \"Banner Health Network has two preferred platforms when it comes to EHRs\" ... \"eClinicalWorks and Cerner Ambulatory.\"",
    },
    {
      id: "contexture",
      title: "HIE Opt-In / Opt-Out",
      publisher: "Contexture",
      url: "https://contexture.org/hie-opt-in-opt-out/",
      year: "2026",
    },
    {
      id: "ars-12-2292",
      title: "A.R.S. 12-2292. Confidentiality of medical records and payment records",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/ars/12/02292.htm",
      year: "2026",
    },
    {
      id: "ars-36-3805",
      title: "A.R.S. 36-3805. Disclosure of individually identifiable health information; transfer; consent",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/ars/36/03805.htm",
      year: "2026",
    },
    {
      id: "ars-44-1278",
      title: "A.R.S. 44-1278. Unlawful practice; powers of attorney general; cumulative remedies",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/ars/44/01278.htm",
      year: "2026",
    },
    {
      id: "ars-44-1271",
      title: "A.R.S. 44-1271. Definitions",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/ars/44/01271.htm",
      year: "2026",
      note: "Quote: paragraph 18, \"Telephone solicitation\" means \"Any voice communication from a live operator, announcing device or otherwise that offers merchandise for sale or rent and that is to or from a person located in this state.\" Read September 22, 2026.",
    },
    {
      id: "ars-44-1282",
      title: "A.R.S. 44-1282. National do-not-call registry; prohibitions; enforcement; civil penalty; definition",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/ars/44/01282.htm",
      year: "2026",
    },
    {
      id: "ars-13-3012",
      title: "A.R.S. 13-3012. Exemptions",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/ars/13/03012.htm",
      year: "2026",
      note: "Quote: paragraph 9 exempts \"The interception of any wire, electronic or oral communication by any person, if the interception is effected with the consent of a party to the communication or a person who is present during the communication\".",
    },
    {
      id: "ars-18-552",
      title: "A.R.S. 18-552. Notification of security system breaches; requirements; enforcement; confidentiality; civil penalty; preemption; exceptions",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/ars/18/00552.htm",
      year: "2026",
    },
    {
      id: "az-hb2311",
      title: "HB2311 House Bill Summary (House engrossed): artificial intelligence service; disclosures; requirements",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/legtext/57leg/2R/summary/H.HB2311_030226_HOUSE%20ENGROSSED.DOCX.htm",
      year: "2026",
      note: "Quote: operators must \"clearly disclose that the conversational AI service is AI if a person is to be misled to believe they are speaking with another human.\" This summary describes the House engrossed version dated March 2, 2026; the vetoed final version may differ.",
    },
    {
      id: "az-vetoes",
      title: "Governor Katie Hobbs Legislative Action Update",
      publisher: "Office of the Arizona Governor",
      url: "https://azgovernor.gov/office-arizona-governor/news/2026/06/governor-katie-hobbs-legislative-action-update-0",
      year: "2026",
      note: "Quote: the update dated June 19, 2026 lists \"HB2311 artificial intelligence service; disclosures; requirements\" among the bills vetoed, with a link to the veto letter. Rechecked September 22, 2026.",
    },
    {
      id: "az-hb2175",
      title: "Chapter 165, House Bill 2175: prior authorization; claims",
      publisher: "Arizona State Legislature",
      url: "https://www.azleg.gov/legtext/57leg/1R/laws/0165.htm",
      year: "2025",
      note: "Quote: \"Before a health care insurer may deny a claim that was submitted by a provider on the basis of medical necessity, the medical director shall individually review the denial.\" Also: \"This act is effective from and after June 30, 2026.\" Approved by the governor May 12, 2025.",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, September 2026.",
    },
  ],
  related: [
    { label: "All locations", href: "/clinical-trial-recruitment", description: "Registry counts and outreach rules for other states and regions." },
    { label: "Bond for research sites", href: "/for/research-sites", description: "How screening, outreach and consent support fit a site's coordinators." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, week by week." },
    { label: "Oncology", href: "/oncology", description: "How Bond screens for cancer trials, Arizona's largest area by count." },
    { label: "Neurology and Alzheimer's", href: "/neurology-and-alzheimers", description: "Screening for memory and movement disorder studies." },
    { label: "Cardiology", href: "/cardiology", description: "Screening for heart failure, hypertension and rhythm studies." },
  ],
};

export default page;
