import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/boston",
  category: "geography",
  title: "Boston clinical trial recruitment for research sites",
  description:
    "Boston-area recruiting-trial counts, research hubs, health system EHRs, languages and the Massachusetts laws that shape AI patient outreach and texting.",
  keywords: [
    "clinical trial recruitment Boston",
    "Boston research sites",
    "clinical trials Boston Cambridge Massachusetts",
    "Massachusetts patient recruitment",
    "Boston health system EHRs",
  ],
  eyebrow: "By location",
  h1: "Recruiting for clinical trials in the Boston area",
  intro:
    "On October 5, 2026, a ClinicalTrials.gov radius search found 2,961 studies recruiting at one or more sites within 25 miles of downtown Boston, about 13% of the 22,007 recruiting in the United States that day.{{cite:ctgov-api}} This page is for research sites in the city and its suburbs. Bond Health is based in Boston.{{cite:bond-site}}",
  summary: "Boston-area recruiting-trial counts, research hubs, health systems and their EHRs, languages, and Massachusetts outreach and privacy rules.",
  lastUpdated: "2026-10-05",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in the Boston area?",
      blocks: [
        {
          type: "p",
          text: "Oncology is the largest area: 1,130 of the 7,064 recruiting US oncology studies, about 16%, list a site within the radius. The area's share is highest in dermatology (39 of 212) and is also above its overall 13% in cardiology (474 of 2,826), gastroenterology (49 of 283) and neurology (160 of 985). It is lowest in obesity and type 2 diabetes, at 75 of 855.{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "boston", cite: "ctgov-api" },
        {
          type: "p",
          text: "A radius count shows where sponsors placed studies, not which ones enroll on schedule, and keyword matching on the condition field can pull in off-target studies. The oncology examples below are the most recently updated recruiting studies in the radius, from investigator-led studies at Dana-Farber and Massachusetts General Hospital to industry trials.{{cite:ctgov-api}} See [oncology](/oncology) for how Bond screens for cancer trials.",
        },
        { type: "trials", geo: "boston", condition: "oncology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are Boston's research hubs?",
      blocks: [
        {
          type: "table",
          caption: "Selected Boston research institutions and what each reports on its own site, as of October 2026",
          columns: ["Institution", "What it is", "What it reports"],
          rows: [
            [
              "Mass General Brigham",
              "Academic health system with 14 hospitals, including Massachusetts General and Brigham and Women's{{cite:mgb-about}}",
              "A $2 billion annual research investment supporting 3,700+ ongoing clinical trials{{cite:mgb-about}}. Massachusetts General and Brigham and Women's ranked first and second on BRIMR's list of hospitals by NIH funding for federal fiscal 2025{{cite:brimr-2025}}",
            ],
            ["Dana-Farber Cancer Institute", "Cancer treatment and research center", "Over 1,200 active trials annually{{cite:dana-farber-trials}}"],
            [
              "Boston Children's Hospital",
              "Pediatric academic hospital",
              "$603 million in externally sponsored research in fiscal 2024{{cite:bch-research}}; third on BRIMR's 2025 hospital list{{cite:brimr-2025}}",
            ],
            [
              "Beth Israel Deaconess Medical Center",
              "Harvard Medical School teaching hospital in Beth Israel Lahey Health{{cite:bidmc-research,bilh-mybilh}}",
              "250+ principal investigators, 2,500+ active sponsored projects and $300M+ in annual funding{{cite:bidmc-research}}",
            ],
            [
              "Boston Medical Center",
              "511-bed academic medical center and the largest essential hospital in New England{{cite:bmc-system-about}}",
              "170+ active clinical trials, with about half of participants people of color{{cite:bmc-research}}",
            ],
            [
              "Tufts Medical Center and Tufts CTSI",
              "Academic medical center in Tufts Medicine{{cite:tufts-medicine-about}}, and Tufts University's translational science institute",
              "Tufts CTSI, established in 2008, is a partnership of 39 organizations{{cite:tufts-ctsi}}",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "**Cancer.** NCI lists two designated cancer centers in Massachusetts: Dana-Farber/Harvard Cancer Center in Boston, a comprehensive cancer center, and the Koch Institute at MIT in Cambridge, a basic laboratory center.{{cite:nci-centers}} The Boston consortium now calls itself the Harvard Cancer Consortium and counts over 1,100 cancer researchers at seven institutions.{{cite:hcc}}",
            "**Translational science.** Three NIH Clinical and Translational Science Award hubs are in Boston: Harvard Catalyst at Harvard Medical School, Tufts CTSI and the Boston University CTSI, whose new award began in August 2026.{{cite:nih-reporter-ctsa,harvard-catalyst,tufts-ctsi,bu-ctsi}} NCATS says more than 60 institutions nationwide receive CTSA funding.{{cite:ncats-ctsa}}",
            "**Federal funding.** Boston ranked second among US cities in NIH funding for federal fiscal 2025, at $2,467,046,114, just behind New York.{{cite:brimr-2025}} MassBio's 2026 snapshot puts Massachusetts first in NIH funding per capita, at $477.{{cite:massbio-2026}}",
            "**Industry trials.** Citing Trialtrove data from July 2026, MassBio counts roughly 2,400 Massachusetts trials in active development, 35% of them early phase, and says 57% of sponsor participation in the state is commercial, against 38% for the US.{{cite:massbio-2026}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do Boston's health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Boston-area health systems, from their own pages, trade press and Epic's endpoint directory, as of October 2026",
          columns: ["System", "Footprint", "EHR"],
          rows: [
            [
              "Mass General Brigham",
              "14 hospitals{{cite:mgb-about}}",
              "Epic; Brigham and Women's went live on May 30, 2015{{cite:bwh-epic,epic-endpoints}}",
            ],
            [
              "Beth Israel Lahey Health",
              "More than 6,300 physicians and 36,000 employees{{cite:bilh-about}}",
              "Epic, in waves: BIDMC, Lahey and other sites from June 1, 2024; Anna Jaques and the BID hospitals in Milton, Needham and Plymouth on October 26, 2024; Mount Auburn on October 4, 2025{{cite:hci-boston-epic,bilh-mybilh,mount-auburn-epic}}",
            ],
            [
              "Boston Children's Hospital",
              "Pediatric academic hospital",
              "Epic since June 1, 2024, after running Cerner from 2007{{cite:hci-boston-epic}}",
            ],
            [
              "Boston Medical Center",
              "511-bed academic medical center{{cite:bmc-system-about}}",
              "Epic; its community hospitals, BMC Brighton and BMC South, moved to Epic on November 1, 2025{{cite:epic-endpoints,bmc-epic-transition}}",
            ],
            [
              "Tufts Medicine",
              "Tufts Medical Center, Lowell General Hospital and MelroseWakefield Hospital{{cite:tufts-medicine-about}}",
              "Epic hosted in the AWS cloud, live since spring 2022, replacing six different EHRs{{cite:hci-tufts-aws}}",
            ],
            [
              "Cambridge Health Alliance",
              "The state's sole public hospital, with 150,000 patients{{cite:cha-about}}",
              "Epic{{cite:epic-endpoints}}",
            ],
            [
              "Community health centers",
              "37 HRSA-funded awardees serving 884,863 patients statewide in 2025{{cite:hrsa-ma}}",
              "Varies by center",
            ],
          ],
        },
        {
          type: "p",
          text: "Nearly every large Boston system now runs Epic, but several switched only in 2024 or 2025. A system that changed EHRs may keep older notes and results in a legacy archive, so confirm how many years of history the live record holds before relying on a lookback criterion. Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR, HL7 or an aggregator.{{cite:bond-site,bond-product}} See [Epic](/integrations/epic), [MEDITECH](/integrations/meditech) and [EHRs for recruitment](/guides/ehr-for-recruitment).",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in the Boston area, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "672,973", label: "Boston residents on July 1, 2025", cite: "census-cities-2025" },
            { value: "5,034,221", label: "Boston-Cambridge-Newton metro residents on July 1, 2025", cite: "census-cbsa-2025" },
            { value: "37.3%", label: "Boston residents 5 and older who speak a language other than English at home, 2024", cite: "census-acs-boston" },
            { value: "47.6%", label: "Massachusetts health center patients with limited English proficiency, 2025", cite: "hrsa-ma" },
          ],
        },
        {
          type: "p",
          text: "Suffolk County, which contains Boston, was 24.9% Hispanic, 17.6% non-Hispanic Black and 10.5% non-Hispanic Asian on July 1, 2025. It has a smaller share of older residents than the state: 14.2% were 65 or older, against 19.9% statewide.{{cite:census-county-ma}} In 2024, 28.5% of Boston residents were born abroad and 3.3% were uninsured.{{cite:census-acs-boston,census-acs-boston-s2701}}",
        },
        {
          type: "p",
          text: "Spanish is the most common language other than English: 101,881 Boston residents speak it at home, and 47,527 of them speak English less than very well. Next are French, Haitian or Cajun (32,474) and Chinese (28,110, of whom 16,378 speak English less than very well).{{cite:census-acs-boston-c16001}} Boston Medical Center says almost 30 percent of its patients speak a primary language other than English, including Haitian Creole and Cape Verdean Creole.{{cite:bmc-about}} At the state's health centers in 2025, 36.91% of patients were Hispanic or Latino and 41.04% had Medicaid or CHIP.{{cite:hrsa-ma}}",
        },
        {
          type: "p",
          text: "A representative Boston cohort usually needs outreach in Spanish, Haitian Creole and Chinese, plus the clinics that serve those patients. Bond's voice and text agents work in the patient's language and can switch languages mid-call.{{cite:bond-product}} See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks and research sites work in the Boston area?",
      blocks: [
        {
          type: "p",
          text: "Beyond the academic centers, several multi-site research organizations list Boston-area locations on their own websites, as of October 2026:",
        },
        {
          type: "ul",
          items: [
            "**Care Access** lists its corporate headquarters at 33 Arch Street in Boston and a multi-specialty site in Quincy.{{cite:care-access}}",
            "**Adams Clinical** lists Boston and Watertown among six locations in New York, Massachusetts, Pennsylvania and Texas.{{cite:adams-clinical}}",
            "**DM Clinical Research** lists a Boston-area site at 209 Harvard Street in Brookline, one of 17 locations across 13 states.{{cite:dm-boston,dm-locations}}",
            "**Alcanza** lists Boston Clinical Trials in Boston and ActivMed Research in Methuen.{{cite:alcanza}}",
          ],
        },
        {
          type: "p",
          text: "Bond is a CRIO Certified Partner, its only vendor certification.{{cite:bond-site}} See how Bond fits [research sites](/for/research-sites), [site networks](/for/site-networks) and [CRIO](/integrations/crio).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which Massachusetts laws apply to AI outreach, texting and health data?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how each applies to pre-screening is unsettled. This is a map for your counsel, current as of October 5, 2026, not legal advice. For federal rules, see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026) and [IRB and HIPAA rules for patient outreach](/guides/irb-hipaa-patient-outreach).",
        },
        {
          type: "ul",
          items: [
            "**Call recording (M.G.L. c. 272, § 99).** Massachusetts treats secretly recording a call as an interception unless every party gave prior authority, with penalties of up to a $10,000 fine or five years in state prison.{{cite:ma-wiretap}} A recorded AI call to a Massachusetts patient should say at the start that it is recorded.",
            "**Telephone solicitation (M.G.L. c. 159C).** Unsolicited sales calls are barred to numbers on the state's no-sales-solicitation list, between 8:00 p.m. and 8:00 a.m., and by recorded message device.{{cite:ma-159c-3}} The law covers calls and messages that encourage the purchase or rental of, or investment in, property, goods or services, so a study invitation may fall outside it.{{cite:ma-159c-1}}",
            "**Genetic information (M.G.L. c. 111, § 70G).** Providers may not disclose genetic test results to anyone but the patient without informed written consent, except as confidential research information under an IRB-approved protocol. The law's definition of a genetic test excludes tests to diagnose or detect an existing disease.{{cite:ma-70g}} If screening reads germline or molecular reports, ask the privacy office how this applies before outreach starts.",
            "**Consumer data privacy (S.2619).** The Senate passed a Massachusetts Data Privacy Act 40-0 in September 2025, and the House passed its version 146-0 on June 4, 2026. The House version treats health and wellness information as sensitive data that cannot be sold without affirmative consent. As of October 5, 2026, the bill sat with a conference committee appointed in June and was not law.{{cite:ma-s2619,ma-house-privacy}}",
            "**AI disclosure.** As of October 5, 2026, no Massachusetts statute we reviewed requires AI disclosure in patient outreach. S.2632, a Senate bill on AI in health care decision-making, would require a licensed professional to tell a therapy patient in writing that AI will be used, and get consent, before using it where sessions are recorded or transcribed. It was sent to Senate Ways and Means on April 2, 2026.{{cite:ma-s2632}}",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI assistance is being used, and patients can reach a person at any time: the agent transfers the call live to a coordinator or books a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Scripts are configured per site and study, so a Massachusetts site can add its IRB-reviewed wording and a recording notice at the start of each call. See [IRB submission language for AI outreach](/templates/irb-submission-language-ai-outreach).",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Boston-area site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration usually takes 48 hours, depending on the EHR, IT review and interface method, and there is no integration fee.{{cite:bond-site,bond-product}} See [implementation](/implementation) for the step-by-step plan and [pricing](/pricing) for how fees work.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Sign the paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path.{{cite:bond-site}} For Massachusetts patients, agree on the recording notice, and if the protocol turns on genetic or molecular results, settle how Section 70G applies.",
            },
            {
              title: "Connect the EHR",
              text: "Connect Epic or another EHR through FHIR, HL7 or an aggregator.{{cite:bond-product}} If the system moved to Epic recently, confirm where pre-migration history lives.",
            },
            {
              title: "Check criteria before outreach",
              text: "Bond reads clinical notes, prescriptions, lab results, imaging data and pathology, radiology and molecular reports, and shows criterion-by-criterion evidence for every match, so coordinators can review a sample before any patient is contacted.{{cite:bond-site,bond-product}} See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Run ads, reach out and book",
              text: "Bond creates and runs Meta and Google ad campaigns for the study, paid from the site's own ad budget. Its voice and text agents contact every new lead immediately, keep following up with those who have not responded, pre-screen in the patient's language and book visits straight into the site's calendar, with reminders by text, voice or email.{{cite:bond-product}}",
            },
            {
              title: "Support consent and retention",
              text: "After the booked visit, the agents can explain the study in plain language and answer questions, escalating to staff; the site and PI obtain consent. After enrollment they send visit reminders, book transportation and flag dropout risk.{{cite:bond-product}} See [consent](/consent).",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting near Boston?",
      a: "On October 5, 2026, a ClinicalTrials.gov search for recruiting studies with a site within 25 miles of downtown Boston returned 2,961, including 1,130 that matched oncology keywords.{{cite:ctgov-api}}",
    },
    {
      q: "Can an AI recruitment call be recorded in Massachusetts?",
      a: "Only if everyone on the call knows. Massachusetts treats secret recording without every party's prior authority as an interception, so recorded calls should open with a recording notice.{{cite:ma-wiretap}} This is not legal advice.",
    },
    {
      q: "Does Massachusetts require patients to be told when AI is used?",
      a: "As of October 5, 2026, no Massachusetts statute we reviewed requires it for patient outreach; S.2632, which covers AI in therapy settings, was still in committee.{{cite:ma-s2632}} Bond's agents disclose AI use regardless.{{cite:bond-site}}",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Radius search queried October 5, 2026: filter.geo=distance(42.3601,-71.0589,25mi) (25 miles of downtown Boston), filter.overallStatus=RECRUITING, countTotal=true; 2,961 studies. US totals from the same day use query.locn=United States; 22,007 studies. Area counts use keyword searches on the condition field. Shares are Bond's arithmetic.",
    },
    {
      id: "census-cities-2025",
      title: "City and Town Population Totals: April 1, 2020 to July 1, 2025 (SUB-EST2025)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/cities/totals/sub-est2025.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row SUMLEV 162, Massachusetts, \"Boston city\": POPESTIMATE2025 672973.",
    },
    {
      id: "census-cbsa-2025",
      title: "Metropolitan and Micropolitan Statistical Area Population Totals: April 1, 2020 to July 1, 2025 (CBSA-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/metro/totals/cbsa-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row CBSA 14460, \"Boston-Cambridge-Newton, MA-NH\", Metropolitan Statistical Area: POPESTIMATE2025 5034221.",
    },
    {
      id: "census-county-ma",
      title: "Annual County Resident Population Estimates by Age, Sex, Race, and Hispanic Origin: April 1, 2020 to July 1, 2025 (CC-EST2025-ALLDATA-25)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/asrh/cc-est2025-alldata-25.csv",
      year: "2026",
      note: "Downloaded October 5, 2026 and summed by Bond for YEAR 7 (\"7/1/2025 population estimate\" in the file layout). Suffolk County total 791,891: Hispanic 197,443 (24.9%); non-Hispanic Black alone 139,196 (17.6%); non-Hispanic Asian alone 83,373 (10.5%); ages 65 and over 112,651 (14.2%). Massachusetts: 1,421,793 of 7,154,084 aged 65 and over (19.9%).",
    },
    {
      id: "census-acs-boston",
      title: "Selected Social Characteristics, Boston city, Massachusetts: 2024 ACS 1-Year Estimates (DP02)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSDP1Y2024.DP02&g=160XX00US2507000",
      year: "2025",
      note: "Read October 5, 2026. DP02_0094PE \"PLACE OF BIRTH!!Total population!!Foreign-born\" 28.5 (margin 1.4); DP02_0114PE \"LANGUAGE SPOKEN AT HOME!!Population 5 years and over!!Language other than English\" 37.3 (margin 1.3).",
    },
    {
      id: "census-acs-boston-s2701",
      title: "Selected Characteristics of Health Insurance Coverage, Boston city, Massachusetts: 2024 ACS 1-Year Estimates (S2701)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSST1Y2024.S2701&g=160XX00US2507000",
      year: "2025",
      note: "Read October 5, 2026. S2701_C05_001E \"Percent Uninsured!!Civilian noninstitutionalized population\" 3.3 (margin 0.7).",
    },
    {
      id: "census-acs-boston-c16001",
      title: "Language Spoken at Home for the Population 5 Years and Over, Boston city, Massachusetts: 2024 ACS 1-Year Estimates (C16001)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSDT1Y2024.C16001&g=160XX00US2507000",
      year: "2025",
      note: "Read October 5, 2026. Total 642,811. \"Spanish:\" 101,881, of whom \"Speak English less than 'very well'\" 47,527; \"French, Haitian, or Cajun:\" 32,474; \"Chinese (incl. Mandarin, Cantonese):\" 28,110, of whom 16,378 speak English less than very well.",
    },
    {
      id: "hrsa-ma",
      title: "Massachusetts Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/MA",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Total Number of Reporting Program Awardees: 37\", \"Reporting Period: 2025\", \"Total Patients Served: 884,863\". Patient characteristics, 2025: Hispanic, Latino/a, or Spanish Origin 36.91%; Limited English Proficiency 47.61% (421,242 patients); Medicaid/CHIP 41.04%.",
    },
    {
      id: "bmc-about",
      title: "About BMC",
      publisher: "Boston Medical Center",
      url: "https://www.bmc.org/about-us",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Almost 30 percent of our patients speak a primary language other than English, and so we offer all our medical care and services in over 160 languages, including Spanish, Haitian Creole, Cape Verdean Creole, and more.\"",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Read October 5, 2026 (page updated June 10, 2026). Massachusetts entries: \"Dana-Farber/Harvard Cancer Center\", Boston, Massachusetts, Comprehensive Cancer Center; \"David H. Koch Institute for Integrative Cancer Research at MIT\", Cambridge, Massachusetts, Basic Laboratory Cancer Center.",
    },
    {
      id: "hcc",
      title: "Harvard Cancer Consortium",
      publisher: "Harvard Cancer Consortium",
      url: "https://www.hcc.harvard.edu/",
      year: "2026",
      note: "Read October 5, 2026 (dfhcc.harvard.edu redirects here). Quote: \"Harvard Cancer Consortium (HCC), an NCI-designated comprehensive cancer center, was founded to integrate and build upon the collective talent and resources of the Harvard cancer research community.\" The site describes over 1,100 cancer researchers at seven institutions.",
    },
    {
      id: "nih-reporter-ctsa",
      title: "NIH RePORTER: NCATS Clinical and Translational Science Award hub awards (UL1/UM1), Massachusetts, fiscal years 2025-2026",
      publisher: "National Institutes of Health",
      url: "https://reporter.nih.gov/project-details/11302273",
      year: "2026",
      note: "Queried October 5, 2026 through the RePORTER API (agency NCATS, activity codes UL1 and UM1, state MA). Boston hub awards: 5UM1TR004408-04, \"Harvard Clinical and Translational Science Center\" (Harvard Medical School); 5UM1TR004398-04, \"Tufts Clinical and Translational Science Institute\"; 1UM1TR005308-01A1, \"Boston University Clinical and Translational Science Institute\", project start 2026-08-22 (the linked record).",
    },
    {
      id: "ncats-ctsa",
      title: "Clinical and Translational Science Awards (CTSA) Program",
      publisher: "National Center for Advancing Translational Sciences, NIH",
      url: "https://ncats.nih.gov/research/research-activities/ctsa",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Currently, more than 60 leading medical institutions across the nation receive CTSA Program funding.\"",
    },
    {
      id: "harvard-catalyst",
      title: "About Harvard Catalyst",
      publisher: "Harvard Catalyst",
      url: "https://catalyst.harvard.edu/about/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"partially funded by the NIH National Center for Advancing Translational Sciences (NCATS) through its Clinical and Translational Science Awards Program, grant number UM1TR004408\".",
    },
    {
      id: "tufts-ctsi",
      title: "About Tufts CTSI",
      publisher: "Tufts Clinical and Translational Science Institute",
      url: "https://www.tuftsctsi.org/about-us/",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Tufts CTSI was established in 2008 with a Clinical and Translational Science Award (CTSA)\" and \"a robust partnership of 39 organizations\"; award number UM1TR004398.",
    },
    {
      id: "bu-ctsi",
      title: "Clinical & Translational Science Institute",
      publisher: "Boston University",
      url: "https://www.bu.edu/ctsi/",
      year: "2026",
      note: "Read October 5, 2026. The page lists the grant \"UM1TR005308\".",
    },
    {
      id: "brimr-2025",
      title: "BRIMR Rankings of NIH Funding in 2025",
      publisher: "Blue Ridge Institute for Medical Research",
      url: "https://brimr.org/brimr-rankings-of-nih-funding-in-2025/",
      year: "2026",
      note: "Read October 5, 2026. The rankings use \"NIH year-end composite data for the federal fiscal year ending 30 September 2025\". Cities spreadsheet (City_2025.xlsx): \"1 | NEW YORK | 2490418623\"; \"2 | BOSTON | 2467046114\". Hospitals spreadsheet (Hospitals_2025.xlsx): \"1 | MASSACHUSETTS GENERAL HOSPITAL | 643313610\"; \"2 | BRIGHAM AND WOMEN'S HOSPITAL | 413986680\"; \"3 | BOSTON CHILDREN'S HOSPITAL | 245459764\".",
    },
    {
      id: "mgb-about",
      title: "About Us",
      publisher: "Mass General Brigham",
      url: "https://www.massgeneralbrigham.org/en/about",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Our $2 billion annual research investment supports 3,700+ ongoing clinical trials\" and \"14 hospitals including 5 nationally ranked teaching hospitals\". A separate Mass General Brigham research page gives \"$2.7 billion+\" as the annual research budget; this page uses the About figure.",
    },
    {
      id: "dana-farber-trials",
      title: "Find a Cancer Clinical Trial at Dana-Farber",
      publisher: "Dana-Farber Cancer Institute",
      url: "https://www.dana-farber.org/clinical-trials",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Dana-Farber's extensive clinical trial program features over 1,200 active trials annually.\"",
    },
    {
      id: "bch-research",
      title: "About Us, Boston Children's Research",
      publisher: "Boston Children's Hospital",
      url: "https://research.childrenshospital.org/about-us",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Boston Children's has the world's largest and most highly funded pediatric research enterprise, investing $603 million in externally sponsored research in FY2024 alone.\"",
    },
    {
      id: "bidmc-research",
      title: "Research",
      publisher: "Beth Israel Deaconess Medical Center",
      url: "https://www.bidmc.org/research",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"250+ Principal Investigators\", \"2,500+ Active Sponsored Projects\", \"$300M+ in Annual Funding\"; describes BIDMC as \"a Harvard Medical School teaching hospital\".",
    },
    {
      id: "bmc-research",
      title: "Boston Medical Center Is a National Leader in Research",
      publisher: "Boston Medical Center",
      url: "https://www.bmc.org/research",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"170+ Active Clinical Trials\" and \"about half of BMC's clinical trial participants are people of color, compared to a national average of 2-16%\".",
    },
    {
      id: "bmc-system-about",
      title: "About Boston Medical Center Health System",
      publisher: "Boston Medical Center Health System",
      url: "https://www.bmchealthsystem.org/about",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Boston Medical Center (BMC) is a 511-bed, equity-led academic medical center\" and \"the largest essential hospital in New England\".",
    },
    {
      id: "massbio-2026",
      title: "2026 MassBio Industry Snapshot",
      publisher: "Massachusetts Biotechnology Council (MassBio)",
      url: "https://www.massbio.org/wp-content/uploads/2026/08/2026_MassBio_IndustrySnapshot_Final.pdf",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Massachusetts sustains roughly 2,400 trials in active development, with 35% in early, first-in-human and proof-of-concept phases\"; \"57% of sponsor participation is commercial against 38% for the U.S.\"; \"Massachusetts drew 9.3% of all NIH funding and leads the nation at $477 per capita\". Trial data credited to \"Trialtrove via Evaluate, July 2026.\" MassBio is an industry association.",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Downloaded October 5, 2026 (bundle total 479). Entries include \"Mass General Brigham\", \"Beth Israel Lahey Health\", \"Boston Medical Center\", \"Boston Children's Hospital (Enterprise)\", \"Tufts Medicine\" and \"Cambridge Health Alliance\". A listing means the organization publishes patient-access FHIR endpoints on Epic.",
    },
    {
      id: "bwh-epic",
      title: "Partners eCare Turns 1: Looking Back on BWHC's First Year with Epic",
      publisher: "Brigham Bulletin, Brigham and Women's Hospital",
      url: "https://bwhbulletin.org/2016/06/09/partners-ecare-turns-1-looking-back-on-bwhcs-first-year-with-epic/",
      year: "2016",
      note: "Article dated June 9, 2016. Quote: Partners eCare, \"BWHC's Epic-based electronic medical record system, which went live May 30, 2015.\"",
    },
    {
      id: "hci-boston-epic",
      title: "Two Boston Hospital CMIOs Report on Their Epic Go-Lives",
      publisher: "Healthcare Innovation",
      url: "https://www.hcinnovationgroup.com/clinical-it/electronic-health-record-electronic-medical-record-ehr-emr/article/55261547/two-boston-hospital-cmios-report-on-their-epic-go-lives",
      year: "2025",
      note: "Article dated January 16, 2025, covering Beth Israel Lahey Health and Boston Children's Hospital. Quotes: \"In June 2024, two Boston-area hospitals went live with transitions to unified Epic EHR platforms.\"; \"Boston Children's had been using Cerner since 2007 for its clinical EHR.\"; and, from Boston Children's CMIO Chase Parsons, \"On June 1, we went live with our Epic system.\"",
    },
    {
      id: "bilh-mybilh",
      title: "Introducing MyBILH Chart",
      publisher: "Beth Israel Lahey Health",
      url: "https://www.bilh.org/patient-portal/mybilh-chart/mybilh-chart-transition",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Beginning June 1, 2024, Beth Israel Lahey Health will launch the new patient portal, MyBILH Chart\" (sites include Beth Israel Deaconess Medical Center and Lahey Hospital & Medical Center); \"On October 26, 2024\" (Anna Jaques Hospital and Beth Israel Deaconess Hospital-Milton, -Needham and -Plymouth); \"In Fall 2025\" (Mount Auburn Hospital, Exeter Hospital and others).",
    },
    {
      id: "mount-auburn-epic",
      title: "MyChart",
      publisher: "Mount Auburn Hospital",
      url: "https://mountauburnhospital.org/patients-visitors/mychart",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Beginning October 4, 2025, Beth Israel Lahey Health (BILH) introduced a new patient portal called MyBILH Chart along with a new electronic health record called Epic.\"",
    },
    {
      id: "bmc-epic-transition",
      title: "Provider Reference Guide: Epic Transition",
      publisher: "Boston Medical Center Health System",
      url: "https://www.bmchealthsystem.org/provider-reference-guide-epic-transition",
      year: "2025",
      note: "Read October 5, 2026. Quote: \"BMC Brighton and BMC South, will be transitioning to a new electronic medical record (EMR) system, Epic, on November 1, 2025.\" The page says SMG Meditech access became read-only on November 8, 2025.",
    },
    {
      id: "hci-tufts-aws",
      title: "How Tufts Medicine Launched a Cloud Ecosystem",
      publisher: "Healthcare Innovation",
      url: "https://www.hcinnovationgroup.com/interoperability-hie/cloud-computing-storage/article/21271473/how-tufts-medicine-launched-a-cloud-ecosystem",
      year: "2022",
      note: "Article dated June 17, 2022. Quotes: \"Health system recently went live with its new Epic implementation and 40 applications in the AWS Cloud\"; \"We've been live for about six weeks on our brand-new Epic implementation\"; before consolidating, Tufts had \"six different EHRs and more than 100 different patient portals\".",
    },
    {
      id: "tufts-medicine-about",
      title: "About Us",
      publisher: "Tufts Medicine",
      url: "https://www.tuftsmedicine.org/about-us",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Tufts Medicine is made up of Care at Home, Lowell General Hospital, MelroseWakefield Hospital, Tufts Medical Center and hundreds of doctor offices.\"",
    },
    {
      id: "cha-about",
      title: "About CHA",
      publisher: "Cambridge Health Alliance",
      url: "https://www.challiance.org/about-cha",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"As the sole public hospital in Massachusetts\" and \"With 150,000 patients in Boston's metro-north region\".",
    },
    {
      id: "bilh-about",
      title: "About Beth Israel Lahey Health",
      publisher: "Beth Israel Lahey Health",
      url: "https://bilh.org/about",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"more than 6,300 physicians and 36,000 employees\".",
    },
    {
      id: "care-access",
      title: "Locations",
      publisher: "Care Access",
      url: "https://careaccess.com/about-us/locations",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Care Access Corporate HQ 33 Arch Street 17th Floor Boston, MA, 02110\"; \"500 Congress St Suite B1 Quincy, MA, 02169\", labeled Multi-Speciality.",
    },
    {
      id: "adams-clinical",
      title: "Adams Clinical",
      publisher: "Adams Clinical",
      url: "https://www.adamsclinical.com/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"With six locations across New York, Massachusetts, Pennsylvania, and Texas\"; locations named Boston, Bronx, Dallas, Harlem, Philadelphia and Watertown; address \"521 Mount Auburn St. | Watertown, MA 02472\".",
    },
    {
      id: "dm-boston",
      title: "Clinical Trials in Boston, MA",
      publisher: "DM Clinical Research",
      url: "https://www.dmclinicalresearch.com/locations/boston-ma/",
      year: "2026",
      note: "Read October 5, 2026. Address: \"209 Harvard St. #502, Brookline, MA 02446\".",
    },
    {
      id: "dm-locations",
      title: "Locations",
      publisher: "DM Clinical Research",
      url: "https://www.dmclinicalresearch.com/locations",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"17 locations across 13 states\".",
    },
    {
      id: "alcanza",
      title: "Locations",
      publisher: "Alcanza Clinical Research",
      url: "https://www.alcanzaclinical.com/locations",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"ActivMed Research – Methuen, 421 Merrimack St, Suite 203, Methuen, Massachusetts 01844\"; \"Boston Clinical Trials, 26 Cummins Hwy, Boston, Massachusetts 02131\".",
    },
    {
      id: "ma-wiretap",
      title: "General Laws c. 272, Section 99: Interception of wire and oral communications",
      publisher: "The 194th General Court of the Commonwealth of Massachusetts",
      url: "https://malegislature.gov/Laws/GeneralLaws/PartIV/TitleI/Chapter272/Section99",
      year: "2026",
      note: "Read October 5, 2026. Paragraph B.4 defines interception as \"to secretly hear, secretly record, or aid another to secretly hear or secretly record the contents of any wire or oral communication through the use of any intercepting device by any person other than a person given prior authority by all parties to such communication\". Paragraph C.1: \"shall be fined not more than ten thousand dollars, or imprisoned in the state prison for not more than five years\".",
    },
    {
      id: "ma-159c-1",
      title: "General Laws c. 159C, Section 1: Definitions",
      publisher: "The 194th General Court of the Commonwealth of Massachusetts",
      url: "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXXII/Chapter159C/Section1",
      year: "2026",
      note: "Read October 5, 2026. \"Marketing or sales solicitation\" means \"the initiation of a telephone call or message to encourage the purchase or rental of, or investment in, property, goods or services\".",
    },
    {
      id: "ma-159c-3",
      title: "General Laws c. 159C, Section 3: Unsolicited telephonic sales calls",
      publisher: "The 194th General Court of the Commonwealth of Massachusetts",
      url: "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXXII/Chapter159C/Section3",
      year: "2026",
      note: "Read October 5, 2026. Bars unsolicited telephonic sales calls \"if the consumer's name and telephone number appear on the then current quarterly no sales solicitation calls listing\", \"between the hours of 8:00 p.m. and 8:00 a.m., local time, at the consumer's location\" and \"by use of a recorded message device\".",
    },
    {
      id: "ma-70g",
      title: "General Laws c. 111, Section 70G: Genetic information and reports protected as private information",
      publisher: "The 194th General Court of the Commonwealth of Massachusetts",
      url: "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXVI/Chapter111/Section70G",
      year: "2026",
      note: "Read October 5, 2026. Subsection (c): no facility, physician or health care provider shall \"disclose the results of a genetic test to any person other than the subject thereof without first obtaining the informed written consent except where the results disclosed will be used only as is confidential research information\". \"Confidential research information\" means genetic test results maintained under research protocols reviewed and approved by an IRB under 45 CFR 46 and 21 CFR 50 and 56. \"Genetic test\" excludes \"any test for the purpose of diagnosing or detecting an existing disease, illness, impairment or disorder.\"",
    },
    {
      id: "ma-s2619",
      title: "Bill S.2619: An Act establishing the Massachusetts data privacy act",
      publisher: "The 194th General Court of the Commonwealth of Massachusetts",
      url: "https://malegislature.gov/Bills/194/S2619",
      year: "2026",
      note: "Bill history read October 5, 2026: \"9/25/2025 Senate Passed to be engrossed\" (Yeas 40 to Nays 0); \"6/4/2026 House Passed to be engrossed - 146 YEAS to 0 NAYS\"; \"6/11/2026 Senate Senate NON-concurred in the House amendment\"; \"6/17/2026 House Committee of conference appointed\". No later action listed.",
    },
    {
      id: "ma-house-privacy",
      title: "House Passes Landmark Data Privacy Legislation with Strong Consumer Protections",
      publisher: "Massachusetts House of Representatives",
      url: "https://malegislature.gov/PressRoom/Detail?pressReleaseId=1396",
      year: "2026",
      note: "Release dated June 4, 2026. Quotes: \"Sensitive data includes information such as biometric or genetic information, precise geolocation data, health and wellness information, reproductive and sexual health data\" and \"Companies cannot sell sensitive data without additional unambiguous, affirmative consent from a consumer.\"",
    },
    {
      id: "ma-s2632",
      title: "Bill S.2632: An Act relative to the use of artificial intelligence and other software tools in healthcare decision-making",
      publisher: "The 194th General Court of the Commonwealth of Massachusetts",
      url: "https://malegislature.gov/Bills/194/S2632",
      year: "2026",
      note: "Read October 5, 2026. Last action: \"4/2/2026 Senate Committee recommended ought to pass and referred to the committee on Senate Ways and Means\". Bill text, Section 298(c): no licensed professional may use AI for supplementary support in therapy where the session is recorded or transcribed unless the patient \"is informed in writing\" \"that artificial intelligence will be used\" and \"provides consent to the use of artificial intelligence.\"",
    },
    { id: "bond-site", title: "Bond Health: platform overview, FAQ and pricing", publisher: "Bond Health", url: "https://bondtrials.com", year: "2026" },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, October 2026.",
    },
  ],
  related: [
    { label: "All locations", href: "/clinical-trial-recruitment", description: "Registry counts and outreach rules for other states and regions." },
    { label: "Bond for research sites", href: "/for/research-sites", description: "How screening, outreach and booked visits fit a site's coordinators." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
    { label: "Oncology", href: "/oncology", description: "How Bond screens for cancer trials, the Boston area's largest area by count." },
    { label: "Epic integration", href: "/integrations/epic", description: "How Bond connects to Epic, which most large Boston systems run." },
    { label: "Neurology and Alzheimer's", href: "/neurology-and-alzheimers", description: "Screening for memory and movement disorder studies." },
  ],
};

export default page;
