import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/los-angeles",
  category: "geography",
  title: "Los Angeles clinical trial recruitment for research sites",
  description:
    "For Los Angeles area research sites: recruiting-trial counts, research hubs, health system EHRs, languages and the California rules on AI outreach.",
  keywords: [
    "clinical trial recruitment Los Angeles",
    "Los Angeles research sites",
    "clinical trials Los Angeles Pasadena Long Beach",
    "California AI disclosure AB 3030",
    "Los Angeles health system EHRs",
  ],
  eyebrow: "By location",
  h1: "Recruiting for clinical trials in the Los Angeles area",
  intro:
    "On October 5, 2026, a ClinicalTrials.gov radius search found 3,231 recruiting studies with at least one site within 30 miles of downtown Los Angeles, about 14.7% of the 22,007 recruiting in the United States that day.{{cite:ctgov-api}} This page is for research sites across Los Angeles County and nearby Orange County: where the research hubs are, which EHRs hold the patients, who lives here, and which California rules shape AI-assisted outreach.",
  summary: "Los Angeles area recruiting-trial counts, research hubs, health systems and their EHRs, languages, and California outreach rules.",
  lastUpdated: "2026-10-05",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in the Los Angeles area?",
      blocks: [
        {
          type: "p",
          text: "Cancer leads. In the same radius search, 1,511 recruiting studies matched an oncology keyword search: 46.8% of the local total and 21.4% of the 7,064 recruiting oncology studies in the US. The area's share of US studies is also high in dermatology (57 of 212) and gastroenterology (75 of 283), and lowest in pain (53 of 625).{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "los-angeles", cite: "ctgov-api" },
        {
          type: "p",
          text: "A radius count includes every recruiting study with at least one location inside the circle, so a study with sites in both Pasadena and Orange counts once. Area counts come from keyword searches, overlap, and can pull in off-target studies. A count shows where sponsors placed studies, not which ones enroll on schedule. The oncology examples below come from the same October 5, 2026 query.{{cite:ctgov-api}} See [oncology](/oncology) for how Bond screens cancer studies.",
        },
        { type: "trials", geo: "los-angeles", condition: "oncology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are the Los Angeles area's research hubs?",
      blocks: [
        {
          type: "table",
          caption: "Los Angeles area research hubs and what their anchor institutions report, as of October 2026",
          columns: ["Hub", "Anchor institutions", "What they report"],
          rows: [
            [
              "Westwood and the Westside",
              "UCLA Health and the UCLA Jonsson Comprehensive Cancer Center{{cite:nci-centers}}; Cedars-Sinai",
              "UCLA's Clinical and Translational Science Institute (CTSI) lists Cedars-Sinai, Charles R. Drew University and The Lundquist Institute at Harbor-UCLA as partner institutions{{cite:ucla-ctsi}}",
            ],
            [
              "Central and East Los Angeles",
              "Keck Medicine of USC and the USC Norris Comprehensive Cancer Center{{cite:nci-centers}}; Children's Hospital Los Angeles; the county Department of Health Services",
              "The Southern California CTSI at USC and CHLA says it supports more than 1,000 researchers in a city where 90 languages are spoken{{cite:sc-ctsi}}",
            ],
            [
              "Duarte (San Gabriel Valley)",
              "City of Hope Comprehensive Cancer Center{{cite:nci-centers}}",
              "City of Hope's system includes its Los Angeles campus, clinical care locations across Southern California and a new cancer center in Orange County{{cite:coh-about}}",
            ],
            [
              "Pasadena",
              "Kaiser Permanente Southern California, headquartered there{{cite:kp-facts}}",
              "About 5 million members and 16 hospitals across Southern California as of June 30, 2026{{cite:kp-facts}}",
            ],
            [
              "Orange, near the edge of the radius",
              "UC Irvine Chao Family Comprehensive Cancer Center{{cite:nci-centers}}",
              "UC Irvine also hosts one of the National Institute on Aging's Alzheimer's Disease Research Centers{{cite:nia-adrc}}",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "**Cancer.** The National Cancer Institute lists four comprehensive cancer centers inside the 30-mile circle: UCLA Jonsson, USC Norris, City of Hope in Duarte and UC Irvine's Chao Family center in Orange.{{cite:nci-centers}}",
            "**Memory.** The National Institute on Aging funds Alzheimer's Disease Research Centers at USC and UC Irvine.{{cite:nia-adrc}} See [neurology and Alzheimer's](/neurology-and-alzheimers).",
            "**Community research.** The UCLA CTSI runs clinical research centers with Cedars-Sinai and Lundquist/Harbor-UCLA and lists research centers at Charles R. Drew University in South Los Angeles.{{cite:ucla-ctsi}} The SC CTSI says its staff also work at the county Department of Health Services and in Los Angeles neighborhoods.{{cite:sc-ctsi}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do Los Angeles health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Los Angeles area health systems, from vendor FHIR endpoint directories downloaded October 5, 2026",
          columns: ["System", "Footprint", "EHR"],
          rows: [
            ["UCLA Health", "Academic system; home of the Jonsson Comprehensive Cancer Center{{cite:nci-centers}}", "Epic, listed as \"UCLA Medical Center\"{{cite:epic-endpoints}}"],
            ["Cedars-Sinai", "Academic medical center and UCLA CTSI partner{{cite:ucla-ctsi}}", "Epic, listed as \"Cedars-Sinai Health System\"{{cite:epic-endpoints}}"],
            [
              "Kaiser Permanente Southern California",
              "About 5 million members, 16 hospitals and 8,844 physicians in the region{{cite:kp-facts}}",
              "Epic, listed as \"Kaiser Permanente - California - Southern\"{{cite:epic-endpoints}}",
            ],
            ["City of Hope", "Cancer center in Duarte with care locations across Southern California{{cite:coh-about}}", "Epic{{cite:epic-endpoints}}"],
            [
              "Providence, MemorialCare and UCI Health",
              "Hospitals that list recruiting studies in the radius include Providence Saint Joseph Medical Center and MemorialCare Long Beach Medical Center{{cite:ctgov-locations}}",
              "Epic{{cite:epic-endpoints}}",
            ],
            [
              "Keck Medicine of USC",
              "USC's academic system, with the USC Norris Comprehensive Cancer Center{{cite:nci-centers}}",
              "Oracle Health (Cerner), listed as \"USC Health System on behalf of its inpatient and outpatient facilities\"{{cite:oracle-endpoints}}",
            ],
            ["Los Angeles County Department of Health Services", "The county's public hospital and clinic system", "Oracle Health (Cerner){{cite:oracle-endpoints}}"],
            ["Children's Hospital Los Angeles", "Pediatric academic center and SC CTSI partner{{cite:sc-ctsi}}", "Oracle Health (Cerner){{cite:oracle-endpoints}}"],
            ["Huntington Hospital (Pasadena) and Torrance Memorial", "Community hospitals", "Oracle Health (Cerner){{cite:oracle-endpoints}}"],
            [
              "Community health centers",
              "170 HRSA-funded awardees statewide served 5,900,539 patients in 2025{{cite:hrsa-ca}}",
              "Varies; AltaMed is listed in Epic's directory{{cite:epic-endpoints}}",
            ],
          ],
          note: "A directory listing shows a FHIR endpoint, not every system an organization runs. Confirm with the site's IT team.",
        },
        {
          type: "p",
          text: "Los Angeles splits between Epic and Oracle Health. UCLA, Cedars-Sinai, Kaiser and City of Hope appear in Epic's directory, while Keck Medicine of USC, CHLA and the county system appear in Oracle's.{{cite:epic-endpoints,oracle-endpoints}} A study that draws on several of these systems may need both. Bond connects to Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm, OncoEMR and other major EHRs through FHIR, HL7 or an aggregator.{{cite:bond-site,bond-product}} It also works with the CTMS systems sites use, including CRIO, Advarra OnCore, Advarra Clinical Conductor, RealTime and Veeva SiteVault (Bond is a CRIO Certified Partner).{{cite:bond-site}} See [Epic](/integrations/epic) and [Oracle Health (Cerner)](/integrations/oracle-cerner).",
        },
        {
          type: "p",
          text: "Most of what decides eligibility sits in free text: clinic notes, pathology and radiology reports, and molecular results. Bond's screening reads clinical notes, prescriptions, lab results, imaging data and pathology, radiology and molecular reports, and shows criterion-by-criterion evidence for every match.{{cite:bond-product}} See [Identify](/identify).",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in the Los Angeles area, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "9.69 million", label: "Los Angeles County residents on July 1, 2025, down 3.2% since April 2020", cite: "census-co-2025" },
            { value: "49.3%", label: "Hispanic or Latino, Los Angeles County, 2025", cite: "census-cc-2025" },
            { value: "55.2%", label: "Residents 5 and older who speak a language other than English at home, 2024", cite: "acs-c16001" },
            { value: "23.6%", label: "Residents 5 and older who speak English less than \"very well\", 2024", cite: "acs-c16001" },
          ],
        },
        {
          type: "p",
          text: "The Los Angeles-Long Beach-Anaheim metro area had 12,844,441 residents on July 1, 2025.{{cite:census-cbsa-2025}} In Los Angeles County that year, 15.5% of residents were non-Hispanic Asian, 7.5% non-Hispanic Black, and 17.1% were 65 or older.{{cite:census-cc-2025}} In 2024, 34.0% of county residents were born outside the United States, and 7.2% had no health insurance, against 8.2% nationally.{{cite:acs-b05002,acs-c27001}}",
        },
        {
          type: "table",
          caption: "Most common languages spoken at home, Los Angeles County residents 5 and older, 2024",
          columns: ["Language", "Speakers", "Share of residents 5+", "Speak English less than \"very well\""],
          rows: [
            ["Spanish", "3,489,855", "37.6%", "1,479,101"],
            ["Chinese (incl. Mandarin, Cantonese)", "383,333", "4.1%", "219,662"],
            ["Tagalog (incl. Filipino)", "224,158", "2.4%", "66,672"],
            ["Armenian", "198,707", "2.1%", "90,637"],
            ["Korean", "147,864", "1.6%", "88,204"],
            ["Persian (incl. Farsi, Dari)", "74,454", "0.8%", "27,923"],
            ["Vietnamese", "71,281", "0.8%", "44,702"],
          ],
          note: "American Community Survey 1-year estimates, table B16001. Shares are Bond's arithmetic.{{cite:acs-b16001}}",
        },
        {
          type: "p",
          text: "Language is a planning question, not a footnote. More than half of Korean and Chinese speakers in the county report speaking English less than \"very well\".{{cite:acs-b16001}} At California's HRSA-funded health centers in 2025, 64.02% of patients with known ethnicity were Hispanic or Latino and 39.02% had limited English proficiency.{{cite:hrsa-ca}} A cohort that reflects Los Angeles needs Spanish at minimum, and often Chinese, Korean, Armenian or Tagalog, plus a plan for consent forms in those languages. See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks and research sites work in the Los Angeles area?",
      blocks: [
        {
          type: "p",
          text: "Each organization's own website, as of October 2026:",
        },
        {
          type: "ul",
          items: [
            "**Velocity Clinical Research** lists Los Angeles area sites in Los Angeles, Gardena, Huntington Park, North Hollywood and Van Nuys.{{cite:velocity}}",
            "**Flourish Research** lists Los Angeles County sites in Covina and Northridge, which it says focus on cardiovascular, metabolic, kidney and related studies.{{cite:flourish}} See [obesity and metabolic trials](/obesity-and-metabolic).",
            "**START**, an early-phase oncology network, runs START Los Angeles.{{cite:start}}",
            "**Ark Clinical Research** lists sites in Long Beach and Fountain Valley.{{cite:ark}}",
            "**Kaiser Permanente NCORP**, part of NCI's Community Oncology Research Program, lists affiliates at Kaiser medical centers in Los Angeles, West Los Angeles, Bellflower, Panorama City and Woodland Hills.{{cite:ncorp}}",
          ],
        },
        {
          type: "p",
          text: "Much of the area's industry work also runs through hospital and practice sites. Kaiser Permanente medical centers, Providence Saint Joseph Medical Center, Tower Cancer Research Foundation and The Angeles Clinic and Research Institute all appear on location records for recruiting studies in the radius.{{cite:ctgov-locations}} Bond is a CRIO Certified Partner.{{cite:bond-site}} See [research sites](/for/research-sites), [site networks](/for/site-networks) and [physician groups](/for/physician-groups).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which California laws apply to AI outreach, calls and patient records?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how several apply to pre-screening is untested. This is the status as of October 2026 and a map for your counsel, not legal advice.",
        },
        {
          type: "ul",
          items: [
            "**AI-generated patient messages (AB 3030, Health and Safety Code 1339.75).** Since January 1, 2025, a health facility, clinic, physician's office or group practice office that uses generative AI to write or voice patient communications about patient clinical information must include a disclaimer that the communication was AI-generated and clear instructions for reaching a human. On calls, the disclaimer must be spoken at the start and the end; in chat, it must stay on screen. The rule does not apply when a licensed or certified provider reads and reviews the message, and clinical information excludes appointment scheduling, billing and other clerical matters. Physicians answer to the Medical Board of California or the Osteopathic Medical Board.{{cite:ca-hsc-1339-75}} Health-status questions in a pre-screen may count as clinical information; booking alone does not.",
            "**AI and licensed titles (AB 489, Business and Professions Code 4999.8 to 4999.9).** Since January 1, 2026, an AI system may not use terms, letters or phrases in its advertising or functionality that imply its advice or assessments come from a licensed health professional. Each use is a separate violation, enforced by the relevant licensing board.{{cite:ca-ab489}} An agent should not call itself a nurse or a doctor.",
            "**Robocall devices (Public Utilities Code 2871 to 2876).** A call placed with an automatic dialing-announcing device must open with a live, natural-voice announcement that names the caller, asks whether the person consents to hear the prerecorded message and, since January 1, 2025, says whether the message uses an artificial voice. These calls are barred between 9 p.m. and 9 a.m. California time.{{cite:ca-puc-2874,ca-puc-2872}} The law defines the device by its prerecorded message, so whether it reaches a conversational AI agent is untested. Federal rules apply either way; see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026).",
            "**Online bots (Business and Professions Code 17940 to 17943).** Since July 1, 2019, it has been unlawful to use an online bot to mislead someone about its artificial identity to drive a commercial sale or influence a vote; a person who discloses that it is a bot is not liable.{{cite:ca-bpc-17941}}",
            "**Call recording (Penal Code 632 and 637.2).** Recording a confidential communication needs the consent of all parties. Criminal fines run up to $2,500 per violation, and an injured person can sue for $5,000 per violation or three times actual damages.{{cite:ca-pen-632,ca-pen-637-2}} If calls are recorded, say so at the start.",
            "**Medical records (Confidentiality of Medical Information Act, Civil Code 56.10 and 56.36).** A provider needs the patient's authorization to disclose medical information unless an exception applies. One exception allows disclosure to clinical investigators and research organizations for bona fide research purposes, with no further disclosure that would identify the patient. A negligent release can cost $1,000 in nominal damages plus actual damages, and fines or civil penalties up to $2,500 per violation.{{cite:ca-civ-56-10,ca-civ-56-36}} HIPAA's research rules apply alongside it; see [waiver of authorization](/glossary/waiver-of-authorization).",
            "**Consumer privacy (CCPA, Civil Code 1798.146).** The CCPA does not apply to medical information governed by the CMIA, to protected health information held by HIPAA covered entities and business associates, or to information collected, used or disclosed in research, including a clinical trial, conducted under HIPAA, the Common Rule, ICH good clinical practice or FDA human-subject rules.{{cite:ca-civ-1798-146}} Data from ad leads collected before anyone is screened may fall outside those exemptions, so ask counsel how lead forms are covered.",
            "**Research consent (Health and Safety Code 24172 and 24178).** Investigators at institutions with a federal human-subjects assurance who obtain consent under federal rules are exempt from most of California's Protection of Human Subjects in Medical Experimentation Act, but the experimental subject's bill of rights, written in a language the subject is fluent in, still applies.{{cite:ca-hsc-24178,ca-hsc-24172}}",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI is being used, and patients can reach a person at any time, by live transfer to a coordinator or a callback.{{cite:bond-site,bond-product}} For a California site, have counsel decide whether AB 3030 reaches pre-screening, and have the IRB approve the disclosure wording and where it plays in the call.",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Los Angeles site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration typically takes 48 hours, depending on the EHR, IT review and interface method.{{cite:bond-site}} See [implementation](/implementation) for the step-by-step plan.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Agree scope and paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path for screening records.{{cite:bond-site}} Settle the California points up front: AI disclosure wording, the recording notice and calling hours.",
            },
            {
              title: "Connect the EHR",
              text: "Connect Epic or Oracle Health through FHIR, HL7 or an aggregator. A network that spans UCLA-affiliated and USC-affiliated physicians may need one connection per system.",
            },
            {
              title: "Check criteria before outreach",
              text: "Coordinators review the chart evidence behind each criterion on sample matches before any patient is contacted. See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Run ads, reach out and book",
              text: "Bond creates and runs Meta and Google ad campaigns for each study, paid from the site's own ad budget. Its voice and text agents contact every new lead immediately, keep following up with those who have not responded, work in the patient's language and can switch languages mid-call. Pre-screened patients are booked straight into the site's calendar, with reminders by text, voice or email.{{cite:bond-site,bond-product}}",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting in the Los Angeles area?",
      a: "A ClinicalTrials.gov radius search on October 5, 2026 found 3,231 recruiting studies with a site within 30 miles of downtown Los Angeles, 1,511 of them matching an oncology keyword search.{{cite:ctgov-api}}",
    },
    {
      q: "Does California require patients to be told when AI is used?",
      a: "For generative AI communications about patient clinical information from a health facility, clinic or physician's office, yes, since January 1, 2025, unless a licensed provider reads and reviews them first.{{cite:ca-hsc-1339-75}} Bond's agents tell patients that AI is used either way.{{cite:bond-site}}",
    },
    {
      q: "Can a site record AI pre-screening calls in California?",
      a: "Recording a confidential call needs the consent of every party, so announce the recording at the start of each call.{{cite:ca-pen-632}}",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2: recruiting studies within 30 miles of downtown Los Angeles",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?filter.geo=distance(34.0522,-118.2437,30mi)&filter.overallStatus=RECRUITING&countTotal=true&pageSize=1",
      year: "2026",
      note: "Radius search queried October 5, 2026: filter.geo distance(34.0522,-118.2437,30mi), overall status Recruiting; \"totalCount\": 3231. Area counts add a query.cond keyword search (oncology: cancer OR neoplasm OR carcinoma OR lymphoma OR leukemia) and returned oncology 1,511; cardiology 421; obesity and type 2 diabetes 110; neurology 122; dermatology 57; pain 53; gastroenterology 75; psychiatry 152. US totals from query.locn=United States the same day: all 22,007; oncology 7,064; dermatology 212; gastroenterology 283; pain 625. Shares are Bond's arithmetic.",
    },
    {
      id: "ctgov-locations",
      title: "ClinicalTrials.gov API v2: location records for recruiting studies within 30 miles of downtown Los Angeles",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?filter.geo=distance(34.0522,-118.2437,30mi)&filter.overallStatus=RECRUITING&fields=NCTId,LocationFacility,LocationCity,LocationGeoPoint&pageSize=1000",
      year: "2026",
      note: "Queried October 5, 2026; Bond listed the facility names on location records inside the radius. Facility names as they appear: \"Kaiser Permanente Los Angeles Medical Center\"; \"Providence Saint Joseph Medical Center/Disney Family Cancer Center\"; \"Tower Cancer Research Foundation\"; \"The Angeles Clinic and Research Institute\"; \"MemorialCare Long Beach Medical Center\".",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Read October 5, 2026. California entries include \"Chao Family Comprehensive Cancer Center, University of California, Irvine, Orange, California\"; \"City of Hope Comprehensive Cancer Center, Duarte, California\"; \"Jonsson Comprehensive Cancer Center, University of California at Los Angeles, Los Angeles, California\"; \"USC Norris Comprehensive Cancer Center, University of Southern California, Los Angeles, California\", each a \"Comprehensive Cancer Center\".",
    },
    {
      id: "nia-adrc",
      title: "Alzheimer's Disease Research Centers",
      publisher: "National Institute on Aging, NIH",
      url: "https://www.nia.nih.gov/health/clinical-trials-and-studies/alzheimers-disease-research-centers",
      year: "2026",
      note: "Read October 5, 2026. California entries include \"University of California, Irvine ... Alzheimer's Disease Research Center ... Irvine, CA 92697-4545\" and \"University of Southern California ... Alzheimer's Disease Research Center ... 1520 San Pablo Street, Suite 3000 Los Angeles, CA 90033\".",
    },
    {
      id: "ucla-ctsi",
      title: "UCLA Clinical and Translational Science Institute",
      publisher: "UCLA Clinical and Translational Science Institute",
      url: "https://ctsi.ucla.edu/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Partner Institutions Cedars-Sinai Charles R. Drew University The Lundquist Institute at Harbor-UCLA\"; clinical research center links \"Cedars-Sinai CTRC\", \"Lundquist/Harbor-UCLA CTRC\" and \"CDU Research Centers\".",
    },
    {
      id: "sc-ctsi",
      title: "About SC CTSI",
      publisher: "Southern California Clinical and Translational Science Institute (USC and CHLA)",
      url: "https://sc-ctsi.org/about",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Set in the heart of Los Angeles where 90 languages are spoken, we support more than 1,000 researchers\" and \"The majority of us call USC home. Others work at Children's Hospital Los Angeles, Los Angeles County Department of Health Services, or out in the neighborhoods of Los Angeles.\"",
    },
    {
      id: "coh-about",
      title: "Who We Are",
      publisher: "City of Hope",
      url: "https://www.cityofhope.org/about-city-of-hope",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"City of Hope’s growing national system includes its Los Angeles campus, a network of clinical care locations across Southern California, a new cancer center in Orange County, California, and cancer treatment centers and outpatient facilities in the Atlanta, Chicago and Phoenix areas.\" Also: \"Headquartered in Duarte, California\".",
    },
    {
      id: "kp-facts",
      title: "Fast Facts",
      publisher: "Kaiser Permanente",
      url: "https://about.kaiserpermanente.org/who-we-are/fast-facts",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Kaiser Permanente in Southern California opened to the public in 1953. It is headquartered in Pasadena\"; regional figures \"Members 5M\", \"Physicians 8,844\", \"Hospitals 16\". Footnotes: \"Data as of June 30, 2026, unless otherwise noted\"; physician counts \"Approximate as of December 31, 2025\".",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Downloaded October 5, 2026 (bundle \"total\": 479). Endpoint organization names include \"UCLA Medical Center\"; \"Cedars-Sinai Health System\"; \"Kaiser Permanente - California - Southern\"; \"City of Hope\"; \"Providence Health & Services - Oregon/California\"; \"MemorialCare\"; \"University of California Irvine\"; \"AltaMed\", each with status \"active\". A listing shows an Epic FHIR endpoint, not every system an organization runs.",
    },
    {
      id: "oracle-endpoints",
      title: "Oracle Health Millennium patient R4 FHIR endpoints (millennium_patient_r4_endpoints.json)",
      publisher: "Oracle (oracle-samples/ignite-endpoints on GitHub)",
      url: "https://raw.githubusercontent.com/oracle-samples/ignite-endpoints/main/oracle_health_fhir_endpoints/millennium_patient_r4_endpoints.json",
      year: "2026",
      note: "Downloaded October 5, 2026. Organization entries \"USC Health System on behalf of its inpatient and outpatient facilities\" (city \"Los Angeles\", state \"CA\"); \"LOS ANGELES COUNTY DEPT OF HEALTH SERVICES\" (\"Los Angeles\"); \"Children's Hospital Los Angeles\" (\"Los Angeles\"); \"Huntington Hospital\" (\"Pasadena\"); \"TORRANCE MEMORIAL MEDICAL CENTER\" (\"Torrance\"). A listing shows a Millennium FHIR endpoint, not every system the organization runs.",
    },
    {
      id: "hrsa-ca",
      title: "California Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/CA",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Total Number of Reporting Program Awardees: 170 Reporting Period: 2025 Total Patients Served: 5,900,539\". Five-year table, 2025 column: \"% Hispanic, Latino/a, or Spanish Origin Patients\" 64.02% (denominator: patients with known ethnicity); \"Limited English Proficiency\" 39.02% (2,302,159 patients).",
    },
    {
      id: "census-co-2025",
      title: "County Population Totals: April 1, 2020 to July 1, 2025 (CO-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/totals/co-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row \"Los Angeles County\": ESTIMATESBASE2020 10,017,414; POPESTIMATE2025 9,694,934. The 3.2% decline is Bond's arithmetic.",
    },
    {
      id: "census-cc-2025",
      title: "Annual County Resident Population Estimates by Age, Sex, Race, and Hispanic Origin: April 1, 2020 to July 1, 2025 (CC-EST2025-ALLDATA-06)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/asrh/cc-est2025-alldata-06.csv",
      year: "2026",
      note: "Downloaded October 5, 2026 and summed by Bond for Los Angeles County, YEAR 7 (\"7 = 7/1/2025 population estimate\" in the file layout): TOT_POP 9,694,934; Hispanic (H_MALE + H_FEMALE) 4,776,046 (49.3%); not Hispanic, Asian alone 1,498,468 (15.5%); not Hispanic, Black alone 726,958 (7.5%); age 65 and over (AGEGRP 14 to 18) 1,653,035 (17.1%).",
    },
    {
      id: "census-cbsa-2025",
      title: "Metropolitan and Micropolitan Statistical Area Population Totals: April 1, 2020 to July 1, 2025 (CBSA-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/metro/totals/cbsa-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row CBSA 31080 \"Los Angeles-Long Beach-Anaheim, CA\", Metropolitan Statistical Area: POPESTIMATE2025 12,844,441.",
    },
    {
      id: "acs-c16001",
      title: "American Community Survey 2024 1-year estimates, table C16001: Language Spoken at Home for the Population 5 Years and Over",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-c16001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. Los Angeles County (GEO_ID 0500000US06037): C16001_E001 \"Total:\" 9,282,796; C16001_E002 \"Speak only English\" 4,158,130. The sum of all \"Speak English less than 'very well'\" lines is 2,187,790. The 55.2% and 23.6% shares are Bond's arithmetic. The 2025 table-based summary file directory was empty when checked.",
    },
    {
      id: "acs-b16001",
      title: "American Community Survey 2024 1-year estimates, table B16001: Language Spoken at Home by Ability to Speak English for the Population 5 Years and Over",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-b16001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. Los Angeles County, speakers and those who speak English less than \"very well\": Spanish 3,489,855 and 1,479,101; Chinese (incl. Mandarin, Cantonese) 383,333 and 219,662; Tagalog (incl. Filipino) 224,158 and 66,672; Armenian 198,707 and 90,637; Korean 147,864 and 88,204; Persian (incl. Farsi, Dari) 74,454 and 27,923; Vietnamese 71,281 and 44,702. Population 5 and over: 9,282,796.",
    },
    {
      id: "acs-b05002",
      title: "American Community Survey 2024 1-year estimates, table B05002: Place of Birth by Nativity and Citizenship Status",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-b05002.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. Los Angeles County: B05002_E001 \"Total:\" 9,757,179; B05002_E013 \"Foreign-born:\" 3,317,967 (34.0%, Bond's arithmetic).",
    },
    {
      id: "acs-c27001",
      title: "American Community Survey 2024 1-year estimates, table C27001: Health Insurance Coverage Status by Age",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-c27001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026 and summed by Bond across the \"No health insurance coverage\" lines. Los Angeles County: 698,153 of 9,695,736 (7.2%). United States: 27,479,253 of 335,190,522 (8.2%).",
    },
    {
      id: "velocity",
      title: "Locations",
      publisher: "Velocity Clinical Research",
      url: "https://velocityclinical.com/locations/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Velocity Clinical Research Gardena, California\"; \"Velocity Clinical Research Huntington Park, California\"; \"Velocity Clinical Research Los Angeles, California\"; \"Velocity Clinical Research North Hollywood, California\"; \"Velocity Clinical Research Van Nuys, California\".",
    },
    {
      id: "flourish",
      title: "Clinical Trial Site Locations",
      publisher: "Flourish Research",
      url: "https://flourishresearch.com/locations/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Los Angeles (Covina) Clinical Research 315 N 3rd Ave #103, Covina, CA 91723\"; \"Los Angeles (Northridge) Clinical Research 18433 Roscoe Blvd #208, Northridge, CA 91325\"; \"Our two locations in Los Angeles County specialize in Cardiovascular/Metabolic/Kidney, and related therapeutic areas\".",
    },
    {
      id: "start",
      title: "START Locations",
      publisher: "START Center for Cancer Research",
      url: "https://startresearch.com/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"START Los Angeles Los Angeles, California START Los Angeles advances early-phase oncology research by expanding access to clinical trials for a large, diverse patient population in one of America’s most populous states.\"",
    },
    {
      id: "ark",
      title: "Ark Clinical Research",
      publisher: "Ark Clinical Research",
      url: "https://arkclinicalresearch.com/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Locations Long Beach 2220 Clark Ave Unit A Long Beach, CA 90815\" and \"Fountain Valley 11160 Warner Ave. Suite #311 Fountain Valley\".",
    },
    {
      id: "ncorp",
      title: "NCORP Sites (Find a Site)",
      publisher: "National Cancer Institute, NCI Community Oncology Research Program",
      url: "https://ncorp.cancer.gov/findasite/?state=California",
      year: "2026",
      note: "Read October 5, 2026; the page carried a notice that \"Because of a lapse in government funding, the information on this website may not be up to date\". Quote: \"Kaiser Permanente NCORP\" with \"Site Address: Oakland, California\"; affiliates include \"Kaiser Permanente Los Angeles Medical Center\", \"Kaiser Permanente West Los Angeles\", \"Kaiser Permanente - Bellflower\", \"Kaiser Permanente - Panorama City\" and \"Kaiser Permanente - Woodland Hills\".",
    },
    {
      id: "ca-hsc-1339-75",
      title: "Health and Safety Code 1339.75 (added by AB 3030, Stats. 2024, Ch. 848)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=HSC&sectionNum=1339.75",
      year: "2024",
      note: "Read October 5, 2026. Quote: \"For audio communications, the disclaimer shall be provided verbally at the start and the end of the interaction.\" Also: \"If a communication is generated by generative artificial intelligence and read and reviewed by a human licensed or certified health care provider, the requirements of subdivision (a) do not apply.\" Patient clinical information \"does not include administrative matters, including, but not limited to, appointment scheduling, billing, or other clerical or business matters.\" History: \"(Added by Stats. 2024, Ch. 848, Sec. 1. (AB 3030) Effective January 1, 2025.)\"",
    },
    {
      id: "ca-ab489",
      title: "AB-489 Health care professions: deceptive terms or letters: artificial intelligence (Chapter 615, Statutes of 2025)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260AB489",
      year: "2025",
      note: "Read October 5, 2026. \"Approved by Governor October 11, 2025.\" Business and Professions Code 4999.9(c): \"The use of a term, letter, or phrase in the advertising or functionality of an AI or GenAI system, program, device, or similar technology that indicates or implies that the care, advice, reports, or assessments being offered through the AI or GenAI technology is being provided by a natural person in possession of the appropriate license or certificate to practice as a health care professional, is prohibited.\" 4999.9(d): \"Each use of a prohibited term, letter, or phrase shall constitute a separate violation of this chapter.\" The code section history reads \"(Added by Stats. 2025, Ch. 615, Sec. 1. (AB 489) Effective January 1, 2026.)\"",
    },
    {
      id: "ca-puc-2874",
      title: "Public Utilities Code 2874 (amended by AB 2905, Stats. 2024, Ch. 316)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PUC&sectionNum=2874",
      year: "2024",
      note: "Read October 5, 2026. Quote: \"the device may be operated only after an unrecorded, natural voice announcement has been made to the person called by the person calling\"; the announcement must \"Inquire as to whether the person called consents to hear the prerecorded message of the person calling\" and \"Inform the person called if the prerecorded message uses an artificial voice.\" History: \"(Amended by Stats. 2024, Ch. 316, Sec. 1. (AB 2905) Effective January 1, 2025.)\" Section 2871 defines the device as equipment with \"the capability ... to disseminate a prerecorded message to the telephone number called.\"",
    },
    {
      id: "ca-puc-2872",
      title: "Public Utilities Code 2872",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PUC&sectionNum=2872",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"A person shall not operate an automatic dialing-announcing device in this state to place a call that is received by a telephone in this state during the hours between 9 p.m. and 9 a.m. California time.\"",
    },
    {
      id: "ca-bpc-17941",
      title: "Business and Professions Code 17941 (SB 1001, Stats. 2018, Ch. 892)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=17941",
      year: "2018",
      note: "Read October 5, 2026. Quote: \"It shall be unlawful for any person to use a bot to communicate or interact with another person in California online, with the intent to mislead the other person about its artificial identity for the purpose of knowingly deceiving the person about the content of the communication in order to incentivize a purchase or sale of goods or services in a commercial transaction or to influence a vote in an election. A person using a bot shall not be liable under this section if the person discloses that it is a bot.\" History: \"Operative July 1, 2019, pursuant to Section 17943.\" Section 17940 defines a bot as \"an automated online account\".",
    },
    {
      id: "ca-pen-632",
      title: "Penal Code 632",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PEN&sectionNum=632",
      year: "2016",
      note: "Read October 5, 2026. Quote: \"A person who, intentionally and without the consent of all parties to a confidential communication, uses an electronic amplifying or recording device to eavesdrop upon or record the confidential communication ... shall be punished by a fine not exceeding two thousand five hundred dollars ($2,500) per violation\".",
    },
    {
      id: "ca-pen-637-2",
      title: "Penal Code 637.2",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PEN&sectionNum=637.2",
      year: "2016",
      note: "Read October 5, 2026. Quote: \"Any person who has been injured by a violation of this chapter may bring an action against the person who committed the violation for the greater of the following amounts: (1) Five thousand dollars ($5,000) per violation. (2) Three times the amount of actual damages, if any, sustained by the plaintiff.\" History: \"(Amended by Stats. 2016, Ch. 855, Sec. 4. (AB 1671) Effective January 1, 2017.)\" SB 690 (Chapter 976, Statutes of 2026, approved September 30, 2026; https://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=202520260SB690) amends this section so that only the Attorney General can sue private actors over pen-register claims arising on websites and apps; it does not change the remedy for recorded calls.",
    },
    {
      id: "ca-civ-56-10",
      title: "Civil Code 56.10 (Confidentiality of Medical Information Act)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=56.10",
      year: "2026",
      note: "Read October 5, 2026. Quote, 56.10(a): \"A provider of health care, health care service plan, or contractor shall not disclose medical information regarding a patient ... without first obtaining an authorization, except as provided in subdivision (b) or (c).\" 56.10(c)(7): \"The information may be disclosed to public agencies, clinical investigators, including investigators conducting epidemiologic studies, health care research organizations, and accredited public or private nonprofit educational or health care institutions for bona fide research purposes. However, no information so disclosed shall be further disclosed by the recipient in a way that would disclose the identity of a patient or violate this part.\"",
    },
    {
      id: "ca-civ-56-36",
      title: "Civil Code 56.36 (Confidentiality of Medical Information Act)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=56.36",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"nominal damages of one thousand dollars ($1,000)\" and a person or entity that negligently discloses medical information is liable \"for an administrative fine or civil penalty not to exceed two thousand five hundred dollars ($2,500) per violation.\"",
    },
    {
      id: "ca-civ-1798-146",
      title: "Civil Code 1798.146 (California Consumer Privacy Act)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=1798.146",
      year: "2026",
      note: "Read October 5, 2026. Quote, 1798.146(a)(5): \"Information that is collected, used, or disclosed in research, as defined in Section 164.501 of Title 45 of the Code of Federal Regulations, including, but not limited to, a clinical trial, and that is conducted in accordance with applicable ethics, confidentiality, privacy, and security rules of Part 164 of Title 45 of the Code of Federal Regulations, the Federal Policy for the Protection of Human Subjects, also known as the Common Rule, good clinical practice guidelines issued by the International Council for Harmonisation, or human subject protection requirements of the United States Food and Drug Administration.\"",
    },
    {
      id: "ca-hsc-24178",
      title: "Health and Safety Code 24178",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=HSC&sectionNum=24178",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Except for this section and the requirements set forth in Sections 24172 and 24176, this chapter shall not apply to any person who is conducting a medical experiment as an investigator within an institution that holds an assurance with the United States Department of Health and Human Services pursuant to Part 46 of Title 45 of the Code of Federal Regulations and who obtains informed consent in the method and manner required by those regulations.\"",
    },
    {
      id: "ca-hsc-24172",
      title: "Health and Safety Code 24172",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=HSC&sectionNum=24172",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"“experimental subject’s bill of rights,” means a list of the rights of a subject in a medical experiment, written in a language in which the subject is fluent.\"",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, October 2026.",
    },
  ],
  related: [
    { label: "All locations", href: "/clinical-trial-recruitment", description: "Registry counts and outreach rules for other states and regions." },
    { label: "Bond for research sites", href: "/for/research-sites", description: "How screening, outreach and booked visits fit a site's coordinators." },
    { label: "Oncology", href: "/oncology", description: "How Bond screens for cancer trials, the area's largest category by count." },
    { label: "FQHCs and community sites", href: "/for/fqhcs-and-community-sites", description: "Reaching patients at community health centers." },
    { label: "Engage", href: "/engage", description: "Ads, voice and text outreach, and booked visits." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
  ],
};

export default page;
