import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/nevada",
  category: "geography",
  title: "Nevada clinical trial recruitment: Las Vegas research sites",
  description:
    "For Las Vegas and Reno research sites: Nevada recruiting-trial counts, research hubs, health system EHRs, demographics and state rules on outreach and AI.",
  keywords: [
    "clinical trial recruitment Nevada",
    "Las Vegas research sites",
    "clinical trials Las Vegas Reno Henderson",
    "Nevada patient recruitment",
    "Nevada health system EHRs",
  ],
  eyebrow: "Nevada",
  h1: "Recruiting for clinical trials in Nevada",
  intro:
    "As of September 21, 2026, 565 studies on ClinicalTrials.gov were recruiting at one or more Nevada sites. That is about 17 per 100,000 residents, against about 22 in Arizona and 34 in Utah.{{cite:ctgov-api,census-nst-2025}} Most of that work runs through a few health systems, oncology practices and independent sites in Las Vegas and Reno.",
  summary: "Nevada recruiting-trial counts, Las Vegas and Reno research hubs, health systems and their EHRs, demographics, and state outreach rules.",
  lastUpdated: "2026-09-24",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in Nevada?",
      blocks: [
        {
          type: "p",
          text: "Industry sponsors lead 429 of the 565 Nevada studies, about 76%.{{cite:ctgov-nv}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "nevada", cite: "ctgov-api" },
        {
          type: "p",
          text: "Las Vegas sites appear on 420 studies, Reno on 182, Henderson on 58 and Carson City on 30.{{cite:ctgov-nv}} A count shows where sponsors placed studies, not which ones enroll on schedule. The examples below come from oncology, the largest area. See [oncology](/oncology).",
        },
        { type: "trials", geo: "nevada", condition: "oncology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where does clinical research happen in Nevada?",
      blocks: [
        {
          type: "table",
          caption: "Nevada research hubs",
          columns: ["Hub", "Anchor institutions", "What they report"],
          rows: [
            [
              "Las Vegas",
              "Kirk Kerkorian School of Medicine at UNLV; UMC Southern Nevada; Cleveland Clinic Lou Ruvo Center for Brain Health",
              "Cleveland Clinic says it ran more than 125 neurology studies there in 15 years and that its Nevada research led to eight FDA drug approvals{{cite:cc-nevada}}",
            ],
            [
              "Las Vegas and Henderson oncology",
              "Comprehensive Cancer Centers of Nevada (The US Oncology Network); Nevada Cancer Research Foundation NCORP{{cite:ncorp-nv}}",
              "Comprehensive says it offers more than 170 Phase I to III trials a year{{cite:cccn}} and announced a collaboration with Sarah Cannon Research Institute in May 2026{{cite:cccn-scri}}",
            ],
            [
              "Reno",
              "UNR Med and Renown Health, which formed Nevada's first integrated academic health system in 2021{{cite:unr-history}}",
              "The Healthy Nevada Project, a genetics study Renown and the Desert Research Institute launched in 2016, had enrolled more than 65,000 participants as of May 2026{{cite:unr-hnp}}",
            ],
          ],
        },
        {
          type: "p",
          text: "As of September 2026, Nevada has no NCI-designated cancer center.{{cite:nci-centers}} Cancer trials reach patients through community practices and the Nevada Cancer Research Foundation NCORP, whose affiliates include Comprehensive Cancer Centers of Nevada, OptumCare Cancer Care, UMC, Summerlin and Sunrise hospitals, Carson Tahoe Regional Medical Center and Cure 4 the Kids Foundation.{{cite:ncorp-nv}}",
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do Nevada's health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Nevada health systems, from public sources as of September 2026",
          columns: ["System", "Nevada footprint", "EHR"],
          rows: [
            [
              "Renown Health (Reno)",
              "UNR Med's academic partner{{cite:unr-history}}; on 102 recruiting studies{{cite:ctgov-nv}}",
              "Epic, listed as \"Renown, Barton, CVMC\" in Epic's FHIR endpoint directory{{cite:epic-endpoints}}",
            ],
            [
              "University Medical Center of Southern Nevada (Las Vegas)",
              "Public academic hospital; on 40 recruiting studies{{cite:ctgov-nv}}",
              "Epic; its UMConnect patient portal is developed by Epic{{cite:umc-mychart,epic-endpoints}}",
            ],
            [
              "Intermountain Health (southern Nevada)",
              "More than 65 clinics serving about 350,000 southern Nevadans, per a 2024 UNLV release{{cite:unlv-intermountain}}",
              "Epic, chosen in 2023 partly to replace legacy Nevada systems and switched on across its six-state footprint in September 2025{{cite:intermountain-epic,intermountain-golive,epic-endpoints}}",
            ],
            [
              "Rural hospitals",
              "Humboldt General Hospital (Winnemucca) and Boulder City Hospital",
              "Oracle Health, listed in Oracle's FHIR endpoint directory{{cite:oracle-endpoints}}",
            ],
            [
              "Community health centers",
              "7 HRSA-funded awardees serving 135,913 patients in 2025{{cite:hrsa-nv}}",
              "Varies by center",
            ],
          ],
        },
        {
          type: "p",
          text: "Renown, UMC and Intermountain all run Epic, so a two-metro study can often reuse one FHIR approach, though each system runs its own IT review. Bond connects through FHIR R4 APIs, HL7 v2 or an aggregator.{{cite:bond-site}} See [Epic](/integrations/epic) and [Oracle Health (Cerner)](/integrations/oracle-cerner).",
        },
      ],
    },
    {
      id: "sites-and-physician-groups",
      heading: "Which sites and physician groups run trials in Nevada?",
      blocks: [
        {
          type: "p",
          text: "Oncology and urology practices and NCORP-affiliated hospitals appear on more Nevada studies than standalone research sites.{{cite:ctgov-nv,ncorp-nv}} Networks with Las Vegas sites include The US Oncology Network, through Comprehensive,{{cite:cccn-scri}} and multi-state site companies AMR Clinical, IMA Clinical Research, Wake Research and Alliance Clinical.{{cite:ctgov-nv}}",
        },
        {
          type: "table",
          caption: "Recruiting ClinicalTrials.gov studies that list a Nevada location, selected organizations, September 2026",
          columns: ["Organization", "Type and city", "Studies"],
          rows: [
            ["Renown Health", "Academic health system, Reno", "102{{cite:ctgov-nv}}"],
            ["Comprehensive Cancer Centers of Nevada", "Oncology practice, Las Vegas and Henderson", "67{{cite:ctgov-nv}}"],
            ["Optum Nevada practices, mostly OptumCare Cancer Care", "Physician group, Las Vegas and Henderson", "55{{cite:ctgov-nv}}"],
            ["Cure 4 the Kids Foundation", "Pediatric specialty care, Las Vegas", "49{{cite:ctgov-nv}}"],
            ["UMC Southern Nevada", "Public academic hospital, Las Vegas", "40{{cite:ctgov-nv}}"],
            ["Summerlin Hospital Medical Center", "Hospital, Las Vegas", "38{{cite:ctgov-nv}}"],
            ["Sunrise Hospital and Medical Center", "Hospital, Las Vegas", "31{{cite:ctgov-nv}}"],
            ["Las Vegas Urology and Urology Specialists of Nevada", "Urology physician groups, Las Vegas area", "24{{cite:ctgov-nv}}"],
            ["Excel Clinical Research, also listed as Alliance Clinical Las Vegas", "Research site, Las Vegas", "18{{cite:ctgov-nv}}"],
            ["Vector Clinical Trials", "Research site, Las Vegas", "17{{cite:ctgov-nv}}"],
            ["Advanced Research Institute", "Research site, Reno", "6{{cite:ctgov-nv}}"],
          ],
          note: "Counts group facility-name variants and are approximate.",
        },
        {
          type: "p",
          text: "At a practice-based site, pre-screening competes with clinic work for coordinator time. See [physician groups](/for/physician-groups) and [research sites](/for/research-sites). Bond is a CRIO Certified Partner.{{cite:bond-site}}",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in Nevada, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "3.28 million", label: "Residents on July 1, 2025", cite: "census-nst-2025" },
            { value: "31.2%", label: "Hispanic or Latino, 2025", cite: "census-asrh-2025" },
            { value: "18.3%", label: "Age 65 or older, up from 16.4% in 2020", cite: "census-asrh-2025" },
            { value: "11.4%", label: "Uninsured in 2024, against 8.2% nationally", cite: "census-acs-uninsured" },
          ],
        },
        {
          type: "p",
          text: "Clark County (Las Vegas) had 2,407,226 residents in 2025, 73.3% of the state, and Washoe County (Reno) had 509,386, another 15.5%.{{cite:census-co-2025}} The state grew about 5.7% from April 2020 to July 2025, the 10th-fastest rate of any state.{{cite:census-nst-2025}}",
        },
        {
          type: "p",
          text: "A 2025 University of Nevada, Reno workforce report counts 219.8 active physicians per 100,000 Nevadans against 297.1 nationally, and 64.9% of residents live in a primary care shortage area.{{cite:nv-pwin-2025}} Per 100,000 residents Nevada had 2.4 medical oncologists against 6.4 nationally, 4.3 cardiologists against 9.5 and 3.9 neurologists against 6.8.{{cite:nv-pwin-2025}} Fewer specialists means fewer referrals, so a site's own records must do more of the finding. See [cardiology](/cardiology) and [neurology and Alzheimer's](/neurology-and-alzheimers).",
        },
        {
          type: "p",
          text: "At Nevada's HRSA-funded health centers in 2025, 53.6% of patients were Hispanic or Latino, 30.2% had limited English proficiency and 28.1% were uninsured.{{cite:hrsa-nv}} A representative Nevada cohort usually needs those centers and Spanish-language outreach. See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which Nevada laws apply to AI outreach and patient data?",
      blocks: [
        {
          type: "p",
          text: "None of these laws targets trial recruitment. This is a map for your counsel, not legal advice.",
        },
        {
          type: "ul",
          items: [
            "**AI and mental health care (AB 406).** Since July 1, 2025, an AI provider may not offer a system programmed to provide professional mental or behavioral health care in Nevada, suggest that its system can, or present it as a therapist, counselor or doctor. Civil penalties can reach $15,000 per violation.{{cite:nv-ab406}} Mental health providers may still use AI for scheduling, records and billing.{{cite:nv-ab406}} With 41 recruiting psychiatry studies in Nevada,{{cite:ctgov-api}} keep [psychiatry](/psychiatry) pre-screening scripts to eligibility and logistics.",
            "**Consumer health data (SB 370).** Since March 31, 2024, collecting consumer health data needs affirmative consent unless needed for a service the consumer requested, and sharing it needs separate consent.{{cite:nv-sb370}} HIPAA-regulated entities are exempt, as is research under the Common Rule, FDA human-subject rules or ICH GCP. Recruitment ads run by a company outside HIPAA may still be covered.",
            "**Geofencing (SB 370).** No one may set a geofence within 1,750 feet of a medical facility to track people seeking care or send them health-related ads.{{cite:nv-sb370}} That can reach location-targeted trial ads near clinics.",
            "**Autodialed sales calls (NRS 597.812 to 597.818).** The law covers equipment that dials random or sequential numbers to play prerecorded sales messages. Such calls must open with a natural voice that identifies the caller and may not reach Nevada phones between 8 p.m. and 9 a.m.; calls to people with a preexisting business relationship are exempt.{{cite:nrs-597}} Federal rules still apply; see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026).",
            "**Call recording (NRS 200.620 and 200.690).** Unless an emergency makes a court order impractical, one party's consent is not enough to intercept a phone call, and willful violations are a category D felony.{{cite:nrs-200}} Get every party's consent before recording a call to a Nevada number.",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI assistance is being used, and patients can reach a person at any time: the agent transfers the call live to a coordinator or books a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Scripts are configured per site and study, so a Nevada site can use its own IRB-reviewed wording and recording notice.",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Nevada site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration usually takes 48 hours.{{cite:bond-site}} See [implementation](/implementation).",
        },
        {
          type: "steps",
          items: [
            {
              title: "Agree scope and paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path.",
            },
            {
              title: "Connect the EHR",
              text: "Sites on Epic systems such as Renown, UMC or Intermountain typically connect through Epic's FHIR APIs after IT review. Others use FHIR, HL7 or an aggregator.",
            },
            {
              title: "Check criteria before outreach",
              text: "Coordinators check the chart evidence behind each criterion on sample matches before any outreach. See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Screen, reach out and schedule",
              text: "Voice and text agents pre-screen and schedule in the patient's preferred language, including English, Spanish, Mandarin and many others, then hand off to coordinators.{{cite:bond-product}} Agree calling hours, recording consent and bilingual staff coverage up front.",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting in Nevada?",
      a: "As of September 21, 2026, 565 studies on ClinicalTrials.gov listed a recruiting Nevada site, 205 of them in oncology.{{cite:ctgov-api}}",
    },
    {
      q: "Can an AI agent call patients about a psychiatry study in Nevada?",
      a: "AB 406 bars AI systems programmed to provide professional mental or behavioral health care, and bars presenting an AI system as a therapist, counselor or doctor.{{cite:nv-ab406}} Pre-screening and scheduling are different tasks, but have counsel review psychiatry scripts.",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Queried September 21, 2026.",
    },
    {
      id: "ctgov-nv",
      title: "ClinicalTrials.gov API v2: recruiting studies with a Nevada location",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?query.locn=Nevada&filter.overallStatus=RECRUITING&pageSize=1000",
      year: "2026",
      note: "Queried September 21, 2026 and tallied by Bond. 565 studies returned, all with a location whose state is Nevada. Lead sponsor class INDUSTRY on 429 (76%). Studies by city: Las Vegas 420, Reno 182, Henderson 58, Carson City 30, Pahrump 25. Organization counts group facility-name variants (for example, every Comprehensive Cancer Centers of Nevada location, and \"Excel Clinical Research\" with \"Alliance Clinical Las Vegas (Excel Clinical Research)\" and \"Alliance Clinical - Las Vegas\") and count each study once. Nevada studies listing AMR Clinical: 5; IMA Clinical Research: 6; Wake Research: 5. A follow-up search by each company name in September 2026 found recruiting locations for each in other states (AMR Clinical 11, IMA Clinical Research 9, Wake Research 8, Alliance Clinical 3).",
    },
    {
      id: "census-nst-2025",
      title: "State Population Totals and Components of Change: April 1, 2020 to July 1, 2025 (NST-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/state/totals/NST-EST2025-ALLDATA.csv",
      year: "2025",
      note: "Downloaded September 21, 2026. Row \"Nevada\": ESTIMATESBASE2020 3,105,593; POPESTIMATE2025 3,282,188. Row \"Arizona\": POPESTIMATE2025 7,623,818. Row \"Utah\": POPESTIMATE2025 3,538,904. Nevada's 5.7% growth and its rank (10th of 50 states) are Bond's arithmetic from this file. Recruiting studies per 100,000 residents (Nevada 17.2, Arizona 22.2, Utah 34.2) are Bond's arithmetic from these rows and the ClinicalTrials.gov counts (565, 1,689 and 1,210).",
    },
    {
      id: "census-co-2025",
      title: "County Population Totals: April 1, 2020 to July 1, 2025 (CO-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/totals/co-est2025-alldata.csv",
      year: "2025",
      note: "Downloaded September 21, 2026. POPESTIMATE2025: Nevada 3,282,188; Clark County 2,407,226; Washoe County 509,386. The 73.3% and 15.5% shares are Bond's arithmetic.",
    },
    {
      id: "census-asrh-2025",
      title: "Annual State Resident Population Estimates for 6 Race Groups by Age, Sex, and Hispanic Origin: April 1, 2020 to July 1, 2025 (SC-EST2025-ALLDATA6)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/state/asrh/sc-est2025-alldata6.csv",
      year: "2025",
      note: "Downloaded September 21, 2026 and summed by Bond for Nevada, both sexes: POPESTIMATE2025 total 3,282,188; Hispanic origin 1,024,971 (31.2%); age 65 and over 599,211 (18.3%), against 511,632 of 3,116,851 in POPESTIMATE2020 (16.4%).",
    },
    {
      id: "census-acs-uninsured",
      title: "Health Insurance Coverage by State: 2023 and 2024 (ACSBR-024)",
      publisher: "U.S. Census Bureau, American Community Survey Briefs",
      url: "https://www2.census.gov/library/publications/2025/demo/acsbr-024.pdf",
      year: "2025",
      note: "Quote: Appendix Table 2, \"United States 7.9 0.1 8.2 0.1\" and \"Nevada 10.8 0.5 11.4 0.5\" (2023 and 2024 percent uninsured with margins of error).",
    },
    {
      id: "hrsa-nv",
      title: "Nevada Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/topics/healthcenters/uds/overview/state/NV",
      year: "2026",
      note: "Quote: \"Total Number of Reporting Program Awardees: 7 Reporting Period: 2025 Total Patients Served: 135,913\". Patient characteristics on the same page, 2025: Hispanic/Latino 53.62%; limited English proficiency 30.20%; uninsured 28.10%. Read September 2026.",
    },
    {
      id: "nv-pwin-2025",
      title: "Physician Workforce in Nevada - 2025",
      publisher: "Nevada Health Workforce Research Center, University of Nevada, Reno School of Medicine",
      url: "https://www.nvha.nv.gov/siteassets/content/community/gme/25_PWIN_FINAL_4-21-25_ADA.pdf",
      year: "2025",
      note: "Quote: Figure 7 rows \"Total Physicians 7,183 219.8 297.1\", \"Medical Oncology 78 2.4 6.4\", \"Cardiovascular Disease 141 4.3 9.5\" and \"Neurology 128 3.9 6.8\" (Nevada count, Nevada and US physicians per 100,000). Also: \"An estimated 2,195,138 Nevadans or 64.9% of the state's population currently reside in a federally designated primary care HPSA\" and \"The number of medical school graduates (MD and DO degrees) in Nevada increased from 50 in 2004 to 287 in 2024\".",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Quote: \"Fred and Pamela Buffett Cancer Center, Nebraska Medicine and the University of Nebraska Medical Center (UNMC), Omaha, Nebraska\" is followed directly by \"Dartmouth Cancer Center, Dartmouth Health, Lebanon, New Hampshire\"; no Nevada entry. Read September 21, 2026.",
    },
    {
      id: "ncorp-nv",
      title: "NCORP Find a Site: Nevada",
      publisher: "National Cancer Institute, NCI Community Oncology Research Program",
      url: "https://ncorp.cancer.gov/findasite/?state=Nevada",
      year: "2026",
      note: "Read September 2026. Nevada Cancer Research Foundation NCORP (Las Vegas) is the only Nevada NCORP site. Affiliates listed include \"Alliance for Childhood Diseases/Cure 4 the Kids Foundation\", \"Carson Tahoe Regional Medical Center\", \"Comprehensive Cancer Centers of Nevada\", \"OptumCare Cancer Care at Charleston\", \"Summerlin Hospital Medical Center\", \"Sunrise Hospital and Medical Center\" and \"University Medical Center of Southern Nevada\".",
    },
    {
      id: "cccn",
      title: "Comprehensive Cancer Centers of Nevada",
      publisher: "Comprehensive Cancer Centers of Nevada",
      url: "https://cccnevada.com/",
      year: "2026",
      note: "Quote: \"The practice offers more than 170 Phase I, II & III trials annually.\"",
    },
    {
      id: "cccn-scri",
      title: "Comprehensive Cancer Centers Announces Collaboration with Sarah Cannon Research Institute",
      publisher: "Comprehensive Cancer Centers of Nevada",
      url: "https://cccnevada.com/comprehensive-cancer-centers-announces-collaboration-with-sarah-cannon-research-institute/",
      year: "2026",
    },
    {
      id: "cc-nevada",
      title: "Research & Innovations, Cleveland Clinic Nevada",
      publisher: "Cleveland Clinic",
      url: "https://my.clevelandclinic.org/locations/nevada/research-innovations",
      year: "2026",
      note: "Quote: \"Since our program began in 2009, in its first 15 years, our team conducted more than 125 studies of neurological conditions. ... Our research in Nevada has led to the FDA approval of eight new drug treatments that are now available for clinical use nationwide.\"",
    },
    {
      id: "unr-history",
      title: "UNR Med History",
      publisher: "University of Nevada, Reno School of Medicine",
      url: "https://med.unr.edu/about/mission-vision-values/strategic-plan/history",
      year: "2026",
    },
    {
      id: "unr-hnp",
      title: "Genetic testing informs health and learning",
      publisher: "University of Nevada, Reno (Nevada Today)",
      url: "https://www.unr.edu/nevada-today/news/2026/unr-med-genetic-testing",
      year: "2026",
      note: "Quote: \"So far, the project has enrolled more than 65,000 participants\" and \"In 2016, Renown Health and the Desert Research Institute (DRI) launched the project\".",
    },
    {
      id: "umc-mychart",
      title: "UMC MyChart Privacy Policy",
      publisher: "University Medical Center of Southern Nevada",
      url: "https://www.umcsn.com/privacy-policy/umc-mychart-privacy-policy",
      year: "2024",
      note: "Quote: \"UMConnect is developed by Epic Systems Corporation; please refer to Epic's Mobile Application Privacy Policy for Patients for more detailed information\".",
    },
    {
      id: "unlv-intermountain",
      title: "Intermountain Health Unveils Site of Future Stand-Alone Children's Hospital at UNLV Tech Park",
      publisher: "UNLV News Center",
      url: "https://www.unlv.edu/news/article/intermountain-health-unveils-site-future-stand-alone-childrens-hospital-unlv-tech-park",
      year: "2024",
      note: "Quote: \"Intermountain Health offers patient care at more than 65 clinics across Southern Nevada. With its extended provider network, Intermountain Health delivers patient-centered primary, specialty, and urgent care services to approximately 350,000 Southern Nevadans\".",
    },
    {
      id: "intermountain-epic",
      title: "Intermountain Announces Epic EHR Implementation for Interoperability",
      publisher: "TechTarget / EHRIntelligence",
      url: "https://www.techtarget.com/searchhealthit/news/366578073/Intermountain-Announces-Epic-EHR-Implementation-for-Interoperability",
      year: "2023",
      note: "Quote: \"Additionally, Intermountain facilities in Idaho and Nevada are in need of replacement of legacy EHR systems, the statement indicated.\"",
    },
    {
      id: "intermountain-golive",
      title: "Intermountain Health goes live with Epic EHR across 33 hospitals",
      publisher: "Digital Health News",
      url: "https://www.digitalhealthnews.com/intermountain-health-goes-live-with-epic-ehr-across-33-hospitals",
      year: "2025",
      note: "Quote: \"Salt Lake City-based Intermountain Health has launched Epic across its 33 hospitals and six-state footprint.\" and \"Intermountain opted for a 'big-bang' launch favored by Epic and many health systems nowadays, turning the EHR on at all locations simultaneously.\" Dated September 21, 2025; read September 2026.",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Quote: endpoint entries \"name\": \"UMC Southern Nevada\"; \"name\": \"Renown, Barton, CVMC\"; \"name\": \"Intermountain Healthcare\", each with connection type \"hl7-fhir-rest\" and status \"active\". Downloaded September 21, 2026.",
    },
    {
      id: "oracle-endpoints",
      title: "Oracle Health Millennium patient R4 FHIR endpoints (millennium_patient_r4_endpoints.json)",
      publisher: "Oracle (oracle-samples/ignite-endpoints on GitHub)",
      url: "https://raw.githubusercontent.com/oracle-samples/ignite-endpoints/main/oracle_health_fhir_endpoints/millennium_patient_r4_endpoints.json",
      year: "2026",
      note: "Quote: Organization entries \"Humboldt General Hospital\" (city \"Winnemucca\", state \"NV\") and \"Boulder City Hospital Inc\" (city \"Boulder City\", state \"NV\"). Downloaded September 21, 2026. A listing shows a Millennium FHIR endpoint, not every system the organization runs.",
    },
    {
      id: "nv-ab406",
      title: "Assembly Bill No. 406 (83rd Session, 2025), enrolled",
      publisher: "Nevada Legislature",
      url: "https://www.leg.state.nv.us/Session/83rd2025/Bills/AB/AB406_EN.pdf",
      year: "2025",
      note: "Quote: Sec. 7(1) bars an AI provider from any representation \"that explicitly or implicitly indicates that: (a) The artificial intelligence system is capable of providing professional mental or behavioral health care\" or that it \"is a provider of mental or behavioral health care, a therapist, a clinical therapist, a counselor, a psychiatrist, a doctor\"; Sec. 7(2) bars offering \"an artificial intelligence system that is specifically programmed to provide a service or experience to a user that would constitute the practice of professional mental or behavioral health care if provided by a natural person\"; Sec. 7(5): \"A person who violates any provision of subsection 1, 2 or 3 is subject to a civil penalty not to exceed $15,000 per violation.\" Sec. 10: effective \"On July 1, 2025, for all other purposes.\"",
    },
    {
      id: "nv-sb370",
      title: "Senate Bill No. 370 (82nd Session, 2023), enrolled",
      publisher: "Nevada Legislature",
      url: "https://www.leg.state.nv.us/Session/82nd2023/Bills/SB/SB370_EN.pdf",
      year: "2023",
      note: "Quote: \"A person shall not implement a geofence within 1,750 feet of any medical facility, facility for the dependent or any other person or entity that provides in-person health care services or products\". Sec. 36: \"This act becomes effective on March 31, 2024.\"",
    },
    {
      id: "nrs-597",
      title: "NRS Chapter 597, NRS 597.812 to 597.818",
      publisher: "Nevada Legislature",
      url: "https://www.leg.state.nv.us/NRS/NRS-597.html",
      year: "2021",
      note: "Quote: NRS 597.812 defines the device as equipment that \"utilizes a random or sequential number generator producing telephone numbers to be called\" and is used \"to disseminate a prerecorded message to the telephone number called to solicit a person at the telephone number called to purchase goods or services\". NRS 597.814(1) requires \"a recorded or unrecorded natural voice\" to give \"the nature of the call\" and \"the name, address and telephone number of the business or organization\"; 597.814(2) bars calls \"between 8 p.m. and 9 a.m.\"; 597.814(3) exempts calls to \"a person with whom the person using the device ... has a preexisting business relationship\". Read September 2026.",
    },
    {
      id: "nrs-200",
      title: "NRS Chapter 200, NRS 200.620 and 200.690",
      publisher: "Nevada Legislature",
      url: "https://www.leg.state.nv.us/NRS/NRS-200.html",
      year: "2026",
      note: "Quote: \"it is unlawful for any person to intercept or attempt to intercept any wire communication unless: (a) The interception or attempted interception is made with the prior consent of one of the parties to the communication; and (b) An emergency situation exists and it is impractical to obtain a court order\". NRS 200.690(1): \"A person who willfully and knowingly violates NRS 200.620 to 200.650, inclusive: (a) Shall be punished for a category D felony\". Read September 2026.",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, September 2026.",
    },
  ],
  related: [
    { label: "Recruitment by state and region", href: "/clinical-trial-recruitment", description: "Registry counts and local rules for every location we cover." },
    { label: "For physician groups", href: "/for/physician-groups", description: "How practices run pre-screening without adding coordinator hours." },
    { label: "For research sites", href: "/for/research-sites", description: "What Bond does for independent and hospital-based sites." },
    { label: "Oncology recruitment", href: "/oncology", description: "Nevada's largest therapeutic area by recruiting studies." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
  ],
};

export default page;
