import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/new-york-city",
  category: "geography",
  title: "New York City clinical trial recruitment for sites",
  description:
    "NYC-area recruiting-trial counts, research hubs, health system EHRs, languages and the New York and New Jersey rules on AI outreach, texting and health data.",
  keywords: [
    "clinical trial recruitment New York City",
    "NYC research sites",
    "clinical trials Manhattan Brooklyn Bronx Queens",
    "New York patient recruitment",
    "SHIN-NY research recruitment",
  ],
  eyebrow: "By location",
  h1: "Recruiting for clinical trials in the New York City area",
  intro:
    "On October 5, 2026, a ClinicalTrials.gov radius search found 4,145 studies recruiting at one or more sites within 25 miles of Midtown Manhattan, about 19% of the 22,007 recruiting in the United States that day.{{cite:ctgov-api}} The radius reaches into northern New Jersey, so this page covers New Jersey rules alongside New York's.",
  summary: "NYC-area recruiting-trial counts, research hubs, health systems and their EHRs, languages, and New York and New Jersey outreach and privacy rules.",
  lastUpdated: "2026-10-05",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in the New York City area?",
      blocks: [
        {
          type: "p",
          text: "Oncology dominates: 1,791 of the 7,064 recruiting US oncology studies, about 25%, list a site within the radius. The area's share is also high in gastroenterology (82 of 283) and dermatology (61 of 212), and lowest in obesity and type 2 diabetes (86 of 855) and pain (82 of 625).{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "new-york-city", cite: "ctgov-api" },
        {
          type: "p",
          text: "A radius count shows where sponsors placed studies, not which ones enroll on schedule, and keyword matching on the condition field can pull in off-target studies. The oncology examples below are the most recently updated recruiting studies in the radius; three of the six are sponsored by Memorial Sloan Kettering.{{cite:ctgov-api}} See [oncology](/oncology) for how Bond screens for cancer trials.",
        },
        { type: "trials", geo: "new-york-city", condition: "oncology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are New York City's research hubs?",
      blocks: [
        {
          type: "table",
          caption: "Selected New York City research institutions and what each reports on its own site, as of October 2026",
          columns: ["Institution", "Cancer center", "What it reports"],
          rows: [
            [
              "Memorial Sloan Kettering",
              "NCI comprehensive cancer center{{cite:nci-centers}}",
              "More than 1,800 clinical trials, enrolling some 5,000 people a year in interventional studies{{cite:msk-trials}}",
            ],
            [
              "NYU Langone Health",
              "Perlmutter Cancer Center, comprehensive{{cite:nci-centers}}",
              "A nearly $70 million, seven-year NIH renewal for its CTSI in May 2026; its network includes NYC Health + Hospitals and the Family Health Centers{{cite:nyu-ctsi}}",
            ],
            [
              "Mount Sinai Health System",
              "Tisch Cancer Center, clinical{{cite:nci-centers}}",
              "$501.7 million from NIH to the Icahn School of Medicine in the most recent federal fiscal year, 11th nationally{{cite:mount-sinai-nih}}",
            ],
            [
              "Columbia and NewYork-Presbyterian",
              "Herbert Irving Comprehensive Cancer Center{{cite:nci-centers}}",
              "A seven-year, $75 million CTSA award to Columbia's Irving Institute in June 2026{{cite:columbia-ctsa}}",
            ],
            [
              "Montefiore Einstein (Bronx)",
              "Montefiore Einstein Cancer Center, comprehensive{{cite:nci-centers}}",
              "850+ active clinical trials{{cite:montefiore-research}}",
            ],
            [
              "Northwell Health (Feinstein Institutes)",
              "None listed by NCI",
              "50 research labs, 5,000 clinical research studies and 6,300 researchers and staff{{cite:feinstein}}",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "**Cancer.** NCI lists five designated cancer centers in New York City: four comprehensive centers (Memorial Sloan Kettering, Columbia's Herbert Irving, NYU Langone's Perlmutter and Montefiore Einstein) and Mount Sinai's Tisch Cancer Center, a clinical center. Weill Cornell has no separate listing, and New Jersey's only designated center is Rutgers Cancer Institute in New Brunswick.{{cite:nci-centers}}",
            "**Translational science.** NIH RePORTER lists six Clinical and Translational Science Award hubs in Manhattan and the Bronx with awards in fiscal 2025 or 2026: Columbia, Weill Cornell, Mount Sinai, NYU, Rockefeller University and Einstein-Montefiore. Rutgers runs New Jersey's hub, NJ ACTS, from Newark.{{cite:nih-reporter-ctsa}}",
            "**Federal funding.** New York ranked first among US cities in NIH funding for federal fiscal 2025, at $2,490,418,623.{{cite:brimr-2025}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do New York City's health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected NYC-area health systems, from their own pages, filings and vendor endpoint directories, as of October 2026",
          columns: ["System", "Footprint", "EHR"],
          rows: [
            ["NYC Health + Hospitals", "The city's public system, with 11 hospitals{{cite:nyc-maimonides}}", "Epic{{cite:epic-endpoints}}"],
            [
              "Northwell Health",
              "28 hospitals after its 2025 affiliation with Nuvance Health{{cite:northwell-q2}}",
              "Moving from Allscripts to Epic: phase one went live in November 2025 and phase two in May 2026, together 17 hospitals and over 900 locations, with more waves planned{{cite:northwell-q2,hitc-northwell}}",
            ],
            [
              "NewYork-Presbyterian, Columbia and Weill Cornell",
              "NewYork-Presbyterian has eight campuses and over 4,000 beds{{cite:nyp-about}}",
              "One shared Epic record since early 2020{{cite:cuimc-epic,epic-endpoints}}",
            ],
            ["NYU Langone Health", "7 inpatient and over 400 outpatient locations{{cite:nyu-facts}}", "Epic{{cite:epic-endpoints}}"],
            ["Mount Sinai Health System", "Seven hospitals{{cite:mount-sinai-nih}}", "Epic{{cite:epic-endpoints}}"],
            ["Montefiore and Memorial Sloan Kettering", "Bronx; Manhattan", "Epic{{cite:epic-endpoints}}"],
            ["One Brooklyn Health", "Brookdale, Interfaith and Kingsbrook Jewish{{cite:obh-about}}", "Epic{{cite:epic-endpoints}}"],
            [
              "Maimonides Health",
              "Three hospitals and more than 80 community-based sites in Brooklyn{{cite:nyc-maimonides}}",
              "Set to adopt Epic through a merger with NYC Health + Hospitals, announced in December 2025 pending final legal and regulatory approval{{cite:nyc-maimonides}}",
            ],
            ["Hackensack Meridian Health (NJ)", "18 hospitals and 500+ patient care locations{{cite:hmh-about}}", "Epic{{cite:epic-endpoints}}"],
            ["RWJBarnabas Health (NJ)", "12 acute-care hospitals{{cite:rwjbh-facts}}", "Epic{{cite:epic-endpoints}}"],
            ["St. Joseph's Regional Medical Center (Paterson, NJ)", "Hospital", "Oracle Health (Cerner) endpoint listed{{cite:oracle-endpoints}}"],
            [
              "Community health centers",
              "64 New York awardees serving 2,314,742 patients and 23 New Jersey awardees serving 643,753 in 2025{{cite:hrsa-ny,hrsa-nj}}",
              "Varies by center",
            ],
          ],
        },
        {
          type: "p",
          text: "Epic dominates, but Northwell is mid-migration, so confirm whether a given hospital has gone live before planning chart review there. Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR, HL7 or an aggregator.{{cite:bond-site,bond-product}} It also works with the CTMS systems sites use, including CRIO, Advarra OnCore, Advarra Clinical Conductor, RealTime and Veeva SiteVault (Bond is a CRIO Certified Partner).{{cite:bond-site}} See [Epic](/integrations/epic), [Oracle Health (Cerner)](/integrations/oracle-cerner) and [eClinicalWorks](/integrations/eclinicalworks).",
        },
        {
          type: "p",
          text: "New York's statewide exchange, the SHIN-NY, connects regional Qualified Entities and, according to NYeC, which manages the platform with the Department of Health, 100% of the state's hospitals.{{cite:nyec-shinny}} A Qualified Entity may not disclose a patient's information to a participant without the patient's affirmative consent. For recruitment, state policy lets it review records on a researcher's behalf to find who may qualify and pass names only to a provider with a treating relationship, after IRB and QE research committee approval and with the data suppliers' agreement.{{cite:shinny-policy}} Screening the site's own EHR avoids that process.",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in New York City, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "8,584,629", label: "New York City residents on July 1, 2025", cite: "census-cities-2025" },
            { value: "20,112,448", label: "New York-Newark-Jersey City metro residents on July 1, 2025", cite: "census-cbsa-2025" },
            { value: "48.3%", label: "NYC residents 5 and older who speak a language other than English at home, 2024", cite: "census-acs-nyc" },
            { value: "23.3%", label: "NYC residents 5 and older who speak English less than very well, 2024", cite: "census-acs-nyc" },
          ],
        },
        {
          type: "p",
          text: "On July 1, 2025, the five boroughs were 29.6% Hispanic, 20.1% non-Hispanic Black and 17.0% non-Hispanic Asian, and 17.3% of residents were 65 or older, against 19.3% statewide.{{cite:census-county-ny}} In 2024, 36.7% of New Yorkers were born abroad and 5.9% were uninsured.{{cite:census-acs-nyc,census-acs-nyc-s2701}}",
        },
        {
          type: "p",
          text: "Spanish is spoken at home by 1,808,138 New Yorkers aged 5 and older, 860,328 of whom speak English less than very well. Chinese follows with 525,042 speakers (350,619 less than very well), then Russian, Polish or other Slavic languages (275,636) and French, Haitian or Cajun (193,571).{{cite:census-acs-nyc-c16001}} The city designates 10 citywide languages for its own services: Arabic, Bangla, Chinese, French, Haitian Creole, Korean, Polish, Russian, Spanish and Urdu.{{cite:nyc-moia}} At New York health centers in 2025, 38.84% of patients were Hispanic or Latino, 28.87% had limited English proficiency and 52.33% had Medicaid or CHIP; in New Jersey, 51.05% were Hispanic or Latino.{{cite:hrsa-ny,hrsa-nj}}",
        },
        {
          type: "p",
          text: "A New York cohort that reflects the city usually needs outreach in Spanish and Chinese at minimum, and often Russian, Haitian Creole or Bangla. Bond's voice and text agents work in the patient's language and can switch languages mid-call.{{cite:bond-product}} See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks and research sites work in the New York City area?",
      blocks: [
        {
          type: "p",
          text: "Several multi-site research organizations list NYC-area locations on their own websites, as of October 2026:",
        },
        {
          type: "ul",
          items: [
            "**Care Access** lists sites in Brooklyn (multi-specialty) and Yonkers (gastroenterology), and in New Jersey in Clifton (oncology), Hoboken, Ridgewood (psychiatry) and Union.{{cite:care-access}}",
            "**IMA Clinical Research** lists NYC Midtown and NYC Uptown sites, the latter formerly Medical Research Network, plus Warren, New Jersey, with a corporate office in Tarrytown.{{cite:ima}}",
            "**Adams Clinical** lists the Bronx and Harlem among six locations in New York, Massachusetts, Pennsylvania and Texas.{{cite:adams-clinical}}",
            "**DM Clinical Research** lists a Brooklyn site at 466 Bayridge Avenue and a Jersey City site among 17 locations across 13 states.{{cite:dm-brooklyn,dm-locations}}",
            "**Drug Trials America**, an independent site, lists Brooklyn and Hartsdale.{{cite:drug-trials-america}}",
          ],
        },
        {
          type: "p",
          text: "Bond is a CRIO Certified Partner, its only vendor certification.{{cite:bond-site}} See how Bond fits [research sites](/for/research-sites), [site networks](/for/site-networks) and [CRIO](/integrations/crio).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which New York and New Jersey laws apply to AI outreach, texting and health data?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how each applies to pre-screening is unsettled. This is a map for your counsel, current as of October 5, 2026, not legal advice. For federal rules, see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026) and [IRB and HIPAA rules for patient outreach](/guides/irb-hipaa-patient-outreach).",
        },
        {
          type: "ul",
          items: [
            "**Health data (S.9269/A.10357, the New York Health Information Privacy Act).** A revised bill passed the Senate on June 3, 2026 and the Assembly on June 4, after the governor vetoed the first version on December 19, 2025. As of October 5, 2026, the legislature's bill pages showed no delivery to the governor, so it was not law.{{cite:ny-s9269,ny-a10357,nycbar-nyhipa}} If signed, it would require written authorization or a designated necessary purpose before processing health information, take effect six months later, and be enforced by the Attorney General with penalties of up to $15,000 per violation. It exempts HIPAA protected health information and clinical-trial information covered by the Common Rule.{{cite:ny-s9269,mofo-nyhipa}} Answers to an online pre-screener collected before a patient reaches a HIPAA-covered site are the data most likely to fall inside it.",
            "**AI companions (General Business Law Article 47).** Since November 5, 2025, operators of AI companions must tell users at the start of an interaction, and at least every three hours, that they are not communicating with a human.{{cite:ny-gov-ai-companion,ny-gbl-1702}} The law covers systems designed to simulate a sustained human relationship and excludes systems used solely for customer service or built for research or technical assistance, so a study pre-screening agent is unlikely to be one.{{cite:ny-gbl-1700}}",
            "**Telemarketing (General Business Law § 399-z).** The state telemarketing law covers calls and texts made to induce payment for goods or services, limits telemarketing to 8:00 a.m. to 9:00 p.m. without consent, and bars sales calls to numbers on the national do-not-call registry.{{cite:ny-gbl-399z}} A study invitation that asks for no payment likely falls outside it, but the calling window is a sensible default.",
            "**Call recording (Penal Law § 250.00).** New York requires the consent of at least one party to record a conversation.{{cite:ny-pen-250}} Massachusetts and Pennsylvania require every party's consent, so a multi-state study is simpler with one recording notice for everyone.",
            "**Breach notice (General Business Law § 899-aa).** Medical and health insurance information count as private information, and residents must be notified within 30 days of discovering a breach. A HIPAA covered entity that reports a breach to HHS must also notify the state Attorney General within five business days.{{cite:ny-gbl-899aa}}",
            "**Research outside federal rules (Public Health Law Article 24-A).** New York's human research law does not apply to research that is subject to and complies with federal human-subjects regulations; for other human research it requires the subject's written, voluntary informed consent.{{cite:ny-pbh-2445,ny-pbh-2442}}",
            "**New Jersey.** The New Jersey Data Privacy Act, approved January 16, 2024 and in effect 365 days later, requires consent to process sensitive data, including a mental or physical health condition, treatment or diagnosis. It excludes protected health information held by HIPAA covered entities and business associates, and personal data used in research under 45 CFR Part 46 or 21 CFR Parts 50 and 56.{{cite:nj-privacy}}",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI assistance is being used, and patients can reach a person at any time: the agent transfers the call live to a coordinator or books a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Scripts are configured per site and study, so a New York or New Jersey site can use its own IRB-reviewed wording. See [IRB submission language for AI outreach](/templates/irb-submission-language-ai-outreach).",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a New York City site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration usually takes 48 hours, depending on the EHR, IT review and interface method, and there is no integration fee.{{cite:bond-site,bond-product}} See [implementation](/implementation) for the step-by-step plan and [pricing](/pricing) for how fees work.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Sign the paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path.{{cite:bond-site}} Decide up front whether any pre-screener data will be collected outside HIPAA, in case the health privacy bill becomes law.",
            },
            {
              title: "Connect the EHR",
              text: "Connect Epic, Oracle Health or another EHR through FHIR, HL7 or an aggregator.{{cite:bond-product}} Screen the site's own records rather than exchange data.",
            },
            {
              title: "Check criteria before outreach",
              text: "Bond reads clinical notes, prescriptions, lab results, imaging data and pathology, radiology and molecular reports, and shows criterion-by-criterion evidence for every match, so coordinators can review a sample before any patient is contacted.{{cite:bond-site,bond-product}} See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Run ads, reach out and book",
              text: "Bond creates and runs Meta and Google ad campaigns for the study, paid from the site's own ad budget. Its voice and text agents contact every new lead immediately, keep following up with those who have not responded, pre-screen in the patient's language and book visits straight into the site's calendar, with reminders by text, voice or email.{{cite:bond-product}}",
            },
            {
              title: "Support consent and retention",
              text: "After the booked visit, the agents can explain the study in plain language and answer questions, escalating to staff; the site and PI obtain consent. After enrollment they send visit reminders, book transportation and flag dropout risk.{{cite:bond-product}} See [consent](/consent).",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting in the New York City area?",
      a: "On October 5, 2026, a ClinicalTrials.gov search for recruiting studies with a site within 25 miles of Midtown Manhattan returned 4,145, including 1,791 that matched oncology keywords.{{cite:ctgov-api}}",
    },
    {
      q: "Does New York require patients to be told when AI is used?",
      a: "As of October 5, 2026, no New York statute we reviewed requires it for patient outreach. The AI companion law requires disclosure for systems built to simulate a sustained relationship, which a pre-screening agent is unlikely to be.{{cite:ny-gbl-1700}} Bond's agents disclose AI use regardless.{{cite:bond-site}}",
    },
    {
      q: "Can SHIN-NY data be used to find trial patients?",
      a: "Only through the Qualified Entity's research process: the QE can review records on a researcher's behalf and share names with a treating provider after IRB and QE research committee approval.{{cite:shinny-policy}} Most sites screen their own EHR instead.",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Radius search queried October 5, 2026: filter.geo=distance(40.7549,-73.9840,25mi) (25 miles of Midtown Manhattan), filter.overallStatus=RECRUITING, countTotal=true; 4,145 studies. US totals from the same day use query.locn=United States; 22,007 studies. Area counts use keyword searches on the condition field. Shares are Bond's arithmetic.",
    },
    {
      id: "census-cities-2025",
      title: "City and Town Population Totals: April 1, 2020 to July 1, 2025 (SUB-EST2025)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/cities/totals/sub-est2025.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row SUMLEV 162, New York, \"New York city\": POPESTIMATE2025 8584629.",
    },
    {
      id: "census-cbsa-2025",
      title: "Metropolitan and Micropolitan Statistical Area Population Totals: April 1, 2020 to July 1, 2025 (CBSA-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/metro/totals/cbsa-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row CBSA 35620, \"New York-Newark-Jersey City, NY-NJ\", Metropolitan Statistical Area: POPESTIMATE2025 20112448.",
    },
    {
      id: "census-county-ny",
      title: "Annual County Resident Population Estimates by Age, Sex, Race, and Hispanic Origin: April 1, 2020 to July 1, 2025 (CC-EST2025-ALLDATA-36)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/asrh/cc-est2025-alldata-36.csv",
      year: "2026",
      note: "Downloaded October 5, 2026 and summed by Bond for YEAR 7 (\"7/1/2025 population estimate\" in the file layout) over Bronx, Kings, New York, Queens and Richmond counties. Total 8,584,629: Hispanic 2,542,719 (29.6%); non-Hispanic Black alone 1,723,855 (20.1%); non-Hispanic Asian alone 1,455,671 (17.0%); ages 65 and over 1,481,469 (17.3%). New York State: 3,860,551 of 20,002,427 aged 65 and over (19.3%).",
    },
    {
      id: "census-acs-nyc",
      title: "Selected Social Characteristics, New York city, New York: 2024 ACS 1-Year Estimates (DP02)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSDP1Y2024.DP02&g=160XX00US3651000",
      year: "2025",
      note: "Read October 5, 2026. DP02_0094PE \"PLACE OF BIRTH!!Total population!!Foreign-born\" 36.7; DP02_0114PE \"LANGUAGE SPOKEN AT HOME!!Population 5 years and over!!Language other than English\" 48.3; DP02_0115PE \"Speak English less than 'very well'\" 23.3.",
    },
    {
      id: "census-acs-nyc-s2701",
      title: "Selected Characteristics of Health Insurance Coverage, New York city, New York: 2024 ACS 1-Year Estimates (S2701)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSST1Y2024.S2701&g=160XX00US3651000",
      year: "2025",
      note: "Read October 5, 2026. S2701_C05_001E \"Percent Uninsured!!Civilian noninstitutionalized population\" 5.9 (margin 0.2).",
    },
    {
      id: "census-acs-nyc-c16001",
      title: "Language Spoken at Home for the Population 5 Years and Over, New York city, New York: 2024 ACS 1-Year Estimates (C16001)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSDT1Y2024.C16001&g=160XX00US3651000",
      year: "2025",
      note: "Read October 5, 2026. Total 8,022,927. \"Spanish:\" 1,808,138, of whom 860,328 speak English less than \"very well\"; \"Chinese (incl. Mandarin, Cantonese):\" 525,042, of whom 350,619 speak English less than very well; \"Russian, Polish, or other Slavic languages:\" 275,636; \"French, Haitian, or Cajun:\" 193,571.",
    },
    {
      id: "nyc-moia",
      title: "Language Access Hub",
      publisher: "NYC Mayor's Office of Immigrant Affairs",
      url: "https://www.nyc.gov/site/immigrants/language-needs/language-access-hub.page",
      year: "2026",
      note: "Read October 5, 2026. Lists the 10 designated citywide languages: \"Arabic, Bangla, Chinese, French, Haitian Creole, Korean, Polish, Russian, Spanish, and Urdu\".",
    },
    {
      id: "hrsa-ny",
      title: "New York Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/NY",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Total Number of Reporting Program Awardees: 64\", \"Reporting Period: 2025\", \"Total Patients Served: 2,314,742\". 2025: Hispanic, Latino/a, or Spanish Origin 38.84%; Limited English Proficiency 28.87% (668,315 patients); Medicaid/CHIP 52.33%.",
    },
    {
      id: "hrsa-nj",
      title: "New Jersey Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/NJ",
      year: "2026",
      note: "Read October 5, 2026. Awardees 23; reporting period 2025; total patients served 643,753; Hispanic, Latino/a, or Spanish Origin 51.05%; Limited English Proficiency 33.79%.",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Read October 5, 2026 (page updated June 10, 2026). New York City entries: Memorial Sloan-Kettering Cancer Center, Herbert Irving Comprehensive Cancer Center (Columbia University), Laura and Isaac Perlmutter Cancer Center at NYU Langone Health and Montefiore Einstein Cancer Center (Bronx), each a Comprehensive Cancer Center; Mount Sinai Tisch Cancer Center, Clinical Cancer Center. New Jersey: Rutgers Cancer Institute of New Jersey, New Brunswick, Comprehensive Cancer Center.",
    },
    {
      id: "nih-reporter-ctsa",
      title: "NIH RePORTER: NCATS Clinical and Translational Science Award hub awards (UL1/UM1), New York and New Jersey, fiscal years 2025-2026",
      publisher: "National Institutes of Health",
      url: "https://reporter.nih.gov/project-details/11193067",
      year: "2026",
      note: "Queried October 5, 2026 through the RePORTER API (agency NCATS, activity codes UL1 and UM1). New York City awards: 1UM1TR006153-01 Columbia University Health Sciences; 5UL1TR002384-10 Weill Medical College of Cornell University; 5UL1TR004419-05 Icahn School of Medicine at Mount Sinai; 1UM1TR005769-01 \"New York University Clinical and Translational Science Hub\" (the linked record); 5UL1TR001866-10 Rockefeller University (fiscal 2025); 5UM1TR004400-04 \"Einstein-Montefiore Clinical and Translational Science Award Hub\" (Bronx). New Jersey: 5UM1TR004789-03 \"NJ ACTS: A Platform for Translational Science in New Jersey\", Rutgers Biomedical and Health Sciences, Newark.",
    },
    {
      id: "brimr-2025",
      title: "BRIMR Rankings of NIH Funding in 2025",
      publisher: "Blue Ridge Institute for Medical Research",
      url: "https://brimr.org/brimr-rankings-of-nih-funding-in-2025/",
      year: "2026",
      note: "Read October 5, 2026. The rankings use \"NIH year-end composite data for the federal fiscal year ending 30 September 2025\". Cities spreadsheet (City_2025.xlsx): \"1 | NEW YORK | 2490418623\".",
    },
    {
      id: "msk-trials",
      title: "MSK Clinical Trials: Bringing the Promise of New Medicine to More Patients",
      publisher: "Memorial Sloan Kettering Cancer Center",
      url: "https://www.mskcc.org/news/msk-clinical-trials-bringing-promise-of-new-medicine-to-more-patients",
      year: "2026",
      note: "Dated May 11, 2026. Quote: \"more than 1,800 clinical trials, enrolling some 5,000 people annually in interventional studies\".",
    },
    {
      id: "nyu-ctsi",
      title: "NYU Langone Health Secures Nearly $70 Million NIH Grant to Accelerate Scientific Discovery",
      publisher: "NYU Langone Health",
      url: "https://nyulangone.org/news/nyu-langone-health-secures-nearly-70-million-nih-grant-accelerate-scientific-discovery",
      year: "2026",
      note: "Dated May 4, 2026. Quotes: \"awarded a nearly $70 million, seven-year renewal grant from the National Institutes of Health (NIH)\" for its Clinical and Translational Science Institute; \"NYU Langone's large network, including the Family Health Centers, NYC Health + Hospitals, and all 11 schools and colleges of New York University\".",
    },
    {
      id: "nyu-facts",
      title: "NYU Langone Health Facts at a Glance",
      publisher: "NYU Langone Health",
      url: "https://nyulangone.org/news/nyu-langone-health-facts-glance",
      year: "2026",
      note: "Dated September 16, 2026. Inpatient locations \"7\"; outpatient locations \"over 400 across the New York region and in Florida\".",
    },
    {
      id: "mount-sinai-nih",
      title: "Icahn School of Medicine at Mount Sinai Remains Among Top Institutions for NIH Funding",
      publisher: "Mount Sinai Health System",
      url: "https://www.mountsinai.org/about/newsroom/2026/icahn-school-of-medicine-at-mount-sinai-remains-among-top-institutions-for-nih-funding",
      year: "2026",
      note: "Dated March 5, 2026. Quote: \"the School received $501.7 million from the NIH in the most recent federal fiscal year\"; ranked 11th nationally; the health system has \"seven hospitals\".",
    },
    {
      id: "columbia-ctsa",
      title: "Columbia University's Irving Institute for Clinical and Translational Research Awarded $75 Million to Advance Healthcare Discoveries",
      publisher: "Columbia University Irving Medical Center",
      url: "https://www.cuimc.columbia.edu/news/columbia-universitys-irving-institute-clinical-and-translational-research-awarded-75-million-advance-healthcare-discoveries",
      year: "2026",
      note: "Dated June 10, 2026. Quote: \"The Irving Institute for Clinical and Translational Research has been awarded a seven-year, $75 million Clinical and Translational Science Award (CTSA)\".",
    },
    {
      id: "montefiore-research",
      title: "Research & Clinical Trials",
      publisher: "Montefiore Einstein",
      url: "https://montefioreeinstein.org/research",
      year: "2026",
      note: "Read October 5, 2026. Statistic: \"850+\" active clinical trials.",
    },
    {
      id: "feinstein",
      title: "Feinstein Institutes for Medical Research",
      publisher: "Northwell Health",
      url: "https://feinstein.northwell.edu/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Encompassing 50 research labs, 5,000 clinical research studies and 6,300 researchers and staff\".",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Downloaded October 5, 2026 (bundle total 479). Entries include \"NYC Health + Hospitals\", \"New York-Presbyterian\", \"Weill Cornell Medicine\", \"Columbia Physicians\", \"NYU Langone Medical Center\", \"Mount Sinai Health System\", \"Montefiore Medical Center\", \"Memorial Sloan Kettering Cancer Center\", \"One Brooklyn Health System\", \"Hackensack Meridian Health\" and \"RWJBarnabas Health\". Northwell and Maimonides were not listed. A listing means the organization publishes patient-access FHIR endpoints on Epic.",
    },
    {
      id: "oracle-endpoints",
      title: "Oracle Health Millennium patient R4 FHIR endpoints (millennium_patient_r4_endpoints.json)",
      publisher: "Oracle (oracle-samples/ignite-endpoints on GitHub)",
      url: "https://raw.githubusercontent.com/oracle-samples/ignite-endpoints/main/oracle_health_fhir_endpoints/millennium_patient_r4_endpoints.json",
      year: "2026",
      note: "Downloaded October 5, 2026. Organization entry \"St. Joseph's Regional Medical Center\" (city \"PATERSON\", state \"NJ\"). A listing shows a Millennium FHIR endpoint, not every system the organization runs.",
    },
    {
      id: "northwell-q2",
      title: "Northwell Health, Inc. Quarterly Financial Information and Operating Data for the Six Months Ended June 30, 2026 and 2025",
      publisher: "Northwell Health, via MSRB EMMA",
      url: "https://emma.msrb.org/P11974398-P11506210-.pdf",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"created a combined organization with 28 hospitals\"; \"The Epic phase 1 implementation completed in November 2025, and phase 2 completed in May 2026, included a total of 17 hospitals and over 900 locations\"; lessons \"will continue to be applied to subsequent planned waves of the Epic implementation.\"",
    },
    {
      id: "hitc-northwell",
      title: "Northwell to Deploy Epic Enterprise EHR Platform",
      publisher: "HIT Consultant",
      url: "https://hitconsultant.net/2023/03/20/northwell-to-deploy-epic-enterprise-ehr-platform/",
      year: "2023",
      note: "Dated March 20, 2023. Quote: \"The announcement marks the replacement of Allscripts\".",
    },
    {
      id: "nyc-maimonides",
      title: "Mayor Adams, NYC Health + Hospitals President and CEO Dr. Katz Announce Partnership with Maimonides Health",
      publisher: "Office of the Mayor of New York City",
      url: "https://www.nyc.gov/ar/mayors-office/news/2025/12/mayor-adams--nyc-health---hospitals-president-and-ceo-dr--katz-a",
      year: "2025",
      note: "Dated December 29, 2025. Quotes: New Yorkers trust the care they receive \"at its 11 hospitals\"; \"Maimonides Health is a Brooklyn health care system with three hospitals and more than 80 community-based sites\"; \"The merger also allows Maimonides to adopt Epic\"; \"pending final legal and regulatory approval\".",
    },
    {
      id: "cuimc-epic",
      title: "Time for Epic Go-Live",
      publisher: "Columbia University Irving Medical Center",
      url: "https://www.cuimc.columbia.edu/node/21391",
      year: "2020",
      note: "Dated January 29, 2020. Quotes: \"just two days away from go-live\"; \"For the first time in our history, CUIMC's electronic medical record will integrate with NewYork-Presbyterian Hospital and Weill Cornell Medicine.\"",
    },
    {
      id: "nyp-about",
      title: "About Us",
      publisher: "NewYork-Presbyterian",
      url: "https://www.nyp.org/about",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"NewYork-Presbyterian is comprised of eight campuses\"; \"With over 4,000 beds and more than 10,000 affiliated physicians and 50,000 employees\".",
    },
    {
      id: "obh-about",
      title: "About OBH",
      publisher: "One Brooklyn Health",
      url: "https://onebrooklynhealth.org/about-obh",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"OBH is the NYS Department of Health-approved co-operator of Brookdale University Hospital Medical Center, Interfaith Medical Center, and Kingsbrook Jewish Medical Center.\"",
    },
    {
      id: "hmh-about",
      title: "About Us",
      publisher: "Hackensack Meridian Health",
      url: "https://www.hackensackmeridianhealth.org/en/about-us",
      year: "2026",
      note: "Read October 5, 2026. Figures: \"18\" hospitals, \"500+\" patient care locations, \"41K\" team members.",
    },
    {
      id: "rwjbh-facts",
      title: "Facts & Figures",
      publisher: "RWJBarnabas Health",
      url: "https://www.rwjbh.org/why-rwjbarnabas-health-/facts-figures/",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"12 acute-care hospitals\"; \"Top 1% of all Epic customers in the world\".",
    },
    {
      id: "nyec-shinny",
      title: "Statewide Health Information Network for New York (SHIN-NY)",
      publisher: "New York eHealth Collaborative (NYeC)",
      url: "https://nyehealth.org/shin-ny/what-is-the-shin-ny/",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"In partnership with the New York State Department of Health, NYeC developed and manages the technology platform that connects New York's Qualified Entities\"; \"Today, the SHIN-NY connects 100% of the hospitals in New York State\"; QEs give access \"with patient consent\".",
    },
    {
      id: "shinny-policy",
      title: "Privacy and Security Policies and Procedures for Qualified Entities and their Participants in New York State under 10 N.Y.C.R.R. § 300.3(b)(1), Version 4.2",
      publisher: "New York State Department of Health",
      url: "https://www.health.ny.gov/technology/regulations/shin-ny/docs/privacy_and_security_policies.pdf",
      year: "2025",
      note: "Revised January 2025; read October 5, 2026. Section 1.1: \"a QE shall not Disclose a patient's Protected Health Information via the SHIN-NY to a Participant unless the patient has provided an Affirmative Consent\". Section 1.7.3(a): \"Affirmative Consent shall not be required for a QE to review Protected Health Information on behalf of a researcher to determine which individuals may qualify for a Research study\"; names may go \"to a Participant that has a treating relationship with such individual\" if an Institutional Review Board and a QE Research Committee approve and the Data Suppliers agree.",
    },
    {
      id: "care-access",
      title: "Locations",
      publisher: "Care Access",
      url: "https://careaccess.com/about-us/locations",
      year: "2026",
      note: "Read October 5, 2026. New York: \"26 Court St Suite 505 Brooklyn, NY, 11242\" (Multi-Speciality); \"469 North Broadway Yonkers, NY, 10701\" (Gastroenterology). New Jersey: Clifton (Oncology), Hoboken, Ridgewood (Psychiatry), Union.",
    },
    {
      id: "ima",
      title: "Locations",
      publisher: "IMA Clinical Research",
      url: "https://imaresearch.com/locations/",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"33 West 46th St, 3rd Floor New York, NY 10036\" (NYC Midtown); \"134 E 93rd St, Suite 201A New York, NY 10128\" (NYC Uptown, \"formerly Medical Research Network\"); \"10 Independence Blvd, Suite 150 Warren, NJ 07059\"; corporate office \"660 White Plains Rd, Suite 630 Tarrytown, NY 10591\".",
    },
    {
      id: "adams-clinical",
      title: "Adams Clinical",
      publisher: "Adams Clinical",
      url: "https://www.adamsclinical.com/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"With six locations across New York, Massachusetts, Pennsylvania, and Texas\"; locations named Boston, Bronx, Dallas, Harlem, Philadelphia and Watertown.",
    },
    {
      id: "dm-brooklyn",
      title: "Clinical Trials in Brooklyn, NY",
      publisher: "DM Clinical Research",
      url: "https://www.dmclinicalresearch.com/locations/brooklyn-ny/",
      year: "2026",
      note: "Read October 5, 2026. Address: \"466 Bayridge Avenue, Brooklyn, NY 11220\".",
    },
    {
      id: "dm-locations",
      title: "Locations",
      publisher: "DM Clinical Research",
      url: "https://www.dmclinicalresearch.com/locations",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"17 locations across 13 states\"; lists Brooklyn, NY and Jersey City, NJ.",
    },
    {
      id: "drug-trials-america",
      title: "Drug Trials America | Clinical Trials in Brooklyn & Hartsdale, New York",
      publisher: "Drug Trials America",
      url: "https://www.drugtrialsamerica.com/",
      year: "2026",
      note: "Read October 5, 2026. Page title names Brooklyn and Hartsdale; address \"280 North Central Ave, Suite 202 Hartsdale, NY 10530\".",
    },
    {
      id: "ny-s9269",
      title: "Senate Bill S9269 (2025-2026): protection of health information",
      publisher: "New York State Senate",
      url: "https://www.nysenate.gov/legislation/bills/2025/S9269",
      year: "2026",
      note: "Read October 5, 2026. Actions: \"Jun 03, 2026\" passed senate; \"Jun 04, 2026\" passed assembly; no later action listed. Exemptions in the bill text include \"Information that meets the definition of protected health information for purposes of the Health Insurance Portability and Accountability Act of 1996\" and \"Information collected as part of a clinical trial subject to the Federal Policy for the Protection of Human Subjects, also known as the Common Rule\". Section 3: \"This act shall take effect 6 months after it shall have become a law.\"",
    },
    {
      id: "ny-a10357",
      title: "Assembly Bill A10357 (2025-2026): summary and actions",
      publisher: "New York State Assembly",
      url: "https://nyassembly.gov/leg/?default_fld=&leg_video=&bn=A10357&term=2025&Summary=Y&Actions=Y&Memo=Y",
      year: "2026",
      note: "Read October 5, 2026. Summary: \"requires either written consent or a designated necessary purpose for the processing of an individual's health information.\" Last actions: \"06/04/2026 substituted by s9269\"; \"06/04/2026 passed assembly\".",
    },
    {
      id: "nycbar-nyhipa",
      title: "City Bar Supports Revised NY Health Information Privacy Act (NYHIPA, 2026)",
      publisher: "New York City Bar Association",
      url: "https://www.nycbar.org/reports/support-revised-ny-health-information-privacy-act-2026/",
      year: "2026",
      note: "Dated July 9, 2026. Quote: the original bill (A.2141/S.929) \"was passed by both houses of the Legislature during the 2025–2026 legislative session but was vetoed by Governor Kathy Hochul on December 19, 2025.\"",
    },
    {
      id: "mofo-nyhipa",
      title: "NYHIPA Returns in 2026: Revised Health Information Privacy Bill Introduced in New York",
      publisher: "Morrison Foerster",
      url: "https://www.mofo.com/resources/insights/260316-nyhipa-returns-in-2026-revised-bill",
      year: "2026",
      note: "Dated March 17, 2026. Quote: \"Enforcement authority remains vested exclusively in the New York Attorney General, who may seek injunctive relief, restitution, disgorgement, and civil penalties of up to $15,000 per violation.\"",
    },
    {
      id: "ny-gbl-1700",
      title: "New York General Business Law Section 1700: Definitions (Article 47, Artificial Intelligence Companion Models)",
      publisher: "New York State Senate (Consolidated Laws)",
      url: "https://www.nysenate.gov/legislation/laws/GBS/1700",
      year: "2026",
      note: "Read October 5, 2026. An AI companion is a system \"designed to simulate a sustained human or human-like relationship with a user\". It does not include \"any system used by a business entity solely for customer service\" or \"any system that is primarily designed and marketed for providing efficiency improvements or, research or technical assistance\".",
    },
    {
      id: "ny-gbl-1702",
      title: "New York General Business Law Section 1702: Notifications",
      publisher: "New York State Senate (Consolidated Laws)",
      url: "https://www.nysenate.gov/legislation/laws/GBS/1702",
      year: "2026",
      note: "Read October 5, 2026. Operators must notify the user, verbally or in writing, that \"the user is not communicating with a human\" at the beginning of any AI companion interaction and at least every three hours during continuing interactions.",
    },
    {
      id: "ny-gov-ai-companion",
      title: "Governor Hochul Pens Letter to AI Companion Companies Notifying Them Safeguard Requirements Are Now in Effect",
      publisher: "Office of the Governor of New York",
      url: "https://www.governor.ny.gov/news/governor-hochul-pens-letter-ai-companion-companies-notifying-them-safeguard-requirements-are",
      year: "2025",
      note: "Dated November 10, 2025. Quote: \"Effective November 5, 2025, AI Companion operators must\" implement the safeguards.",
    },
    {
      id: "ny-gbl-399z",
      title: "New York General Business Law Section 399-Z: Telemarketing sales call registry",
      publisher: "New York State Senate (Consolidated Laws)",
      url: "https://www.nysenate.gov/legislation/laws/GBS/399-Z",
      year: "2026",
      note: "Read October 5, 2026. A telemarketing sales call is \"a telephone call or electronic messaging text made directly or indirectly by a telemarketer\" for the purpose of \"inducing payment or ... consideration for any goods or services\". Quote: \"No telemarketer or seller shall engage in telemarketing at any time other than between 8:00 A.M. and 9:00 P.M. at the location of the customer unless the customer has given their express consent\".",
    },
    {
      id: "ny-pen-250",
      title: "New York Penal Law Section 250.00: Eavesdropping, definitions",
      publisher: "New York State Senate (Consolidated Laws)",
      url: "https://www.nysenate.gov/legislation/laws/PEN/250.00",
      year: "2026",
      note: "Read October 5, 2026. \"Mechanical overhearing of a conversation\" means the \"intentional overhearing or recording of a conversation or discussion, without the consent of at least one party thereto, by a person not present thereat\".",
    },
    {
      id: "ny-gbl-899aa",
      title: "New York General Business Law Section 899-AA: Notification of breach",
      publisher: "New York State Senate (Consolidated Laws)",
      url: "https://www.nysenate.gov/legislation/laws/GBS/899-AA",
      year: "2026",
      note: "Read October 5, 2026. Private information includes \"medical information\" and \"health insurance information\". Notice \"shall be made within thirty days after the breach has been discovered.\" Subdivision 9: a covered entity required to notify under HIPAA \"shall provide such notification to the state attorney general within five business days of notifying the secretary.\"",
    },
    {
      id: "ny-pbh-2445",
      title: "New York Public Health Law Section 2445: Applicability (Article 24-A)",
      publisher: "New York State Senate (Consolidated Laws)",
      url: "https://www.nysenate.gov/legislation/laws/PBH/2445",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"The provisions of this article shall not apply to the conduct of human research which is subject to, and which is in compliance with, policies and regulations promulgated by any agency of the federal government for the protection of human subjects.\"",
    },
    {
      id: "ny-pbh-2442",
      title: "New York Public Health Law Section 2442: Informed consent",
      publisher: "New York State Senate (Consolidated Laws)",
      url: "https://www.nysenate.gov/legislation/laws/PBH/2442",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"No human research may be conducted in this state in the absence of the voluntary informed consent subscribed to in writing by the human subject.\"",
    },
    {
      id: "nj-privacy",
      title: "P.L.2023, c.266 (New Jersey Data Privacy Act), C.56:8-166.4 et seq.",
      publisher: "New Jersey Legislature",
      url: "https://pub.njleg.gov/bills/2022/PL23/266_.HTM",
      year: "2024",
      note: "Read October 5, 2026. Controllers must \"not process sensitive data concerning a consumer without first obtaining the consumer's consent\"; sensitive data includes \"mental or physical health condition, treatment, or diagnosis\". Section 10 excludes \"protected health information collected by a covered entity or business associate\" and personal data processed \"as part of research conducted in accordance with\" 45 C.F.R. Part 46 or 21 C.F.R. Parts 50 and 56. \"This act shall take effect on the 365th day following the date of enactment\"; \"Approved January 16, 2024.\"",
    },
    { id: "bond-site", title: "Bond Health: platform overview, FAQ and pricing", publisher: "Bond Health", url: "https://bondtrials.com", year: "2026" },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, October 2026.",
    },
  ],
  related: [
    { label: "All locations", href: "/clinical-trial-recruitment", description: "Registry counts and outreach rules for other states and regions." },
    { label: "Bond for research sites", href: "/for/research-sites", description: "How screening, outreach and booked visits fit a site's coordinators." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
    { label: "Oncology", href: "/oncology", description: "How Bond screens for cancer trials, the NYC area's largest area by count." },
    { label: "Epic integration", href: "/integrations/epic", description: "How Bond connects to Epic, which most NYC systems run." },
    { label: "TCPA and AI outreach in 2026", href: "/blog/tcpa-ai-outreach-2026", description: "The federal calling and texting rules that sit on top of state law." },
  ],
};

export default page;
