import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/philadelphia",
  category: "geography",
  title: "Philadelphia clinical trial recruitment for sites",
  description:
    "Philadelphia-area recruiting-trial counts, research hubs, health system EHRs, languages and the Pennsylvania laws on AI outreach, texting and health data.",
  keywords: [
    "clinical trial recruitment Philadelphia",
    "Philadelphia research sites",
    "clinical trials Philadelphia South Jersey",
    "Pennsylvania patient recruitment",
    "Pennsylvania AI health care disclosure",
  ],
  eyebrow: "By location",
  h1: "Recruiting for clinical trials in the Philadelphia area",
  intro:
    "On October 5, 2026, a ClinicalTrials.gov radius search found 2,146 studies recruiting at one or more sites within 25 miles of Center City Philadelphia, about 10% of the 22,007 recruiting in the United States that day.{{cite:ctgov-api}} The radius crosses the Delaware River into South Jersey, so this page covers New Jersey rules alongside Pennsylvania's.",
  summary: "Philadelphia-area recruiting-trial counts, research hubs, health systems and their EHRs, languages, and Pennsylvania and New Jersey outreach rules.",
  lastUpdated: "2026-10-05",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in the Philadelphia area?",
      blocks: [
        {
          type: "p",
          text: "Oncology is the largest area at 811 of the 7,064 recruiting US oncology studies, about 11%, with cardiology next at 322 of 2,826. The area's share is highest in dermatology (29 of 212) and gastroenterology (36 of 283), and lowest in pain (34 of 625) and obesity and type 2 diabetes (55 of 855).{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "philadelphia", cite: "ctgov-api" },
        {
          type: "p",
          text: "A radius count shows where sponsors placed studies, not which ones enroll on schedule, and keyword matching on the condition field can pull in off-target studies. The obesity and type 2 diabetes examples below are the most recently updated recruiting studies in the radius; five of the six are Phase 2 or 3 industry trials from Amgen, Eli Lilly, Novo Nordisk and Boehringer Ingelheim.{{cite:ctgov-api}} See [obesity and metabolic](/obesity-and-metabolic) and [cardiology](/cardiology).",
        },
        { type: "trials", geo: "philadelphia", condition: "obesity", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are Philadelphia's research hubs?",
      blocks: [
        {
          type: "table",
          caption: "Selected Philadelphia research institutions, from NCI, BRIMR and their own sites, as of October 2026",
          columns: ["Institution", "Cancer center", "What the sources report"],
          rows: [
            [
              "Penn Medicine (Perelman School of Medicine)",
              "Abramson Cancer Center, comprehensive{{cite:nci-centers}}",
              "Third among US medical schools in NIH funding for federal fiscal 2025, at $622,537,289{{cite:brimr-2025}}. Penn's CTSA was submitted jointly with CHOP, the Wistar Institute and the University of the Sciences{{cite:itmat}}",
            ],
            [
              "Children's Hospital of Philadelphia",
              "None listed by NCI",
              "Fifth on BRIMR's list of hospitals by NIH funding for fiscal 2025, at $188,552,883{{cite:brimr-2025}}",
            ],
            [
              "Jefferson",
              "Sidney Kimmel Cancer Center, comprehensive since April 2024{{cite:nci-centers,jefferson-skcc}}",
              "First NCI designation in 1996; serves more than 8,900 patients a year{{cite:jefferson-skcc}}",
            ],
            [
              "Temple Health and Fox Chase",
              "Fox Chase Cancer Center, comprehensive{{cite:nci-centers}}",
              "Fox Chase joined Temple University Health System in 2012{{cite:fox-chase}}",
            ],
            [
              "The Wistar Institute",
              "Basic laboratory cancer center{{cite:nci-centers}}",
              "The first NCI-designated basic cancer center, recognized since 1971{{cite:wistar}}",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "**Cancer.** NCI lists three comprehensive cancer centers in Philadelphia (Abramson, Fox Chase and Sidney Kimmel) plus Wistar's basic laboratory center. It lists none in Delaware, and New Jersey's only designated center, Rutgers Cancer Institute, is in New Brunswick.{{cite:nci-centers}}",
            "**Translational science.** Penn's Institute for Translational Medicine and Therapeutics is the academic home of its CTSA, and NIH RePORTER shows Penn's new hub award starting July 1, 2026. The nearest other hubs are Penn State's in Hershey and Rutgers' NJ ACTS in Newark.{{cite:itmat,nih-reporter-ctsa}}",
            "**Federal funding.** Philadelphia ranked third among US cities in NIH funding for federal fiscal 2025, at $1,271,020,768, and the University of Pennsylvania ranked fifth among all funded institutions, at $722,746,749.{{cite:brimr-2025}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do Philadelphia's health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Philadelphia-area health systems, from their own pages, press and vendor endpoint directories, as of October 2026",
          columns: ["System", "Footprint", "EHR"],
          rows: [
            ["Penn Medicine", "Academic system", "Epic{{cite:epic-endpoints}}"],
            [
              "Jefferson Health",
              "32 hospitals and 700+ sites of care after combining with Lehigh Valley Health Network in August 2024{{cite:lvhn-jefferson}}",
              "Epic at nearly all facilities; Einstein, acquired in 2021, was to be the last to join (December 2024 report) and still has an Oracle Health endpoint listed{{cite:inquirer-jefferson,oracle-endpoints}}",
            ],
            ["Temple Health, including Fox Chase", "Academic system{{cite:fox-chase}}", "Epic; named to Epic's 2026 Honor Roll in July 2026{{cite:temple-epic,epic-endpoints}}"],
            ["Children's Hospital of Philadelphia", "Pediatric academic hospital", "Epic{{cite:epic-endpoints}}"],
            [
              "Main Line Health",
              "Five hospitals, including Lankenau, Bryn Mawr, Paoli and Riddle{{cite:mlh-about}}",
              "Epic{{cite:mlh-epic}}",
            ],
            [
              "Trinity Health Mid-Atlantic",
              "Mercy Fitzgerald, Nazareth, Saint Francis and St. Mary{{cite:trinity-ma}}",
              "Epic; its MyChart page calls the system \"an EHR and billing system\"{{cite:trinity-ma,epic-endpoints}}",
            ],
            ["Cooper University Health Care (Camden, NJ)", "Academic system in South Jersey", "Epic, live since April 30, 2009{{cite:cooper-epic,epic-endpoints}}"],
            ["Virtua Health (South Jersey)", "Five hospitals and more than 400 other locations{{cite:virtua-about}}", "Epic{{cite:epic-endpoints}}"],
            ["Inspira Health (South Jersey)", "Health system", "Scheduled to move to Epic on July 25, 2026; Oracle Health endpoints still listed{{cite:inspira-epic,oracle-endpoints}}"],
            ["ChristianaCare (Delaware)", "Four hospitals with 1,440 beds{{cite:christianacare-epic}}", "Epic launch scheduled for October 3, 2026{{cite:christianacare-epic}}"],
            [
              "Community health centers",
              "40 Pennsylvania awardees serving 869,212 patients and 23 New Jersey awardees serving 643,753 in 2025{{cite:hrsa-pa,hrsa-nj}}",
              "Varies by center",
            ],
          ],
        },
        {
          type: "p",
          text: "Epic is the regional default, but Jefferson's Einstein campuses, Inspira and ChristianaCare are recent or pending conversions, so confirm which record holds a patient's history. Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR, HL7 or an aggregator.{{cite:bond-site,bond-product}} It also works with the CTMS systems sites use, including CRIO, Advarra OnCore, Advarra Clinical Conductor, RealTime and Veeva SiteVault (Bond is a CRIO Certified Partner).{{cite:bond-site}} See [Epic](/integrations/epic) and [Oracle Health (Cerner)](/integrations/oracle-cerner).",
        },
        {
          type: "p",
          text: "Delaware County lost two hospitals in spring 2025. Taylor Hospital closed in late April and Crozer-Chester Medical Center on May 2, leaving Riddle and Mercy Fitzgerald as the county's only two hospitals.{{cite:inquirer-crozer,nbc-crozer}} With Crozer closed, a Delaware County study may need outreach that does not depend on one hospital's EHR, such as ads.",
        },
        {
          type: "p",
          text: "HealthShare Exchange, the region's nonprofit health information exchange, connects more than 500 entities, including more than 60 hospitals and 10 health plans.{{cite:hsx-home}} Its permitted-use policy requires IRB approval or exemption for research and says HSX data cannot be used for recruitment.{{cite:hsx-uses}} Statewide, Act 76 of 2016 created the PA Patient & Provider Network, and patients whose providers connect to it are included unless they opt out.{{cite:pa-dhs-p3n}} Screening should run on the site's own EHR.",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in the Philadelphia area, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "1,574,281", label: "Philadelphia residents on July 1, 2025", cite: "census-cities-2025" },
            { value: "6,329,118", label: "Philadelphia-Camden-Wilmington metro residents on July 1, 2025", cite: "census-cbsa-2025" },
            { value: "36.8%", label: "Philadelphia residents who are non-Hispanic Black, 2025", cite: "census-county-pa" },
            { value: "24.9%", label: "Philadelphia residents 5 and older who speak a language other than English at home, 2024", cite: "census-acs-phl" },
          ],
        },
        {
          type: "p",
          text: "On July 1, 2025, Philadelphia was 36.8% non-Hispanic Black, 33.6% non-Hispanic white, 17.2% Hispanic and 9.0% non-Hispanic Asian, and 15.9% of residents were 65 or older, against 21.4% statewide.{{cite:census-county-pa}} In 2024, 16.1% of residents were born abroad and 7.5% were uninsured.{{cite:census-acs-phl,census-acs-phl-s2701}}",
        },
        {
          type: "p",
          text: "Spanish is spoken at home by 163,503 Philadelphians aged 5 and older, 65,235 of whom speak English less than very well. Next are Chinese (38,444, of whom 27,231 speak English less than very well), Russian, Polish or other Slavic languages (24,889), French, Haitian or Cajun (24,591) and Vietnamese (15,479).{{cite:census-acs-phl-c16001}} At Pennsylvania health centers in 2025, 25.21% of patients were Hispanic or Latino, 19.86% had limited English proficiency and 42.81% had Medicaid or CHIP; in New Jersey, 51.05% were Hispanic or Latino.{{cite:hrsa-pa,hrsa-nj}}",
        },
        {
          type: "p",
          text: "A cohort that reflects the city needs strong reach into Black and Hispanic communities, plus Spanish and Chinese outreach, which usually means working with community clinics as well as the academic centers. Bond's voice and text agents work in the patient's language and can switch languages mid-call.{{cite:bond-product}} See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks and research sites work in the Philadelphia area?",
      blocks: [
        {
          type: "p",
          text: "Several multi-site research organizations list Philadelphia-area locations on their own websites, as of October 2026:",
        },
        {
          type: "ul",
          items: [
            "**Care Access** lists cardiology sites in Philadelphia (2418 E York St) and King of Prussia.{{cite:care-access}}",
            "**DM Clinical Research** lists a Philadelphia site at 231 N Broad St, one of 17 locations across 13 states.{{cite:dm-philadelphia,dm-locations}}",
            "**Adams Clinical** lists Philadelphia among six locations in New York, Massachusetts, Pennsylvania and Texas.{{cite:adams-clinical}}",
            "**Flourish Research** lists a site in Plymouth Meeting.{{cite:flourish}}",
            "**Suburban Research Associates**, part of Atlas Clinical Research, lists sites in Media and West Chester.{{cite:suburban-research}}",
          ],
        },
        {
          type: "p",
          text: "Bond is a CRIO Certified Partner, its only vendor certification.{{cite:bond-site}} See how Bond fits [research sites](/for/research-sites), [site networks](/for/site-networks) and [CRIO](/integrations/crio).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which Pennsylvania and New Jersey laws apply to AI outreach, texting and health data?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how each applies to pre-screening is unsettled. This is a map for your counsel, current as of October 5, 2026, not legal advice. For federal rules, see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026) and [IRB and HIPAA rules for patient outreach](/guides/irb-hipaa-patient-outreach).",
        },
        {
          type: "ul",
          items: [
            "**Call recording (18 Pa.C.S. §§ 5703 and 5704).** Intentionally intercepting a call is a third-degree felony unless an exception applies, and the exception for private parties requires that all parties to the call have given prior consent.{{cite:pa-5703,pa-5704}} A recorded AI call to a Pennsylvania patient should ask for consent to record at the start.",
            "**Telemarketing (Act 47 of 2026).** Signed July 20, 2026 and effective 90 days later, it extends the Telemarketer Registration Act to texts and ringless voicemail and defines a robocall to include artificial voice. Covered solicitations may not be made on Sundays, legal holidays, or before 9 a.m. or after 7 p.m.; robocalls need prior express written consent; text recipients can opt out by replying words such as \"stop\" or \"unsubscribe\"; and synthetic or computer-generated messaging may not be used to deceive.{{cite:pa-act47-2026}} The act covers solicitations to sell consumer goods or services and excludes calls made on behalf of 501(c)(3) organizations, so a study invitation, especially from a nonprofit hospital, likely falls outside it.{{cite:pa-tra}}",
            "**AI in health care (HB 1925).** The House passed this bill 144-59 on September 30, 2026, and as of October 5 it had not reached a Senate committee. As passed, a facility that uses AI to generate personalized written or verbal communications about a patient's clinical information would have to include a plain-language AI disclaimer and instructions for reaching a person. Messages that only cover administrative matters, such as appointment scheduling, would be exempt. It would take effect one year after enactment.{{cite:pa-hb1925,pa-hb1925-text}}",
            "**Consumer data privacy (HB 78).** The House passed it 127-76 on October 1, 2025, and the Senate gave it second consideration on June 25, 2026. It would require consent to process sensitive data, including a mental or physical health condition or diagnosis, and exempts HIPAA protected health information. It was not law as of October 5, 2026.{{cite:pa-hb78}}",
            "**New Jersey.** The New Jersey Data Privacy Act, approved January 16, 2024 and in effect 365 days later, requires consent to process sensitive data, including a mental or physical health condition, treatment or diagnosis. It excludes protected health information held by HIPAA covered entities and business associates, and personal data used in research under 45 CFR Part 46 or 21 CFR Parts 50 and 56.{{cite:nj-privacy}}",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI assistance is being used, and patients can reach a person at any time: the agent transfers the call live to a coordinator or books a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Scripts are configured per site and study, so a Pennsylvania site can add its IRB-reviewed wording and a request for consent to record, whether or not HB 1925 becomes law. See [IRB submission language for AI outreach](/templates/irb-submission-language-ai-outreach).",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Philadelphia-area site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration usually takes 48 hours, depending on the EHR, IT review and interface method, and there is no integration fee.{{cite:bond-site,bond-product}} See [implementation](/implementation) for the step-by-step plan and [pricing](/pricing) for how fees work.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Sign the paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path.{{cite:bond-site}} For Pennsylvania patients, agree on how recorded calls ask for consent to record.",
            },
            {
              title: "Connect the EHR",
              text: "Connect Epic, Oracle Health or another EHR through FHIR, HL7 or an aggregator.{{cite:bond-product}} Screen the site's own records, not exchange data.",
            },
            {
              title: "Check criteria before outreach",
              text: "Bond reads clinical notes, prescriptions, lab results, imaging data and pathology, radiology and molecular reports, and shows criterion-by-criterion evidence for every match, so coordinators can review a sample before any patient is contacted.{{cite:bond-site,bond-product}} See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Run ads, reach out and book",
              text: "Bond creates and runs Meta and Google ad campaigns for the study, paid from the site's own ad budget. Its voice and text agents contact every new lead immediately, keep following up with those who have not responded, pre-screen in the patient's language and book visits straight into the site's calendar, with reminders by text, voice or email.{{cite:bond-product}}",
            },
            {
              title: "Support consent and retention",
              text: "After the booked visit, the agents can explain the study in plain language and answer questions, escalating to staff; the site and PI obtain consent. After enrollment they send visit reminders, book transportation and flag dropout risk.{{cite:bond-product}} See [consent](/consent).",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting in the Philadelphia area?",
      a: "On October 5, 2026, a ClinicalTrials.gov search for recruiting studies with a site within 25 miles of Center City Philadelphia returned 2,146, including 811 that matched oncology keywords.{{cite:ctgov-api}}",
    },
    {
      q: "Does Pennsylvania require patients to be told when AI is used?",
      a: "Not yet. HB 1925, which would require an AI disclaimer on AI-generated clinical communications but exempt scheduling messages, passed the House on September 30, 2026 and awaits the Senate.{{cite:pa-hb1925}} Bond's agents disclose AI use regardless.{{cite:bond-site}}",
    },
    {
      q: "Can HealthShare Exchange data be used to find trial patients?",
      a: "No. HSX's permitted-use policy says its data cannot be used for recruitment, so screening runs on the site's own EHR.{{cite:hsx-uses}}",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Radius search queried October 5, 2026: filter.geo=distance(39.9526,-75.1652,25mi) (25 miles of Center City Philadelphia), filter.overallStatus=RECRUITING, countTotal=true; 2,146 studies. US totals from the same day use query.locn=United States; 22,007 studies. Area counts use keyword searches on the condition field. Shares are Bond's arithmetic.",
    },
    {
      id: "census-cities-2025",
      title: "City and Town Population Totals: April 1, 2020 to July 1, 2025 (SUB-EST2025)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/cities/totals/sub-est2025.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row SUMLEV 162, Pennsylvania, \"Philadelphia city\": POPESTIMATE2025 1574281.",
    },
    {
      id: "census-cbsa-2025",
      title: "Metropolitan and Micropolitan Statistical Area Population Totals: April 1, 2020 to July 1, 2025 (CBSA-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/metro/totals/cbsa-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row CBSA 37980, \"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD\", Metropolitan Statistical Area: POPESTIMATE2025 6329118.",
    },
    {
      id: "census-county-pa",
      title: "Annual County Resident Population Estimates by Age, Sex, Race, and Hispanic Origin: April 1, 2020 to July 1, 2025 (CC-EST2025-ALLDATA-42)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/asrh/cc-est2025-alldata-42.csv",
      year: "2026",
      note: "Downloaded October 5, 2026 and summed by Bond for YEAR 7 (\"7/1/2025 population estimate\" in the file layout). Philadelphia County total 1,574,281: non-Hispanic Black alone 579,847 (36.8%); non-Hispanic white alone 528,442 (33.6%); Hispanic 271,320 (17.2%); non-Hispanic Asian alone 141,765 (9.0%); ages 65 and over 250,073 (15.9%). Pennsylvania: 2,799,790 of 13,059,432 aged 65 and over (21.4%).",
    },
    {
      id: "census-acs-phl",
      title: "Selected Social Characteristics, Philadelphia city, Pennsylvania: 2024 ACS 1-Year Estimates (DP02)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSDP1Y2024.DP02&g=160XX00US4260000",
      year: "2025",
      note: "Read October 5, 2026. DP02_0094PE \"PLACE OF BIRTH!!Total population!!Foreign-born\" 16.1; DP02_0114PE \"LANGUAGE SPOKEN AT HOME!!Population 5 years and over!!Language other than English\" 24.9.",
    },
    {
      id: "census-acs-phl-s2701",
      title: "Selected Characteristics of Health Insurance Coverage, Philadelphia city, Pennsylvania: 2024 ACS 1-Year Estimates (S2701)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSST1Y2024.S2701&g=160XX00US4260000",
      year: "2025",
      note: "Read October 5, 2026. S2701_C05_001E \"Percent Uninsured!!Civilian noninstitutionalized population\" 7.5 (margin 0.7).",
    },
    {
      id: "census-acs-phl-c16001",
      title: "Language Spoken at Home for the Population 5 Years and Over, Philadelphia city, Pennsylvania: 2024 ACS 1-Year Estimates (C16001)",
      publisher: "U.S. Census Bureau, American Community Survey (data.census.gov)",
      url: "https://data.census.gov/api/access/data/table?id=ACSDT1Y2024.C16001&g=160XX00US4260000",
      year: "2025",
      note: "Read October 5, 2026. Total 1,482,857. \"Spanish:\" 163,503, of whom 65,235 speak English less than \"very well\"; \"Chinese (incl. Mandarin, Cantonese):\" 38,444, of whom 27,231 speak English less than very well; \"Russian, Polish, or other Slavic languages:\" 24,889; \"French, Haitian, or Cajun:\" 24,591; \"Vietnamese:\" 15,479.",
    },
    {
      id: "hrsa-pa",
      title: "Pennsylvania Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/PA",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Total Number of Reporting Program Awardees: 40\", \"Reporting Period: 2025\", \"Total Patients Served: 869,212\". 2025: Hispanic, Latino/a, or Spanish Origin 25.21%; Limited English Proficiency 19.86% (172,585 patients); Medicaid/CHIP 42.81%.",
    },
    {
      id: "hrsa-nj",
      title: "New Jersey Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/NJ",
      year: "2026",
      note: "Read October 5, 2026. Awardees 23; reporting period 2025; total patients served 643,753; Hispanic, Latino/a, or Spanish Origin 51.05%.",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Read October 5, 2026 (page updated June 10, 2026). Philadelphia entries: \"Abramson Cancer Center\", \"Fox Chase Cancer Center\" and \"Sidney Kimmel Cancer Center at Thomas Jefferson University\", each a Comprehensive Cancer Center; \"The Wistar Institute Cancer Center\", Basic Laboratory Cancer Center. New Jersey: Rutgers Cancer Institute of New Jersey, New Brunswick. No Delaware entry.",
    },
    {
      id: "nih-reporter-ctsa",
      title: "NIH RePORTER: NCATS Clinical and Translational Science Award hub awards (UL1/UM1), Pennsylvania and New Jersey, fiscal years 2025-2026",
      publisher: "National Institutes of Health",
      url: "https://reporter.nih.gov/project-details/11336512",
      year: "2026",
      note: "Queried October 5, 2026 through the RePORTER API (agency NCATS, activity codes UL1 and UM1). University of Pennsylvania: 1UM1TR006155-01, \"Institutional Clinical and Translational Science Award\", project start 2026-07-01 (the linked record). Others: 1UM1TR006339-01, \"Penn State Clinical and Translational Science Institute\", Hershey; 5UM1TR004789-03, \"NJ ACTS: A Platform for Translational Science in New Jersey\", Rutgers Biomedical and Health Sciences, Newark.",
    },
    {
      id: "itmat",
      title: "CTSA Partners",
      publisher: "Institute for Translational Medicine and Therapeutics, Perelman School of Medicine at the University of Pennsylvania",
      url: "https://www.itmat.upenn.edu/ctsa-partners.html",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"The Clinical and Translational Science Award was submitted jointly by the University of Pennsylvania, The Children's Hospital of Philadelphia, The Wistar Institute, and the University of the Sciences in Philadelphia.\" and \"The academic home for the CTSA is the Institute for Translational Medicine and Therapeutics (ITMAT) at the University of Pennsylvania.\"",
    },
    {
      id: "brimr-2025",
      title: "BRIMR Rankings of NIH Funding in 2025",
      publisher: "Blue Ridge Institute for Medical Research",
      url: "https://brimr.org/brimr-rankings-of-nih-funding-in-2025/",
      year: "2026",
      note: "Read October 5, 2026. The rankings use \"NIH year-end composite data for the federal fiscal year ending 30 September 2025\". Spreadsheet rows: Cities (City_2025.xlsx) \"3 | PHILADELPHIA | 1271020768\"; Schools of Medicine (SchoolOfMedicine_2025.xlsx) \"3 | UNIVERSITY OF PENNSYLVANIA | 622537289\"; All institutions (Institution_2025.xlsx) \"5 | UNIVERSITY OF PENNSYLVANIA | 722746749\"; Hospitals (Hospitals_2025.xlsx) \"5 | CHILDREN'S HOSP OF PHILADELPHIA | 188552883\".",
    },
    {
      id: "jefferson-skcc",
      title: "National Cancer Institute Designates Jefferson's Sidney Kimmel Cancer Center as a Comprehensive Cancer Center",
      publisher: "Thomas Jefferson University",
      url: "https://www.jefferson.edu/about/news-and-events/2024/04/national-cancer-institute-designates-jeffersons-sidney-kimmel-cancer-center-as-a-comprehensive-cancer-center.html",
      year: "2024",
      note: "Dated April 18, 2024. Quotes: \"Jefferson received an initial NCI Designation in 1996.\" and \"Serving more than 8,900 patients annually\".",
    },
    {
      id: "fox-chase",
      title: "About Fox Chase Cancer Center",
      publisher: "Fox Chase Cancer Center",
      url: "https://www.foxchase.org/about-us",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Fox Chase Cancer Center, part of the Temple University Health System\" and \"In 2012, we joined Temple University Health System\".",
    },
    {
      id: "wistar",
      title: "About The Wistar Institute",
      publisher: "The Wistar Institute",
      url: "https://www.wistar.org/about-wistar/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"First NCI-designated Basic Cancer Center (with continued recognition and support since 1971)\".",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Downloaded October 5, 2026 (bundle total 479). Entries include \"Penn Medicine\", \"Jefferson Health\", \"Lehigh Valley Health Network\", \"TempleHealth\", \"Children's Hospital of Philadelphia\", \"Main Line Health\", \"Virtua Health\", \"Cooper University Health Care\" and \"Trinity Health\". ChristianaCare and Inspira were not listed. A listing means the organization publishes patient-access FHIR endpoints on Epic.",
    },
    {
      id: "oracle-endpoints",
      title: "Oracle Health Millennium patient R4 FHIR endpoints (millennium_patient_r4_endpoints.json)",
      publisher: "Oracle (oracle-samples/ignite-endpoints on GitHub)",
      url: "https://raw.githubusercontent.com/oracle-samples/ignite-endpoints/main/oracle_health_fhir_endpoints/millennium_patient_r4_endpoints.json",
      year: "2026",
      note: "Downloaded October 5, 2026. Organization entries include \"Albert Einstein Healthcare Network\" (Philadelphia, PA), \"Inspira Health Network, Inc.\" (Vineland, NJ) and \"Christiana Care Health Services, Inc.\" (Wilmington, DE). A listing shows a Millennium FHIR endpoint and may lag a system's move to another EHR.",
    },
    {
      id: "lvhn-jefferson",
      title: "Jefferson, Lehigh Valley Health Network Complete Combination",
      publisher: "Lehigh Valley Health Network",
      url: "https://www.lvhn.org/news/jefferson-lehigh-valley-health-network-complete-combination",
      year: "2024",
      note: "Dated August 1, 2024. Quote: \"The system is now among the top 15 not-for-profit health systems in the U.S. with 32 hospitals and more than 700 sites of care\".",
    },
    {
      id: "inquirer-jefferson",
      title: "Jefferson President Talks About Creating Cohesion Across the Health System's Growing Empire",
      publisher: "The Philadelphia Inquirer",
      url: "https://www.inquirer.com/health/baligh-yehia-jefferson-health-president-philadelphia-hospitals-20241202.html",
      year: "2024",
      note: "Dated December 2, 2024. Quote: \"nearly all are now using the Epic brand electronic medical record ... Einstein, acquired in 2021, will be the last to join Epic within the next few years. Lehigh Valley already uses Epic.\"",
    },
    {
      id: "temple-epic",
      title: "Epic Names Temple Health to 2026 Honor Roll for EMR System Optimization",
      publisher: "Temple Health",
      url: "https://www.templehealth.org/about/newsroom/epic-names-temple-health-2026-honor-roll-emr-system-optimization",
      year: "2026",
      note: "Dated July 16, 2026. Quote: \"Epic named Temple Health to its 2026 'Honor Roll' at the Cum Laude level.\"",
    },
    {
      id: "mlh-about",
      title: "About Main Line Health",
      publisher: "Main Line Health",
      url: "https://www.mainlinehealth.org/about",
      year: "2026",
      note: "Read October 5, 2026. Quote: Main Line Health \"consists of five hospitals, seven health centers and over 150 medical practice locations\"; acute care hospitals Lankenau Medical Center, Bryn Mawr Hospital, Paoli Hospital and Riddle Hospital.",
    },
    {
      id: "mlh-epic",
      title: "EpicCare Link, For Physicians",
      publisher: "Main Line Health",
      url: "https://www.mainlinehealth.org/physicians/epiccare-link",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"If you are not using Main Line Health's Epic electronic medical record system, signing up for EpicCare Link provides you and your staff with a secure platform\".",
    },
    {
      id: "trinity-ma",
      title: "MyChart",
      publisher: "Trinity Health Mid-Atlantic",
      url: "https://www.trinityhealthma.org/mychart",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Trinity Health Mid-Atlantic is now on MyChart, an EHR and billing system that allows us to better meet your needs.\" and \"You can now get your hospital records from Mercy Fitzgerald, Nazareth, Saint Francis or St. Mary\".",
    },
    {
      id: "cooper-epic",
      title: "Cooper University Hospital \"Goes Live\" with EPIC Electronic Health Record System",
      publisher: "Cooper University Health Care",
      url: "https://blogs.cooperhealth.org/news/2009/05/cooper-university-hospital-%E2%80%9Cgoes-live%E2%80%9D-with-epic-electronic-health-record-system/",
      year: "2009",
      note: "Dated May 8, 2009. Quote: \"Cooper University Hospital has launched its new electronic health record system, EPIC, going 'live' throughout the hospital on April 30, 2009.\"",
    },
    {
      id: "virtua-about",
      title: "About Virtua Health",
      publisher: "Virtua Health",
      url: "https://www.virtua.org/About",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"In addition to five hospitals, two satellite emergency departments, 40+ ambulatory surgery centers, and more than 400 other locations\".",
    },
    {
      id: "inspira-epic",
      title: "Epic Is Coming: What Patients Need to Know About Inspira's New Health Record System",
      publisher: "Inspira Health",
      url: "https://www.inspirahealthnetwork.org/news/healthy-living/epic-coming-what-patients-need-know-about-inspiras-new-health-record-system",
      year: "2026",
      note: "Dated May 14, 2026. Quote: \"Inspira Health will transition to Epic on July 25, 2026\". Whether the go-live happened on that date was not confirmed.",
    },
    {
      id: "christianacare-epic",
      title: "ChristianaCare Advances Epic Electronic Health Record Implementation Ahead of October 3, 2026 Go-Live",
      publisher: "ChristianaCare",
      url: "https://news.christianacare.org/pressrelease/christianacare-advances-epic-electronic-health-record-implementation-ahead-of-october-3-2026-go-live/",
      year: "2026",
      note: "Dated July 22, 2026. Quotes: \"Epic implementation, scheduled to launch on October 3, 2026\" and \"four hospitals (1,440 beds)\". Whether the launch happened on that date was not confirmed.",
    },
    {
      id: "inquirer-crozer",
      title: "Crozer-Chester Medical Center and Taylor Hospital Are Closing, Owner Prospect Says",
      publisher: "The Philadelphia Inquirer",
      url: "https://www.inquirer.com/health/crozer-hospitals-closing-20250421.html",
      year: "2025",
      note: "Dated April 21, 2025. Quote: Prospect Medical Holdings \"filed a bankruptcy notice Monday saying it is closing Delaware County's Crozer-Chester Medical Center and Taylor Hospital.\"",
    },
    {
      id: "nbc-crozer",
      title: "Crozer-Chester Medical Center Closes",
      publisher: "NBC10 Philadelphia",
      url: "https://www.nbcphiladelphia.com/news/health/crozer-chester-hospital-closes/",
      year: "2025",
      note: "Dated May 2, 2025. Quotes: Crozer-Chester Medical Center \"ceases operations on May 2, 2025\"; \"Taylor Hospital closed all operations last week.\"; services diverted \"to the only two remaining Delaware County hospitals -- Riddle and Mercy Fitzgerald.\"",
    },
    {
      id: "hsx-home",
      title: "HealthShare Exchange",
      publisher: "HealthShare Exchange (HSX)",
      url: "https://healthshareexchange.org/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Our connections to more than 500 entities in the tri-state region with national reach support seamless information sharing across the full continuum of care, including more than 60 hospitals and 10 health plans\". The About page calls HSX \"a nonprofit community-directed organization\" serving the Greater Philadelphia/Delaware Valley area.",
    },
    {
      id: "hsx-uses",
      title: "Permitted Uses",
      publisher: "HealthShare Exchange (HSX)",
      url: "https://healthshareexchange.org/permitted-uses/",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"Researchers must align with HSX's mission and purpose and need IRB approval or exemption.\" and \"HSX data cannot be used for the purpose of recruitment, marketing, analysis of cost and/or utilization for tiering purposes by health plans.\"",
    },
    {
      id: "pa-dhs-p3n",
      title: "eHealth Partnership",
      publisher: "Pennsylvania Department of Human Services",
      url: "https://www.pa.gov/agencies/dhs/departments-offices/omap-info/ehealth-partnership",
      year: "2026",
      note: "Read October 5, 2026. Quotes: \"The Pennsylvania eHealth Partnership is responsible, under Act 76 of 2016, for the creation and maintenance of Pennsylvania's secure health information exchange, known as the PA Patient & Provider Network, or P3N.\" and \"patients who do not want their medical information available for exchange across the network may opt-out of the P3N.\"",
    },
    {
      id: "care-access",
      title: "Locations",
      publisher: "Care Access",
      url: "https://careaccess.com/about-us/locations",
      year: "2026",
      note: "Read October 5, 2026. Pennsylvania: \"170 N Henderson Rd # 310 King of Prussia, PA, 19406\" and \"2418 E York St. Philadelphia, PA, 19125\", both labeled Cardiology.",
    },
    {
      id: "dm-philadelphia",
      title: "Clinical Trials in Philadelphia, PA",
      publisher: "DM Clinical Research",
      url: "https://www.dmclinicalresearch.com/locations/philadelphia-pa/",
      year: "2026",
      note: "Read October 5, 2026. Address: \"231 N Broad St., 1st & 3rd Floor, Philadelphia, PA 19107\".",
    },
    {
      id: "dm-locations",
      title: "Locations",
      publisher: "DM Clinical Research",
      url: "https://www.dmclinicalresearch.com/locations",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"17 locations across 13 states\".",
    },
    {
      id: "adams-clinical",
      title: "Adams Clinical",
      publisher: "Adams Clinical",
      url: "https://www.adamsclinical.com/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"With six locations across New York, Massachusetts, Pennsylvania, and Texas\"; locations named Boston, Bronx, Dallas, Harlem, Philadelphia and Watertown.",
    },
    {
      id: "flourish",
      title: "Locations",
      publisher: "Flourish Research",
      url: "https://flourishresearch.com/locations/",
      year: "2026",
      note: "Read October 5, 2026. Pennsylvania address: \"920 Germantown Pike Suite 102 & 203, Plymouth Meeting, PA 19462\".",
    },
    {
      id: "suburban-research",
      title: "Suburban Research Associates | Atlas Clinical Research Site",
      publisher: "Suburban Research Associates",
      url: "https://www.suburbanresearch.com/",
      year: "2026",
      note: "Read October 5, 2026. Addresses: \"107 Chesley Drive, Unit 4 Media, PA 19063\" and \"1065 Andrew Drive, Unit B3 West Chester, PA 19380\".",
    },
    {
      id: "pa-5703",
      title: "18 Pa.C.S. § 5703: Interception, disclosure or use of wire, electronic or oral communications",
      publisher: "Pennsylvania General Assembly",
      url: "https://www.palegis.us/WU01/LI/LI/CT/HTM/18/00.057.003.000..HTM",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Except as otherwise provided in this chapter, a person is guilty of a felony of the third degree if he: (1) intentionally intercepts, endeavors to intercept, or procures any other person to intercept or endeavor to intercept any wire, electronic or oral communication\".",
    },
    {
      id: "pa-5704",
      title: "18 Pa.C.S. § 5704: Exceptions to prohibition of interception and disclosure of communications",
      publisher: "Pennsylvania General Assembly",
      url: "https://www.palegis.us/WU01/LI/LI/CT/HTM/18/00.057.004.000..HTM",
      year: "2026",
      note: "Read October 5, 2026. Paragraph (4): \"A person, to intercept a wire, electronic or oral communication, where all parties to the communication have given prior consent to such interception.\"",
    },
    {
      id: "pa-act47-2026",
      title: "Act of Jul. 20, 2026, P.L. 532, No. 47 (SB 992): Telemarketer Registration Act, omnibus amendments",
      publisher: "Pennsylvania General Assembly",
      url: "https://www.palegis.us/WU01/LI/LI/US/HTM/2026/0/0047..HTM",
      year: "2026",
      note: "Read October 5, 2026. \"Robocall\" now means a telephone solicitation \"that uses an automated dialing system to deliver prerecorded or artificial voice calls or messages.\" Prohibited: \"Initiating or causing to be initiated a telephone solicitation on a Sunday or after 7 p.m. or before 9 a.m.\"; a telephone solicitation \"on a legal holiday\"; a robocall \"without the prior express written consent of a called party\"; and \"Using or causing to be used any technology or any synthetic or computer-generated messaging to defraud, deceive or mislead\". Text recipients may reply \"stop,\" \"quit,\" \"end,\" \"revoke,\" \"opt out,\" \"cancel\" or \"unsubscribe\". \"This act shall take effect in 90 days. APPROVED--The 20th day of July, A.D. 2026.\"",
    },
    {
      id: "pa-tra",
      title: "Telemarketer Registration Act (Act of Dec. 4, 1996, P.L. 911, No. 147), as amended",
      publisher: "Pennsylvania General Assembly",
      url: "https://www.palegis.us/WU01/LI/LI/US/HTM/1996/0/0147..HTM",
      year: "2026",
      note: "Read October 5, 2026. \"Telephone solicitation\" means \"A telephone call, voicemail, ringless voicemail or text message made to a residential, business or wireless telephone subscriber for the purpose of soliciting the sale of consumer goods or services\"; the term excludes a call or message \"On behalf of an organization granted tax-exempt status under 26 U.S.C. § 501(c)(3), (5) or (8)\". Definition amended July 20, 2026, P.L.532, No.47.",
    },
    {
      id: "pa-hb1925",
      title: "House Bill 1925 (2025-2026 Regular Session): artificial intelligence in facilities, insurers and MA or CHIP managed care plans",
      publisher: "Pennsylvania General Assembly",
      url: "https://www.palegis.us/legislation/bills/2025/hb1925",
      year: "2026",
      note: "Read October 5, 2026. History: \"Third consideration and final passage, Sept. 30, 2026 (144-59)\"; in the Senate, \"Referred to Committee\" shows \"Has not yet reached this milestone\".",
    },
    {
      id: "pa-hb1925-text",
      title: "House Bill 1925, Printer's No. 3963",
      publisher: "Pennsylvania General Assembly",
      url: "https://www.palegis.us/legislation/bills/text/HTM/2025/0/HB1925/PN3963",
      year: "2026",
      note: "Read October 5, 2026. Proposed 35 Pa.C.S. § 3502(b): a facility that uses AI to generate personalized written or verbal patient communications about an individual patient's clinical information must include \"A clear and conspicuous disclaimer in plain language that indicates that the communication was generated by artificial intelligence\" and \"Clear instructions on how the patient may contact a human health care provider or relevant employee of the facility with questions.\" The requirement does not apply to communications that \"only pertain to administrative matters\", including appointment scheduling, or that a human provider has individually read, reviewed and approved. Section 4: \"This act shall take effect in one year.\"",
    },
    {
      id: "pa-hb78",
      title: "House Bill 78 (2025-2026 Regular Session): consumer data privacy",
      publisher: "Pennsylvania General Assembly",
      url: "https://www.palegis.us/legislation/bills/2025/hb78",
      year: "2026",
      note: "Read October 5, 2026. History: \"Third consideration and final passage, Oct. 1, 2025 (127-76)\"; \"Re-reported as amended, June 24, 2026\"; \"Second consideration, June 25, 2026\". Bill text (Printer's No. 3688): controllers must \"Refrain from processing sensitive data concerning a consumer without obtaining the consumer's consent\"; sensitive data includes \"Mental or physical health condition or diagnosis\"; exempt: \"Protected health information under HIPAA.\"",
    },
    {
      id: "nj-privacy",
      title: "P.L.2023, c.266 (New Jersey Data Privacy Act), C.56:8-166.4 et seq.",
      publisher: "New Jersey Legislature",
      url: "https://pub.njleg.gov/bills/2022/PL23/266_.HTM",
      year: "2024",
      note: "Read October 5, 2026. Controllers must \"not process sensitive data concerning a consumer without first obtaining the consumer's consent\"; sensitive data includes \"mental or physical health condition, treatment, or diagnosis\". Section 10 excludes \"protected health information collected by a covered entity or business associate\" and personal data processed \"as part of research conducted in accordance with\" 45 C.F.R. Part 46 or 21 C.F.R. Parts 50 and 56. \"This act shall take effect on the 365th day following the date of enactment\"; \"Approved January 16, 2024.\"",
    },
    { id: "bond-site", title: "Bond Health: platform overview, FAQ and pricing", publisher: "Bond Health", url: "https://bondtrials.com", year: "2026" },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, October 2026.",
    },
  ],
  related: [
    { label: "All locations", href: "/clinical-trial-recruitment", description: "Registry counts and outreach rules for other states and regions." },
    { label: "Bond for research sites", href: "/for/research-sites", description: "How screening, outreach and booked visits fit a site's coordinators." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
    { label: "Oncology", href: "/oncology", description: "How Bond screens for cancer trials, the Philadelphia area's largest area by count." },
    { label: "Obesity and metabolic", href: "/obesity-and-metabolic", description: "Recruiting for GLP-1, obesity and type 2 diabetes studies." },
    { label: "Epic integration", href: "/integrations/epic", description: "How Bond connects to Epic, the region's most common EHR." },
  ],
};

export default page;
