import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/san-francisco-bay-area",
  category: "geography",
  title: "Bay Area clinical trial recruitment for research sites",
  description:
    "For San Francisco Bay Area research sites: recruiting-trial counts, research hubs, health system EHRs, languages and the California rules on AI outreach.",
  keywords: [
    "clinical trial recruitment San Francisco",
    "Bay Area research sites",
    "clinical trials San Francisco Oakland San Jose",
    "California AI disclosure AB 3030",
    "Bay Area health system EHRs",
  ],
  eyebrow: "By location",
  h1: "Recruiting for clinical trials in the San Francisco Bay Area",
  intro:
    "On October 5, 2026, a ClinicalTrials.gov radius search found 2,270 recruiting studies with at least one site within 40 miles of San Mateo, a circle that covers San Francisco, Oakland and San Jose. That is about 10.3% of the 22,007 studies recruiting in the United States that day.{{cite:ctgov-api}} This page is for research sites across the Bay Area: where the research hubs are, which EHRs hold the patients, who lives here, and which California rules shape AI-assisted outreach.",
  summary: "Bay Area recruiting-trial counts, research hubs, health systems and their EHRs, languages, and California outreach rules.",
  lastUpdated: "2026-10-05",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in the Bay Area?",
      blocks: [
        {
          type: "p",
          text: "Oncology is the largest area, with 803 studies: 35.4% of the local total and 11.4% of the 7,064 recruiting oncology studies in the US. Cardiology follows with 320 studies and neurology with 113, each about 11% of the US total. The Bay Area's share is highest in dermatology (42 of 212) and lowest in obesity and type 2 diabetes (61 of 855).{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "san-francisco-bay-area", cite: "ctgov-api" },
        {
          type: "p",
          text: "A radius count includes every recruiting study with at least one location inside the circle, so a study with sites at both UCSF and Stanford counts once. Area counts come from keyword searches, overlap, and can pull in off-target studies, and a count shows where sponsors placed studies, not which ones enroll on schedule. The examples below are obesity and type 2 diabetes studies from the same October 5, 2026 query.{{cite:ctgov-api}} See [obesity and metabolic](/obesity-and-metabolic).",
        },
        { type: "trials", geo: "san-francisco-bay-area", condition: "obesity", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are the Bay Area's research hubs?",
      blocks: [
        {
          type: "table",
          caption: "Bay Area research hubs and what their anchor institutions report, as of October 2026",
          columns: ["Hub", "Anchor institutions", "What they report"],
          rows: [
            [
              "San Francisco",
              "UCSF and the UCSF Helen Diller Family Comprehensive Cancer Center{{cite:nci-centers}}",
              "UCSF's Clinical and Translational Science Institute is part of the NIH's CTSA program{{cite:ucsf-ctsi}}. The UCSF Memory and Aging Center hosts an NIA-funded Alzheimer's Disease Research Center{{cite:nia-adrc}}",
            ],
            [
              "Stanford and Palo Alto",
              "Stanford Medicine and the Stanford Cancer Institute{{cite:nci-centers}}",
              "Spectrum, the Stanford Center for Clinical and Translational Research and Education, says it is supported by the NIH{{cite:stanford-spectrum}}. Stanford's Alzheimer's Disease Research Center is in Palo Alto{{cite:nia-adrc}}",
            ],
            [
              "Oakland and the East Bay",
              "Kaiser Permanente Northern California, headquartered in Oakland{{cite:kp-facts}}",
              "About 4.7 million members and 21 hospitals as of June 30, 2026{{cite:kp-facts}}. Kaiser Permanente NCORP, an NCI community oncology research site based in Oakland, lists affiliates at Kaiser medical centers across the region{{cite:ncorp}}",
            ],
            [
              "Across the region",
              "Sutter Health, whose hospitals include Alta Bates Summit Medical Center, California Pacific Medical Center and Sutter Eden Medical Center{{cite:sutter-about}}",
              "The Sutter Cancer Research Consortium and Palo Alto Medical Foundation sites appear on location records for recruiting studies in the radius{{cite:ctgov-locations}}",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "**Cancer.** The National Cancer Institute lists two comprehensive cancer centers inside the 40-mile circle, UCSF Helen Diller and the Stanford Cancer Institute. The UC Davis center is in Sacramento, outside it.{{cite:nci-centers}}",
            "**Memory.** The National Institute on Aging funds Alzheimer's Disease Research Centers at UCSF and Stanford.{{cite:nia-adrc}} See [neurology and Alzheimer's](/neurology-and-alzheimers).",
            "**Asian American research.** UCSF's CARE registry connects Asian American, Native Hawaiian and Pacific Islander adults with health research, and accepts people who read or speak English, Cantonese, Mandarin, Hindi, Japanese, Korean, Samoan, Tagalog or Vietnamese.{{cite:ucsf-care}} Stanford's Center for Asian Health Research and Education works on diseases that affect Asian communities disproportionately.{{cite:stanford-care}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do Bay Area health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Bay Area health systems, from vendor FHIR endpoint directories downloaded October 5, 2026",
          columns: ["System", "Footprint", "EHR"],
          rows: [
            ["UCSF Health", "Academic system, including UCSF Benioff Children's Hospital{{cite:epic-endpoints}}", "Epic{{cite:epic-endpoints}}"],
            ["Stanford Health Care and Stanford Children's Health", "Academic system and home of the Stanford Cancer Institute{{cite:nci-centers}}", "Epic{{cite:epic-endpoints}}"],
            [
              "Kaiser Permanente Northern California",
              "About 4.7 million members, 21 hospitals and 9,976 physicians in the region{{cite:kp-facts}}",
              "Epic, listed as \"Kaiser Permanente - California - Northern\"{{cite:epic-endpoints}}",
            ],
            ["Sutter Health", "Hospitals including Alta Bates Summit, California Pacific Medical Center and Sutter Eden{{cite:sutter-about}}", "Epic{{cite:epic-endpoints}}"],
            ["John Muir Health and El Camino Hospital", "Community hospital systems", "Epic{{cite:epic-endpoints}}"],
            [
              "County and public systems",
              "San Francisco Department of Public Health, Santa Clara Valley Medical Center Hospitals and Clinics, Alameda Health System, Contra Costa and the County of San Mateo",
              "Epic, each listed separately{{cite:epic-endpoints}}",
            ],
            ["CommonSpirit Health, Dignity Health and Chinese Hospital", "San Francisco listings in Oracle's directory", "Oracle Health (Cerner){{cite:oracle-endpoints}}"],
            [
              "Community health centers",
              "170 HRSA-funded awardees statewide served 5,900,539 patients in 2025{{cite:hrsa-ca}}",
              "Varies by center",
            ],
          ],
          note: "A directory listing shows a FHIR endpoint, not every system an organization runs. Confirm with the site's IT team.",
        },
        {
          type: "p",
          text: "The Bay Area is mostly an Epic market: the academic centers, Kaiser, Sutter and five county and public systems all appear in Epic's directory.{{cite:epic-endpoints}} That makes a multi-system study simpler, though each system still runs its own IT, privacy and research review. Bond connects to Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm, OncoEMR and other major EHRs through FHIR, HL7 or an aggregator.{{cite:bond-site,bond-product}} It also works with the CTMS systems sites use, including CRIO, Advarra OnCore, Advarra Clinical Conductor, RealTime and Veeva SiteVault (Bond is a CRIO Certified Partner).{{cite:bond-site}} See [Epic](/integrations/epic) and [Oracle Health (Cerner)](/integrations/oracle-cerner).",
        },
        {
          type: "p",
          text: "Eligibility usually turns on free text: oncology notes, pathology and molecular reports, imaging reads. Bond's screening reads clinical notes, prescriptions, lab results, imaging data and pathology, radiology and molecular reports, and shows criterion-by-criterion evidence for every match.{{cite:bond-product}} See [Identify](/identify) and [oncology](/oncology).",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in the Bay Area, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "6.29 million", label: "Residents of San Francisco, San Mateo, Santa Clara, Alameda and Contra Costa counties, July 1, 2025", cite: "census-co-2025" },
            { value: "34.9%", label: "Non-Hispanic Asian in those five counties, 2025", cite: "census-cc-2025" },
            { value: "47.9%", label: "Residents 5 and older who speak a language other than English at home, 2024", cite: "acs-c16001" },
            { value: "35.9%", label: "Born outside the United States, 2024", cite: "acs-b05002" },
          ],
        },
        {
          type: "table",
          caption: "The five core Bay Area counties",
          columns: ["County", "Residents, July 1, 2025", "Hispanic or Latino", "Non-Hispanic Asian", "Speak a language other than English at home, 2024", "Largest non-English language, 2024"],
          rows: [
            ["San Francisco", "826,079", "17.3%", "35.6%", "43.9%", "Chinese, 16.5% of residents 5+"],
            ["San Mateo", "743,568", "25.2%", "33.4%", "46.1%", "Spanish, 17.5%"],
            ["Santa Clara", "1,914,391", "24.9%", "43.1%", "55.7%", "Spanish, 16.7%"],
            ["Alameda", "1,636,630", "23.8%", "35.4%", "48.2%", "Spanish, 17.5%"],
            ["Contra Costa", "1,170,070", "28.7%", "21.3%", "38.9%", "Spanish, 19.5%"],
          ],
          note: "Population Estimates Program, Vintage 2025, and American Community Survey 2024 1-year estimates. Shares are Bond's arithmetic.{{cite:census-co-2025,census-cc-2025,acs-c16001}}",
        },
        {
          type: "p",
          text: "The region is shrinking slightly. The five counties had 2.1% fewer residents in July 2025 than in April 2020, and San Francisco County 6.0% fewer, and the San Francisco-Oakland-Fremont and San Jose-Sunnyvale-Santa Clara metro areas had 4,630,041 and 1,984,473 residents in 2025.{{cite:census-co-2025,census-cbsa-2025}} Few people lack coverage: 2.8% of San Francisco residents and 3.8% in Santa Clara and Alameda counties were uninsured in 2024, against 8.2% nationally.{{cite:acs-c27001}}",
        },
        {
          type: "p",
          text: "Language is where Bay Area outreach plans differ from most US markets. In San Francisco, 56.6% of the county's 131,407 Chinese speakers report speaking English less than \"very well\". Santa Clara County has 123,953 Vietnamese speakers, 60.5% of them with limited English, and 64,537 Hindi speakers.{{cite:acs-b16001}} At California's HRSA-funded health centers in 2025, 39.02% of patients had limited English proficiency.{{cite:hrsa-ca}} Plan for Cantonese, Mandarin, Vietnamese, Tagalog and Spanish, and for translated consent forms. See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks and research sites work in the Bay Area?",
      blocks: [
        {
          type: "p",
          text: "Each organization's own website or registry listing, as of October 2026:",
        },
        {
          type: "ul",
          items: [
            "**Flourish Research** lists a Walnut Creek site.{{cite:flourish}} Diablo Clinical Research, at the same address, says it is now part of the Flourish network as Flourish Research – Walnut Creek and was established in 1995.{{cite:diablo}}",
            "**Kaiser Permanente NCORP**, part of NCI's Community Oncology Research Program, lists affiliates at Kaiser medical centers in Oakland, San Francisco, South San Francisco, Santa Clara, San Jose (Santa Teresa), Walnut Creek and other Bay Area cities.{{cite:ncorp}} See [oncology](/oncology).",
            "**Western States Cancer Research NCORP** lists Contra Costa Regional Medical Center as an affiliate.{{cite:ncorp}}",
            "**Independent and practice sites** that appear on location records for recruiting studies in the radius include Sunwise Clinical Research, San Francisco Research Institute, Alethios, Center for Dermatology Clinical Research, Bay Area Tumor Institute and BASS Medical Group.{{cite:ctgov-locations}}",
          ],
        },
        {
          type: "p",
          text: "Bond is a CRIO Certified Partner.{{cite:bond-site}} See [research sites](/for/research-sites), [site networks](/for/site-networks) and [physician groups](/for/physician-groups).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which California laws apply to AI outreach, calls and patient records?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how several apply to pre-screening is untested. This is the status as of October 2026 and a map for your counsel, not legal advice.",
        },
        {
          type: "ul",
          items: [
            "**AI-generated patient messages (AB 3030, Health and Safety Code 1339.75).** Since January 1, 2025, a health facility, clinic, physician's office or group practice office that uses generative AI for written or verbal patient communications about patient clinical information must include a disclaimer that the communication was AI-generated and clear instructions for reaching a human. On calls, the disclaimer is spoken at the start and the end; in chat, it stays on screen throughout. It does not apply when a licensed or certified provider reads and reviews the message, and appointment scheduling, billing and other clerical matters are excluded.{{cite:ca-hsc-1339-75}} Health-status questions in a pre-screen may count as clinical information.",
            "**AI and licensed titles (AB 489).** Since January 1, 2026, AI systems may not use terms, letters or phrases in their advertising or functionality that imply their advice or assessments come from a licensed health professional, and each use is a separate violation.{{cite:ca-ab489}}",
            "**Robocall devices (Public Utilities Code 2871 to 2876).** Calls placed with an automatic dialing-announcing device need a live, natural-voice introduction that asks whether the person consents to hear the prerecorded message and, since January 1, 2025, says whether it uses an artificial voice. These calls are barred between 9 p.m. and 9 a.m.{{cite:ca-puc-2874,ca-puc-2872}} Whether the definition, built around a prerecorded message, reaches a conversational AI agent is untested. Federal rules apply either way; see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026).",
            "**Online bots (Business and Professions Code 17940 to 17943).** Since July 1, 2019, using an online bot to mislead someone about its artificial identity in order to drive a sale or influence a vote has been unlawful; disclosing the bot avoids liability.{{cite:ca-bpc-17941}}",
            "**Call recording (Penal Code 632 and 637.2).** Recording a confidential call needs every party's consent. Criminal fines reach $2,500 per violation, and an injured person can sue for $5,000 per violation or three times actual damages.{{cite:ca-pen-632,ca-pen-637-2}}",
            "**Medical records (Civil Code 56.10 and 56.36).** Under the Confidentiality of Medical Information Act, a provider needs the patient's authorization to disclose medical information unless an exception applies, including disclosure to clinical investigators and research organizations for bona fide research purposes without further identifying disclosure. Negligent release can bring $1,000 in nominal damages plus actual damages, and fines or civil penalties up to $2,500 per violation.{{cite:ca-civ-56-10,ca-civ-56-36}} See [preparatory to research](/glossary/preparatory-to-research).",
            "**Consumer privacy (Civil Code 1798.146).** The CCPA excludes CMIA medical information, protected health information held by HIPAA covered entities and business associates, and information collected, used or disclosed in research, including clinical trials, conducted under HIPAA, the Common Rule, ICH good clinical practice or FDA rules.{{cite:ca-civ-1798-146}} Ask counsel how ad-lead forms collected before screening are covered.",
            "**Research consent (Health and Safety Code 24172 and 24178).** Investigators at institutions with a federal human-subjects assurance who follow federal consent rules are exempt from most of California's medical experimentation statute, but the experimental subject's bill of rights, in a language the subject is fluent in, still applies.{{cite:ca-hsc-24178,ca-hsc-24172}}",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI is being used, and patients can reach a person at any time, by live transfer to a coordinator or a callback.{{cite:bond-site,bond-product}} For a California site, have counsel decide whether AB 3030 reaches pre-screening, and have the IRB approve the disclosure wording and when it plays.",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Bay Area site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration typically takes 48 hours, depending on the EHR, IT review and interface method.{{cite:bond-site}} See [implementation](/implementation) for the step-by-step plan.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Agree scope and paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path for screening records.{{cite:bond-site}} Settle the AI disclosure wording, recording notice and calling hours before launch.",
            },
            {
              title: "Connect the EHR",
              text: "Most Bay Area systems run Epic, so a site usually connects through Epic's FHIR APIs after IT review. Others use HL7 or an aggregator.",
            },
            {
              title: "Check criteria before outreach",
              text: "Coordinators review the chart evidence behind each criterion on sample matches before any patient is contacted. See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Run ads, reach out and book",
              text: "Bond creates and runs Meta and Google ad campaigns for each study, paid from the site's own ad budget. Its voice and text agents contact every new lead immediately, keep following up with those who have not responded, work in the patient's language and can switch languages mid-call. Pre-screened patients are booked straight into the site's calendar, with reminders by text, voice or email.{{cite:bond-site,bond-product}}",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting in the San Francisco Bay Area?",
      a: "A ClinicalTrials.gov radius search on October 5, 2026 found 2,270 recruiting studies with a site within 40 miles of San Mateo, covering San Francisco, Oakland and San Jose; 803 of them matched an oncology keyword search.{{cite:ctgov-api}}",
    },
    {
      q: "Which EHR do most Bay Area health systems use?",
      a: "Epic. UCSF Health, Stanford Health Care, Kaiser Permanente Northern California, Sutter Health and several county systems appear in Epic's FHIR endpoint directory.{{cite:epic-endpoints}}",
    },
    {
      q: "Does California require patients to be told when AI is used?",
      a: "For generative AI communications about patient clinical information from a health facility, clinic or physician's office, yes, since January 1, 2025, unless a licensed provider reads and reviews them first.{{cite:ca-hsc-1339-75}} Bond's agents tell patients that AI is used either way.{{cite:bond-site}}",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2: recruiting studies within 40 miles of San Mateo, covering San Francisco, Oakland and San Jose",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?filter.geo=distance(37.5630,-122.3255,40mi)&filter.overallStatus=RECRUITING&countTotal=true&pageSize=1",
      year: "2026",
      note: "Radius search queried October 5, 2026: filter.geo distance(37.5630,-122.3255,40mi), overall status Recruiting; \"totalCount\": 2270. Area counts add a query.cond keyword search (oncology: cancer OR neoplasm OR carcinoma OR lymphoma OR leukemia; obesity: obesity OR overweight OR type 2 diabetes) and returned oncology 803; cardiology 320; neurology 113; obesity and type 2 diabetes 61; dermatology 42. US totals from query.locn=United States the same day: all 22,007; oncology 7,064; cardiology 2,826; neurology 985; obesity 855; dermatology 212. Shares are Bond's arithmetic.",
    },
    {
      id: "ctgov-locations",
      title: "ClinicalTrials.gov API v2: location records for recruiting studies within 40 miles of San Mateo",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?filter.geo=distance(37.5630,-122.3255,40mi)&filter.overallStatus=RECRUITING&fields=NCTId,LocationFacility,LocationCity,LocationGeoPoint&pageSize=1000",
      year: "2026",
      note: "Queried October 5, 2026; Bond listed the facility names on location records inside the radius. Facility names as they appear: \"Sutter Cancer Research Consortium\"; \"Palo Alto Medical Foundation Health Care\"; \"Sunwise Clinical Research\"; \"San Francisco Research Institute\"; \"Alethios, Inc.\"; \"Center For Dermatology Clinical Research, Inc.\"; \"Bay Area Tumor Institute\"; \"BASS Medical Group - Lennon\".",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Read October 5, 2026. California entries include \"Stanford Cancer Institute (SCI), Stanford University, Stanford, California\"; \"UCSF Helen Diller Family Comprehensive Cancer Center, University of California at San Francisco, San Francisco, California\"; \"UC Davis Comprehensive Cancer Center, University of California at Davis, Sacramento, California\", each a \"Comprehensive Cancer Center\".",
    },
    {
      id: "nia-adrc",
      title: "Alzheimer's Disease Research Centers",
      publisher: "National Institute on Aging, NIH",
      url: "https://www.nia.nih.gov/health/clinical-trials-and-studies/alzheimers-disease-research-centers",
      year: "2026",
      note: "Read October 5, 2026. California entries include \"Stanford Alzheimer’s Disease Research Center 213 Quarry Road Palo Alto, CA 94305\" and \"University of California, San Francisco ... Alzheimer's Disease Research Center ... University of California, San Francisco Memory and Aging Center 675 Nelson Rising Lane, Suite 190 San Francisco, CA 94143\".",
    },
    {
      id: "ucsf-ctsi",
      title: "About Us",
      publisher: "UCSF Clinical and Translational Science Institute",
      url: "https://ctsi.ucsf.edu/about-us",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"The UCSF Clinical and Translational Science Institute (CTSI) is part of the Clinical and Translational Science Award (CTSA) program funded by the National Center for Advancing Translational Sciences (NCATS) at the National Institutes of Health (NIH) (Grant Number UL1 TR001872).\"",
    },
    {
      id: "stanford-spectrum",
      title: "Spectrum",
      publisher: "Stanford Medicine",
      url: "https://med.stanford.edu/spectrum",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Spectrum – Stanford Center for Clinical & Translational Research & Education\" and \"Supported by the NIH, we’re here to help improve the quality, speed, and impact of researchers working to get more treatments to more patients.\"",
    },
    {
      id: "kp-facts",
      title: "Fast Facts",
      publisher: "Kaiser Permanente",
      url: "https://about.kaiserpermanente.org/who-we-are/fast-facts",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Kaiser Permanente in Northern California, headquartered in Oakland, comprises: Kaiser Foundation Health Plan, Inc. Kaiser Foundation Hospitals The Permanente Medical Group\"; regional figures \"Members 4.7M\", \"Physicians 9,976\", \"Hospitals 21\". Footnotes: \"Data as of June 30, 2026, unless otherwise noted\"; physician counts \"Approximate as of December 31, 2025\".",
    },
    {
      id: "ncorp",
      title: "NCORP Sites (Find a Site)",
      publisher: "National Cancer Institute, NCI Community Oncology Research Program",
      url: "https://ncorp.cancer.gov/findasite/?state=California",
      year: "2026",
      note: "Read October 5, 2026; the page carried a notice that \"Because of a lapse in government funding, the information on this website may not be up to date\". Quote: \"Kaiser Permanente NCORP\" with \"Site Address: Oakland, California\"; affiliates include \"Kaiser Permanente - Oakland\", \"Kaiser Permanente - San Francisco\", \"Kaiser Permanente - South San Francisco\", \"Kaiser Permanente Medical Center - Santa Clara\", \"Kaiser Permanente - Santa Teresa - San Jose\" and \"Kaiser Permanente - Walnut Creek\". \"Western States Cancer Research NCORP\" lists affiliate \"Contra Costa Regional Medical Center\".",
    },
    {
      id: "sutter-about",
      title: "About Us",
      publisher: "Sutter Health",
      url: "https://www.sutterhealth.org/about-us",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Our hospitals Alta Bates Summit Medical Center California Pacific Medical Center Sutter Eden Medical Center\" (list continues).",
    },
    {
      id: "ucsf-care",
      title: "CARE Registry for Asian Americans, Native Hawaiians, and Pacific Islanders",
      publisher: "University of California, San Francisco",
      url: "https://careregistry.ucsf.edu/",
      year: "2026",
      note: "Read October 5, 2026. Quote: eligibility includes being \"Able to read or speak one of the following languages: English, Cantonese, Mandarin, Hindi, Japanese, Korean, Samoan, Tagalog, or Vietnamese\" and \"Willing to be contacted to participate in health research\"; \"CARE is actively supporting participation from AANHPI communities in health research.\"",
    },
    {
      id: "stanford-care",
      title: "Center for Asian Health Research and Education (CARE)",
      publisher: "Stanford Medicine",
      url: "https://asianhealth.stanford.edu/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Our mission is clear: to predict, prevent, and cure diseases disproportionately affecting Asian communities.\"",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Downloaded October 5, 2026 (bundle \"total\": 479). Endpoint organization names include \"UCSF Health\"; \"UCSF Benioff Children's Hospital\"; \"Stanford Health Care\"; \"Stanford Children's Health\"; \"Kaiser Permanente - California - Northern\"; \"Sutter Health\"; \"John Muir Health\"; \"El Camino Hospital\"; \"San Francisco Department of Public Health\"; \"Santa Clara Valley Medical Center Hospitals and Clinics\"; \"Alameda Health System\"; \"Contra Costa\"; \"County of San Mateo\", each with status \"active\". A listing shows an Epic FHIR endpoint, not every system an organization runs.",
    },
    {
      id: "oracle-endpoints",
      title: "Oracle Health Millennium patient R4 FHIR endpoints (millennium_patient_r4_endpoints.json)",
      publisher: "Oracle (oracle-samples/ignite-endpoints on GitHub)",
      url: "https://raw.githubusercontent.com/oracle-samples/ignite-endpoints/main/oracle_health_fhir_endpoints/millennium_patient_r4_endpoints.json",
      year: "2026",
      note: "Downloaded October 5, 2026. Organization entries \"CommonSpirit Health\" (city \"San Francisco\", state \"CA\"); \"Dignity Health CAREB\" (\"San Francisco\"); \"Chinese Hospital\" (\"San Francisco\"). A listing shows a Millennium FHIR endpoint, not every system the organization runs.",
    },
    {
      id: "hrsa-ca",
      title: "California Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/CA",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Total Number of Reporting Program Awardees: 170 Reporting Period: 2025 Total Patients Served: 5,900,539\". Five-year table, 2025 column: \"Limited English Proficiency\" 39.02% (2,302,159 patients).",
    },
    {
      id: "census-co-2025",
      title: "County Population Totals: April 1, 2020 to July 1, 2025 (CO-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/totals/co-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. POPESTIMATE2025: San Francisco County 826,079 (ESTIMATESBASE2020 878,550); San Mateo County 743,568; Santa Clara County 1,914,391; Alameda County 1,636,630; Contra Costa County 1,170,070. ESTIMATESBASE2020: San Mateo 764,508; Santa Clara 1,936,274; Alameda 1,682,246; Contra Costa 1,166,035. The five-county totals (6,427,613 in 2020 and 6,290,738 in 2025, a 2.1% decline) and San Francisco's 6.0% decline are Bond's arithmetic.",
    },
    {
      id: "census-cc-2025",
      title: "Annual County Resident Population Estimates by Age, Sex, Race, and Hispanic Origin: April 1, 2020 to July 1, 2025 (CC-EST2025-ALLDATA-06)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/asrh/cc-est2025-alldata-06.csv",
      year: "2026",
      note: "Downloaded October 5, 2026 and summed by Bond, YEAR 7 (\"7 = 7/1/2025 population estimate\"), all ages. Hispanic and not-Hispanic Asian alone: San Francisco 142,522 and 293,677; San Mateo 187,277 and 248,721; Santa Clara 476,396 and 825,748; Alameda 390,152 and 579,642; Contra Costa 335,538 and 248,988. Five-county not-Hispanic Asian alone: 2,196,776 of 6,290,738 (34.9%).",
    },
    {
      id: "census-cbsa-2025",
      title: "Metropolitan and Micropolitan Statistical Area Population Totals: April 1, 2020 to July 1, 2025 (CBSA-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/metro/totals/cbsa-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. POPESTIMATE2025: CBSA 41860 \"San Francisco-Oakland-Fremont, CA\" 4,630,041; CBSA 41940 \"San Jose-Sunnyvale-Santa Clara, CA\" 1,984,473.",
    },
    {
      id: "acs-c16001",
      title: "American Community Survey 2024 1-year estimates, table C16001: Language Spoken at Home for the Population 5 Years and Over",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-c16001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. C16001_E001 \"Total:\" and C16001_E002 \"Speak only English\": San Francisco 795,144 and 446,434; San Mateo 705,462 and 380,207; Santa Clara 1,832,328 and 810,961; Alameda 1,566,092 and 811,956; Contra Costa 1,111,236 and 679,163. Five-county share speaking another language, 2,881,541 of 6,010,262 (47.9%), is Bond's arithmetic. Spanish (C16001_E003): San Mateo 123,586; Santa Clara 305,493; Alameda 274,802; Contra Costa 216,564. Chinese (C16001_E021): San Francisco 131,407.",
    },
    {
      id: "acs-b16001",
      title: "American Community Survey 2024 1-year estimates, table B16001: Language Spoken at Home by Ability to Speak English for the Population 5 Years and Over",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-b16001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. Speakers and those who speak English less than \"very well\": San Francisco, Chinese (incl. Mandarin, Cantonese) 131,407 and 74,357; Santa Clara, Vietnamese 123,953 and 75,021; Santa Clara, Hindi 64,537. Percentages are Bond's arithmetic.",
    },
    {
      id: "acs-b05002",
      title: "American Community Survey 2024 1-year estimates, table B05002: Place of Birth by Nativity and Citizenship Status",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-b05002.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. B05002_E013 \"Foreign-born:\" and B05002_E001 \"Total:\": San Francisco 283,085 of 827,526; San Mateo 264,655 of 742,893; Santa Clara 811,040 of 1,926,325; Alameda 584,328 of 1,649,060; Contra Costa 324,002 of 1,172,607. Five-county total 2,267,110 of 6,318,411 (35.9%, Bond's arithmetic).",
    },
    {
      id: "acs-c27001",
      title: "American Community Survey 2024 1-year estimates, table C27001: Health Insurance Coverage Status by Age",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-c27001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026 and summed by Bond across the \"No health insurance coverage\" lines: San Francisco 23,323 of 823,851 (2.8%); Santa Clara 72,481 of 1,916,065 (3.8%); Alameda 61,830 of 1,638,526 (3.8%); United States 27,479,253 of 335,190,522 (8.2%).",
    },
    {
      id: "flourish",
      title: "Clinical Trial Site Locations",
      publisher: "Flourish Research",
      url: "https://flourishresearch.com/locations/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Medical Trials in Walnut Creek 2255 Ygnacio Valley Rd m, Walnut Creek, CA 94598, USA\".",
    },
    {
      id: "diablo",
      title: "Diablo Clinical Research",
      publisher: "Diablo Clinical Research (Flourish Research – Walnut Creek)",
      url: "https://diabloclinical.com/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"We are excited to announce we’re now part of the Flourish Research Network, we’re now known as Flourish Research – Walnut Creek.\" Also: \"Established in 1995\" and \"2255 Ygnacio Valley Road, Suite M Walnut Creek, CA 94598\".",
    },
    {
      id: "ca-hsc-1339-75",
      title: "Health and Safety Code 1339.75 (added by AB 3030, Stats. 2024, Ch. 848)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=HSC&sectionNum=1339.75",
      year: "2024",
      note: "Read October 5, 2026. Quote: \"For audio communications, the disclaimer shall be provided verbally at the start and the end of the interaction.\" Also: \"If a communication is generated by generative artificial intelligence and read and reviewed by a human licensed or certified health care provider, the requirements of subdivision (a) do not apply.\" Patient clinical information \"does not include administrative matters, including, but not limited to, appointment scheduling, billing, or other clerical or business matters.\" History: \"(Added by Stats. 2024, Ch. 848, Sec. 1. (AB 3030) Effective January 1, 2025.)\"",
    },
    {
      id: "ca-ab489",
      title: "AB-489 Health care professions: deceptive terms or letters: artificial intelligence (Chapter 615, Statutes of 2025)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/billNavClient.xhtml?bill_id=202520260AB489",
      year: "2025",
      note: "Read October 5, 2026. \"Approved by Governor October 11, 2025.\" Business and Professions Code 4999.9(c): \"The use of a term, letter, or phrase in the advertising or functionality of an AI or GenAI system, program, device, or similar technology that indicates or implies that the care, advice, reports, or assessments being offered through the AI or GenAI technology is being provided by a natural person in possession of the appropriate license or certificate to practice as a health care professional, is prohibited.\" 4999.9(d): \"Each use of a prohibited term, letter, or phrase shall constitute a separate violation of this chapter.\" The code section history reads \"(Added by Stats. 2025, Ch. 615, Sec. 1. (AB 489) Effective January 1, 2026.)\"",
    },
    {
      id: "ca-puc-2874",
      title: "Public Utilities Code 2874 (amended by AB 2905, Stats. 2024, Ch. 316)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PUC&sectionNum=2874",
      year: "2024",
      note: "Read October 5, 2026. Quote: \"the device may be operated only after an unrecorded, natural voice announcement has been made to the person called by the person calling\"; the announcement must \"Inquire as to whether the person called consents to hear the prerecorded message of the person calling\" and \"Inform the person called if the prerecorded message uses an artificial voice.\" History: \"(Amended by Stats. 2024, Ch. 316, Sec. 1. (AB 2905) Effective January 1, 2025.)\" Section 2871 defines the device as equipment with \"the capability ... to disseminate a prerecorded message to the telephone number called.\"",
    },
    {
      id: "ca-puc-2872",
      title: "Public Utilities Code 2872",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PUC&sectionNum=2872",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"A person shall not operate an automatic dialing-announcing device in this state to place a call that is received by a telephone in this state during the hours between 9 p.m. and 9 a.m. California time.\"",
    },
    {
      id: "ca-bpc-17941",
      title: "Business and Professions Code 17941 (SB 1001, Stats. 2018, Ch. 892)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=17941",
      year: "2018",
      note: "Read October 5, 2026. Quote: \"It shall be unlawful for any person to use a bot to communicate or interact with another person in California online, with the intent to mislead the other person about its artificial identity for the purpose of knowingly deceiving the person about the content of the communication in order to incentivize a purchase or sale of goods or services in a commercial transaction or to influence a vote in an election. A person using a bot shall not be liable under this section if the person discloses that it is a bot.\" History: \"Operative July 1, 2019, pursuant to Section 17943.\"",
    },
    {
      id: "ca-pen-632",
      title: "Penal Code 632",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PEN&sectionNum=632",
      year: "2016",
      note: "Read October 5, 2026. Quote: \"A person who, intentionally and without the consent of all parties to a confidential communication, uses an electronic amplifying or recording device to eavesdrop upon or record the confidential communication ... shall be punished by a fine not exceeding two thousand five hundred dollars ($2,500) per violation\".",
    },
    {
      id: "ca-pen-637-2",
      title: "Penal Code 637.2",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=PEN&sectionNum=637.2",
      year: "2016",
      note: "Read October 5, 2026. Quote: \"Any person who has been injured by a violation of this chapter may bring an action against the person who committed the violation for the greater of the following amounts: (1) Five thousand dollars ($5,000) per violation. (2) Three times the amount of actual damages, if any, sustained by the plaintiff.\" SB 690 (Chapter 976, Statutes of 2026, approved September 30, 2026) amends this section so that only the Attorney General can sue private actors over pen-register claims arising on websites and apps; it does not change the remedy for recorded calls.",
    },
    {
      id: "ca-civ-56-10",
      title: "Civil Code 56.10 (Confidentiality of Medical Information Act)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=56.10",
      year: "2026",
      note: "Read October 5, 2026. Quote, 56.10(c)(7): \"The information may be disclosed to public agencies, clinical investigators, including investigators conducting epidemiologic studies, health care research organizations, and accredited public or private nonprofit educational or health care institutions for bona fide research purposes. However, no information so disclosed shall be further disclosed by the recipient in a way that would disclose the identity of a patient or violate this part.\"",
    },
    {
      id: "ca-civ-56-36",
      title: "Civil Code 56.36 (Confidentiality of Medical Information Act)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=56.36",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"nominal damages of one thousand dollars ($1,000)\" and a person or entity that negligently discloses medical information is liable \"for an administrative fine or civil penalty not to exceed two thousand five hundred dollars ($2,500) per violation.\"",
    },
    {
      id: "ca-civ-1798-146",
      title: "Civil Code 1798.146 (California Consumer Privacy Act)",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=1798.146",
      year: "2026",
      note: "Read October 5, 2026. Quote, 1798.146(a)(5): \"Information that is collected, used, or disclosed in research, as defined in Section 164.501 of Title 45 of the Code of Federal Regulations, including, but not limited to, a clinical trial, and that is conducted in accordance with applicable ethics, confidentiality, privacy, and security rules of Part 164 of Title 45 of the Code of Federal Regulations, the Federal Policy for the Protection of Human Subjects, also known as the Common Rule, good clinical practice guidelines issued by the International Council for Harmonisation, or human subject protection requirements of the United States Food and Drug Administration.\"",
    },
    {
      id: "ca-hsc-24178",
      title: "Health and Safety Code 24178",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=HSC&sectionNum=24178",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Except for this section and the requirements set forth in Sections 24172 and 24176, this chapter shall not apply to any person who is conducting a medical experiment as an investigator within an institution that holds an assurance with the United States Department of Health and Human Services pursuant to Part 46 of Title 45 of the Code of Federal Regulations and who obtains informed consent in the method and manner required by those regulations.\"",
    },
    {
      id: "ca-hsc-24172",
      title: "Health and Safety Code 24172",
      publisher: "California Legislative Information",
      url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=HSC&sectionNum=24172",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"“experimental subject’s bill of rights,” means a list of the rights of a subject in a medical experiment, written in a language in which the subject is fluent.\"",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, October 2026.",
    },
  ],
  related: [
    { label: "All locations", href: "/clinical-trial-recruitment", description: "Registry counts and outreach rules for other states and regions." },
    { label: "Bond for research sites", href: "/for/research-sites", description: "How screening, outreach and booked visits fit a site's coordinators." },
    { label: "Epic integration", href: "/integrations/epic", description: "How Bond connects to the EHR most Bay Area systems run." },
    { label: "Oncology", href: "/oncology", description: "How Bond screens for cancer trials, the area's largest category by count." },
    { label: "FQHCs and community sites", href: "/for/fqhcs-and-community-sites", description: "Reaching patients at community health centers." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
  ],
};

export default page;
