import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/seattle",
  category: "geography",
  title: "Seattle clinical trial recruitment for research sites",
  description:
    "For Seattle area research sites: recruiting-trial counts, research hubs, health system EHRs, languages and the Washington rules on health data and outreach.",
  keywords: [
    "clinical trial recruitment Seattle",
    "Seattle research sites",
    "clinical trials Seattle Bellevue Everett",
    "My Health My Data Act clinical trials",
    "Seattle health system EHRs",
  ],
  eyebrow: "By location",
  h1: "Recruiting for clinical trials in the Seattle area",
  intro:
    "On October 5, 2026, a ClinicalTrials.gov radius search found 1,475 recruiting studies with at least one site within 25 miles of downtown Seattle, about 6.7% of the 22,007 recruiting in the United States that day.{{cite:ctgov-api}} This page is for research sites across King County and the rest of the Puget Sound area: where the research hubs are, which EHRs hold the patients, who lives here, and which Washington rules shape AI-assisted outreach.",
  summary: "Seattle area recruiting-trial counts, research hubs, health systems and their EHRs, languages, and Washington health data and outreach rules.",
  lastUpdated: "2026-10-05",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in the Seattle area?",
      blocks: [
        {
          type: "p",
          text: "Cancer dominates. 687 of the 1,475 studies matched an oncology keyword search, 46.6% of the local total and 9.7% of the 7,064 recruiting oncology studies in the US. Seattle's share of US studies is highest in gastroenterology (50 of 283) and lowest in psychiatry (57 of 1,275).{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "seattle", cite: "ctgov-api" },
        {
          type: "p",
          text: "A radius count includes every recruiting study with at least one location inside the circle, so a study with sites in Seattle and Bellevue counts once. Area counts come from keyword searches, overlap, and can pull in off-target studies, and a count shows where sponsors placed studies, not which ones enroll on schedule. The oncology examples below come from the same October 5, 2026 query.{{cite:ctgov-api}} See [oncology](/oncology).",
        },
        { type: "trials", geo: "seattle", condition: "oncology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are the Seattle area's research hubs?",
      blocks: [
        {
          type: "table",
          caption: "Seattle area research hubs and what their anchor institutions report, as of October 2026",
          columns: ["Focus", "Anchor institutions", "What they report"],
          rows: [
            [
              "Cancer",
              "Fred Hutchinson Cancer Center, the University of Washington and Seattle Children's, listed by NCI as one comprehensive cancer center consortium{{cite:nci-centers}}",
              "Fred Hutch describes itself as an independent nonprofit that serves as UW Medicine's cancer program and the only NCI-designated comprehensive cancer center in Washington{{cite:fred-hutch}}",
            ],
            [
              "Translational science",
              "Institute of Translational Health Sciences (ITHS), a partnership of the University of Washington, Fred Hutch and Seattle Children's{{cite:iths}}",
              "More than 6,500 researchers from over 220 organizations across Washington, Wyoming, Alaska, Montana and Idaho have worked with ITHS{{cite:iths}}",
            ],
            [
              "Memory",
              "UW Alzheimer's Disease Research Center, based at Harborview Medical Center{{cite:nia-adrc}}",
              "Seattle also hosts the National Alzheimer's Coordinating Center, which coordinates data collection among the NIA-funded centers{{cite:nia-adrc}}",
            ],
            [
              "Immune disease",
              "Benaroya Research Institute at Virginia Mason{{cite:ctgov-locations}}",
              "Its BRIAR autoimmune registry connects volunteers with studies that match their interests, health history and eligibility{{cite:bri}}",
            ],
            [
              "Integrated care",
              "Kaiser Permanente Washington and its Health Research Institute{{cite:kpwhri}}",
              "562,812 members as of June 30, 2026{{cite:kp-facts}}",
            ],
          ],
        },
        {
          type: "ul",
          items: [
            "**Cancer.** Fred Hutch says it was the first NCI-designated comprehensive cancer center in the Pacific Northwest.{{cite:fred-hutch}} Swedish Cancer Institute and Swedish Medical Center campuses in Seattle, Edmonds and Issaquah are affiliates of the Seattle-based Pacific Cancer Research Consortium NCORP, part of NCI's community oncology program.{{cite:ncorp}}",
            "**Memory.** The UW ADRC is one of the National Institute on Aging's Alzheimer's Disease Research Centers.{{cite:nia-adrc}} See [neurology and Alzheimer's](/neurology-and-alzheimers).",
            "**Regional reach.** ITHS serves the five-state WWAMI region, so a Seattle study can draw on investigators and community partners well beyond King County.{{cite:iths}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which EHRs do Seattle area health systems run?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Seattle area health systems, from vendor FHIR endpoint directories and system websites, October 2026",
          columns: ["System", "Footprint", "EHR"],
          rows: [
            [
              "UW Medicine",
              "Academic system; Fred Hutch serves as its cancer program{{cite:fred-hutch}}",
              "Epic, listed as \"UW Medicine (Washington)\"; Valley Medical Center is listed separately{{cite:epic-endpoints}}",
            ],
            [
              "Providence Swedish",
              "Swedish campuses on First Hill, Cherry Hill and Ballard and in Edmonds and Issaquah are NCORP affiliates{{cite:ncorp}}",
              "Epic: Providence's Washington/Montana endpoint is in Epic's directory, and Swedish points patients to the Providence MyChart app{{cite:epic-endpoints,swedish}}",
            ],
            [
              "Virginia Mason Franciscan Health",
              "Health system; Benaroya Research Institute at Virginia Mason appears on location records for recruiting studies in the radius{{cite:ctgov-locations}}",
              "Epic, listed as \"Virginia Mason Franciscan Health\"{{cite:epic-endpoints}}. Oracle's directory also lists \"VIRGINIA MASON MEDICAL CENTER\"{{cite:oracle-endpoints}}, so confirm which system holds the records you need",
            ],
            ["Kaiser Permanente Washington", "562,812 members and 31 medical offices{{cite:kp-facts}}", "Epic, listed as \"Kaiser Permanente - Washington\"{{cite:epic-endpoints}}"],
            ["Seattle Children's", "Pediatric academic center and ITHS partner{{cite:iths}}", "Epic, listed as \"Seattle Children's Hospital\"{{cite:epic-endpoints}}"],
            ["MultiCare, Overlake and EvergreenHealth", "Regional and community hospital systems", "Epic{{cite:epic-endpoints}}"],
            [
              "Community health centers",
              "27 HRSA-funded awardees statewide served 1,294,656 patients in 2025{{cite:hrsa-wa}}",
              "Varies by center",
            ],
          ],
          note: "A directory listing shows a FHIR endpoint, not every system an organization runs. Confirm with the site's IT team.",
        },
        {
          type: "p",
          text: "Seattle is close to an all-Epic market: UW Medicine, Providence, Kaiser, Seattle Children's, MultiCare, Overlake and EvergreenHealth all appear in Epic's directory.{{cite:epic-endpoints}} A study across several systems can often reuse one FHIR approach, though each system runs its own IT, privacy and research review. Bond connects to Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm, OncoEMR and other major EHRs through FHIR, HL7 or an aggregator.{{cite:bond-site,bond-product}} See [Epic](/integrations/epic).",
        },
        {
          type: "p",
          text: "Bond's screening reads clinical notes, prescriptions, lab results, imaging data and pathology, radiology and molecular reports, and shows criterion-by-criterion evidence for every match.{{cite:bond-product}} That matters in oncology, where stage, prior lines of therapy and biomarkers often sit only in reports. See [Identify](/identify).",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in the Seattle area, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "2.34 million", label: "King County residents on July 1, 2025, up 3.3% since April 2020", cite: "census-co-2025" },
            { value: "23.8%", label: "Non-Hispanic Asian, King County, 2025", cite: "census-cc-2025" },
            { value: "33.0%", label: "Residents 5 and older who speak a language other than English at home, 2024", cite: "acs-c16001" },
            { value: "27.1%", label: "Born outside the United States, 2024", cite: "acs-b05002" },
          ],
        },
        {
          type: "p",
          text: "The Seattle-Tacoma-Bellevue metro area had 4,161,883 residents on July 1, 2025, up 3.6% from April 2020, while the Los Angeles and San Francisco metros shrank.{{cite:census-cbsa-2025}} In King County that year, 11.7% of residents were Hispanic or Latino, 6.9% non-Hispanic Black, and 15.2% were 65 or older.{{cite:census-cc-2025}} In 2024, 5.3% of King County residents had no health insurance, against 8.2% nationally.{{cite:acs-c27001}}",
        },
        {
          type: "table",
          caption: "Most common languages spoken at home, King County residents 5 and older, 2024",
          columns: ["Language", "Speakers", "Share of residents 5+", "Speak English less than \"very well\""],
          rows: [
            ["Spanish", "159,850", "7.2%", "65,477"],
            ["Chinese (incl. Mandarin, Cantonese)", "127,380", "5.7%", "52,738"],
            ["Vietnamese", "43,645", "2.0%", "25,842"],
            ["Hindi", "35,583", "1.6%", "3,334"],
            ["Korean", "30,953", "1.4%", "14,559"],
            ["Amharic, Somali or other Afro-Asiatic languages", "29,282", "1.3%", "11,960"],
            ["Russian", "26,971", "1.2%", "9,265"],
            ["Tagalog (incl. Filipino)", "26,572", "1.2%", "9,078"],
          ],
          note: "American Community Survey 1-year estimates, table B16001. Shares are Bond's arithmetic.{{cite:acs-b16001}}",
        },
        {
          type: "p",
          text: "No single second language dominates: Spanish, the most common, is spoken at home by 7.2% of King County residents 5 and older. The county's 269,941 residents who speak English less than \"very well\", 12.1% of those 5 and older, are spread across Spanish, Chinese, Vietnamese, Amharic, Somali, Russian and more.{{cite:acs-c16001,acs-b16001}} At Washington's HRSA-funded health centers in 2025, 37.07% of patients with known ethnicity were Hispanic or Latino and 27.98% had limited English proficiency.{{cite:hrsa-wa}} Plan language coverage and translated consent materials per study population. See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks and research sites work in the Seattle area?",
      blocks: [
        {
          type: "p",
          text: "Each organization's own website or registry listing, as of October 2026:",
        },
        {
          type: "ul",
          items: [
            "**Velocity Clinical Research** lists Washington sites in Seattle and Spokane.{{cite:velocity}}",
            "**Pacific Cancer Research Consortium NCORP**, based in Seattle, lists Swedish Cancer Institute and Swedish Medical Center campuses among its affiliates.{{cite:ncorp}}",
            "**Kaiser Permanente NCORP** lists Kaiser Permanente Bellevue Medical Center as an affiliate.{{cite:ncorp}}",
            "**Northwest Clinical Research Center**, a research site in Bellevue, says it has more than 30 years of experience.{{cite:nwcrc}}",
            "**Other independent and practice sites** that appear on location records for recruiting studies in the radius include Rainier Clinical Research Center, Seattle Clinical Research Center, Eastside Research Associates, Seattle Neuropsychiatric Treatment Center, Pacific Gynecology Specialists and Northwest Medical Specialties.{{cite:ctgov-locations}}",
          ],
        },
        {
          type: "p",
          text: "Bond is a CRIO Certified Partner.{{cite:bond-site}} See [research sites](/for/research-sites), [site networks](/for/site-networks) and [physician groups](/for/physician-groups).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which Washington laws apply to AI outreach, ads and patient data?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how several apply to pre-screening is untested. This is the status as of October 2026 and a map for your counsel, not legal advice.",
        },
        {
          type: "ul",
          items: [
            "**Consumer health data (My Health My Data Act, RCW 19.373).** Since March 31, 2024 (June 30, 2024 for small businesses), regulated entities may collect consumer health data only with consent for a specified purpose or as needed to provide a product or service the consumer asked for, and sharing needs a separate consent. A violation is an unfair or deceptive act under the state Consumer Protection Act.{{cite:wa-rcw-19-373-030,wa-rcw-19-373-090}} The law exempts HIPAA protected health information, health care information handled under RCW 70.02, and information used in research under the Common Rule, ICH good clinical practice or FDA human-subject rules.{{cite:wa-rcw-19-373-100}} Health details typed into an ad-lead form before anyone is screened may still count as consumer health data, so have counsel review lead forms and consent language.",
            "**Geofencing (RCW 19.373.080).** No one may set a geofence around a provider of in-person health care to identify or track people seeking care, collect their health data, or send them messages or ads about health care services. The statute defines a geofence as a virtual boundary 2,000 feet or less from the location's perimeter.{{cite:wa-rcw-19-373-080,wa-rcw-19-373-010}} Keep recruitment ad targeting away from clinic and hospital perimeters.",
            "**Health care information (RCW 70.02).** A provider may not disclose health care information without the patient's written authorization unless an exception applies. One exception covers research projects that an IRB has found important enough to outweigh the privacy intrusion, impracticable without identifiable data, and protected against redisclosure.{{cite:wa-rcw-70-02-020,wa-rcw-70-02-210}} See [waiver of authorization](/glossary/waiver-of-authorization).",
            "**Call recording (RCW 9.73.030).** Recording a private phone conversation needs the consent of all participants. Consent counts as obtained when one party announces the recording to everyone in a reasonably effective manner, and the announcement itself must be recorded.{{cite:wa-rcw-9-73-030}}",
            "**Commercial texts (RCW 19.190).** A business may not send commercial text messages, those that promote goods or services for sale or lease, to Washington cell numbers. Damages are $100 per message or actual damages, whichever is greater, under a 2026 amendment that applies to suits filed on or after June 11, 2026.{{cite:wa-rcw-19-190-060,wa-rcw-19-190-040}} A study invitation sells nothing, but have counsel confirm how your texts are worded.",
            "**Robocalls (RCW 80.36.400).** No one may use an automatic dialing and announcing device, a system that dials automatically and plays a recorded or artificial voice message, for commercial solicitation. An injured person can recover actual damages or $1,000 per violation, whichever is greater.{{cite:wa-rcw-80-36-400}} Federal rules apply either way; see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026).",
            "**AI companion chatbots (HB 2225, chapter 168, Laws of 2026).** From January 1, 2027, operators of AI companion chatbots must disclose that the chatbot is artificially generated and not human at the start of an interaction and at least every three hours. The law excludes bots used only for business operations, technical assistance or customer service that do not sustain a relationship across multiple interactions and generate emotionally engaging output.{{cite:wa-hb2225}} As of October 2026, no Washington statute we reviewed requires AI disclosure in patient outreach.",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI is being used, and patients can reach a person at any time, by live transfer to a coordinator or a callback.{{cite:bond-site,bond-product}} For a Washington site, settle the recording announcement, ad targeting and lead-form consent with counsel and the IRB before launch.",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Seattle site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration typically takes 48 hours, depending on the EHR, IT review and interface method.{{cite:bond-site}} See [implementation](/implementation) for the step-by-step plan.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Agree scope and paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path for screening records.{{cite:bond-site}} For Washington, add the recording announcement and the My Health My Data review of ad-lead forms.",
            },
            {
              title: "Connect the EHR",
              text: "Most Seattle systems run Epic, so a site usually connects through Epic's FHIR APIs after IT review. Others use HL7 or an aggregator.",
            },
            {
              title: "Check criteria before outreach",
              text: "Coordinators review the chart evidence behind each criterion on sample matches before any patient is contacted. See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Run ads, reach out and book",
              text: "Bond creates and runs Meta and Google ad campaigns for each study, paid from the site's own ad budget; in Washington, leave clinic geofences out of the targeting. Its voice and text agents contact every new lead immediately, keep following up with those who have not responded, work in the patient's language and can switch languages mid-call. Pre-screened patients are booked straight into the site's calendar, with reminders by text, voice or email.{{cite:bond-site,bond-product}}",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How many clinical trials are recruiting in the Seattle area?",
      a: "A ClinicalTrials.gov radius search on October 5, 2026 found 1,475 recruiting studies with a site within 25 miles of downtown Seattle, 687 of them matching an oncology keyword search.{{cite:ctgov-api}}",
    },
    {
      q: "Does Washington's My Health My Data Act apply to trial recruitment?",
      a: "It exempts HIPAA protected health information, health care information under RCW 70.02 and data used in research under the Common Rule, ICH good clinical practice or FDA rules, but consumer health data collected outside those, such as some ad-lead forms, may be covered.{{cite:wa-rcw-19-373-100}} It also bars geofences around in-person health care providers for health-related ads.{{cite:wa-rcw-19-373-080}}",
    },
    {
      q: "Does Washington require AI disclosure on recruitment calls?",
      a: "As of October 2026, no Washington statute we reviewed requires it. A companion-chatbot law takes effect January 1, 2027 and excludes many customer-service bots.{{cite:wa-hb2225}} Bond's agents tell patients that AI is used either way.{{cite:bond-site}}",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2: recruiting studies within 25 miles of downtown Seattle",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?filter.geo=distance(47.6062,-122.3321,25mi)&filter.overallStatus=RECRUITING&countTotal=true&pageSize=1",
      year: "2026",
      note: "Radius search queried October 5, 2026: filter.geo distance(47.6062,-122.3321,25mi), overall status Recruiting; \"totalCount\": 1475. Area counts add a query.cond keyword search (oncology: cancer OR neoplasm OR carcinoma OR lymphoma OR leukemia) and returned oncology 687; gastroenterology 50; psychiatry 57. US totals from query.locn=United States the same day: all 22,007; oncology 7,064; gastroenterology 283; psychiatry 1,275. Shares are Bond's arithmetic.",
    },
    {
      id: "ctgov-locations",
      title: "ClinicalTrials.gov API v2: location records for recruiting studies within 25 miles of downtown Seattle",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?filter.geo=distance(47.6062,-122.3321,25mi)&filter.overallStatus=RECRUITING&fields=NCTId,LocationFacility,LocationCity,LocationGeoPoint&pageSize=1000",
      year: "2026",
      note: "Queried October 5, 2026; Bond listed the facility names on location records inside the radius. Facility names as they appear: \"Benaroya Research Institute at Virginia Mason\"; \"Rainier Clinical Research Center\"; \"Seattle Clinical Research Center\"; \"Eastside Research Associates\"; \"Seattle Neuropsychiatric Treatment Center\"; \"Pacific Gynecology Specialists\"; \"Northwest Medical Specialties\".",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Read October 5, 2026. Washington entry: \"Fred Hutchinson/University of Washington/Seattle Children’s Cancer Consortium, Seattle, Washington\", \"Comprehensive Cancer Center\".",
    },
    {
      id: "fred-hutch",
      title: "Who We Are at Fred Hutch",
      publisher: "Fred Hutchinson Cancer Center",
      url: "https://www.fredhutch.org/en/about/about-the-hutch.html",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Fred Hutch is an independent, nonprofit organization that also serves as UW Medicine’s cancer program\" and \"Fred Hutch is proud to be the only National Cancer Institute (NCI)-designated comprehensive cancer center in Washington state and was the first in the Pacific Northwest.\"",
    },
    {
      id: "iths",
      title: "About ITHS",
      publisher: "Institute of Translational Health Sciences",
      url: "https://www.iths.org/about/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"The ITHS is a partnership between the University of Washington, Fred Hutchinson Cancer Center, and Seattle Children’s.\" and \"More than 6,500 researchers from over 220 different organizations across the five-state WWAMI region have collaborated with us\"; WWAMI is \"Washington, Wyoming, Alaska, Montana, Idaho\".",
    },
    {
      id: "nia-adrc",
      title: "Alzheimer's Disease Research Centers",
      publisher: "National Institute on Aging, NIH",
      url: "https://www.nia.nih.gov/health/clinical-trials-and-studies/alzheimers-disease-research-centers",
      year: "2026",
      note: "Read October 5, 2026. Washington entry: \"University of Washington Alzheimer's Disease Research Center Harborview Medical Center ... Seattle, WA 98104\". Also: \"National Alzheimer's Coordinating Center (NACC) The Center coordinates data collection and fosters collaborative research among ADRCs.\" at \"4311 11th Avenue NE, Suite 300 Seattle, WA 98105\".",
    },
    {
      id: "bri",
      title: "Join Our Research",
      publisher: "Benaroya Research Institute",
      url: "https://www.benaroyaresearch.org/join-our-research",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"The best way to get started is by joining the Benaroya Research Institute Autoimmune Registry (BRIAR). BRIAR connects volunteers with research opportunities that match their interests, health history and eligibility.\" The site navigation links to \"Clinical Research at VMMC\" (Virginia Mason Medical Center).",
    },
    {
      id: "kpwhri",
      title: "About Us",
      publisher: "Kaiser Permanente Washington Health Research Institute",
      url: "https://www.kpwashingtonresearch.org/about-us",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Kaiser Permanente Washington Health Research Institute improves health and well-being for our members and all communities through collaborative research and evaluation.\"",
    },
    {
      id: "kp-facts",
      title: "Fast Facts",
      publisher: "Kaiser Permanente",
      url: "https://about.kaiserpermanente.org/who-we-are/fast-facts",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Founded in 2017, Kaiser Permanente in Washington is headquartered in the Seattle metro area\"; regional figures \"Members 562,812\" and \"Medical offices 31\". Footnote: \"Data as of June 30, 2026, unless otherwise noted.\"",
    },
    {
      id: "ncorp",
      title: "NCORP Sites (Find a Site)",
      publisher: "National Cancer Institute, NCI Community Oncology Research Program",
      url: "https://ncorp.cancer.gov/findasite/?state=Washington",
      year: "2026",
      note: "Read October 5, 2026; the page carried a notice that \"Because of a lapse in government funding, the information on this website may not be up to date\". Quote: \"Pacific Cancer Research Consortium NCORP\" with \"Site Address: Seattle, Washington\"; affiliates include \"Swedish Cancer Institute - Edmonds\", \"Swedish Cancer Institute - Issaquah\", \"Swedish Medical Center - Ballard Campus\", \"Swedish Medical Center - Cherry Hill\" and \"Swedish Medical Center - First Hill\". \"Kaiser Permanente NCORP\" lists affiliate \"Kaiser Permanente Bellevue Medical Center\".",
    },
    {
      id: "swedish",
      title: "Swedish Health Services",
      publisher: "Swedish (Providence)",
      url: "https://www.swedish.org/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"The Providence MyChart App offers high-quality, personalized healthcare – at your fingertips. Schedule and manage your appointments, view test results, and so much more.\"",
    },
    {
      id: "epic-endpoints",
      title: "open.epic: FHIR R4 Endpoints",
      publisher: "Epic Systems (open.epic)",
      url: "https://open.epic.com/Endpoints/R4",
      year: "2026",
      note: "Downloaded October 5, 2026 (bundle \"total\": 479). Endpoint organization names include \"UW Medicine (Washington)\"; \"Valley Medical Center\"; \"Providence Health & Services - Washington/Montana\"; \"Virginia Mason Franciscan Health\"; \"Kaiser Permanente - Washington\"; \"Seattle Children's Hospital\"; \"MultiCare Health System\"; \"Overlake Hospital Medical Center\"; \"EvergreenHealth\", each with status \"active\". A listing shows an Epic FHIR endpoint, not every system an organization runs.",
    },
    {
      id: "oracle-endpoints",
      title: "Oracle Health Millennium patient R4 FHIR endpoints (millennium_patient_r4_endpoints.json)",
      publisher: "Oracle (oracle-samples/ignite-endpoints on GitHub)",
      url: "https://raw.githubusercontent.com/oracle-samples/ignite-endpoints/main/oracle_health_fhir_endpoints/millennium_patient_r4_endpoints.json",
      year: "2026",
      note: "Downloaded October 5, 2026. Organization entry \"VIRGINIA MASON MEDICAL CENTER\" (city \"SEATTLE\", state \"WA\"). A listing shows a Millennium FHIR endpoint, not every system the organization runs.",
    },
    {
      id: "hrsa-wa",
      title: "Washington Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/WA",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Total Number of Reporting Program Awardees: 27 Reporting Period: 2025 Total Patients Served: 1,294,656\". Five-year table, 2025 column: \"% Hispanic, Latino/a, or Spanish Origin Patients\" 37.07% (denominator: patients with known ethnicity); \"Limited English Proficiency\" 27.98% (362,294 patients).",
    },
    {
      id: "census-co-2025",
      title: "County Population Totals: April 1, 2020 to July 1, 2025 (CO-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/totals/co-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. Row \"King County\", Washington: ESTIMATESBASE2020 2,269,668; POPESTIMATE2025 2,344,939. The 3.3% increase is Bond's arithmetic.",
    },
    {
      id: "census-cc-2025",
      title: "Annual County Resident Population Estimates by Age, Sex, Race, and Hispanic Origin: April 1, 2020 to July 1, 2025 (CC-EST2025-ALLDATA-53)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/counties/asrh/cc-est2025-alldata-53.csv",
      year: "2026",
      note: "Downloaded October 5, 2026 and summed by Bond for King County, YEAR 7 (\"7 = 7/1/2025 population estimate\" in the file layout): TOT_POP 2,344,939; Hispanic 274,308 (11.7%); not Hispanic, Asian alone 558,026 (23.8%); not Hispanic, Black alone 160,678 (6.9%); age 65 and over (AGEGRP 14 to 18) 355,535 (15.2%).",
    },
    {
      id: "census-cbsa-2025",
      title: "Metropolitan and Micropolitan Statistical Area Population Totals: April 1, 2020 to July 1, 2025 (CBSA-EST2025-ALLDATA)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/metro/totals/cbsa-est2025-alldata.csv",
      year: "2026",
      note: "Downloaded October 5, 2026. CBSA 42660 \"Seattle-Tacoma-Bellevue, WA\": ESTIMATESBASE2020 4,018,766; POPESTIMATE2025 4,161,883 (up 3.6%). For comparison, \"Los Angeles-Long Beach-Anaheim, CA\" fell from 13,204,693 to 12,844,441 and \"San Francisco-Oakland-Fremont, CA\" from 4,753,651 to 4,630,041. Percentages are Bond's arithmetic.",
    },
    {
      id: "acs-c16001",
      title: "American Community Survey 2024 1-year estimates, table C16001: Language Spoken at Home for the Population 5 Years and Over",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-c16001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. King County (GEO_ID 0500000US53033): C16001_E001 \"Total:\" 2,222,819; C16001_E002 \"Speak only English\" 1,490,379. The sum of all \"Speak English less than 'very well'\" lines is 269,941. The 33.0% and 12.1% shares are Bond's arithmetic.",
    },
    {
      id: "acs-b16001",
      title: "American Community Survey 2024 1-year estimates, table B16001: Language Spoken at Home by Ability to Speak English for the Population 5 Years and Over",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-b16001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. King County, speakers and those who speak English less than \"very well\": Spanish 159,850 and 65,477; Chinese (incl. Mandarin, Cantonese) 127,380 and 52,738; Vietnamese 43,645 and 25,842; Hindi 35,583 and 3,334; Korean 30,953 and 14,559; \"Amharic, Somali, or other Afro-Asiatic languages\" 29,282 and 11,960; Russian 26,971 and 9,265; Tagalog (incl. Filipino) 26,572 and 9,078. Population 5 and over: 2,222,819.",
    },
    {
      id: "acs-b05002",
      title: "American Community Survey 2024 1-year estimates, table B05002: Place of Birth by Nativity and Citizenship Status",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-b05002.dat",
      year: "2025",
      note: "Downloaded October 5, 2026. King County: B05002_E001 \"Total:\" 2,340,211; B05002_E013 \"Foreign-born:\" 634,674 (27.1%, Bond's arithmetic).",
    },
    {
      id: "acs-c27001",
      title: "American Community Survey 2024 1-year estimates, table C27001: Health Insurance Coverage Status by Age",
      publisher: "U.S. Census Bureau (table-based summary file)",
      url: "https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/data/1YRData/acsdt1y2024-c27001.dat",
      year: "2025",
      note: "Downloaded October 5, 2026 and summed by Bond across the \"No health insurance coverage\" lines. King County: 123,256 of 2,327,970 (5.3%). United States: 27,479,253 of 335,190,522 (8.2%).",
    },
    {
      id: "velocity",
      title: "Locations",
      publisher: "Velocity Clinical Research",
      url: "https://velocityclinical.com/locations/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Velocity Clinical Research Seattle, Washington\" and \"Velocity Clinical Research Spokane, Washington\".",
    },
    {
      id: "nwcrc",
      title: "Northwest Clinical Research Center",
      publisher: "Northwest Clinical Research Center",
      url: "https://www.nwcrc.net/",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"30+ YEARS EXPERIENCE\" and \"1951 152nd Pl NE, Suite 200 Bellevue, WA, 98007\".",
    },
    {
      id: "wa-rcw-19-373-010",
      title: "RCW 19.373.010, Definitions (Washington My Health My Data Act)",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.373.010",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"For purposes of this definition, \"geofence\" means a virtual boundary that is 2,000 feet or less from the perimeter of the physical location.\" Also: \"Consumer health data\" means \"personal information that is linked or reasonably linkable to a consumer and that identifies the consumer's past, present, or future physical or mental health status.\"",
    },
    {
      id: "wa-rcw-19-373-030",
      title: "RCW 19.373.030, Collection or sharing of consumer health data",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.373.030",
      year: "2023",
      note: "Read October 5, 2026. Quote: \"beginning March 31, 2024, a regulated entity or a small business may not collect any consumer health data except: (i) With consent from the consumer for such collection for a specified purpose; or (ii) To the extent necessary to provide a product or service that the consumer to whom such consumer health data relates has requested\"; sharing requires consent \"that is separate and distinct from the consent obtained to collect consumer health data\"; \"A small business must comply with this section beginning June 30, 2024.\"",
    },
    {
      id: "wa-rcw-19-373-080",
      title: "RCW 19.373.080, Geofence restrictions",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.373.080",
      year: "2023",
      note: "Read October 5, 2026. Quote: \"It is unlawful for any person to implement a geofence around an entity that provides in-person health care services where such geofence is used to: (1) Identify or track consumers seeking health care services; (2) collect consumer health data from consumers; or (3) send notifications, messages, or advertisements to consumers related to their consumer health data or health care services.\"",
    },
    {
      id: "wa-rcw-19-373-090",
      title: "RCW 19.373.090, Application of consumer protection act",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.373.090",
      year: "2023",
      note: "Read October 5, 2026. Quote: \"A violation of this chapter is not reasonable in relation to the development and preservation of business, and is an unfair or deceptive act in trade or commerce and an unfair method of competition for the purpose of applying the consumer protection act, chapter 19.86 RCW.\"",
    },
    {
      id: "wa-rcw-19-373-100",
      title: "RCW 19.373.100, Exemptions",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.373.100",
      year: "2026",
      note: "Read October 5, 2026. Quote: the chapter does not apply to \"(i) Protected health information for purposes of the federal health insurance portability and accountability act of 1996\"; \"(ii) Health care information collected, used, or disclosed in accordance with chapter 70.02 RCW\"; and \"(iv) Identifiable private information for purposes of the federal policy for the protection of human subjects, 45 C.F.R. Part 46; identifiable private information that is otherwise information collected as part of human subjects research pursuant to the good clinical practice guidelines issued by the international council for harmonization; the protection of human subjects under 21 C.F.R. Parts 50 and 56; or personal data used or shared in research conducted in accordance with one or more of the requirements set forth in this subsection\".",
    },
    {
      id: "wa-rcw-70-02-020",
      title: "RCW 70.02.020, Disclosure by health care provider",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=70.02.020",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Except as authorized elsewhere in this chapter, a health care provider ... may not disclose health care information about a patient to any other person without the patient's written authorization.\"",
    },
    {
      id: "wa-rcw-70-02-210",
      title: "RCW 70.02.210, Disclosure without patient's authorization — Research",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=70.02.210",
      year: "2014",
      note: "Read October 5, 2026. Quote: a provider may disclose without authorization \"if the disclosure is for use in a research project that an institutional review board has determined: (i) Is of sufficient importance to outweigh the intrusion into the privacy of the patient that would result from the disclosure; (ii) Is impracticable without the use or disclosure of the health care information in individually identifiable form; (iii) Contains reasonable safeguards to protect the information from redisclosure\".",
    },
    {
      id: "wa-rcw-9-73-030",
      title: "RCW 9.73.030, Intercepting, recording, or divulging private communication — Consent required — Exceptions",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=9.73.030",
      year: "2026",
      note: "Read October 5, 2026. Quote: recording a private telephone communication is unlawful \"without first obtaining the consent of all the participants in the communication\"; \"consent shall be considered obtained whenever one party has announced to all other parties engaged in the communication or conversation, in any reasonably effective manner, that such communication or conversation is about to be recorded or transmitted: PROVIDED, That if the conversation is to be recorded that said announcement shall also be recorded.\"",
    },
    {
      id: "wa-rcw-19-190-060",
      title: "RCW 19.190.060, Commercial electronic text message — Prohibition on initiation or assistance",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.190.060",
      year: "2003",
      note: "Read October 5, 2026. Quote: \"No person conducting business in the state may initiate or assist in the transmission of an electronic commercial text message to a telephone number assigned to a Washington resident for cellular telephone or pager service\". RCW 19.190.010 (https://app.leg.wa.gov/RCW/default.aspx?cite=19.190.010): \"Commercial electronic text message\" means \"an electronic text message sent to promote real property, goods, or services for sale or lease.\"",
    },
    {
      id: "wa-rcw-19-190-040",
      title: "RCW 19.190.040, Violations — Damages",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.190.040",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"Damages to the recipient of a commercial electronic mail message or a commercial electronic text message sent in violation of this chapter are $100, or actual damages, whichever is greater.\" History: \"[ 2026 c 135 s 2 ; 2003 c 137 s 5 ; 1998 c 149 s 5 .]\" The note following RCW 19.190.020 reads: \"This act applies to all causes of action commenced on or after June 11, 2026, regardless of when the cause of action arose.\"",
    },
    {
      id: "wa-rcw-80-36-400",
      title: "RCW 80.36.400, Automatic dialing and announcing device — Commercial solicitation by",
      publisher: "Washington State Legislature",
      url: "https://app.leg.wa.gov/RCW/default.aspx?cite=80.36.400",
      year: "2023",
      note: "Read October 5, 2026. Quote: \"\"Automatic dialing and announcing device\" is a system which automatically dials telephone numbers and transmits a recorded or artificial voice message once a connection is made\"; \"No person may use an automatic dialing and announcing device for purposes of commercial solicitation\"; an injured person \"shall recover actual damages or $1,000 per violation of this section, whichever is greater.\" \"Commercial solicitation\" means \"the unsolicited initiation of a telephone communication made for the purpose of encouraging a person to purchase property, goods, or services, or wrongfully obtaining anything of value.\"",
    },
    {
      id: "wa-hb2225",
      title: "Engrossed Substitute House Bill 2225, Chapter 168, Laws of 2026 (artificial intelligence companion chatbots)",
      publisher: "Washington State Legislature",
      url: "https://lawfilesext.leg.wa.gov/biennium/2025-26/Htm/Bills/Session%20Laws/House/2225-S.SL.htm",
      year: "2026",
      note: "Read October 5, 2026. Quote: \"An operator must provide a clear and conspicuous disclosure that an AI companion chatbot is artificially generated and not human\" ... \"(a) At the beginning of the interaction; and (b) At least every three hours during continued interaction.\" Exclusion: \"A bot that is used only for a business' operational purposes, productivity and analysis related to source information, internal research, technical assistance, or customer service, if such bot does not sustain a relationship across multiple interactions and generate outputs that are likely to elicit emotional responses in the user\". \"This act takes effect January 1, 2027.\" \"Approved by the Governor March 24, 2026.\" HB 1170 (Chapter 167, Laws of 2026, AI content provenance) takes effect February 1, 2027 and was also reviewed.",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, October 2026.",
    },
  ],
  related: [
    { label: "All locations", href: "/clinical-trial-recruitment", description: "Registry counts and outreach rules for other states and regions." },
    { label: "Bond for research sites", href: "/for/research-sites", description: "How screening, outreach and booked visits fit a site's coordinators." },
    { label: "Epic integration", href: "/integrations/epic", description: "How Bond connects to the EHR most Seattle systems run." },
    { label: "Oncology", href: "/oncology", description: "How Bond screens for cancer trials, the area's largest category by count." },
    { label: "Engage", href: "/engage", description: "Ads, voice and text outreach, and booked visits." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
  ],
};

export default page;
