import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/southeast",
  category: "geography",
  title: "Clinical trial recruitment in the Southeast: GA, NC, TN",
  description:
    "Clinical trial recruitment in Georgia, North Carolina, Tennessee and seven more Southeast states: trial counts, research hubs, EHRs, demographics, state laws.",
  keywords: [
    "clinical trial recruitment Southeast",
    "clinical trials Georgia North Carolina Tennessee",
    "Southeast research sites",
    "Research Triangle clinical research",
    "Southeast AI disclosure laws",
  ],
  eyebrow: "Southeast",
  h1: "Recruiting for clinical trials in the Southeast",
  intro:
    "As of September 2026, 6,258 studies on ClinicalTrials.gov were recruiting at one or more sites in ten Southeast states, about 28% of the 22,041 recruiting at a US site.{{cite:ctgov-southeast-unique,ctgov-api}} The ten are Georgia, North Carolina, South Carolina, Tennessee, Alabama, Mississippi, Kentucky, Virginia, Louisiana and Arkansas. Below: research hubs, EHRs, demographics, state laws, and how Bond Health deploys with a site.",
  summary: "Southeast recruiting-trial counts, research hubs, health systems and their EHRs, demographics, and state AI and privacy rules.",
  lastUpdated: "2026-09-24",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in the Southeast?",
      blocks: [
        {
          type: "p",
          text: "The table below adds up ten state searches, so a study with sites in Atlanta and Nashville counts twice and the share column overstates the region. Counted once, 6,258 studies list a Southeast site, about 28% of the national total, while the ten states hold 18.9% of US residents.{{cite:ctgov-southeast-unique,census-asrh-2025}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "southeast", cite: "ctgov-api" },
        {
          type: "p",
          text: "Oncology is the largest area: counted once, 2,296 of the 6,258 studies match an oncology keyword search.{{cite:ctgov-southeast-unique}} See [oncology](/oncology) and [cardiology](/cardiology) for how Bond approaches each area.",
        },
        { type: "trials", geo: "southeast", condition: "oncology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are the main research hubs in the Southeast?",
      blocks: [
        {
          type: "table",
          caption: "Research hubs and their medical schools' NIH funding, fiscal 2025",
          columns: ["Hub", "Anchor institutions", "NIH rank and funding"],
          rows: [
            ["Research Triangle, NC", "Duke, UNC-Chapel Hill and their cancer centers; Research Triangle Park{{cite:nci-centers,rtp}}", "Duke #9, $515 million; UNC #18, $353 million{{cite:brimr-2025}}"],
            ["Atlanta, GA", "Emory and its Winship Cancer Institute; Grady Memorial Hospital{{cite:nci-centers,grady}}", "Emory #16, $385 million{{cite:brimr-2025}}"],
            ["Nashville, TN", "Vanderbilt University Medical Center and Vanderbilt-Ingram Cancer Center{{cite:nci-centers}}", "Vanderbilt #7, $564 million{{cite:brimr-2025}}"],
            ["Birmingham, AL", "UAB and its O'Neal Comprehensive Cancer Center{{cite:nci-centers}}", "UAB #28, $256 million{{cite:brimr-2025}}"],
            ["Charleston, SC", "MUSC and its Hollings Cancer Center{{cite:nci-centers}}", "MUSC #48, $132 million{{cite:brimr-2025}}"],
          ],
        },
        {
          type: "ul",
          items: [
            "**Nashville.** Vanderbilt's Recruitment Innovation Center, founded in 2016, develops and tests ways to recruit participants. In 2023 VUMC won two NIH grants totaling $51 million to improve recruitment and trial efficiency nationally.{{cite:vumc-ric}}",
            "**New Orleans.** Ochsner Health reports more than 700 clinical trials across its Gulf South system, per its website.{{cite:ochsner}}",
            "**Cancer centers.** As of September 2026, NCI lists 11 designated cancer centers in the ten states, 10 of them comprehensive. Arkansas, Louisiana and Mississippi have none.{{cite:nci-centers}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which health systems and EHRs hold the patients?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected health systems, per each system or trade press, checked September 2026",
          columns: ["System", "Base", "EHR"],
          rows: [
            ["Duke Health", "Durham, NC", "Epic (Maestro Care), live across Duke Health since March 1, 2014{{cite:duke-maestro}}"],
            ["Atrium Health, part of Advocate Health{{cite:atrium-about}}", "Charlotte, NC, with locations in Georgia", "Epic, chosen in 2020 as its single EHR across three states{{cite:atrium-epic}}"],
            ["Emory Healthcare", "Atlanta, GA", "Epic since October 1, 2022, replacing Cerner{{cite:emory-epic}}"],
            ["MUSC", "Charleston, SC", "Epic since 2012 (ambulatory) and 2014 (inpatient), with data available for cohort discovery{{cite:musc-epic}}"],
            ["Vanderbilt University Medical Center", "Nashville, TN", "eStar, its Epic-based EHR, activated November 2, 2017{{cite:vumc-estar,vumc-estar-epic}}"],
            ["UAB Health System", "Birmingham, AL", "Moving to Epic, including for clinical research, approved September 2024; confirm go-live status{{cite:uab-epic}}"],
            ["HCA Healthcare", "Multistate, including Virginia", "Moving to MEDITECH Expanse; its 18-hospital Capital Division (Virginia and New Hampshire) finished in August 2026, per trade press. Confirm each hospital{{cite:hca-meditech}}"],
            ["Community health centers", "All ten states", "Varies; eClinicalWorks said in 2023 it served roughly 60% of US health centers{{cite:ecw-fqhc}}"],
          ],
        },
        {
          type: "p",
          text: "Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR R4 APIs, HL7 v2 where applicable, or an aggregator.{{cite:bond-site,bond-product}} For MEDITECH, eClinicalWorks and other EHRs, Bond uses the same FHIR-based path, and the site's IT team provides API access. See [Epic](/integrations/epic), [MEDITECH](/integrations/meditech) and [eClinicalWorks](/integrations/eclinicalworks).",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in the Southeast, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "64.8 million", label: "Residents of the ten states on July 1, 2025, 18.9% of the US", cite: "census-asrh-2025" },
            { value: "32.6%", label: "Share of US Black residents (Black alone) living in the ten states, 2025", cite: "census-asrh-2025" },
            { value: "33.2%", label: "Share of the ten states' residents living in rural areas, 2020 Census", cite: "census-urban-rural-2020" },
            { value: "12.0%", label: "Georgia's uninsured rate in 2024, second-highest of any state after Texas", cite: "census-acs-uninsured" },
          ],
        },
        {
          type: "table",
          caption: "By state: Black and 65+ shares (July 1, 2025) and rural share (2020 Census)",
          columns: ["State", "Black or African American", "Age 65 and over", "Rural"],
          rows: [
            ["Mississippi{{cite:census-asrh-2025,census-urban-rural-2020}}", "36.8%", "19.3%", "53.7%"],
            ["Georgia{{cite:census-asrh-2025,census-urban-rural-2020}}", "32.4%", "16.7%", "25.9%"],
            ["Louisiana{{cite:census-asrh-2025,census-urban-rural-2020}}", "32.1%", "18.8%", "28.5%"],
            ["Alabama{{cite:census-asrh-2025,census-urban-rural-2020}}", "25.9%", "19.4%", "42.3%"],
            ["South Carolina{{cite:census-asrh-2025,census-urban-rural-2020}}", "24.4%", "21.1%", "32.1%"],
            ["North Carolina{{cite:census-asrh-2025,census-urban-rural-2020}}", "21.3%", "18.9%", "33.3%"],
            ["Virginia{{cite:census-asrh-2025,census-urban-rural-2020}}", "19.5%", "18.4%", "24.4%"],
            ["Tennessee{{cite:census-asrh-2025,census-urban-rural-2020}}", "15.7%", "18.6%", "33.8%"],
            ["Arkansas{{cite:census-asrh-2025,census-urban-rural-2020}}", "15.2%", "19.0%", "44.5%"],
            ["Kentucky{{cite:census-asrh-2025,census-urban-rural-2020}}", "8.7%", "18.8%", "41.3%"],
            ["United States{{cite:census-asrh-2025,census-urban-rural-release}}", "13.5%", "18.9%", "20.0%"],
          ],
          note: "Black or African American alone, of any Hispanic origin.",
        },
        {
          type: "p",
          text: "As of August 2026, Alabama, Georgia, Mississippi, South Carolina and Tennessee had not expanded Medicaid, per KFF.{{cite:kff-medicaid}} North Carolina expanded in December 2023, and its uninsured rate fell from 9.2% in 2023 to 8.6% in 2024.{{cite:census-acs-uninsured}} In 2025, Black patients were 60.0% of HRSA-funded health center patients in Mississippi and 46.7% in Georgia, and about a quarter in each state were uninsured.{{cite:hrsa-ms,hrsa-ga}} A cohort that reflects the region usually has to reach patients at these clinics. See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
        {
          type: "callout",
          tone: "info",
          title: "Where trials do not reach",
          text: "In North Carolina, 229 multiple myeloma trials registered from 2002 to 2021 had sites in just 34 counties; low-poverty counties had 5.6 times the odds of hosting one that high-poverty counties had.{{cite:jco-nc-myeloma}} In a 2020 national survey, rural adults had about one-third the odds of urban adults of ever being invited to a trial.{{cite:hints-2021}}",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks work in the Southeast?",
      blocks: [
        {
          type: "ul",
          items: [
            "**Duke Clinical Research Institute**, in Durham, reports on its website a network of more than 1,100 US research sites, including community-based practices.{{cite:dcri}}",
            "**Velocity Clinical Research**, headquartered in Durham, says on its website that it has more than 70 integrated research sites and 200 investigators.{{cite:velocity}}",
            "**Javara**, a Winston-Salem integrated research organization, in 2021 extended its partnership with Wake Forest Baptist Health to run trials at the point of care in the system's community clinics.{{cite:javara}}",
          ],
        },
        {
          type: "p",
          text: "Commonwealth Pain and Spine Clinic, a Kentucky practice, is listed among the partners on Bond's site, and Bond is a CRIO Certified Partner.{{cite:bond-site}} See how Bond fits [research sites](/for/research-sites), [site networks](/for/site-networks), [pain studies](/pain) and [CRIO](/integrations/crio).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which state laws touch AI outreach and patient data?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how each applies is unsettled. Treat this as a map for counsel, not legal advice; for federal rules, see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026).",
        },
        {
          type: "ul",
          items: [
            "**Tennessee.** The ELVIS Act, in effect since July 1, 2024, gives each person a property right in their voice, which bears on cloned voices.{{cite:tn-elvis}} SB 1580, in effect since July 1, 2026, bars presenting an AI system as able to act as a qualified mental health professional.{{cite:tn-sb1580}} The Tennessee Information Protection Act, in effect since July 1, 2025, exempts HIPAA covered entities and business associates.{{cite:tn-tipa}}",
            "**Louisiana.** Act 649 of 2026 requires a licensed healthcare professional to tell a patient out loud before recording any part of an appointment or treatment that will be transcribed by AI.{{cite:la-act649}} Plan for it at screening visits that use an AI scribe.",
            "**Virginia.** The Consumer Data Protection Act exempts HIPAA covered entities, business associates, and research data collected under the Common Rule or ICH good clinical practice.{{cite:va-cdpa}} Under the state's telephone solicitation law, a STOP or UNSUBSCRIBE reply to a text must be honored for at least 10 years.{{cite:va-texting}} Ask counsel whether a study invitation counts as a solicitation.",
            "**Kentucky.** A consumer data privacy law, HB 15, took effect January 1, 2026.{{cite:ky-hb15}} Check its HIPAA and research exemptions with counsel.",
            "**Alabama and Georgia.** Their 2026 AI laws govern insurers' prior authorization decisions, not outreach, and take effect October 1, 2026 and January 1, 2027.{{cite:hk-ai-2026}}",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI assistance is being used, and patients can reach a person at any time: the agent transfers the call live to a coordinator or books a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Scripts are configured per site and study, so each site can use the disclosure and opt-out wording its IRB has reviewed.",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Southeast site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration usually takes 4 to 6 weeks, depending on the EHR, IT review and interface method. A pilot from a patient list, without EHR integration, can begin in under 2 weeks.{{cite:bond-site}} See [implementation](/implementation) for the week-by-week plan.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Agree on scope and paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path. Settle AI disclosure and text opt-out wording early.",
            },
            {
              title: "Connect the EHR",
              text: "Connect through FHIR or HL7 interfaces or an aggregator. If your system is switching EHRs, as UAB and HCA are, agree on which record Bond reads during the move.",
            },
            {
              title: "Configure and validate criteria",
              text: "Bond configures the protocol's criteria and shows the evidence behind each ranked candidate, so coordinators can check early matches.{{cite:bond-site}} See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Screen, reach out and schedule",
              text: "Voice and text agents pre-screen and schedule, then hand off to coordinators. The dashboard tracks each patient from match to randomization.{{cite:bond-site}}",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "Do Southeast states require patients to be told when AI is used?",
      a: "None of the laws reviewed here was written for recruitment outreach. Louisiana requires disclosure before an appointment is recorded for AI transcription, and Tennessee restricts AI presented as a mental health professional.{{cite:la-act649,tn-sb1580}}",
    },
    {
      q: "Does Bond work with sites in the Southeast?",
      a: "Commonwealth Pain and Spine Clinic in Kentucky is listed among Bond's partners.{{cite:bond-site}} Bond can connect through FHIR, HL7 or an aggregator, or start from a patient list.",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Queried September 21, 2026.",
    },
    {
      id: "ctgov-southeast-unique",
      title: "ClinicalTrials.gov API v2 study search: recruiting studies with a location in the ten Southeast states",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/api/v2/studies?query.locn=AREA%5BLocationState%5D%28%22Georgia%22+OR+%22North+Carolina%22+OR+%22South+Carolina%22+OR+%22Tennessee%22+OR+%22Alabama%22+OR+%22Mississippi%22+OR+%22Kentucky%22+OR+%22Virginia%22+OR+%22Louisiana%22+OR+%22Arkansas%22%29&filter.overallStatus=RECRUITING&countTotal=true&pageSize=1&fields=NCTId",
      year: "2026",
      note: "Quote: \"totalCount\":6258 (API response to this query, run September 22, 2026: overall status Recruiting, at least one location in any of the ten states, each study counted once). The same query with LocationCountry \"United States\" returned \"totalCount\":22041. 6,258 / 22,041 = 28.4%, computed by Bond. The same Southeast query with query.cond=cancer OR neoplasm OR carcinoma OR lymphoma OR leukemia returned \"totalCount\":2296 (run September 22, 2026).",
    },
    {
      id: "census-asrh-2025",
      title: "Annual State Resident Population Estimates for 6 Race Groups by Age, Sex, and Hispanic Origin: April 1, 2020 to July 1, 2025 (SC-EST2025-ALLDATA6)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/datasets/2020-2025/state/asrh/sc-est2025-alldata6.csv",
      year: "2026",
      note: "Downloaded September 22, 2026 and summed by Bond from POPESTIMATE2025, both sexes, all origins: ten-state total 64,753,265 of 341,784,857 US residents (18.9%); Black or African American alone 15,061,735 of 46,248,715 nationally (32.6%); Georgia 3,659,052, third after Texas and Florida. Black alone and age 65+ shares: Mississippi 36.8/19.3, Georgia 32.4/16.7, Louisiana 32.1/18.8, Alabama 25.9/19.4, South Carolina 24.4/21.1, North Carolina 21.3/18.9, Virginia 19.5/18.4, Tennessee 15.7/18.6, Arkansas 15.2/19.0, Kentucky 8.7/18.8, United States 13.5/18.9.",
    },
    {
      id: "census-urban-rural-2020",
      title: "2020 Census Urban and Rural Population by State (State_Urban_Rural_Pop_2020_2010)",
      publisher: "U.S. Census Bureau",
      url: "https://www2.census.gov/geo/docs/reference/ua/State_Urban_Rural_Pop_2020_2010.xlsx",
      year: "2023",
      note: "Downloaded September 22, 2026. Column 2020 PCT RURAL POP: Mississippi 53.7, Arkansas 44.5, Alabama 42.3, Kentucky 41.3, Tennessee 33.8, North Carolina 33.3, South Carolina 32.1, Louisiana 28.5, Georgia 25.9, Virginia 24.4. Ten-state rural population 20,571,012 of 61,972,629 (33.2%), summed by Bond.",
    },
    {
      id: "census-urban-rural-release",
      title: "Nation's Urban and Rural Populations Shift Following 2020 Census",
      publisher: "U.S. Census Bureau",
      url: "https://www.census.gov/newsroom/press-releases/2022/urban-rural-populations.html",
      year: "2022",
    },
    {
      id: "census-acs-uninsured",
      title: "Health Insurance Coverage by State: 2023 and 2024 (ACSBR-024)",
      publisher: "U.S. Census Bureau, American Community Survey Briefs",
      url: "https://www2.census.gov/library/publications/2025/demo/acsbr-024.pdf",
      year: "2025",
      note: "Quote: \"The uninsured rate declined in California and North Carolina.\" Appendix table, all ages, 2024 uninsured rate: Texas 16.7, Georgia 12.0 (second-highest), United States 8.2.",
    },
    {
      id: "kff-medicaid",
      title: "Status of State Action on the Medicaid Expansion Decision",
      publisher: "KFF",
      url: "https://www.kff.org/affordable-care-act/state-indicator/state-activity-around-expanding-medicaid-under-the-affordable-care-act/",
      year: "2026",
      note: "Quote: \"Adopted: 41 states (incl. DC) Not Adopted: 10 states\". Checked September 2026 (data as of August 2026): Alabama, Georgia, Mississippi, South Carolina and Tennessee are listed as not adopted; Arkansas, Kentucky, Louisiana, North Carolina and Virginia as adopted.",
    },
    {
      id: "hrsa-ga",
      title: "Georgia Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/GA",
      year: "2026",
      note: "Quote: \"Total Number of Reporting Program Awardees: 35 Reporting Period: 2025 Total Patients Served: 766,045\". Same page, 2025: % Black or African American Patients 46.74%; % None/Uninsured Patients 24.78%.",
    },
    {
      id: "hrsa-ms",
      title: "Mississippi Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/MS",
      year: "2026",
      note: "Quote: \"Total Number of Reporting Program Awardees: 20 Reporting Period: 2025 Total Patients Served: 306,400\". Same page, 2025: % Black or African American Patients 59.95%; % None/Uninsured Patients 25.36%.",
    },
    {
      id: "jco-nc-myeloma",
      title: "Cross-Sectional Analysis of Clinical Trial Availability and North Carolina Neighborhood Social Vulnerability",
      publisher: "JCO Oncology Practice",
      url: "https://pubmed.ncbi.nlm.nih.gov/36473128/",
      year: "2023",
      note: "Quote: \"Between 2002 and 2021, 229 trials were registered across 462 nonunique trial sites in 34 counties.\" and \"Counties with low as opposed to high poverty rates had six times greater odds of having ≥ 1 MM trial sites (odds ratio [OR], 5.60; 95% CI, 1.85 to 19.64)\"",
    },
    {
      id: "hints-2021",
      title: "Demographic and Health Behavior Factors Associated With Clinical Trial Invitation and Participation in the United States",
      publisher: "JAMA Network Open",
      url: "https://pubmed.ncbi.nlm.nih.gov/34586365/",
      year: "2021",
      note: "Rural vs urban respondents: adjusted odds ratio of invitation 0.33 (95% CI 0.17 to 0.65), HINTS 2020.",
    },
    {
      id: "brimr-2025",
      title: "BRIMR Rankings of NIH Funding in 2025: Schools of Medicine",
      publisher: "Blue Ridge Institute for Medical Research",
      url: "https://brimr.org/wp-content/uploads/2026/02/SchoolOfMedicine_2025.xlsx",
      year: "2026",
      note: "Downloaded September 22, 2026. Rank, name and School of Medicine award: 7 Vanderbilt University $564,267,623; 9 Duke University $514,509,019; 16 Emory University $385,377,125; 18 University of North Carolina Chapel Hill $353,001,816; 28 University of Alabama Birmingham $256,056,953; 48 Medical University of South Carolina $132,423,003.",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Checked September 22, 2026. Entries in the ten states: Winship Cancer Institute (Atlanta), Duke Cancer Institute (Durham), UNC Lineberger (Chapel Hill), Wake Forest Baptist (Winston-Salem), St. Jude Children's Research Hospital (Memphis), Vanderbilt-Ingram (Nashville), O'Neal (Birmingham), Markey (Lexington), VCU Massey (Richmond) and University of Virginia (Charlottesville), all Comprehensive Cancer Centers; Hollings Cancer Center (Charleston), a Clinical Cancer Center. None listed in Arkansas, Louisiana or Mississippi.",
    },
    {
      id: "rtp",
      title: "Research Triangle Park: Where People + Ideas Converge (home page and company directory)",
      publisher: "Research Triangle Foundation of North Carolina",
      url: "https://www.rtp.org/",
      year: "2026",
    },
    {
      id: "grady",
      title: "Grady Memorial Hospital",
      publisher: "Grady Health System",
      url: "https://www.gradyhealth.org/locations/grady-memorial-hospital/",
      year: "2026",
    },
    {
      id: "ochsner",
      title: "About Ochsner",
      publisher: "Ochsner Health",
      url: "https://www.ochsner.org/about-ochsner/",
      year: "2026",
      note: "Checked September 22, 2026. Quote: \"Over 700 clinical trials being conducted at Ochsner.\" and \"Ochsner Health is the leading nonprofit healthcare provider in Louisiana, Mississippi and across the Gulf South\"",
    },
    {
      id: "vumc-ric",
      title: "VUMC receives $51 million in NIH grants to improve efficiency of conducting clinical trials across the US",
      publisher: "Vanderbilt University Medical Center (VUMC News)",
      url: "https://news.vumc.org/2023/08/09/vumc-receives-51-million-in-grants-to-improve-the-efficiency-of-conducting-clinical-trials-across-the-u-s/",
      year: "2023",
    },
    {
      id: "dcri",
      title: "About",
      publisher: "Duke Clinical Research Institute",
      url: "https://dcri.org/about",
      year: "2026",
    },
    {
      id: "velocity",
      title: "About Velocity Clinical Research",
      publisher: "Velocity Clinical Research",
      url: "https://velocityclinical.com/about/",
      year: "2026",
      note: "Quote: \"Headquartered in Durham, NC, Velocity Clinical Research is the world's leading organization of fully integrated clinical research sites. With more than 70 sites and 200 investigators, Velocity partners with pharmaceutical and biotechnology companies\"",
    },
    {
      id: "javara",
      title: "Javara Inc. and Wake Forest Baptist Health launch an innovative partnership to amplify clinical trial access",
      publisher: "Javara",
      url: "https://javararesearch.com/2021/02/08/javara-inc-and-wake-forest-baptist-health-launch-an-innovative-partnership-to-amplify-clinical-trial-access/",
      year: "2021",
      note: "Release dated February 8, 2021. Quote: \"extend their existing partnership to provide clinical research services at the point of care with physicians and patients within Wake Forest Baptist Health's community health care clinics and designated medical centers.\"",
    },
    {
      id: "duke-maestro",
      title: "Maestro Care for Research",
      publisher: "Duke University School of Medicine, Duke Office of Clinical Research",
      url: "https://medschool.duke.edu/research/research-support/research-support-offices/duke-office-clinical-research-docr/get-docr-5",
      year: "2026",
    },
    {
      id: "atrium-about",
      title: "About Us",
      publisher: "Atrium Health",
      url: "https://atriumhealth.org/about-us",
      year: "2026",
      note: "Checked September 22, 2026. Quote: \"Based in Charlotte, North Carolina, Atrium Health is part of Advocate Health, the third-largest nonprofit health system in the United States\"",
    },
    {
      id: "atrium-epic",
      title: "Atrium Health Selects Epic for Implementation of Electronic Health Records Across Three States",
      publisher: "Atrium Health",
      url: "https://atriumhealth.org/about-us/newsroom/news/2020/02/atrium-health-selects-epic-for-implementation-of-electronic-health-records-across-three-states",
      year: "2020",
    },
    {
      id: "emory-epic",
      title: "Emory Healthcare moves to new system-wide electronic health record to advance patient experience and care",
      publisher: "Emory University (Emory News)",
      url: "https://news.emory.edu/stories/2022/09/hs_ehc_epic_ehr_22-09-2022/story.html",
      year: "2022",
    },
    {
      id: "musc-epic",
      title: "Research Data Overview, Biomedical Informatics Center",
      publisher: "Medical University of South Carolina, College of Medicine",
      url: "https://medicine.musc.edu/biomedical-informatics-center/services/data-request/overview",
      year: "2026",
    },
    {
      id: "vumc-estar",
      title: "Transition to eStar system off to strong start",
      publisher: "Vanderbilt University Medical Center (VUMC News)",
      url: "https://news.vumc.org/2017/11/09/transition-to-estar-system-off-to-strong-start/",
      year: "2017",
      note: "Quote: \"With the Nov. 2 activation of eStar, an operational command center and a separate technical command center have been operating around the clock\". The article names the implementation project Epic Leap.",
    },
    {
      id: "vumc-estar-epic",
      title: "Upgrade to bring enhanced features, functionality to eStar",
      publisher: "Vanderbilt University Medical Center (VUMC News)",
      url: "https://news.vumc.org/2019/04/04/upgrade-to-bring-enhanced-features-functionality-to-estar/",
      year: "2019",
      note: "Article dated April 4, 2019. Quote: \"eStar, the Epic-based electronic health record (EHR) at Vanderbilt University Medical Center\"",
    },
    {
      id: "uab-epic",
      title: "UAB Health System announces investment in new EHR platform",
      publisher: "UAB Medicine",
      url: "https://www.uabmedicine.org/news/uab-health-system-announces-investment-in-new-ehr-platform/",
      year: "2024",
      note: "Quote: \"The University of Alabama System Board of Trustees unanimously approved plans on Sept. 25, 2024, for the UAB Health System to transition to a new electronic health record platform, EPIC, for electronic health records, revenue cycle and clinical research functions.\" The same release cites an \"approximately $380 million project budget\".",
    },
    {
      id: "hca-meditech",
      title: "MEDITECH Completes Expanse Implementation Across 34 Hospitals in HCA Healthcare's First Two U.S. Divisions",
      publisher: "HIT Consultant",
      url: "https://hitconsultant.net/2026/09/16/meditech-completes-expanse-ehr-implementation-34-hospitals-hca-healthcare-divisions/",
      year: "2026",
      note: "Article dated September 16, 2026. Quote: \"Capital Division: 18 hospitals operating across Virginia and New Hampshire\" and \"The completion of the 34 facilities in August pushed the active hospital count to 72.\"",
    },
    {
      id: "ecw-fqhc",
      title: "eClinicalWorks Kicks off the Largest Summit for Federally Qualified Health Centers and Community Health Centers Nationwide",
      publisher: "eClinicalWorks",
      url: "https://www.eclinicalworks.com/eclinicalworks-kicks-off-the-largest-summit-for-federally-qualified-health-centers-and-community-health-centers-nationwide/",
      year: "2023",
    },
    {
      id: "tn-elvis",
      title: "Bill Information: HB 2091 (113th General Assembly), Ensuring Likeness, Voice, and Image Security Act of 2024",
      publisher: "Tennessee General Assembly",
      url: "https://wapp.capitol.tn.gov/apps/BillInfo/Default.aspx?BillNumber=HB2091&GA=113",
      year: "2024",
    },
    {
      id: "tn-sb1580",
      title: "Bill Information: SB 1580 (114th General Assembly)",
      publisher: "Tennessee General Assembly",
      url: "https://wapp.capitol.tn.gov/apps/BillInfo/Default.aspx?BillNumber=SB1580&GA=114",
      year: "2026",
    },
    {
      id: "tn-tipa",
      title: "Bill Information: HB 1181 (113th General Assembly), Tennessee Information Protection Act",
      publisher: "Tennessee General Assembly",
      url: "https://wapp.capitol.tn.gov/apps/BillInfo/Default.aspx?BillNumber=HB1181&GA=113",
      year: "2023",
    },
    {
      id: "la-act649",
      title: "HB 475, Act 649 (2026 Regular Session), enrolled text",
      publisher: "Louisiana State Legislature",
      url: "https://legis.la.gov/legis/ViewDocument.aspx?d=1480567",
      year: "2026",
      note: "Quote: \"A healthcare professional licensed by this Title shall verbally disclose the use of any recording device, software, or service to a patient before recording any part of an appointment or treatment to be transcribed by artificial intelligence.\"",
    },
    {
      id: "va-cdpa",
      title: "Code of Virginia § 59.1-576. Scope; exemptions",
      publisher: "Virginia General Assembly, Legislative Information System",
      url: "https://law.lis.virginia.gov/vacode/title59.1/chapter53/section59.1-576/",
      year: "2026",
    },
    {
      id: "va-texting",
      title: "Code of Virginia § 59.1-514. Unwanted telephone solicitations prohibited",
      publisher: "Virginia General Assembly, Legislative Information System",
      url: "https://law.lis.virginia.gov/vacode/title59.1/chapter51/section59.1-514/",
      year: "2026",
      note: "Quote: \"In the case of a telephone solicitation via text message, such statement shall be made by replying to the text message with the word 'UNSUBSCRIBE' or 'STOP.'\" (inner quotation marks shown as single quotes) and \"Any such request not to receive telephone solicitations shall be honored for at least 10 years from the time the request is made.\"",
    },
    {
      id: "ky-hb15",
      title: "24RS HB 15: An Act relating to consumer data privacy",
      publisher: "Kentucky General Assembly",
      url: "https://apps.legislature.ky.gov/record/24rs/hb15.html",
      year: "2024",
      note: "Quote: \"04/04/24: signed by Governor (Acts Ch. 72) ... Effective Dates, Delayed - Personal data protection, data privacy rights, January 1, 2026\"",
    },
    {
      id: "hk-ai-2026",
      title: "States Continue Efforts to Regulate AI in Healthcare: A Review of Legislation Passed in 2026",
      publisher: "Holland & Knight",
      url: "https://www.hklaw.com/en/insights/publications/2026/05/states-continue-efforts-to-regulate-ai-in-healthcare",
      year: "2026",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, September 2026.",
    },
  ],
  related: [
    { label: "Recruitment by state and region", href: "/clinical-trial-recruitment", description: "Registry counts and local rules for every location page." },
    { label: "For research sites", href: "/for/research-sites", description: "How Bond fits a site's coordinators, EHR and CTMS." },
    { label: "FQHCs and community sites", href: "/for/fqhcs-and-community-sites", description: "Outreach through community health centers and their EHRs." },
    { label: "Oncology recruitment", href: "/oncology", description: "The largest area on the Southeast trial count." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, week by week." },
  ],
};

export default page;
