import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/clinical-trial-recruitment/texas",
  category: "geography",
  title: "Clinical trial recruitment in Texas for research sites",
  description:
    "Recruiting-trial counts, research hubs, health system EHRs, demographics and the Texas AI and privacy laws that shape patient outreach for research sites.",
  keywords: [
    "clinical trial recruitment Texas",
    "Texas research sites",
    "clinical trials Houston Dallas San Antonio Austin",
    "Texas AI disclosure health care",
    "TRAIGA patient outreach",
  ],
  eyebrow: "Texas",
  h1: "Recruiting for clinical trials in Texas",
  intro:
    "As of September 21, 2026, 4,854 studies on ClinicalTrials.gov were recruiting at one or more Texas locations, about 22% of the 22,041 recruiting anywhere in the United States.{{cite:ctgov-api}}",
  summary: "Texas recruiting-trial counts, research hubs, health systems and their EHRs, demographics, and state AI and privacy rules.",
  lastUpdated: "2026-09-24",
  showLastUpdated: true,
  heroCta: { label: "Book a demo", href: "/book-a-demo", secondaryLabel: "All locations", secondaryHref: "/clinical-trial-recruitment" },
  sections: [
    {
      id: "trial-counts",
      heading: "How many trials are recruiting in Texas?",
      blocks: [
        {
          type: "p",
          text: "Oncology is the largest area. 2,128 of the 7,074 recruiting US oncology studies, about 30%, list a Texas site, well above the state's 22% share of all studies.{{cite:ctgov-api}} Compare [other states and regions](/clinical-trial-recruitment).",
        },
        { type: "trialCounts", geo: "texas", cite: "ctgov-api" },
        {
          type: "p",
          text: "A count shows where sponsors placed studies, not which ones are enrolling on schedule. The neurology examples below, from Alzheimer's screening to migraine prevention, come from the same query.{{cite:ctgov-api}} See [neurology and Alzheimer's](/neurology-and-alzheimers) and [oncology](/oncology) for how Bond screens in each area.",
        },
        { type: "trials", geo: "texas", condition: "neurology", cite: "ctgov-api" },
      ],
    },
    {
      id: "research-hubs",
      heading: "Where are the main research hubs in Texas?",
      blocks: [
        {
          type: "table",
          caption: "Texas research hubs and metro population on July 1, 2025",
          columns: ["Metro area", "Population", "Anchor institutions"],
          rows: [
            [
              "Houston",
              "7,904,627{{cite:census-metro-2025}}",
              "Texas Medical Center: MD Anderson, Baylor College of Medicine and its Dan L Duncan Comprehensive Cancer Center, UTHealth Houston{{cite:tmc,nci-centers,ut-system-ctsa}}",
            ],
            ["Dallas-Fort Worth", "8,477,157{{cite:census-metro-2025}}", "UT Southwestern and its Harold C. Simmons Comprehensive Cancer Center{{cite:utsw,nci-centers}}"],
            ["San Antonio", "2,813,140{{cite:census-metro-2025}}", "UT Health San Antonio and its Mays Cancer Center{{cite:uthsa,nci-centers}}"],
            ["Austin", "2,620,945{{cite:census-metro-2025}}", "Dell Medical School at UT Austin, which took its first class in 2016{{cite:dell-med}}"],
          ],
        },
        {
          type: "ul",
          items: [
            "**Houston.** The Texas Medical Center's website calls it the largest medical complex in the world, with about 10 million patient encounters a year.{{cite:tmc}} MD Anderson reports 1,579 clinical trials and about 10,700 patients enrolled in fiscal 2025.{{cite:mdanderson}}",
            "**Dallas-Fort Worth.** UT Southwestern reports more than $816 million a year in research funding.{{cite:utsw}}",
            "**San Antonio.** In a 2024 profile, UT Health San Antonio calls itself the largest academic research institution in South Texas, with a research portfolio above $413 million a year.{{cite:uthsa}}",
            "**Statewide.** According to the UT System, four of its institutions hold NIH Clinical and Translational Science Awards and form the Texas CTSA Consortium.{{cite:ut-system-ctsa}} Voters created CPRIT, the state cancer research and prevention institute, in 2007 and added $3 billion in 2019, for a total of $6 billion.{{cite:cprit}}",
            "**Dementia.** Proposition 14, approved by voters in November 2025, gives a new Dementia Prevention and Research Institute of Texas $3 billion over 10 years. As of September 2026, litigation had delayed its launch.{{cite:dprit}}",
          ],
        },
      ],
    },
    {
      id: "health-systems-and-ehrs",
      heading: "Which health systems and EHRs hold the patients?",
      blocks: [
        {
          type: "table",
          caption: "EHRs at selected Texas health systems, from their public statements and trade press, as of September 2026",
          columns: ["System", "Texas footprint", "EHR"],
          rows: [
            [
              "Memorial Hermann (Houston)",
              "17 hospitals and more than 250 care delivery sites as of October 2024{{cite:memorial-hermann}}",
              "Epic, live systemwide since October 5, 2024{{cite:memorial-hermann}}",
            ],
            [
              "Baylor Scott & White Health",
              "55 hospitals and 1,300+ access points; calls itself the largest not-for-profit system in Texas{{cite:bsw}}",
              "Epic{{cite:bsw-epic}}",
            ],
            ["Texas Health Resources (North Texas)", "Hospital system", "Epic, per its EpicCare Link portal{{cite:thr-epic}}"],
            ["UT Health San Antonio", "Academic health center", "Epic, per its EpicCare Link portal{{cite:uthsa-epic}}"],
            [
              "HCA Healthcare",
              "Hospitals in Houston, Dallas-Fort Worth, San Antonio, Austin and other Texas markets, per a 2022 release{{cite:hca-texas}}",
              "Moving companywide to MEDITECH Expanse: 72 of about 182 planned hospitals in the US and UK were live by August 2026. The report gives no Texas dates.{{cite:hca-meditech}}",
            ],
            [
              "Community health centers",
              "71 HRSA-funded awardees serving 1,898,301 patients in 2025{{cite:hrsa-tx}}",
              "Varies. eClinicalWorks said in 2023 it served roughly 60% of US health centers{{cite:ecw-fqhc}}",
            ],
          ],
        },
        {
          type: "p",
          text: "The nonprofit and academic systems in the table run Epic; HCA is moving to MEDITECH. Bond connects to all the major EHRs, including Epic, Oracle Health (Cerner), MEDITECH, athenahealth, eClinicalWorks, NextGen, Veradigm and OncoEMR, through FHIR R4 APIs, HL7 v2 where applicable, or an aggregator.{{cite:bond-site,bond-product}} For MEDITECH, eClinicalWorks and other EHRs, Bond uses the same FHIR-based path, and the site arranges API access with its vendor. See [Epic](/integrations/epic), [MEDITECH](/integrations/meditech) and [eClinicalWorks](/integrations/eclinicalworks).",
        },
      ],
    },
    {
      id: "population",
      heading: "Who lives in Texas, and what does that mean for outreach?",
      blocks: [
        {
          type: "stats",
          items: [
            { value: "31.7 million", label: "Residents on July 1, 2025, second only to California", cite: "census-pop-2025" },
            { value: "40.9%", label: "Hispanic or Latino, the largest group", cite: "census-race-2025" },
            { value: "16.7%", label: "Uninsured in 2024, the highest rate of any state", cite: "census-acs-uninsured" },
            { value: "34.6%", label: "Texas health center patients with limited English proficiency, 2025", cite: "hrsa-tx" },
          ],
        },
        {
          type: "p",
          text: "On July 1, 2025, non-Hispanic White residents made up 37.3% of the population and non-Hispanic Black residents 12.3%.{{cite:census-race-2025}} In 2024, 21.6% of Texans aged 19 to 64 were uninsured, the highest rate for that age group in any state.{{cite:census-acs-uninsured}} At Texas health centers in 2025, 62.6% of patients with known ethnicity were Hispanic or Latino and 32.2% were uninsured.{{cite:hrsa-tx}} A cohort that reflects Texas usually needs those clinics and Spanish-language outreach. See [FQHCs and community sites](/for/fqhcs-and-community-sites).",
        },
      ],
    },
    {
      id: "site-networks",
      heading: "Which site networks work in Texas?",
      blocks: [
        {
          type: "ul",
          items: [
            "**DM Clinical Research**, headquartered in Houston, says on its website (September 2026) that it is the largest privately owned US site network, with 30+ integrated sites across 13 states.{{cite:dm-clinical}}",
            "**Summit Clinical Research Solutions**, based in San Antonio, reported 15 owned US sites and 110+ partner sites in eight countries, focused on metabolic disease, MASH, obesity and Alzheimer's, when it announced its purchase of Dallas Research Institute on September 10, 2026.{{cite:summit-pinnacle}} See [obesity and metabolic trials](/obesity-and-metabolic).",
            "**Tekton Research**, founded in Austin in 2006, lists Texas sites on its website (September 2026) in Austin, Beaumont, Coppell, Houston, Irving, McKinney and San Antonio.{{cite:tekton}}",
          ],
        },
        {
          type: "p",
          text: "Southwest Family Medicine Associates, a Texas practice, is listed among the partners on Bond's site, and Bond is a CRIO Certified Partner.{{cite:bond-site}} See how Bond fits [research sites](/for/research-sites), [site networks](/for/site-networks) and [CRIO](/integrations/crio).",
        },
      ],
    },
    {
      id: "state-rules",
      heading: "Which Texas laws apply to AI outreach and patient records?",
      blocks: [
        {
          type: "p",
          text: "None of these laws was written for trial recruitment, and how each applies is unsettled. This is a map for your counsel, not legal advice.",
        },
        {
          type: "ul",
          items: [
            "**TRAIGA (HB 149)**, in effect since January 1, 2026. When AI is used in relation to a health care service or treatment, the provider must disclose it to the patient by the date the service is first provided. The disclosure must be clear, conspicuous and in plain language, even when AI use would be obvious. The Attorney General enforces it, and licensing agencies can sanction licensees on the AG's recommendation. There is a 60-day cure period and no private right of action. Penalties run from $10,000 to $12,000 per curable violation and $80,000 to $200,000 per uncurable one.{{cite:tx-hb149}}",
            "**SB 1188**, in effect since September 1, 2025. Covered entities must keep electronic health records with patient information physically in the United States or a US territory, including records held by cloud or other third-party hosts. A practitioner who uses AI for diagnostic purposes must review AI-created records under Texas Medical Board standards and disclose the use to patients.{{cite:tx-sb1188}}",
            "**Health and Safety Code Chapter 181.** Texas defines a covered entity more broadly than HIPAA, naming health researchers, anyone who comes into possession of protected health information, and their employees, agents and contractors who handle it. Covered entities must train employees on PHI law within 90 days of hire.{{cite:tx-hs181-001,tx-hs181-101}}",
            "**SB 140**, in effect since September 1, 2025. The state telephone-solicitation law now covers text messages, and violations can be pursued under the Deceptive Trade Practices Act, including by private suit. It covers messages meant to get someone to buy, rent, claim or receive an item; whether a study invitation counts is untested.{{cite:tx-sb140}} Federal TCPA rules are a separate question; see [TCPA and AI outreach in 2026](/blog/tcpa-ai-outreach-2026).",
          ],
        },
        {
          type: "callout",
          tone: "bond",
          title: "How Bond handles disclosure",
          text: "Bond's voice and text agents tell patients that AI assistance is being used, and patients can reach a person at any time: the agent transfers the call live to a coordinator or books a human callback, whichever the site prefers.{{cite:bond-site,bond-product}} Scripts are configured per site and study, so a Texas site can set the disclosure wording with its IRB and counsel, whether or not TRAIGA turns out to cover pre-screening.",
        },
      ],
    },
    {
      id: "how-bond-deploys",
      heading: "How does Bond deploy with a Texas site?",
      blocks: [
        {
          type: "p",
          text: "Full EHR integration usually takes 48 hours, depending on the EHR, IT review and interface method.{{cite:bond-site}} The [implementation](/implementation) page has the step-by-step plan.",
        },
        {
          type: "steps",
          items: [
            {
              title: "Sign the paperwork",
              text: "Bond signs a business associate agreement, and the site confirms its IRB or privacy board path.{{cite:bond-site}} For Texas, agree on the AI disclosure wording and confirm Chapter 181 training for everyone who handles PHI.",
            },
            {
              title: "Connect the EHR or start from a list",
              text: "Given SB 1188, ask every vendor, Bond included, to state in writing where PHI is stored.",
            },
            {
              title: "Configure and validate criteria",
              text: "Bond configures the protocol's criteria and shows the criterion-to-evidence rationale for each ranked candidate, so coordinators can check the logic before live screening. See [validating eligibility logic before go-live](/blog/validating-eligibility-logic-before-go-live).",
            },
            {
              title: "Reach out, pre-screen and schedule",
              text: "Voice and text agents contact patients, pre-screen and book visits, then hand off to coordinators. The dashboard reports patients matched, contacted, pre-screened, consented and randomized.",
            },
          ],
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "Bring one open protocol and tell us which EHR your patients are in.",
          secondaryLabel: "How implementation works",
          secondaryHref: "/implementation",
        },
      ],
    },
  ],
  faq: [
    {
      q: "Does Texas require patients to be told when AI is used?",
      a: "For health care services and treatment, yes, since January 1, 2026.{{cite:tx-hb149}} Whether a recruitment call counts is unsettled. Bond's agents tell patients that AI assistance is used either way.{{cite:bond-site}}",
    },
    {
      q: "Why are Texas oncology counts so high?",
      a: "MD Anderson reports running 1,579 clinical trials in fiscal 2025, and NCI lists four designated cancer centers in Texas.{{cite:mdanderson,nci-centers}} Registry counts include every study with at least one Texas site, so large multi-site studies count here too.",
    },
  ],
  sources: [
    {
      id: "ctgov-api",
      title: "ClinicalTrials.gov API v2",
      publisher: "U.S. National Library of Medicine",
      url: "https://clinicaltrials.gov/data-api/api",
      year: "2026",
      note: "Queried September 21, 2026.",
    },
    {
      id: "census-pop-2025",
      title: "U.S. Population Growth Slows Due to Historic Decline in Net International Migration (Press Release CB26-20)",
      publisher: "U.S. Census Bureau",
      url: "https://www.census.gov/newsroom/press-releases/2026/population-growth-slows.html",
      year: "2026",
      note: "Release dated January 27, 2026. Quote: \"Texas (1.2%) grew rapidly from a combination of natural change and net international migration, despite a sharp slowdown in gains from the latter.\" The release tables list Texas second among the most populous states at 31,709,821 on July 1, 2025, and first in numeric growth at 391,243.",
    },
    {
      id: "census-race-2025",
      title: "Annual Estimates of the Resident Population by Sex, Race, and Hispanic Origin for Texas: April 1, 2020 to July 1, 2025 (SC-EST2025-SR11H-48)",
      publisher: "U.S. Census Bureau, Population Estimates Program",
      url: "https://www2.census.gov/programs-surveys/popest/tables/2020-2025/state/asrh/sc-est2025-sr11h-48.xlsx",
      year: "2026",
      note: "Read September 22, 2026. July 1, 2025 column: \"TOTAL POPULATION 31,709,821\"; \"HISPANIC 12,965,860\" (40.9%); Not Hispanic, one race, \"White 11,814,178\" (37.3%) and \"Black or African American 3,890,682\" (12.3%). Percentages computed by Bond.",
    },
    {
      id: "census-metro-2025",
      title: "Slow Growth Impacts Nation's Largest Counties Hardest (Press Release CB26-56)",
      publisher: "U.S. Census Bureau",
      url: "https://www.census.gov/newsroom/press-releases/2026/2025-popest-metro-micro-counties.html",
      year: "2026",
      note: "Release dated March 26, 2026. Quote from the table of top 10 metro areas by numeric growth, July 1, 2025 populations: \"Houston-Pasadena-The Woodlands, TX 7,904,627\"; \"Dallas-Fort Worth-Arlington, TX 8,477,157\"; \"San Antonio-New Braunfels, TX 2,813,140\"; \"Austin-Round Rock-San Marcos, TX 2,620,945\".",
    },
    {
      id: "census-acs-uninsured",
      title: "Health Insurance Coverage by State: 2023 and 2024 (ACSBR-024)",
      publisher: "U.S. Census Bureau, American Community Survey Briefs",
      url: "https://www2.census.gov/library/publications/2025/demo/acsbr-024.pdf",
      year: "2025",
    },
    {
      id: "hrsa-tx",
      title: "Texas Health Center Program Uniform Data System (UDS) Data",
      publisher: "Health Resources and Services Administration (HRSA), HHS",
      url: "https://data.hrsa.gov/tools/data-reporting/program-data/state/TX",
      year: "2026",
      note: "Quote: \"Total Number of Reporting Program Awardees: 71 Reporting Period: 2025 Total Patients Served: 1,898,301\". Patient characteristics on the same page: Hispanic, Latino/a, or Spanish Origin 62.63% of patients with known ethnicity; Limited English Proficiency 34.62% (657,133 patients); uninsured 32.20% (611,166 patients).",
    },
    {
      id: "tmc",
      title: "About Us",
      publisher: "Texas Medical Center",
      url: "https://www.tmc.edu/about-tmc/",
      year: "2026",
    },
    {
      id: "mdanderson",
      title: "Institutional Profile and Quick Facts",
      publisher: "The University of Texas MD Anderson Cancer Center",
      url: "https://www.mdanderson.org/about-md-anderson/facts-history/institutional-profile.html",
      year: "2026",
    },
    {
      id: "utsw",
      title: "Facts and Figures",
      publisher: "UT Southwestern Medical Center",
      url: "https://www.utsouthwestern.edu/about-us/facts/",
      year: "2026",
    },
    {
      id: "uthsa",
      title: "About UT Health San Antonio",
      publisher: "UT Health San Antonio",
      url: "https://news.uthscsa.edu/about-ut-health-san-antonio/",
      year: "2024",
    },
    {
      id: "dell-med",
      title: "Dell Medical School Welcomes Its First Class",
      publisher: "Dell Medical School, The University of Texas at Austin",
      url: "https://dellmed.utexas.edu/news/dell-medical-school-welcomes-its-first-class-another-major-milestone",
      year: "2016",
    },
    {
      id: "nci-centers",
      title: "Find a Cancer Center: NCI-Designated Cancer Centers",
      publisher: "National Cancer Institute",
      url: "https://www.cancer.gov/research/infrastructure/cancer-centers/find",
      year: "2026",
      note: "Read September 22, 2026. Texas entries: Dan L Duncan Comprehensive Cancer Center (Houston, Comprehensive Cancer Center); Harold C. Simmons Comprehensive Cancer Center (Dallas, Comprehensive Cancer Center); Mays Cancer Center at UT Health San Antonio (San Antonio, Clinical Cancer Center); The University of Texas MD Anderson Cancer Center (Houston, Comprehensive Cancer Center).",
    },
    {
      id: "ut-system-ctsa",
      title: "Research, Office of Health Affairs",
      publisher: "The University of Texas System",
      url: "https://www.utsystem.edu/offices/health-affairs/research",
      year: "2026",
    },
    {
      id: "cprit",
      title: "About the Cancer Prevention and Research Institute of Texas",
      publisher: "Cancer Prevention and Research Institute of Texas (Texas Cancer Plan)",
      url: "https://texascancerplan.org/about-cprit/",
      year: "2026",
      note: "Page published by the Cancer Prevention and Research Institute of Texas. Quotes: \"Created by the Texas Legislature and approved by a statewide vote in 2007\" and \"In 2019, Texans again voted overwhelmingly to support CPRIT with an additional $3 billion, for a total investment of $6 billion in cancer research and prevention.\"",
    },
    {
      id: "dprit",
      title: "American Heart Association and Alzheimer's Association File Amicus Brief Supporting Voter-Approved DPRIT",
      publisher: "American Heart Association Newsroom",
      url: "https://newsroom.heart.org/news/organizations-unite-to-defend-texas-dementia-research-initiative",
      year: "2026",
      note: "Release dated September 17, 2026, from organizations that support DPRIT. Quotes: \"Proposition 14 provides $3 billion to DPRIT over 10 years\"; \"The filing comes as litigation has delayed implementation of the groundbreaking initiative approved through Proposition 14 in November 2025\"; \"The brief requests the Court of Appeals for the Fifteenth Judicial District\" to affirm dismissal of the case.",
    },
    {
      id: "memorial-hermann",
      title: "Memorial Hermann Completes Full Transition to Epic's Electronic Health Record System",
      publisher: "Memorial Hermann Health System",
      url: "https://memorialhermann.org/about-us/newsroom/press-releases/completes-full-transition-epic-electronic-health-record-system",
      year: "2024",
      note: "Release dated October 7, 2024. Quote: \"As of Oct. 5, the Epic system is live across each of the health system's 17 hospitals and more than 250 care delivery sites.\"",
    },
    {
      id: "bsw",
      title: "About Baylor Scott & White Health",
      publisher: "Baylor Scott & White Health",
      url: "https://www.bswhealth.com/about",
      year: "2026",
      note: "Read September 22, 2026. Quote: \"the largest not-for-profit health system in the state of Texas\" serving customers \"through 55 hospitals\" and \"1,300+ access points\".",
    },
    {
      id: "bsw-epic",
      title: "EpicCare Link, Medical Professionals",
      publisher: "Baylor Scott & White Health",
      url: "https://www.bswhealth.com/medical-professionals/referrals/epiccare-link",
      year: "2026",
      note: "Read September 22, 2026. Quote: \"EpicCare Link securely connects referring practitioners and staff to select patient information in the Baylor Scott & White Health Epic electronic health record\".",
    },
    {
      id: "thr-epic",
      title: "EpicCare Link Access",
      publisher: "Texas Health Resources",
      url: "https://thepiccarelink.org/carelink/access.html",
      year: "2026",
      note: "Read September 22, 2026. Quote: \"Texas Health EpicCare Link is a web-based application that facilitates secure, real-time access to your patient's demographic and clinical information documented during an encounter at a Texas Health hospital.\"",
    },
    {
      id: "uthsa-epic",
      title: "EpicCare Link, UT Health Physicians",
      publisher: "UT Health San Antonio",
      url: "https://uthscsa.edu/physicians/epiccare-link",
      year: "2026",
    },
    {
      id: "hca-texas",
      title: "HCA Healthcare Announces Plans to Build Five New Hospitals in Texas",
      publisher: "HCA Healthcare",
      url: "https://investor.hcahealthcare.com/news/news-details/2022/HCA-Healthcare-Announces-Plans-to-Build-Five-New-Hospitals-in-Texas/default.aspx",
      year: "2022",
      note: "Release dated January 26, 2022. Quote naming HCA's Texas markets: \"Austin, El Paso, the Dallas-Fort Worth metroplex, San Antonio, Houston, Corpus Christi and the Rio Grande Valley.\" The hospital count in this release is dated, so it is not used.",
    },
    {
      id: "hca-meditech",
      title: "MEDITECH Completes Expanse Implementation Across 34 Hospitals in HCA Healthcare's First Two U.S. Divisions",
      publisher: "HIT Consultant",
      url: "https://hitconsultant.net/2026/09/16/meditech-completes-expanse-ehr-implementation-34-hospitals-hca-healthcare-divisions/",
      year: "2026",
      note: "Article dated September 16, 2026. Quote: \"Expands HCA Healthcare's total operational footprint on MEDITECH Expanse to 72 hospitals live across the United States and the United Kingdom\" and \"The completion of the 34 facilities in August pushed the active hospital count to 72.\" The planned scope is \"approximately 182 hospitals and over 2,300 care sites.\" The two completed divisions are Capital (Virginia and New Hampshire) and North Florida.",
    },
    {
      id: "ecw-fqhc",
      title: "eClinicalWorks Kicks off the Largest Summit for Federally Qualified Health Centers and Community Health Centers Nationwide",
      publisher: "eClinicalWorks",
      url: "https://www.eclinicalworks.com/eclinicalworks-kicks-off-the-largest-summit-for-federally-qualified-health-centers-and-community-health-centers-nationwide/",
      year: "2023",
      note: "Vendor self-report, May 2023. Quote: \"the leading ambulatory cloud EHR and vendor of choice for more than 800 or roughly 60% of the nation's health centers\".",
    },
    {
      id: "dm-clinical",
      title: "About DM Clinical Research",
      publisher: "DM Clinical Research",
      url: "https://www.dmclinicalresearch.com/about",
      year: "2026",
    },
    {
      id: "summit-pinnacle",
      title: "Summit Clinical Research Solutions Expands Pinnacle Site Network with Acquisition of Dallas Research Institute",
      publisher: "LongueVue Capital via PR Newswire (BioSpace)",
      url: "https://www.biospace.com/press-releases/summit-clinical-research-solutions-expands-pinnacle-site-network-with-acquisition-of-dallas-research-institute",
      year: "2026",
      note: "Release dated September 10, 2026.",
    },
    {
      id: "tekton",
      title: "About Tekton Research",
      publisher: "Tekton Research",
      url: "https://tektonresearch.com/about-tekton/",
      year: "2026",
      note: "Read September 22, 2026. Quote: \"Founded in Austin, Texas, in 2006, Tekton is a diversified, multi-specialty research site organization\". Texas locations listed on the page: Austin, Beaumont, Coppell, Houston, Irving, McKinney, San Antonio.",
    },
    {
      id: "tx-hb149",
      title: "H.B. No. 149 (89R), Texas Responsible Artificial Intelligence Governance Act, enrolled version",
      publisher: "Texas Legislature",
      url: "https://capitol.texas.gov/tlodocs/89R/billtext/html/HB00149F.htm",
      year: "2025",
      note: "Bill history (https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB149): signed by the Governor \"06/22/2025\"; \"Effective on 1/1/26\". Secs. 552.051(c) to (f) cover disclosure; Secs. 552.101 to 552.105 cover enforcement and penalties.",
    },
    {
      id: "tx-sb1188",
      title: "S.B. No. 1188 (89R), enrolled version",
      publisher: "Texas Legislature",
      url: "https://capitol.texas.gov/tlodocs/89R/billtext/html/SB01188F.htm",
      year: "2025",
      note: "Sec. 183.002(a) applies to \"electronic health records that are stored by a third-party or subcontracted computing facility or an entity that provides cloud computing services\". A transition section of the Act says Sec. 183.002 \"applies to the storage of an electronic health record on or after January 1, 2026.\" Sec. 183.005(a) allows diagnostic AI use if \"the practitioner is acting within the scope of the practitioner's license\" and \"reviews all records created with artificial intelligence in a manner that is consistent with medical records standards developed by the Texas Medical Board\"; Sec. 183.005(b) requires the practitioner to \"disclose the practitioner's use of that technology to the practitioner's patients.\" Act effective September 1, 2025.",
    },
    {
      id: "tx-hs181-001",
      title: "Texas Health and Safety Code Sec. 181.001, Definitions",
      publisher: "Texas Legislature, via Texas Public Law",
      url: "https://texas.public.law/statutes/tex._health_and_safety_code_section_181.001",
      year: "2026",
      note: "Quote: \"includes a business associate, health care payer, governmental unit, information or computer management entity, school, health researcher, health care facility, clinic, health care provider, or person who maintains an Internet site\"; any person who \"comes into possession of protected health information\"; and \"an employee, agent, or contractor of a person described by Paragraph (A), (B), or (C) insofar as the employee, agent, or contractor creates, receives, obtains, maintains, uses, or transmits protected health information.\"",
    },
    {
      id: "tx-hs181-101",
      title: "Texas Health and Safety Code Sec. 181.101, Training Required",
      publisher: "Texas Legislature, via Texas Public Law",
      url: "https://texas.public.law/statutes/tex._health_and_safety_code_section_181.101",
      year: "2026",
      note: "Quote: employees must complete training \"not later than the 90th day after the date the employee is hired by the covered entity.\"",
    },
    {
      id: "tx-sb140",
      title: "S.B. No. 140 (89R), enrolled version",
      publisher: "Texas Legislature",
      url: "https://capitol.texas.gov/tlodocs/89R/billtext/html/SB00140F.htm",
      year: "2025",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
    {
      id: "bond-product",
      title: "Bond Health product information",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
      note: "Capabilities, pricing and compliance status described by Bond Health, September 2026.",
    },
  ],
  related: [
    { label: "Recruitment by state and region", href: "/clinical-trial-recruitment", description: "Registry counts and local rules for every location Bond covers." },
    { label: "For research sites", href: "/for/research-sites", description: "How Bond fits an independent or hospital-based site." },
    { label: "Oncology", href: "/oncology", description: "Screening for oncology, the largest area of recruiting studies in Texas." },
    { label: "Obesity and metabolic", href: "/obesity-and-metabolic", description: "Recruiting for GLP-1, MASH and type 2 diabetes studies." },
    { label: "Implementation", href: "/implementation", description: "What a deployment involves, step by step." },
  ],
};

export default page;
