import type { SeoPage } from "../../types";

const page: SeoPage = {
  path: "/templates/coordinator-chart-review-checklist",
  category: "template",
  title: "Coordinator chart review checklist for pre-screening",
  description:
    "A step-by-step chart review checklist for coordinators: criteria mapping, where to look in the EHR, rationale notes, pre-screening log fields and time tracking.",
  keywords: [
    "clinical research coordinator chart review checklist",
    "pre-screening chart review",
    "pre-screening log template",
    "clinical trial eligibility chart review",
    "HIPAA minimum necessary chart review",
  ],
  eyebrow: "Template",
  h1: "Chart review checklist for clinical research coordinators",
  intro:
    "Manual chart review is slow, and its quality depends on habits that rarely get written down. This checklist writes them down: how to map each criterion before the first chart, where to look for each kind of evidence, how to record a decision someone else can check, and what goes in the pre-screening log. Copy it, edit it, and hand it to the next coordinator you train.",
  summary: "A manual pre-screening checklist with criteria mapping, EHR data sources, rationale notes, log fields, time tracking and escalation.",
  lastUpdated: "2026-09-24",
  heroCta: {
    label: "Book a demo",
    href: "/book-a-demo",
    secondaryLabel: "See how Identify works",
    secondaryHref: "/identify",
  },
  sections: [
    {
      id: "what-it-is-for",
      heading: "What is this chart review checklist for?",
      blocks: [
        {
          type: "p",
          text: "This checklist covers pre-screening by chart review: a coordinator reads a patient's existing medical record to decide whether the patient might qualify for a study, before anyone contacts the patient or asks for consent. It is written for coordinators who do this by hand in the EHR, and for the site directors and CRO leads who need that work to be consistent and documented.",
        },
        {
          type: "p",
          text: "The work takes real time, and the time varies widely from chart to chart. At one academic cancer center that tracked eligibility work for its cancer trials as it happened, the largest share of evaluations took 10 to 30 minutes, but more than 10 percent took 2 to 4 hours.{{cite:penberthy-2012}} Part H lists other published figures for comparison.",
        },
        {
          type: "p",
          text: "The checklist will not make charts faster to read. It makes each review consistent, traceable and countable, which is what a PI, a monitor and a sponsor ask about later.",
        },
        {
          type: "download",
          label: "Coordinator chart review checklist (Word)",
          href: "/downloads/coordinator-chart-review-checklist.docx",
          format: "Word document (.docx), editable",
        },
      ],
    },
    {
      id: "how-to-use",
      heading: "How do you use the checklist on a new study?",
      blocks: [
        {
          type: "steps",
          items: [
            {
              title: "Confirm you are allowed to look",
              text: "Complete the study setup checklist (Part A) before the first chart, including IRB approval of chart review and the HIPAA pathway named by your privacy office.",
            },
            {
              title: "Map the criteria with the PI",
              text: "Fill in the criteria mapping worksheet (Part B) and agree on how each criterion will be read. Use Part C to decide where in the chart each one will be checked.",
            },
            {
              title: "Work every chart in the same order",
              text: "Follow the per-chart checklist (Part D) and write a rationale note (Part E) for each decision.",
            },
            {
              title: "Escalate instead of guessing",
              text: "Send judgment calls, conflicting evidence and ambiguous protocol language to the right person using the escalation matrix (Part F).",
            },
            {
              title: "Log every chart you open",
              text: "Record each review in the pre-screening log (Part G), including charts ruled out quickly. Unlogged work is invisible to the sponsor and to your own planning.",
            },
            {
              title: "Review the numbers each week",
              text: "Use the time tracker (Part H) to see minutes per chart and yield per study, and bring the numbers to your team meeting.",
            },
          ],
        },
        {
          type: "callout",
          tone: "info",
          title: "Pre-screening is not screening",
          text: "Chart review happens before consent and uses information already in the record from routine care. Anything done only to establish eligibility, such as a new lab test or a medication washout, is screening and needs informed consent first.{{cite:fda-screening-tests}} The [pre-screening vs screening guide](/guides/pre-screening-vs-screening) covers the line in more detail.",
        },
      ],
    },
    {
      id: "criteria-mapping",
      heading: "How do you map each criterion before reviewing charts?",
      blocks: [
        {
          type: "p",
          text: "Two careful reviewers can read the same criterion differently. In a calibration exercise, two trained coordinators abstracting the same oncology charts had 86.1 percent agreement on eligibility criteria, a Cohen's kappa of 0.72.{{cite:parikh-2026}} In a research benchmark whose criteria were chosen to be difficult, two medical experts judging the same records averaged a kappa of 0.54, and some of the lowest agreement came on criteria that needed several pieces of evidence or reasoning about dates.{{cite:n2c2-2019}} The fix is to agree on each reading once, in writing, before anyone opens a chart.",
        },
        { type: "h3", text: "Part A. Study setup checklist" },
        {
          type: "checklist",
          items: [
            "Current protocol version and amendment date recorded: [protocol number, version, date].",
            "IRB approval of chart review as a recruitment method confirmed, with approval date: [date].",
            "HIPAA pathway confirmed with the privacy office: [review preparatory to research / waiver of authorization / other].",
            "Approved source of charts named: [EHR report name, clinic schedules, referral list].",
            "EHR access limited to the staff named on the study's delegation log.",
            "Criteria mapping worksheet (Part B) completed and initialed by the PI.",
            "Ambiguous criteria sent to the sponsor or CRO, and the written answers filed with the study.",
            "Pre-screening log format agreed with the sponsor. If the sponsor supplies one, use it.",
            "Escalation contacts named: PI [name], sub-investigator [name], sponsor or CRO contact [name, email], privacy office [contact].",
            "Time-tracking method chosen and explained to everyone who will review charts.",
          ],
        },
        { type: "h3", text: "Part B. Criteria mapping worksheet" },
        {
          type: "table",
          caption: "One row per inclusion and exclusion criterion",
          columns: ["Ref", "Criterion, verbatim", "Data type and where to look", "Time window", "Chart can decide?", "Agreed reading (PI initials, date)"],
          rows: [
            ["I-1", "[Copy inclusion criterion word for word]", "Diagnosis: problem list, then specialist notes", "[From protocol, e.g., diagnosed at least N months before consent]", "Yes", "[e.g., biopsy-confirmed only; a clinical diagnosis is not enough]"],
            ["I-2", "[Inclusion criterion]", "Lab value: results view, then outside labs in scanned documents", "[e.g., within N days of the screening visit]", "Yes, if a result falls in the window", "[Units, and which labs count]"],
            ["E-1", "[Exclusion criterion]", "Medication: active list, then notes and fill history", "[Washout period from protocol]", "Partly: confirm on the call", "[Drug class or named drugs]"],
            ["E-2", "[Exclusion criterion]", "Condition history: problem list, notes, discharge summaries", "[e.g., no event within N months]", "Partly", "[What counts as an event]"],
            ["E-3", "[Exclusion criterion]", "Patient-reported: not reliably in the chart", "Not applicable", "No: ask on the pre-screening call", "[Question number in the call script]"],
          ],
          note: "Add a row for every criterion, including the ones that seem obvious. Reissue the worksheet with a new date whenever the protocol is amended.",
        },
      ],
    },
    {
      id: "where-to-look",
      heading: "Where in the chart should you look for each data type?",
      blocks: [
        {
          type: "p",
          text: "Structured fields are quick to check but can be incomplete or out of date. When Brigham and Women's Hospital used a rule-based EHR search to find heart failure patients eligible for guideline-directed therapy (not a trial), only 32.1 percent of the patients staff then screened by hand were truly eligible. Over 38 percent of the false positives came from misjudging symptomatic heart failure and medication history, and the authors pointed to clinical notes as the fix.{{cite:hf-structured-2024}} Notes and reports are slower to read, but they usually hold the detail a criterion turns on. The [EHR for recruitment guide](/guides/ehr-for-recruitment) explains what each part of the record can and cannot tell you.",
        },
        { type: "h3", text: "Part C. Where to look, by data type" },
        {
          type: "table",
          caption: "Default search order. Adjust it for your EHR and your protocol.",
          columns: ["Data type", "Look first", "Then check", "Common traps"],
          rows: [
            ["Diagnosis", "Problem list and encounter diagnoses", "Specialist notes, discharge summaries, pathology reports", "\"Rule out\" and historical codes; diagnoses copied forward and never resolved"],
            ["Lab values", "Results view, filtered by date", "Outside results in scanned documents or the health information exchange", "Units and reference ranges differ by lab; the result must fall inside the protocol window"],
            ["Medications", "Active medication list and administration record", "Progress notes and prescription fill history", "Drugs still listed after they were stopped; doses held rather than discontinued"],
            ["Procedures and surgery", "Surgical history and procedure list", "Operative and procedure notes", "Missing or approximate dates; outside procedures recorded only in notes"],
            ["Imaging", "Radiology report impression", "Full report body and prior comparisons", "Measurements the protocol needs may appear only in the body of the report"],
            ["Pathology and biomarkers", "Pathology reports", "Molecular and genomic reports, often scanned files", "Outside results filed as documents rather than as discrete results"],
            ["Performance status and function", "Specialist progress notes", "Nursing and therapy notes", "Recorded once and not updated; different scales used by different clinicians"],
            ["Vital signs and BMI", "Flowsheets", "Clinic intake notes", "Single readings where the protocol requires an average or a repeat"],
            ["Social history", "Social history section", "Notes and screening questionnaires", "Often out of date; confirm smoking, alcohol and substance use on the call"],
            ["Reproductive status, willingness, availability", "Usually not in the chart", "Not applicable", "Mark for the pre-screening call and do not infer"],
            ["Research participation", "Research flags or study associations in the EHR; your CTMS", "Notes from other study teams", "Competing studies at your site; washout after a prior investigational drug"],
            ["Contact preferences", "Demographics and research contact preferences", "Site do-not-contact list", "Check before any outreach is planned"],
          ],
        },
      ],
    },
    {
      id: "per-chart-review",
      heading: "What should you check and record on each chart?",
      blocks: [
        {
          type: "p",
          text: "Work every chart in the same order. Check the hard exclusions first, because a chart that fails one criterion can be logged and closed. Record a decision for every criterion you check, not only the one that failed, so the chart does not have to be read again if the protocol or the patient changes.",
        },
        { type: "h3", text: "Part D. Per-chart checklist" },
        {
          type: "checklist",
          items: [
            "Chart came from the approved source list for this study.",
            "Research opt-out, do-not-contact flag and current study participation checked before reading further.",
            "Hard exclusions checked first, in the order set in Part B.",
            "Each criterion checked is marked Pass, Fail or Unknown, with the document and date that support it.",
            "Every date checked against the protocol window, counted from [anticipated consent date / screening visit / randomization].",
            "Notes read for anything that contradicts the structured data, such as a drug stopped or a diagnosis ruled out.",
            "Criteria that need the patient's own answer marked for the pre-screening call.",
            "Outcome recorded: Potentially eligible, Not eligible, Needs PI review, or Not enough information.",
            "Primary reason recorded as a criterion reference (for example, E-2) when the outcome is Not eligible.",
            "Minutes spent recorded.",
            "Log entry completed the same day, with no chart content copied outside approved systems.",
          ],
        },
        { type: "h3", text: "Part E. Rationale note" },
        {
          type: "p",
          text: "Write each decision so that a monitor, or a colleague next month, would reach the same answer from the same record. Reading data out of charts by hand is error-prone. A 2025 meta-analysis of clinical research data methods, covering papers published from 1978 to 2008, found that manual medical record abstraction had both high and highly variable error rates, with a pooled error rate of 6.57 percent.{{cite:garza-2025}} A short, structured note is the cheapest check against that.",
        },
        {
          type: "callout",
          tone: "info",
          title: "Use Pass, Fail and Unknown for every criterion",
          text: "Use the same three words for inclusion and exclusion criteria, so that Pass always means \"still eligible on this criterion\". Unknown is an honest answer. It tells the next reviewer exactly what to look for, and it keeps a guess out of the log.",
        },
        {
          type: "table",
          caption: "Rationale note format, with example entries",
          columns: ["Criterion", "Status", "Evidence: document, date, value", "Reviewer note"],
          rows: [
            ["I-1", "Pass", "[Pathology report, date, diagnosis as written]", "[None]"],
            ["I-2", "Unknown", "[Most recent result is outside the window: test, date]", "[Recheck after the next scheduled lab on date]"],
            ["E-1", "Pass", "[Progress note, date: drug stopped]", "[Medication list still shows it as active; the note is more recent]"],
            ["E-2", "Fail", "[Discharge summary, date: qualifying event]", "[Event falls inside the exclusion window]"],
            ["E-3", "Unknown", "[Not in chart]", "[Ask on the pre-screening call]"],
          ],
        },
        { type: "h3", text: "Part F. Escalation matrix" },
        {
          type: "table",
          caption: "Who decides when the chart does not settle it",
          columns: ["Situation", "Escalate to", "What to record"],
          rows: [
            ["A criterion needs clinical judgment, such as \"clinically significant\" or \"stable disease\"", "PI or sub-investigator", "The question, the decision, who made it and the date"],
            ["Protocol wording is ambiguous or two criteria seem to conflict", "Sponsor or CRO, through the study's query process", "The query and the written answer; update Part B"],
            ["Structured data and notes disagree", "PI or sub-investigator", "Both sources and which one was relied on"],
            ["Eligibility depends on a test that was not done for routine care", "PI", "That the test can only happen after consent; do not order it to pre-screen"],
            ["The patient looks eligible for more than one study at the site", "PI or site director, under the site's prioritization policy", "Studies considered and the decision"],
            ["Chart review turns up a possible unaddressed clinical issue", "[Treating clinician contact, per site policy]", "That the concern was passed on, to whom and when"],
            ["You are unsure whether you may open a chart, for example a restricted record", "Privacy office", "Stop, and record the question and the answer"],
          ],
        },
      ],
    },
    {
      id: "log-and-time",
      heading: "What goes in the pre-screening log and time tracker?",
      blocks: [
        {
          type: "p",
          text: "ICH E6(R2) listed a subject screening log among the essential documents, to record the identification of subjects who entered pre-trial screening.{{cite:ich-e6-r2}} Its 2025 replacement, ICH E6(R3), keeps a completed screening log in its essential records, along with records that document the recruitment and pre-trial screening process.{{cite:ich-e6-r3}} FDA's Bioresearch Monitoring compliance program for clinical investigators tells inspectors to obtain a site's screening and enrollment logs and confirm that the counts match the subjects actually screened and enrolled.{{cite:fda-bimo}}",
        },
        {
          type: "p",
          text: "Whether chart review before contact goes on the formal screening log or a separate pre-screening log is a sponsor and site decision. NIMH's public pre-screening log template is a useful reference: it covers everyone who completed initial screening and captures how many were eligible for a screening visit and why others were not.{{cite:nimh-toolbox}}",
        },
        {
          type: "callout",
          tone: "warning",
          title: "Keep identifiers inside the site",
          text: "FDA guidance says that when records are reviewed to judge eligibility, limited information about the prospective subject may be recorded.{{cite:fda-consent-2023}} Under HIPAA's preparatory-to-research pathway, the researcher must represent that no PHI will be removed from the covered entity during the review.{{cite:hipaa-164-512}} Keep the linking key inside the site, and send the sponsor de-identified entries and counts unless your IRB and privacy office have approved more.",
        },
        {
          type: "form",
          title: "Part G. Pre-screening log fields",
          fields: [
            { label: "Pre-screen ID", hint: "Site-assigned code. The key linking it to the medical record number stays inside the EHR or an access-controlled site file.", kind: "text" },
            { label: "Study", hint: "[Protocol number and short title]", kind: "text" },
            { label: "Date reviewed", kind: "text" },
            { label: "Reviewer initials", kind: "text" },
            {
              label: "Identification source",
              kind: "select",
              options: ["EHR report", "Clinic schedule", "Physician referral", "Patient self-referral", "Other"],
            },
            { label: "Record sections reviewed", hint: "Problem list, labs, medications, notes, pathology, imaging, outside records.", kind: "textarea" },
            { label: "Demographics requested by the sponsor", hint: "Only what the sponsor log requires, such as age band and sex. No names or dates of birth on shared logs.", kind: "text" },
            {
              label: "Outcome",
              kind: "select",
              options: ["Potentially eligible", "Not eligible", "Needs PI review", "Not enough information in the chart"],
            },
            { label: "Primary reason not eligible", hint: "Criterion reference from Part B, for example E-2.", kind: "text" },
            { label: "Other reasons", hint: "Further criterion references, if checked.", kind: "text" },
            {
              label: "PI review",
              kind: "select",
              options: ["Not needed", "Requested", "Completed"],
            },
            {
              label: "Next step",
              kind: "select",
              options: ["Contact using the IRB-approved script", "Recheck on a set date", "Refer concern to treating clinician", "Close"],
            },
            { label: "Recheck date", kind: "text" },
            { label: "Minutes spent", hint: "Record as you go. Mark whether this was a first pass or a full review.", kind: "number" },
            { label: "Notes", hint: "Nothing beyond what the approved HIPAA pathway allows.", kind: "textarea" },
          ],
        },
        {
          type: "p",
          text: "Record minutes per chart as you go, not at the end of the week, and keep a first pass separate from a full review. Published figures depend heavily on what the reviewer had to establish, as the table below shows, so compare your numbers only with reviews of the same kind.",
        },
        {
          type: "table",
          caption: "Published time per chart, for comparison",
          columns: ["Setting", "Type of review", "Reported time"],
          rows: [
            ["Yale Cancer Center, GI oncology clinic, one interventional trial", "Staff chart review of one week of clinic visits, most of whom were not eligible", "3.11 minutes per patient on average{{cite:yale-aaci-2023}}"],
            ["VCU Massey Cancer Center, open cancer trials", "Full eligibility evaluation", "10 to 30 minutes for the largest share; more than 10 percent took 2 to 4 hours{{cite:penberthy-2012}}"],
            ["Lung and colorectal cancer charts, randomized evaluation", "Full-criteria review by trained research staff", "37.8 minutes per chart on average{{cite:parikh-2026}}"],
            ["VCU Massey Cancer Center, per enrolled patient", "Finding, screening and enrolling one patient, counting time spent on patients who never enrolled", "3.4 to 8.8 staff hours, by study phase{{cite:penberthy-2012}}"],
          ],
        },
        {
          type: "form",
          title: "Part H. Weekly time tracker (one per study)",
          fields: [
            { label: "Week of", kind: "text" },
            { label: "Charts opened", kind: "number" },
            { label: "First-pass minutes, total", kind: "number" },
            { label: "Full reviews completed", kind: "number" },
            { label: "Full-review minutes, total", kind: "number" },
            { label: "Potentially eligible", kind: "number" },
            { label: "Sent for PI review", kind: "number" },
            { label: "Contacted", kind: "number" },
            { label: "Consented", kind: "number" },
            { label: "Minutes per potentially eligible patient", hint: "All minutes this week divided by the number potentially eligible.", kind: "number" },
          ],
        },
        {
          type: "p",
          text: "Two figures matter most. Minutes per potentially eligible patient tells you what pre-screening costs for this study. The share of potentially eligible patients who go on to consent tells you whether chart review is finding the right people.",
        },
      ],
    },
    {
      id: "irb-and-hipaa",
      heading: "What needs IRB approval, and what does HIPAA require?",
      blocks: [
        {
          type: "p",
          text: "The IRB decides whether chart review is an approved way to find participants for this study. HIPAA sets the basis on which the site may use the records, and how much of them. The rules below are summarized as of September 2026; your IRB and privacy office have the final word.",
        },
        {
          type: "p",
          text: "Institutional IRB guidance, such as the University of Miami's, treats pre-screening as part of recruitment that requires IRB oversight,{{cite:umiami-hsro}} and ICH E6(R3) lists the mechanism for pre-screening, where appropriate, as protocol content.{{cite:ich-e6-r3}} For research under the Common Rule, an IRB may approve screening through access to existing records without informed consent.{{cite:common-rule-116}} FDA guidance says a preliminary review of records to judge eligibility does not require informed consent under FDA regulations, although HIPAA still applies.{{cite:fda-consent-2023}}",
        },
        {
          type: "table",
          caption: "What usually applies to each chart review activity",
          columns: ["Activity", "What usually applies", "Check with"],
          rows: [
            ["Reviewing EHR records to find potential participants", "IRB approval of chart review as a recruitment method, plus a HIPAA pathway such as review preparatory to research or an IRB or privacy board waiver of authorization{{cite:hipaa-164-512}}", "IRB and privacy office"],
            ["Recording pre-screen results", "Record only what the pathway allows; under review preparatory to research, no PHI leaves the covered entity{{cite:hipaa-164-512}}", "Privacy office"],
            ["Keeping identifiers of patients found ineligible", "Some IRBs require them to be destroyed unless authorization or a waiver covers a failure log{{cite:umiami-hsro,nih-ohsrp}}", "IRB"],
            ["Contacting a potentially eligible patient", "An IRB-approved script or letter; see the [pre-screening call script](/templates/pre-screening-call-script)", "IRB"],
            ["Ordering a test only to confirm eligibility", "Informed consent first{{cite:fda-screening-tests}}", "PI and IRB"],
            ["Sharing the log with the sponsor", "De-identified entries and counts, unless the IRB and privacy office approve more", "Privacy office and sponsor"],
          ],
        },
        {
          type: "p",
          text: "HIPAA's minimum necessary standard requires reasonable efforts to limit the PHI used or disclosed to the minimum needed for the purpose.{{cite:hipaa-164-502}} For chart review, that becomes a short list of habits. The [IRB and HIPAA outreach guide](/guides/irb-hipaa-patient-outreach) and the glossary entry on [review preparatory to research](/glossary/preparatory-to-research) cover the rules in more depth.",
        },
        { type: "h3", text: "Part I. Minimum necessary checklist" },
        {
          type: "checklist",
          items: [
            "Open only charts on the approved source list for this study.",
            "Read only the sections the criteria mapping points to, and stop when a criterion fails.",
            "Do not print, screenshot or paste chart content into email, personal files or messaging apps.",
            "Keep the pre-screen ID key in the EHR or an access-controlled site location.",
            "Remove EHR research access for staff who leave the study team.",
            "Share de-identified log entries with the sponsor unless the IRB and privacy office approve more.",
          ],
        },
      ],
    },
    {
      id: "how-bond-relates",
      heading: "How does Bond relate to this checklist?",
      blocks: [
        {
          type: "p",
          text: "Bond Health's [Identify](/identify) stage does the first read of the chart in software. It reads structured and unstructured records against a study's inclusion and exclusion criteria, ranks candidates, and shows the rationale linking each criterion to evidence in the record. Results sit in a dashboard with an audit trail.{{cite:bond-site}}",
        },
        {
          type: "p",
          text: "As of September 2026, Bond's website reports that it cuts coordinator chart review by 50 percent or more, and that full EHR integration takes 48 hours, depending on the EHR, IT review and interface method.{{cite:bond-site}} The checklist still matters with software: the criteria mapping, escalation rules and log fields are what a site should check any screening tool against. The [manual chart review comparison](/compare/bond-vs-manual-chart-review) sets the two approaches side by side, and the rest of our [templates](/templates) cover the steps before and after chart review.",
        },
        {
          type: "cta",
          label: "Book a demo",
          href: "/book-a-demo",
          text: "See how Identify reads eligibility criteria against a chart and shows its evidence for each one.",
          secondaryLabel: "All templates",
          secondaryHref: "/templates",
        },
      ],
    },
  ],
  faq: [
    {
      q: "How long should one chart review take?",
      a: "It depends on the protocol and the chart. In one oncology clinic, staff reviewing a week of visits for a single trial averaged 3.11 minutes per patient; in a randomized evaluation, trained staff abstracting every eligibility criterion averaged 37.8 minutes per chart.{{cite:yale-aaci-2023,parikh-2026}} Track your own minutes per chart for each study rather than relying on a benchmark.",
    },
    {
      q: "Do I need patient consent to review charts for pre-screening?",
      a: "Under FDA guidance, a preliminary review of records to judge eligibility does not require informed consent under FDA regulations, but HIPAA still applies.{{cite:fda-consent-2023}} Confirm that your IRB has approved chart review as a recruitment method and that your privacy office has named the HIPAA pathway before you start.",
    },
    {
      q: "Is a pre-screening log required?",
      a: "ICH E6 lists a screening log among the essential records, and FDA inspectors are told to check screening and enrollment logs against the subjects actually screened and enrolled.{{cite:ich-e6-r3,fda-bimo}} Whether chart-level pre-screening goes on that log or a separate one depends on the sponsor and your IRB.",
    },
    {
      q: "Can I keep the names of patients who were not eligible?",
      a: "Often not without specific approval. NIH's human research protections office tells its investigators that identifiable data collected before consent cannot be kept, and other IRBs require authorization or a waiver to keep a failure log.{{cite:nih-ohsrp,umiami-hsro}} Log ineligible patients by pre-screen ID and reason, and follow your IRB's rule on retention.",
    },
  ],
  sources: [
    {
      id: "penberthy-2012",
      title: "Effort required in eligibility screening for clinical trials",
      publisher: "Journal of Oncology Practice (Penberthy LT, Dahman BA, Petkov VI, DeShazo JP)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3500483/",
      year: "2012",
      note: "VCU Massey Cancer Center, 18 months of prospectively tracked eligibility evaluations.",
    },
    {
      id: "parikh-2026",
      title: "Human-AI teaming to improve accuracy and efficiency of eligibility criteria prescreening for oncology trials: a randomized evaluation trial using retrospective electronic health records",
      publisher: "Nature Communications (Parikh RB et al.)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12976108/",
      year: "2026",
    },
    {
      id: "yale-aaci-2023",
      title: "Automated Patient Pre-Screening Using a Clinical Trials Patient Matching Algorithm",
      publisher: "Association of American Cancer Institutes, Clinical Research Innovation abstracts (Wiess C, Gong G, Kunz P; Yale Cancer Center)",
      url: "https://www.aaci-cancer.org/Files/Admin/CRI/2023/77-Automated-Patient-Pre-Screening-Using-Clinical-Trials-Patient-Matching-Algorithm.pdf",
      year: "2023",
      note: "Staff chart review for one interventional trial in GI oncology, one week of clinic visits (161 patients, 6 eligible): \"The time for eligibility review per subject with and without the use of the CTPM was tracked, taking an average of 1.82 and 3.11 minutes respectively.\"",
    },
    {
      id: "n2c2-2019",
      title: "Cohort selection for clinical trials: n2c2 2018 shared task track 1",
      publisher: "Journal of the American Medical Informatics Association (Stubbs A et al.)",
      url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6798568/",
      year: "2019",
    },
    {
      id: "garza-2025",
      title: "Error rates of data processing methods in clinical research: A systematic review and meta-analysis of manuscripts identified through PubMed",
      publisher: "International Journal of Medical Informatics (Garza MY et al.)",
      url: "https://pubmed.ncbi.nlm.nih.gov/39647291/",
      year: "2025",
      note: "93 papers published from 1978 to 2008. \"MRA was associated with both high and highly variable error rates, having a pooled error rate of 6.57% (95% CI: 5.51, 7.72).\"",
    },
    {
      id: "hf-structured-2024",
      title: "Identifying Patients with Heart Failure Eligible for Guideline-Directed Medical Therapy",
      publisher: "Population Health Management",
      url: "https://pubmed.ncbi.nlm.nih.gov/39630562/",
      year: "2024",
      note: "Brigham and Women's Hospital population health program. \"A total 5460 patients were manually screened, of which 1754 were found to be truly eligible with an accuracy of 32.1%.\"",
    },
    {
      id: "ich-e6-r2",
      title: "ICH E6(R2) Integrated Addendum: Guideline for Good Clinical Practice, section 8.3.20",
      publisher: "International Council for Harmonisation",
      url: "https://database.ich.org/sites/default/files/E6_R2_Addendum.pdf",
      year: "2016",
    },
    {
      id: "ich-e6-r3",
      title: "ICH E6(R3) Guideline for Good Clinical Practice, Appendix B (B.5.3) and Appendix C (Essential Records)",
      publisher: "International Council for Harmonisation",
      url: "https://database.ich.org/sites/default/files/ICH_E6%28R3%29_Step4_FinalGuideline_2025_0106.pdf",
      year: "2025",
    },
    {
      id: "fda-bimo",
      title: "Compliance Program 7348.811: Clinical Investigators and Sponsor-Investigators (Bioresearch Monitoring)",
      publisher: "U.S. Food and Drug Administration",
      url: "https://www.fda.gov/media/75927/download",
      year: "2020",
    },
    {
      id: "fda-consent-2023",
      title: "Informed Consent: Guidance for IRBs, Clinical Investigators, and Sponsors",
      publisher: "U.S. Food and Drug Administration",
      url: "https://www.fda.gov/media/88915/download",
      year: "2023",
    },
    {
      id: "fda-screening-tests",
      title: "Screening Tests Prior to Study Enrollment (Information Sheet for IRBs and Clinical Investigators)",
      publisher: "U.S. Food and Drug Administration",
      url: "https://www.fda.gov/regulatory-information/search-fda-guidance-documents/screening-tests-prior-study-enrollment",
      year: "1998",
    },
    {
      id: "hipaa-164-512",
      title: "45 CFR 164.512(i): Uses and disclosures for research purposes",
      publisher: "eCFR (Office of the Federal Register)",
      url: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E/section-164.512",
      year: "2026",
      note: "Text current as of September 2026.",
    },
    {
      id: "hipaa-164-502",
      title: "45 CFR 164.502(b): Standard, minimum necessary",
      publisher: "eCFR (Office of the Federal Register)",
      url: "https://www.ecfr.gov/current/title-45/section-164.502",
      year: "2026",
      note: "Text current as of September 2026: \"a covered entity or business associate must make reasonable efforts to limit protected health information to the minimum necessary to accomplish the intended purpose of the use, disclosure, or request.\"",
    },
    {
      id: "common-rule-116",
      title: "45 CFR 46.116(g): Screening, recruiting, or determining eligibility",
      publisher: "eCFR (Office of the Federal Register)",
      url: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-46/subpart-A/section-46.116",
      year: "2018",
      note: "2018 Requirements; text current as of September 2026.",
    },
    {
      id: "nimh-toolbox",
      title: "NIMH Clinical Research Toolbox: Screening and Enrollment Logs and Materials (Participant Pre-Screening Log Template)",
      publisher: "National Institute of Mental Health",
      url: "https://www.nimh.nih.gov/funding/clinical-research/clinical-research-toolbox/nimh-clinical-research-toolbox",
      year: "2026",
    },
    {
      id: "nih-ohsrp",
      title: "Screening for Research Studies",
      publisher: "NIH Office of Human Subjects Research Protections",
      url: "https://irbo.nih.gov/conducting-your-study/screening-for-research-studies/",
      year: "2026",
    },
    {
      id: "umiami-hsro",
      title: "Guidance on Screening Research Subjects for Recruitment: Screening Process and Documentation",
      publisher: "University of Miami Human Subject Research Office",
      url: "https://www.hsro.uresearch.miami.edu/_assets/pdf/guidance-screening-process-and-documentation-10.14.2011.pdf",
      year: "2011",
    },
    {
      id: "bond-site",
      title: "Bond Health: platform overview, FAQ and pricing",
      publisher: "Bond Health",
      url: "https://bondtrials.com",
      year: "2026",
    },
  ],
  related: [
    { label: "Bond vs manual chart review", href: "/compare/bond-vs-manual-chart-review", description: "How software screening compares with coordinator chart review." },
    { label: "Identify: LLM-based EHR screening", href: "/identify", description: "Criterion-by-criterion matching with evidence from the chart." },
    { label: "Using the EHR for recruitment", href: "/guides/ehr-for-recruitment", description: "What structured fields and notes can tell you about eligibility." },
    { label: "Pre-screening vs screening", href: "/guides/pre-screening-vs-screening", description: "Where pre-consent review ends and consented screening begins." },
    { label: "Pre-screening call script", href: "/templates/pre-screening-call-script", description: "The next step after a chart passes review." },
    { label: "All templates", href: "/templates", description: "Editable templates for feasibility, outreach, IRB language and more." },
  ],
};

export default page;
